;Test file to check compatibility with TIniFile (and a little with TMemInifile).
[Section0]
IdentWith=
IdentWithOut

[Section1]
IdentWithoutSpace="Without OK"
Ident with space ="With OK"

[Section2]
Überhaupt="Ok"
