<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GXX.Integration.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\GXX.LoginGate\GXX.LoginGate.csproj" />
    <ProjectReference Include="..\..\src\GXX.SelGate\GXX.SelGate.csproj" />
    <ProjectReference Include="..\..\src\GXX.RunGate\GXX.RunGate.csproj" />
    <ProjectReference Include="..\..\src\GXX.LoginSrv\GXX.LoginSrv.csproj" />
    <ProjectReference Include="..\..\src\GXX.DBServer\GXX.DBServer.csproj" />
    <ProjectReference Include="..\..\src\GXX.M2Server\GXX.M2Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
