// 源单元: Source/Client-HGE/GameConfig/MirReturn/MirReturnConfigDlg.pas (GBK, 5954 lines, CRLF)
// ** 本文件由脚本生成，禁止手工编辑 ** tools/mirreturn/Generate-MirReturnControls.ps1
// Default seam implementation: pure in-memory (no WinForms dependency); used by tests and
// before Initialize. The real WinForms adapter is injected by the host.

namespace GXX.Client.GUI.GameConfig.Seams;

public sealed partial class MirReturnConfigDlgControlsStub
{
    public int PlugBtnBossAdd { get; set; }
    public bool PlugBtnBossDel { get; set; }
    public bool PlugBtnBossModify { get; set; }
    public int PlugBtnDiyAdd { get; set; }
    public int PlugBtnDiyDel { get; set; }
    public int PlugBtnDiyLoad { get; set; }
    public int PlugBtnDiySave { get; set; }
    public int PlugButtonGJRun { get; set; }
    public int PlugButtonMonNameAdd { get; set; }
    public bool PlugButtonMonNameDel { get; set; }
    public bool PlugButtonMonNameEdit { get; set; }
    public bool PlugCheckBoxAssistantHeroAutoShield { get; set; }
    public bool PlugCheckBoxAutoCHangePoison { get; set; }
    public bool PlugCheckBoxAutoDownHorse { get; set; }
    public bool PlugCheckBoxAutoHideMode { get; set; }
    public bool PlugCheckBoxAutoLock { get; set; }
    public bool PlugCheckBoxAutoMagic { get; set; }
    public bool PlugCheckBoxAutoOrderItem { get; set; }
    public bool PlugCheckBoxAutoPercent { get; set; }
    public bool PlugCheckBoxAutoPickup { get; set; }
    public bool PlugCheckBoxAutoPickUpItem { get; set; }
    public bool PlugCheckBoxAutoTakeOnItem { get; set; }
    public bool PlugCheckBoxBagFull { get; set; }
    public bool PlugCheckBoxBGMusic { get; set; }
    public bool PlugCheckBoxBlacklistHit { get; set; }
    public bool PlugCheckBoxCheckDuraIsAuto { get; set; }
    public bool PlugCheckBoxCheckHPIsAuto { get; set; }
    public bool PlugCheckBoxCheckMPIsAuto { get; set; }
    public bool PlugCheckBoxColorShow { get; set; }
    public bool PlugCheckBoxContinueButchItem { get; set; }
    public bool PlugCheckBoxDFAvoid { get; set; }
    public bool PlugCheckBoxDisableSelfStruck { get; set; }
    public bool PlugCheckBoxDuraWarning { get; set; }
    public bool PlugCheckBoxExpFilter { get; set; }
    public bool PlugCheckBoxFriendHit { get; set; }
    public bool PlugCheckBoxGroupAttack { get; set; }
    public bool PlugCheckBoxHeroAutoShield { get; set; }
    public bool PlugCheckBoxHeroContinuousNoHitMon { get; set; }
    public bool PlugCheckBoxHeroRenewAlcoholIsAuto { get; set; }
    public bool PlugCheckBoxHeroRenewMedicineAlcoholIsAuto { get; set; }
    public bool PlugCheckBoxHeroShowNumberState { get; set; }
    public bool PlugCheckBoxHideDescUserName { get; set; }
    public bool PlugCheckBoxHideGhost { get; set; }
    public bool PlugCheckBoxHideHumEffect { get; set; }
    public bool PlugCheckBoxHideTitle { get; set; }
    public bool PlugCheckBoxHideWeaponEffect { get; set; }
    public bool PlugCheckBoxHumAutoShield { get; set; }
    public bool PlugCheckBoxHumManuallyFireBoom { get; set; }
    public bool PlugCheckBoxHumManuallyMeteorShower { get; set; }
    public bool PlugCheckBoxHumManuallySnowWind { get; set; }
    public bool PlugCheckBoxHumShootLightenLockTarget { get; set; }
    public bool PlugCheckBoxHumStruckShield { get; set; }
    public bool PlugCheckBoxItemCmp { get; set; }
    public bool PlugCheckBoxItemHint { get; set; }
    public bool PlugCheckBoxJobAndLevel { get; set; }
    public bool PlugCheckBoxLimitScreen { get; set; }
    public bool PlugCheckBoxMagicLock { get; set; }
    public bool PlugCheckBoxMovePick { get; set; }
    public bool PlugCheckBoxNearHint { get; set; }
    public bool PlugCheckBoxNoBluePoison { get; set; }
    public bool PlugCheckBoxNoDuFu { get; set; }
    public bool PlugCheckBoxNoRedPoison { get; set; }
    public bool PlugCheckBoxNoShift { get; set; }
    public bool PlugCheckBoxNotParaly { get; set; }
    public bool PlugCheckBoxNotRushMon { get; set; }
    public bool PlugCheckBoxNumberLable { get; set; }
    public bool PlugCheckBoxPickUpAll { get; set; }
    public bool PlugCheckBoxPlayAttack { get; set; }
    public bool PlugCheckBoxRenewAlcoholIsAuto { get; set; }
    public bool PlugCheckBoxRenewAutoPercent { get; set; }
    public bool PlugCheckBoxRenewDeliriaIsAuto { get; set; }
    public bool PlugCheckBoxRenewHPIsAuto { get; set; }
    public bool PlugCheckBoxRenewMedicineAlcoholIsAuto { get; set; }
    public bool PlugCheckBoxRenewMPIsAuto { get; set; }
    public bool PlugCheckBoxRenewSpecialHPIsAuto { get; set; }
    public bool PlugCheckBoxRenewSpecialMPIsAuto { get; set; }
    public bool PlugCheckBoxRepeatBGMusic { get; set; }
    public bool PlugCheckBoxSceneShake { get; set; }
    public bool PlugCheckBoxShiftSwitch { get; set; }
    public bool PlugCheckBoxShowActorName { get; set; }
    public bool PlugCheckBoxShowFilterItem { get; set; }
    public bool PlugCheckBoxShowGreenHint { get; set; }
    public bool PlugCheckBoxShowHealthNumber { get; set; }
    public bool PlugCheckBoxShowHighlightHPLabel { get; set; }
    public bool PlugCheckBoxShowHPLabel { get; set; }
    public bool PlugCheckBoxShowItemName { get; set; }
    public bool PlugCheckBoxShowMimiMapDesc { get; set; }
    public bool PlugCheckBoxShowMonName { get; set; }
    public bool PlugCheckBoxShowNGLabel { get; set; }
    public bool PlugCheckBoxShowNpcHPLabel { get; set; }
    public bool PlugCheckBoxShowNpcName { get; set; }
    public bool PlugCheckBoxSmartCRSHit { get; set; }
    public bool PlugCheckBoxSmartFireHit { get; set; }
    public bool PlugCheckBoxSmartKTZHit { get; set; }
    public bool PlugCheckBoxSmartLongHit { get; set; }
    public bool PlugCheckBoxSmartPosLongHit { get; set; }
    public bool PlugCheckBoxSmartSwordHit { get; set; }
    public bool PlugCheckBoxSmartTWNHit { get; set; }
    public bool PlugCheckBoxSmartWalkLongHit { get; set; }
    public bool PlugCheckBoxSmartWideHit { get; set; }
    public bool PlugCheckBoxSpecialQuickFlashing { get; set; }
    public bool PlugCheckBoxSpeedSlow { get; set; }
    public bool PlugCheckBoxSuperMedicaPercent { get; set; }
    public bool PlugCheckBoxUseKeyBoard { get; set; }
    public bool PlugCheckBoxUseSuperMedica { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName0 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName1 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName2 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName3 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName4 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName5 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName6 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName7 { get; set; }
    public bool PlugCheckBoxUseSuperMedicaItemName8 { get; set; }
    public bool PlugCheckBoxVolume { get; set; }
    public bool PlugCheckDisableChartMemoSize { get; set; }
    public int PlugComboBoxBagFullValue { get; set; }
    public int PlugComboBoxCheckHPValue { get; set; }
    public int PlugComboBoxCheckMPValue { get; set; }
    public int PlugComboBoxColorShow { get; set; }
    public int PlugComboBoxItemStdMode { get; set; }
    public int PlugComboBoxNoBluePoisonValue { get; set; }
    public int PlugComboBoxNoDuFuValue { get; set; }
    public int PlugComboBoxNoRedPoisonValue { get; set; }
    public int PlugComboBoxPlayAttackValue { get; set; }
    public int PlugEditAutoMagicTime { get; set; }
    public string PlugEditBoss { get; set; }
    public int PlugEditCheckDura { get; set; }
    public int PlugEditCheckDuraTime { get; set; }
    public string PlugEditCheckDuraValue { get; set; }
    public int PlugEditCheckHPPercent { get; set; }
    public int PlugEditCheckMPPercent { get; set; }
    public int PlugEditExpFilter { get; set; }
    public int PlugEditHeroDodgeHPPercent { get; set; }
    public int PlugEditHeroRenewAlcoholPercent { get; set; }
    public int PlugEditHeroRenewMedicineAlcoholPercent { get; set; }
    public string PlugEditMonName { get; set; }
    public int PlugEditNotGroupAttackCount { get; set; }
    public int PlugEditNotRushMonRange { get; set; }
    public int PlugEditRenewAlcoholPercent { get; set; }
    public int PlugEditRenewHPPercent { get; set; }
    public int PlugEditRenewHPTime { get; set; }
    public int PlugEditRenewMedicineAlcoholPercent { get; set; }
    public int PlugEditRenewMPPercent { get; set; }
    public int PlugEditRenewMPTime { get; set; }
    public int PlugEditRenewSpecialHPPercent { get; set; }
    public int PlugEditRenewSpecialHPTime { get; set; }
    public int PlugEditRenewSpecialMPPercent { get; set; }
    public int PlugEditRenewSpecialMPTime { get; set; }
    public int PlugEditSearchItem { get; set; }
    public int PlugEditSpecialColor { get; set; }
    public string PlugEditSpecialName { get; set; }
    public int PlugEditSuperMedicaHP0 { get; set; }
    public int PlugEditSuperMedicaHP1 { get; set; }
    public int PlugEditSuperMedicaHP2 { get; set; }
    public int PlugEditSuperMedicaHP3 { get; set; }
    public int PlugEditSuperMedicaHP4 { get; set; }
    public int PlugEditSuperMedicaHP5 { get; set; }
    public int PlugEditSuperMedicaHP6 { get; set; }
    public int PlugEditSuperMedicaHP7 { get; set; }
    public int PlugEditSuperMedicaHP8 { get; set; }
    public int PlugEditSuperMedicaHPTime0 { get; set; }
    public int PlugEditSuperMedicaHPTime1 { get; set; }
    public int PlugEditSuperMedicaHPTime2 { get; set; }
    public int PlugEditSuperMedicaHPTime3 { get; set; }
    public int PlugEditSuperMedicaHPTime4 { get; set; }
    public int PlugEditSuperMedicaHPTime5 { get; set; }
    public int PlugEditSuperMedicaHPTime6 { get; set; }
    public int PlugEditSuperMedicaHPTime7 { get; set; }
    public int PlugEditSuperMedicaHPTime8 { get; set; }
    public int PlugEditSuperMedicaMP0 { get; set; }
    public int PlugEditSuperMedicaMP1 { get; set; }
    public int PlugEditSuperMedicaMP2 { get; set; }
    public int PlugEditSuperMedicaMP3 { get; set; }
    public int PlugEditSuperMedicaMP4 { get; set; }
    public int PlugEditSuperMedicaMP5 { get; set; }
    public int PlugEditSuperMedicaMP6 { get; set; }
    public int PlugEditSuperMedicaMP7 { get; set; }
    public int PlugEditSuperMedicaMP8 { get; set; }
    public int PlugEditSuperMedicaMPTime0 { get; set; }
    public int PlugEditSuperMedicaMPTime1 { get; set; }
    public int PlugEditSuperMedicaMPTime2 { get; set; }
    public int PlugEditSuperMedicaMPTime3 { get; set; }
    public int PlugEditSuperMedicaMPTime4 { get; set; }
    public int PlugEditSuperMedicaMPTime5 { get; set; }
    public int PlugEditSuperMedicaMPTime6 { get; set; }
    public int PlugEditSuperMedicaMPTime7 { get; set; }
    public int PlugEditSuperMedicaMPTime8 { get; set; }
    public int PlugLabelConfig82C1 { get; set; }
    public int PlugLabelConfig82C2 { get; set; }
    public int PlugLabelConfig83C1 { get; set; }
    public int PlugLabelConfig83C2 { get; set; }
    public int PlugLabelDefaultItem { get; set; }
    public int PlugLabelGroupAttack { get; set; }
    public int PlugLabelMonName { get; set; }
    public int PlugLabelNotRushMon { get; set; }
    public int PlugLabelShortKey { get; set; }
    public int PlugLabelSpecialColor { get; set; }
    public int PlugLblBoss { get; set; }
    public int PlugLineConfig82C { get; set; }
    public int PlugLineConfig83C { get; set; }
    public int PlugMemoConfig1 { get; set; }
    public int PlugMemoConfig2 { get; set; }
    public int PlugMemoConfig2Label24 { get; set; }
    public int PlugMemoConfig2Label25 { get; set; }
    public int PlugMemoConfig2Label26 { get; set; }
    public int PlugMemoConfig2Label27 { get; set; }
    public int PlugMemoConfig2Label28 { get; set; }
    public int PlugMemoConfig2Label29 { get; set; }
    public int PlugMemoConfig2Line1 { get; set; }
    public int PlugMemoConfig2Line2 { get; set; }
    public int PlugMemoConfig3 { get; set; }
    public int PlugMemoConfig3Label1 { get; set; }
    public int PlugMemoConfig3Label2 { get; set; }
    public int PlugMemoConfig3Label3 { get; set; }
    public int PlugMemoConfig3Label4 { get; set; }
    public int PlugMemoConfig3Label5 { get; set; }
    public int PlugMemoConfig3Label6 { get; set; }
    public int PlugMemoConfig3Label7 { get; set; }
    public int PlugMemoConfig3Label8 { get; set; }
    public int PlugMemoConfig4 { get; set; }
    public bool PlugMemoConfig4Button1 { get; set; }
    public bool PlugMemoConfig4Button2 { get; set; }
    public bool PlugMemoConfig4Button3 { get; set; }
    public bool PlugMemoConfig4Button4 { get; set; }
    public bool PlugMemoConfig4Button5 { get; set; }
    public int PlugMemoConfig4Label1 { get; set; }
    public int PlugMemoConfig4Label2 { get; set; }
    public int PlugMemoConfig4Label3 { get; set; }
    public int PlugMemoConfig4Label4 { get; set; }
    public int PlugMemoConfig4Label5 { get; set; }
    public int PlugMemoConfig4Label6 { get; set; }
    public int PlugMemoConfig4Label7 { get; set; }
    public int PlugMemoConfig4Label8 { get; set; }
    public int PlugMemoConfig4LabelHint { get; set; }
    public int PlugMemoConfig4LabelHint2 { get; set; }
    public int PlugMemoConfig4Line1 { get; set; }
    public int PlugMemoConfig4Line2 { get; set; }
    public int PlugMemoConfig4Line3 { get; set; }
    public int PlugMemoConfig4Line4 { get; set; }
    public int PlugMemoConfig4Line5 { get; set; }
    public int PlugMemoConfig5 { get; set; }
    public int PlugMemoConfig5Label19 { get; set; }
    public int PlugMemoConfig5Label20 { get; set; }
    public int PlugMemoConfig5Label21 { get; set; }
    public int PlugMemoConfig5Label22 { get; set; }
    public int PlugMemoConfig5Label23 { get; set; }
    public int PlugMemoConfig6 { get; set; }
    public int PlugMemoConfig6Label1 { get; set; }
    public int PlugMemoConfig6Label2 { get; set; }
    public int PlugMemoConfig6Label3 { get; set; }
    public string PlugMemoConfig6LabelKeyBoard { get; set; }
    public int PlugMemoConfig6LabelKeyBoard1 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard10 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard11 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard12 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard2 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard3 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard4 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard5 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard6 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard7 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard8 { get; set; }
    public int PlugMemoConfig6LabelKeyBoard9 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc1 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc10 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc11 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc12 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc2 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc3 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc4 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc5 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc6 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc7 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc8 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardDesc9 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal1 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal10 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal11 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal12 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal2 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal3 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal4 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal5 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal6 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal7 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal8 { get; set; }
    public int PlugMemoConfig6LabelKeyBoardNormal9 { get; set; }
    public int PlugMemoConfig6Line1 { get; set; }
    public int PlugMemoConfig8 { get; set; }
    public int PlugMemoConfig82 { get; set; }
    public int PlugMemoConfig83 { get; set; }
    public int PlugMemoConfig8Button1 { get; set; }
    public int PlugMemoConfig8Button2 { get; set; }
    public int PlugMemoConfig8Button3 { get; set; }
    public int PlugMemoConfig8Line1 { get; set; }
    public int PlugMemoConfig8Line2 { get; set; }
    public int PlugMemoConfig8Page { get; set; }
    public int PlugMemoConfigBoss { get; set; }
    public int PlugPageControlConfig { get; set; }
    public int PlugTabSheetConfig1 { get; set; }
    public int PlugTabSheetConfig2 { get; set; }
    public int PlugTabSheetConfig3 { get; set; }
    public int PlugTabSheetConfig4 { get; set; }
    public int PlugTabSheetConfig5 { get; set; }
    public int PlugTabSheetConfig6 { get; set; }
    public int PlugTabSheetConfig7 { get; set; }
    public int PlugTabSheetConfig8 { get; set; }
    public int PlugTabSheetConfig81 { get; set; }
    public int PlugTabSheetConfig82 { get; set; }
    public int PlugTabSheetConfig83 { get; set; }
    public int PlugTabSheetConfig9 { get; set; }
}
