namespace GXX.Configurator;

/// <summary>
/// <c>ClientConfigs[]</c> 各下标的语义名与中文说明。
/// 取自 <c>Source\Client-HGE\GameConfig\Common\GameConfigDlg.pas</c> 的 <c>TConfigChecked</c> 枚举（134 项）。
/// 真机实测复选框个数为 <b>101</b>（下标 0..100），对应枚举的前 101 项。
/// </summary>
public static class CheckboxNames
{
    /// <summary>(枚举名, 中文说明)。下标与 ClientConfigs[] 一一对应。</summary>
    public static readonly (string Name, string Desc)[] Items =
    {
        ("ckShowHPLabel",              "显示血条"),
        ("ckShowNumberLable",          "数字显血"),
        ("ckShowJobAndLevel",          "显示职业等级"),
        ("ckFilterExp",                "经验过滤"),
        ("ckShowGreenHint",            "显示顶部绿色信息"),
        ("ckShowUserName",             "显示人名"),
        ("ckOnlyShowCharName",         "只显示人名"),
        ("ckShowMoveLable",            "数字飘血"),
        ("ckAutoPickUpItem",           "自动捡取"),
        ("ckNoCaton",                  "超级不卡"),
        ("ckSimpleShowHumanWeapon",    "武器简装"),
        ("ckDisableSelfStruck",        "稳如泰山"),
        ("ckSpeedSlow",                "免负重 行动慢"),
        ("ckMagicLock",                "魔法锁定"),
        ("ckPickUpAll",                "全部拾取"),
        ("ckAutoOrderItem",            "自动放药"),
        ("ckAutoCloseGroup",           "自动关组"),
        ("ckDuraWarning",              "持久警告"),
        ("ckNotNeedShift",             "免 Shift 键"),
        ("ckShiftSwitch",              "Shift 开关"),
        ("ckHideGhost",                "隐藏尸体"),
        ("ckHideHumEffect",            "隐藏翅膀效果"),
        ("ckHideWeaponEffect",         "隐藏武器效果"),
        ("ckShowMapDesc",              "显示地图标识"),
        ("ckShowHighlightHPLabel",     "人物高亮显血"),
        ("ckAutoHideMode",             "自动隐身"),
        ("ckSmart113Hit",              "自动断空斩"),
        ("ckHumAutoShield",            "自动开盾"),
        ("ckHumStruckShield",          "被攻击开盾"),
        ("ckSmartLongHit",             "刀刀刺杀"),
        ("ckSmartPosLongHit",          "隔位刺杀"),
        ("ckSmartWalkLongHit",         "走位刺杀"),
        ("ckSmartWideHit",             "智能半月"),
        ("ckSmartFireHit",             "自动烈火"),
        ("ckSmartSwordHit",            "逐日剑法"),
        ("ckSmartCrsHit",              "抱月刀 / 双龙斩"),
        ("ckSmartTwnHit",              "龙影剑法"),
        ("ckBGMusic",                  "背景音乐"),
        ("ckRepeatBGMusic",            "重复背景音乐"),
        ("ckShowMonName",              "显示怪名"),
        ("ckShowNGLabel",              "显示内功黄条"),
        ("ckNotParaly",                "防止石化"),
        ("ckHumManuallySnowWind",      "手动控制冰咆哮"),
        ("ckHumManuallyFireBoom",      "手动控制爆裂火焰"),
        ("ckHumShootLightenLockTarget","疾光电影锁定目标"),
        ("ckHumManuallyMeteorShower",  "手动控制流星火雨"),
        ("ckAutoCHangePoison",         "红绿毒互换"),
        ("ckParam9",                   "免助跑"),
        ("ckSmart66Hit",               "开天斩"),
        ("ckHeroAutoShield",           "自动开盾(英雄)"),
        ("ckAssistantHeroAutoShield",  "自动开盾(副英雄)"),
        ("ckParam10",                  "主将英雄药品"),
        ("ckParam11",                  "副将英雄药品"),
        ("ckSceneShake",               "屏幕震动"),
        ("ckShowNpcName",              "显示 NPC 名"),
        ("ckShowNpcHPLabel",           "显示 NPC 血条"),
        ("ckHideTitle",                "隐藏称号"),
        ("ckAutoOpenSpell",            "自动凝聚技能"),
        ("ckDisableChartMemoSize",     "禁止拉动聊天框"),
        ("ckItemCompare",              "装备对比"),
        ("ckVolume",                   "音量"),
        ("ckContinueButchItem",        "持续挖取"),
        ("ckDisableDeal",              "禁止交易"),
        ("ckShowUpdateStatus",         "微端状态显示"),
        ("ckSimpleShowActor",          "简装显示"),
        ("ckShowFashion",              "外显时装"),
        ("ckHumManuallyMove10Attack",  "手动控制10步一杀"),
        ("ckSimpleShowHumanDress",     "人物简装"),
        ("ckHideItemEffect",           "隐藏物品特效"),
        ("ckAutoGroupAttack",          "自动组队攻击"),
        ("ckAutoGroupNoAttackMon",     "组队不攻击怪物"),
        ("ckBagFastItemCompare",       "背包快速对比"),
        ("ckHumManuallyFire",          "手动控制地狱火"),
        ("ckShowHPUnit",               "血量单位显示"),
        ("ckShowTargetAperture",       "显示目标光圈"),
        ("ckShowNewGroupInfo",         "显示新组队信息"),
        ("ckSimpleShowBB",             "宝宝简装"),
        ("ckSmartCustomHit1",          "自定义技能1"),
        ("ckSmartCustomHit2",          "自定义技能2"),
        ("ckSmartCustomHit3",          "自定义技能3"),
        ("ckSmartCustomHit4",          "自定义技能4"),
        ("ckSmartCustomHit5",          "自定义技能5"),
        ("ckSmartCustomHit6",          "自定义技能6"),
        ("ckSmartCustomHit7",          "自定义技能7"),
        ("ckSmartCustomHit8",          "自定义技能8"),
        ("ckHumManuallyCustomHit1",    "手动技能1"),
        ("ckHumManuallyCustomHit2",    "手动技能2"),
        ("ckHumManuallyCustomHit3",    "手动技能3"),
        ("ckHumManuallyCustomHit4",    "手动技能4"),
        ("ckHumManuallyCustomHit5",    "手动技能5"),
        ("ckShowValueItemEffect",      "贵重物品特效"),
        ("ckAutoContinueAttack",       "自动持续攻击"),
        ("ckHideActorIcons",           "隐藏人物顶戴"),
        ("ckHideMonsterIcons",         "隐藏怪物顶戴花翎"),
        ("ckDimFireEffect",            "火墙淡化"),
        ("ckAutoDetourPath",           "自动绕行"),
        ("ckParam12",                  "保留12"),
        ("ckParam13",                  "保留13"),
        ("ckParam14",                  "保留14"),
        ("ckParam15",                  "保留15"),
        ("ckParam16",                  "保留16"),
    };

    public static string Label(int i) =>
        i >= 0 && i < Items.Length ? $"{i:000} {Items[i].Desc}  ({Items[i].Name})" : $"Checked{i}";
}
