// Auto-generated: GameCommand.pas AddAdminCommandToList/AddDebugCommandToList entries (J33).
// 5 wrapped entries (MobPlace/DISABLESENDMSG/DENYACCOUNTLOGON/DENYIPLOCALLOGON/DENYMACHINEIDLOGON) merged manually.
namespace GXX.M2Server.Engine;

public static class GameCommandTables
{
    public static readonly (string Section, string CmdName, string IsPermission, string Param, string Desc)[] RawEntries =
    {
        new("admin", "GAMEMASTER", "True", "", "进入/退出管理员模式(进入模式后不会受到任何角色攻击)"),
        new("admin", "OBSERVER", "True", "", "进入/退出隐身模式(进入模式后别人看不到自己)"),
        new("admin", "SUEPRMAN", "True", "", "进入/退出无敌模式(进入模式后人物不会死亡)"),
        new("admin", "KICK", "True", "人物名", "将指定人物踢下线"),
        new("admin", "ReAlive", "True", "人物名", "将指定人物复活"),
        new("admin", "KILL", "True", "人物名", "将人物或怪物杀死(杀怪物时需面对怪物)"),
        new("admin", "CHANGEJOB", "True", "人物名 职业(Warr/Wizard/Taos)", "调整人物的职业"),
        new("admin", "CHANGEGENDER", "True", "人物名 性别(男/女)", "调整人物的性别"),
        new("admin", "HAIR", "True", "人物名 发型", "调整人物的发型"),
        new("admin", "ADJUESTLEVEL", "True", "人物名 等级", "调整人物的等级"),
        new("admin", "Level", "True", "", "调整自己的等级"),
        new("admin", "NGLevel", "True", "人物名 内功等级", "调整人物的内功等级"),
        new("admin", "RENEWLEVEL", "True", "人物名 点数(为空则查看)", "调整/查看人物的转生等级"),
        new("admin", "ADJUESTEXP", "True", "人物名 经验值", "调整指定人物的经验值"),
        new("admin", "SETPERMISSION", "True", "人物名 权限等级(0-10)", "调整人物的权限等级(可升GM权限)"),
        new("admin", "Attack", "False", "攻击模式", "设置自己的攻击模式"),
        new("admin", "HUNGER", "True", "人物名 能量值", "调整人物的能量值"),
        new("admin", "PKPOINT", "True", "人物名", "查看人物的PK值"),
        new("admin", "IncPkPoint", "True", "人物名 点数", "增加人物的PK值"),
        new("admin", "FREEPENALTY", "True", "人物名", "清除人物的PK值，同时清零此人英雄的PK值"),
        new("admin", "BonusPoint", "True", "人物名 属性点数", "调整人物的属性点数"),
        new("admin", "DELBONUSPOINT", "True", "人物名", "删除人物的属性点数"),
        new("admin", "RESTBONUSPOINT", "True", "人物名", "将人物的属性点数重新分配"),
        new("admin", "CLEARMISSION", "True", "人物名", "清除人物的任务标志"),
        new("admin", "CLRPASSWORD", "True", "人物名", "清除人物仓库/登录密码"),
        new("admin", "CHANGEDEARNAME", "True", "人物名 配偶名称(如果为 无 则清除)", "更改人物的配偶名称"),
        new("admin", "CHANGEMASTERNAME", "True", "人物名 师徒名称(如果为 无 则清除)", "更改人物的师徒名称"),
        new("admin", "DelUserShop", "True", "人物名", "删除人物的个人商店"),
        new("admin", "SetUserShopName", "True", "人物名 新商店名称", "修改人物的个人商店名称"),
        new("admin", "DelSellPlayer", "True", "人物名", "下架出售的角色"),
        new("admin", "DELGOLD", "True", "人物名 数量", "减少人物金币数量"),
        new("admin", "ADDGOLD", "True", "人物名 数量", "增加人物金币数量"),
        new("admin", "GAMEGOLD", "True", "人物名 控制符(+ - =) 数量", "调整人物的游戏币数量"),
        new("admin", "GAMEPOINT", "True", "人物名 控制符(+ - =) 数量", "调整人物的游戏点数量"),
        new("admin", "CHANGEGAMEDIAMOND", "True", "物名 控制符(+,-,=) 数量", "调整金刚石数量"),
        new("admin", "CHANGEGAMEGIRD", "True", "物名 控制符(+,-,=) 数量", "调整灵符数量"),
        new("admin", "CREDITPOINT", "True", "人物名 控制符(+ - =) 点数", "调整人物的声望点数"),
        new("admin", "LUCKYPOINT", "True", "物名 控制符 幸运点数", "调整人物的幸运点数"),
        new("admin", "CHANGEGAMEGLORY", "True", "物名 控制符(+,-,=) 数量", "调整荣誉值数量"),
        new("admin", "TRAININGSKILL", "True", "人物名  技能名称 修炼等级(0-3)", "增加人物的技能"),
        new("admin", "DELETESKILL", "True", "人物名 技能名称(All)", "删除人物的技能，All代表删除全部技能"),
        new("admin", "TRAINING", "True", "人物名  技能名称 修炼等级(0-3)", "调整人物的技能等级"),
        new("admin", "POSITIONMOVE", "True", "地图号 X Y", "移动到地图指定坐标(小于最大权限受受禁止传送地图列表限制)"),
        new("admin", "Move", "True", "地图号", "移动到地图随机坐标(小于最大权限受受禁止传送地图列表限制)"),
        new("admin", "TING", "True", "人物名", "随机传送人物"),
        new("admin", "RECALL", "True", "人物名", "召唤人物到身边"),
        new("admin", "SUPERTING", "True", "人物名 范围大小", "将指定人物身边范围内的人物随机传送"),
        new("admin", "MAPMOVE", "True", "源地图号 目标地图号", "将整个地图中的人物移动到其它地图中"),
        new("admin", "REGOTO", "True", "人物名", "跟踪人物"),
        new("admin", "MAKE", "True", "物品名称 数量", "制造物品/刷物品"),
        new("admin", "GiveMine", "True", "物品名称 数量 当前持久", "制造物品/刷物品"),
        new("admin", "SMAKE", "True", "参数详见使用说明", "调整自己身上的物品属性"),
        new("admin", "REFINEWEAPON", "True", "攻击力 魔法力 道术 准确度", "调整身上武器属性"),
        new("admin", "DELETEITEM", "True", "人物名 物品名称 数量", "删除人物身上指定的物品"),
        new("admin", "MOB", "True", "怪物名称 数量 等级 国家代码 同国家玩家是否攻击 不同国家怪物是否PK 怪物颜色", "在身边放置怪物/刷怪"),
        new("admin", "RECALLMOB", "True", "怪物名称 数量 召唤等级", "召唤怪物宝宝"),
        new("admin", "Mission", "True", "X  Y", "设置怪物的集中点(举行怪物攻城用)"),
        new("admin", "CLEARMON", "True", "地图号(* 为所有) 怪物名称(* 为所有) 掉物品(0,1)", "清除地图中的怪物"),
        new("admin", "SPIRIT", "False", "时间", "祈祷生效宝宝叛变"),
        new("admin", "SPIRITSTOP", "False", "", "祈祷叛变已停止"),
        new("admin", "LoyaltyPoint", "True", "", "调整英雄忠诚度(调整点数/100，有效点数0-10000)"),
        new("admin", "Map", "True", "", "显示当前所在地图相关信息"),
        new("admin", "SHOWMAPMODE", "False", "", "显示地图模式"),
        new("admin", "SetMapMode", "False", "地图号 模式", "设置地图模式"),
        new("admin", "MOBCOUNT", "True", "地图号", "查看地图中怪物数量"),
        new("admin", "HUMANLOCAL", "True", "地图号", "查询人物IP所在地区(需加载IP地区查询插件)"),
        new("admin", "AddGuild", "True", "行会名称 掌门人", "新建一个行会"),
        new("admin", "DELGUILD", "True", "行会名称", "删除一个行会"),
        new("admin", "CHANGESABUKLORD", "True", "行会名称", "更改城堡所属行会"),
        new("admin", "FORCEDWALLCONQUESTWAR", "True", "", "强行开始/停止攻城战"),
        new("admin", "STARTCONTEST", "True", "", "开始行会争霸赛"),
        new("admin", "CONTESTPOINT", "True", "行会名称", "查看行会争霸赛得分情况"),
        new("admin", "ENDCONTEST", "True", "", "结束行会争霸赛"),
        new("admin", "ANNOUNCEMENT", "True", "", "查看行会争霸赛结果"),
        new("admin", "WHO", "True", "", "查看当前服务器在线人数"),
        new("admin", "TOTAL", "True", "", "查看所有服务器在线人数"),
        new("admin", "INFO", "True", "人物名", "看人物信息"),
        new("admin", "VIEWWHISPER", "True", "人物名", "查看指定人物的私聊信息"),
        new("admin", "MOBLEVEL", "True", "", "查看身边角色信息"),
        new("admin", "HUMANCOUNT", "True", "", "查看身边人数"),
        new("admin", "SABUKWALLGOLD", "True", "", "查看城堡金币数"),
        new("admin", "MACHINEID", "True", "", "取用户的机器码"),
        new("admin", "ENABLESENDMSG", "True", "", "将指定人物从发言过滤列表中删除"),
        new("admin", "DISABLESENDMSGLIST", "True", "", "查看发言过滤列表中的内容"),
        new("admin", "SHUTUP", "True", "人物名", "将指定人物禁言"),
        new("admin", "RELEASESHUTUP", "True", "人物名", "将指定人物从禁言列表中删除"),
        new("admin", "SHUTUPLIST", "True", "", "查看禁言列表中的内容"),
        new("admin", "DELDENYACCOUNTLOGON", "True", "登录帐号", "从禁止登录帐号列表中删除帐号"),
        new("admin", "SHOWDENYACCOUNTLOGON", "True", "", "显示禁止登录帐号列表"),
        new("admin", "DENYCHARNAMELOGON", "True", "人物名 是否永久封(0,1)", "将人物名加入禁止登录列表，此人物将无法进入游戏"),
        new("admin", "DELDENYCHARNAMELOGON", "True", "人物名", "从禁止登录人物列表中删除人物"),
        new("admin", "SHOWDENYCHARNAMELOGON", "True", "", "显示禁止登录人物名列表"),
        new("admin", "DENYIPLOGON", "True", "IP地址 是否永久封(0,1)", "将IP加入禁止登录列表，以这些IP登录的用户将无法进入游戏"),
        new("admin", "DELDENYIPLOGON", "True", "IP地址", "从禁止登录IP列表中删除IP"),
        new("admin", "SHOWDENYIPLOGON", "True", "", "显示禁止登录IP列表"),
        new("admin", "DELDENYIPLOCALLOGON", "True", "IP所在地", "从禁止登录IP所在地列表中删除IP所在地"),
        new("admin", "SHOWDENYIPLOCALLOGON", "True", "", "显示禁止登录IP所在地列表"),
        new("admin", "DELMACHINEIDLOGON", "True", "机器码", "从禁止登录机器机列表中删除指定机器码"),
        new("admin", "SHOWMACHINEIDLOGON", "True", "", "显示禁止登录机器码列表"),
        new("admin", "STARTQUEST", "True", "", "开始提问功能，游戏中所有人同时跳出问题窗口"),
        new("debug", "RELOADADMIN", "", "", "重新加载管理员列表"),
        new("debug", "ReLoadNpc", "", "", "重新加载NPC脚本"),
        new("debug", "RELOADMANAGE", "", "", "重新加载登录脚本"),
        new("debug", "RELOADROBOTMANAGE", "", "", "重新加载机器人配置"),
        new("debug", "RELOADROBOT", "", "", "重新加载机器人脚本"),
        new("debug", "RELOADMONITEMS", "", "", "重新加载怪物爆率配置"),
        new("debug", "RELOADDIARY", "", "", "未使用"),
        new("debug", "RELOADITEMDB", "", "", "重新加载物品数据库"),
        new("debug", "RELOADMAGICDB", "", "", "未使用"),
        new("debug", "RELOADMONSTERDB", "", "", "重新加载怪物数据库"),
        new("debug", "RELOADMINMAP", "", "", "重新加载小地图配置"),
        new("debug", "RELOADGUILD", "", "", ""),
        new("debug", "RELOADGUILDALL", "", "", ""),
        new("debug", "RELOADLINENOTICE", "", "", "重新加载游戏公告信息"),
        new("debug", "RELOADABUSE", "", "", "重新加载脏话过滤配置"),
        new("debug", "SHOWFLAG", "", "", ""),
        new("debug", "SETFLAG", "", "", ""),
        new("debug", "SHOWOPEN", "", "", ""),
        new("debug", "SETOPEN", "", "", ""),
        new("debug", "SHOWUNIT", "", "", ""),
        new("debug", "SETUNIT", "", "", ""),
        new("debug", "MOBNPC", "", "", ""),
        new("debug", "DELNPC", "", "", ""),
        new("debug", "LOTTERYTICKET", "", "", ""),
        new("debug", "BACKSTEP", "", "", ""),
        new("debug", "RECONNECTION", "", "", "将指定人物重新切换网络连接"),
        new("debug", "CHANGEGATE", "", "", "切换网络连接"),
        new("debug", "DISABLEFILTER", "", "", "禁用脏话过滤功能"),
        new("debug", "CHGUSERFULL", "", "", ""),
        new("debug", "CHGZENFASTSTEP", "", "", ""),
        new("debug", "OXQUIZROOM", "", "", ""),
        new("debug", "BALL", "", "", ""),
        new("debug", "FIREBURN", "", "", ""),
        new("debug", "TESTFIRE", "", "", ""),
        new("debug", "TESTSTATUS", "", "", ""),
        new("debug", "TESTGOLDCHANGE", "", "", ""),
        new("debug", "GSA", "", "", ""),
        new("debug", "TESTGA", "", "", ""),
        new("debug", "MAPINFO", "", "", "显示地图信息"),
        new("debug", "CLEARBAG", "", "", "清除背包全部物品"),
        new("admin", "MobPlace", "True", "X  Y 怪物名称 怪物数量", "在当前地图指定XY放置怪物(先必须设置怪物的集中点，放置的怪物大刀守卫不会攻击这些怪物)"),
        new("admin", "DISABLESENDMSG", "True", "人物名", "将指定人物加入发言过滤列表，加入列表后自己发的文字自己可以看到，其他人看不到"),
        new("admin", "DENYACCOUNTLOGON", "True", "登录帐号 是否永久封(0,1)", "将登录帐号加入禁止登录列表，此帐号登录的用户将无法进入游戏"),
        new("admin", "DENYIPLOCALLOGON", "True", "IP所在地 是否永久封(0,1)", "将IP所在地加入禁止登录列表，以这些IP所在地登录的用户将无法进入游戏"),
        new("admin", "DENYMACHINEIDLOGON", "True", "机器码 是否永久封(0,1)", "将指定机器码加入禁止登录列表，以这些机器码登录的用户将无法进入游戏"),
    };
}
