// Auto-generated: ItemSet.pas ButtonAddValueSaveClick ordered keys + typed-constant defaults (J35).
namespace GXX.M2Server.Engine;

public static class ItemSetAddValueTables
{
    public static readonly (string Key, string Field)[] Keys =
    {
        new("MonRandomAddValue", "nMonRandomAddValue"),
        new("MakeRandomAddValue", "nMakeRandomAddValue"),
        new("WeaponDCAddValueMaxLimit", "nWeaponDCAddValueMaxLimit"),
        new("WeaponDCAddValueRate", "nWeaponDCAddValueRate"),
        new("WeaponMCAddValueMaxLimit", "nWeaponMCAddValueMaxLimit"),
        new("WeaponMCAddValueRate", "nWeaponMCAddValueRate"),
        new("WeaponSCAddValueMaxLimit", "nWeaponSCAddValueMaxLimit"),
        new("WeaponSCAddValueRate", "nWeaponSCAddValueRate"),
        new("WeaponDCAddRate", "nWeaponDCAddRate"),
        new("WeaponSCAddRate", "nWeaponSCAddRate"),
        new("WeaponMCAddRate", "nWeaponMCAddRate"),
        new("WeaponHitSpeedAddValueMaxLimit", "nWeaponHitSpeedAddValueMaxLimit"),
        new("WeaponHitSpeedAddValueRate", "nWeaponHitSpeedAddValueRate"),
        new("WeaponHitSpeedAddRate", "nWeaponHitSpeedAddRate"),
        new("DressDCAddRate", "nDressDCAddRate"),
        new("DressDCAddValueMaxLimit", "nDressDCAddValueMaxLimit"),
        new("DressDCAddValueRate", "nDressDCAddValueRate"),
        new("DressMCAddRate", "nDressMCAddRate"),
        new("DressMCAddValueMaxLimit", "nDressMCAddValueMaxLimit"),
        new("DressMCAddValueRate", "nDressMCAddValueRate"),
        new("DressSCAddRate", "nDressSCAddRate"),
        new("DressSCAddValueMaxLimit", "nDressSCAddValueMaxLimit"),
        new("DressSCAddValueRate", "nDressSCAddValueRate"),
        new("DressACAddValueMaxLimit", "nDressACAddValueMaxLimit"),
        new("DressACAddValueRate", "nDressACAddValueRate"),
        new("DressACAddRate", "nDressACAddRate"),
        new("DressMACAddValueMaxLimit", "nDressMACAddValueMaxLimit"),
        new("DressMACAddValueRate", "nDressMACAddValueRate"),
        new("DressMACAddRate", "nDressMACAddRate"),
        new("NeckLace19DCAddRate", "nNeckLace19DCAddRate"),
        new("NeckLace19DCAddValueMaxLimit", "nNeckLace19DCAddValueMaxLimit"),
        new("NeckLace19DCAddValueRate", "nNeckLace19DCAddValueRate"),
        new("NeckLace19MCAddRate", "nNeckLace19MCAddRate"),
        new("NeckLace19MCAddValueMaxLimit", "nNeckLace19MCAddValueMaxLimit"),
        new("NeckLace19MCAddValueRate", "nNeckLace19MCAddValueRate"),
        new("NeckLace19SCAddRate", "nNeckLace19SCAddRate"),
        new("NeckLace19SCAddValueMaxLimit", "nNeckLace19SCAddValueMaxLimit"),
        new("NeckLace19SCAddValueRate", "nNeckLace19SCAddValueRate"),
        new("NeckLace19ACAddValueMaxLimit", "nNeckLace19ACAddValueMaxLimit"),
        new("NeckLace19ACAddValueRate", "nNeckLace19ACAddValueRate"),
        new("NeckLace19ACAddRate", "nNeckLace19ACAddRate"),
        new("NeckLace19MACAddValueMaxLimit", "nNeckLace19MACAddValueMaxLimit"),
        new("NeckLace19MACAddValueRate", "nNeckLace19MACAddValueRate"),
        new("NeckLace19MACAddRate", "nNeckLace19MACAddRate"),
        new("NeckLace202124DCAddRate", "nNeckLace202124DCAddRate"),
        new("NeckLace202124DCAddValueMaxLimit", "nNeckLace202124DCAddValueMaxLimit"),
        new("NeckLace202124DCAddValueRate", "nNeckLace202124DCAddValueRate"),
        new("NeckLace202124MCAddRate", "nNeckLace202124MCAddRate"),
        new("NeckLace202124MCAddValueMaxLimit", "nNeckLace202124MCAddValueMaxLimit"),
        new("NeckLace202124MCAddValueRate", "nNeckLace202124MCAddValueRate"),
        new("NeckLace202124SCAddRate", "nNeckLace202124SCAddRate"),
        new("NeckLace202124SCAddValueMaxLimit", "nNeckLace202124SCAddValueMaxLimit"),
        new("NeckLace202124SCAddValueRate", "nNeckLace202124SCAddValueRate"),
        new("NeckLace202124ACAddValueMaxLimit", "nNeckLace202124ACAddValueMaxLimit"),
        new("NeckLace202124ACAddValueRate", "nNeckLace202124ACAddValueRate"),
        new("NeckLace202124ACAddRate", "nNeckLace202124ACAddRate"),
        new("NeckLace202124MACAddValueMaxLimit", "nNeckLace202124MACAddValueMaxLimit"),
        new("NeckLace202124MACAddValueRate", "nNeckLace202124MACAddValueRate"),
        new("NeckLace202124MACAddRate", "nNeckLace202124MACAddRate"),
        new("Ring22DCAddValueMaxLimit", "nRing22DCAddValueMaxLimit"),
        new("Ring22DCAddValueRate", "nRing22DCAddValueRate"),
        new("Ring22DCAddRate", "nRing22DCAddRate"),
        new("Ring22MCAddValueMaxLimit", "nRing22MCAddValueMaxLimit"),
        new("Ring22MCAddValueRate", "nRing22MCAddValueRate"),
        new("Ring22MCAddRate", "nRing22MCAddRate"),
        new("Ring22SCAddValueMaxLimit", "nRing22SCAddValueMaxLimit"),
        new("Ring22SCAddValueRate", "nRing22SCAddValueRate"),
        new("Ring22SCAddRate", "nRing22SCAddRate"),
        new("Ring22ACAddValueMaxLimit", "nRing22ACAddValueMaxLimit"),
        new("Ring22ACAddValueRate", "nRing22ACAddValueRate"),
        new("Ring22ACAddRate", "nRing22ACAddRate"),
        new("Ring22MACAddValueMaxLimit", "nRing22MACAddValueMaxLimit"),
        new("Ring22MACAddValueRate", "nRing22MACAddValueRate"),
        new("Ring22MACAddRate", "nRing22MACAddRate"),
        new("ArmRing26DCAddRate", "nArmRing26DCAddRate"),
        new("ArmRing26DCAddValueMaxLimit", "nArmRing26DCAddValueMaxLimit"),
        new("ArmRing26DCAddValueRate", "nArmRing26DCAddValueRate"),
        new("ArmRing26MCAddRate", "nArmRing26MCAddRate"),
        new("ArmRing26MCAddValueMaxLimit", "nArmRing26MCAddValueMaxLimit"),
        new("ArmRing26MCAddValueRate", "nArmRing26MCAddValueRate"),
        new("ArmRing26SCAddRate", "nArmRing26SCAddRate"),
        new("ArmRing26SCAddValueMaxLimit", "nArmRing26SCAddValueMaxLimit"),
        new("ArmRing26SCAddValueRate", "nArmRing26SCAddValueRate"),
        new("ArmRing26ACAddValueMaxLimit", "nArmRing26ACAddValueMaxLimit"),
        new("ArmRing26ACAddValueRate", "nArmRing26ACAddValueRate"),
        new("ArmRing26ACAddRate", "nArmRing26ACAddRate"),
        new("ArmRing26MACAddValueMaxLimit", "nArmRing26MACAddValueMaxLimit"),
        new("ArmRing26MACAddValueRate", "nArmRing26MACAddValueRate"),
        new("ArmRing26MACAddRate", "nArmRing26MACAddRate"),
        new("Ring23DCAddRate", "nRing23DCAddRate"),
        new("Ring23DCAddValueMaxLimit", "nRing23DCAddValueMaxLimit"),
        new("Ring23DCAddValueRate", "nRing23DCAddValueRate"),
        new("Ring23MCAddRate", "nRing23MCAddRate"),
        new("Ring23MCAddValueMaxLimit", "nRing23MCAddValueMaxLimit"),
        new("Ring23MCAddValueRate", "nRing23MCAddValueRate"),
        new("Ring23SCAddRate", "nRing23SCAddRate"),
        new("Ring23SCAddValueMaxLimit", "nRing23SCAddValueMaxLimit"),
        new("Ring23SCAddValueRate", "nRing23SCAddValueRate"),
        new("Ring23ACAddValueMaxLimit", "nRing23ACAddValueMaxLimit"),
        new("Ring23ACAddValueRate", "nRing23ACAddValueRate"),
        new("Ring23ACAddRate", "nRing23ACAddRate"),
        new("Ring23MACAddValueMaxLimit", "nRing23MACAddValueMaxLimit"),
        new("Ring23MACAddValueRate", "nRing23MACAddValueRate"),
        new("Ring23MACAddRate", "nRing23MACAddRate"),
        new("BootsDCAddValueMaxLimit", "nBootsDCAddValueMaxLimit"),
        new("BootsDCAddValueRate", "nBootsDCAddValueRate"),
        new("BootsDCAddRate", "nBootsDCAddRate"),
        new("BootsSCAddValueMaxLimit", "nBootsSCAddValueMaxLimit"),
        new("BootsSCAddValueRate", "nBootsSCAddValueRate"),
        new("BootsSCAddRate", "nBootsSCAddRate"),
        new("BootsMCAddValueMaxLimit", "nBootsMCAddValueMaxLimit"),
        new("BootsMCAddValueRate", "nBootsMCAddValueRate"),
        new("BootsMCAddRate", "nBootsMCAddRate"),
        new("BootsACAddValueMaxLimit", "nBootsACAddValueMaxLimit"),
        new("BootsACAddValueRate", "nBootsACAddValueRate"),
        new("BootsACAddRate", "nBootsACAddRate"),
        new("BootsMACAddValueMaxLimit", "nBootsMACAddValueMaxLimit"),
        new("BootsMACAddValueRate", "nBootsMACAddValueRate"),
        new("BootsMACAddRate", "nBootsMACAddRate"),
        new("HelMetDCAddRate", "nHelMetDCAddRate"),
        new("HelMetDCAddValueMaxLimit", "nHelMetDCAddValueMaxLimit"),
        new("HelMetDCAddValueRate", "nHelMetDCAddValueRate"),
        new("HelMetMCAddRate", "nHelMetMCAddRate"),
        new("HelMetMCAddValueMaxLimit", "nHelMetMCAddValueMaxLimit"),
        new("HelMetMCAddValueRate", "nHelMetMCAddValueRate"),
        new("HelMetSCAddRate", "nHelMetSCAddRate"),
        new("HelMetSCAddValueMaxLimit", "nHelMetSCAddValueMaxLimit"),
        new("HelMetSCAddValueRate", "nHelMetSCAddValueRate"),
        new("HelMetACAddValueMaxLimit", "nHelMetACAddValueMaxLimit"),
        new("HelMetACAddValueRate", "nHelMetACAddValueRate"),
        new("HelMetACAddRate", "nHelMetACAddRate"),
        new("HelMetMACAddValueMaxLimit", "nHelMetMACAddValueMaxLimit"),
        new("HelMetMACAddValueRate", "nHelMetMACAddValueRate"),
        new("HelMetMACAddRate", "nHelMetMACAddRate"),
        new("FashionWeaponDCAddValueMaxLimit", "nFashionWeaponDCAddValueMaxLimit"),
        new("FashionWeaponDCAddValueRate", "nFashionWeaponDCAddValueRate"),
        new("FashionWeaponMCAddValueMaxLimit", "nFashionWeaponMCAddValueMaxLimit"),
        new("FashionWeaponMCAddValueRate", "nFashionWeaponMCAddValueRate"),
        new("FashionWeaponSCAddValueMaxLimit", "nFashionWeaponSCAddValueMaxLimit"),
        new("FashionWeaponSCAddValueRate", "nFashionWeaponSCAddValueRate"),
        new("FashionWeaponDCAddRate", "nFashionWeaponDCAddRate"),
        new("FashionWeaponSCAddRate", "nFashionWeaponSCAddRate"),
        new("FashionWeaponMCAddRate", "nFashionWeaponMCAddRate"),
        new("FashionWeaponHitSpeedAddValueMaxLimit", "nFashionWeaponHitSpeedAddValueMaxLimit"),
        new("FashionWeaponHitSpeedAddValueRate", "nFashionWeaponHitSpeedAddValueRate"),
        new("FashionWeaponHitSpeedAddRate", "nFashionWeaponHitSpeedAddRate"),
        new("FashionDressDCAddRate", "nFashionDressDCAddRate"),
        new("FashionDressDCAddValueMaxLimit", "nFashionDressDCAddValueMaxLimit"),
        new("FashionDressDCAddValueRate", "nFashionDressDCAddValueRate"),
        new("FashionDressMCAddRate", "nFashionDressMCAddRate"),
        new("FashionDressMCAddValueMaxLimit", "nFashionDressMCAddValueMaxLimit"),
        new("FashionDressMCAddValueRate", "nFashionDressMCAddValueRate"),
        new("FashionDressSCAddRate", "nFashionDressSCAddRate"),
        new("FashionDressSCAddValueMaxLimit", "nFashionDressSCAddValueMaxLimit"),
        new("FashionDressSCAddValueRate", "nFashionDressSCAddValueRate"),
        new("FashionDressACAddValueMaxLimit", "nFashionDressACAddValueMaxLimit"),
        new("FashionDressACAddValueRate", "nFashionDressACAddValueRate"),
        new("FashionDressACAddRate", "nFashionDressACAddRate"),
        new("FashionDressMACAddValueMaxLimit", "nFashionDressMACAddValueMaxLimit"),
        new("FashionDressMACAddValueRate", "nFashionDressMACAddValueRate"),
        new("FashionDressMACAddRate", "nFashionDressMACAddRate"),
        new("HorseDCAddRate", "nHorseDCAddRate"),
        new("HorseDCAddValueMaxLimit", "nHorseDCAddValueMaxLimit"),
        new("HorseDCAddValueRate", "nHorseDCAddValueRate"),
        new("HorseMCAddRate", "nHorseMCAddRate"),
        new("HorseMCAddValueMaxLimit", "nHorseMCAddValueMaxLimit"),
        new("HorseMCAddValueRate", "nHorseMCAddValueRate"),
        new("HorseSCAddRate", "nHorseSCAddRate"),
        new("HorseSCAddValueMaxLimit", "nHorseSCAddValueMaxLimit"),
        new("HorseSCAddValueRate", "nHorseSCAddValueRate"),
        new("HorseACAddValueMaxLimit", "nHorseACAddValueMaxLimit"),
        new("HorseACAddValueRate", "nHorseACAddValueRate"),
        new("HorseACAddRate", "nHorseACAddRate"),
        new("HorseMACAddValueMaxLimit", "nHorseMACAddValueMaxLimit"),
        new("HorseMACAddValueRate", "nHorseMACAddValueRate"),
        new("HorseMACAddRate", "nHorseMACAddRate"),
        new("DrumDCAddRate", "nDrumDCAddRate"),
        new("DrumDCAddValueMaxLimit", "nDrumDCAddValueMaxLimit"),
        new("DrumDCAddValueRate", "nDrumDCAddValueRate"),
        new("DrumMCAddRate", "nDrumMCAddRate"),
        new("DrumMCAddValueMaxLimit", "nDrumMCAddValueMaxLimit"),
        new("DrumMCAddValueRate", "nDrumMCAddValueRate"),
        new("DrumSCAddRate", "nDrumSCAddRate"),
        new("DrumSCAddValueMaxLimit", "nDrumSCAddValueMaxLimit"),
        new("DrumSCAddValueRate", "nDrumSCAddValueRate"),
        new("DrumACAddValueMaxLimit", "nDrumACAddValueMaxLimit"),
        new("DrumACAddValueRate", "nDrumACAddValueRate"),
        new("DrumACAddRate", "nDrumACAddRate"),
        new("DrumMACAddValueMaxLimit", "nDrumMACAddValueMaxLimit"),
        new("DrumMACAddValueRate", "nDrumMACAddValueRate"),
        new("DrumMACAddRate", "nDrumMACAddRate"),
        new("ShieldDCAddRate", "nShieldDCAddRate"),
        new("ShieldDCAddValueMaxLimit", "nShieldDCAddValueMaxLimit"),
        new("ShieldDCAddValueRate", "nShieldDCAddValueRate"),
        new("ShieldMCAddRate", "nShieldMCAddRate"),
        new("ShieldMCAddValueMaxLimit", "nShieldMCAddValueMaxLimit"),
        new("ShieldMCAddValueRate", "nShieldMCAddValueRate"),
        new("ShieldSCAddRate", "nShieldSCAddRate"),
        new("ShieldSCAddValueMaxLimit", "nShieldSCAddValueMaxLimit"),
        new("ShieldSCAddValueRate", "nShieldSCAddValueRate"),
        new("ShieldACAddValueMaxLimit", "nShieldACAddValueMaxLimit"),
        new("ShieldACAddValueRate", "nShieldACAddValueRate"),
        new("ShieldACAddRate", "nShieldACAddRate"),
        new("ShieldMACAddValueMaxLimit", "nShieldMACAddValueMaxLimit"),
        new("ShieldMACAddValueRate", "nShieldMACAddValueRate"),
        new("ShieldMACAddRate", "nShieldMACAddRate"),
    };

    public static readonly System.Collections.Generic.Dictionary<string, int> Defaults = new()
    {
        ["MonRandomAddValue"] = 10,
        ["MakeRandomAddValue"] = 10,
        ["WeaponDCAddValueMaxLimit"] = 12,
        ["WeaponDCAddValueRate"] = 15,
        ["WeaponMCAddValueMaxLimit"] = 12,
        ["WeaponMCAddValueRate"] = 15,
        ["WeaponSCAddValueMaxLimit"] = 12,
        ["WeaponSCAddValueRate"] = 15,
        ["WeaponDCAddRate"] = 40,
        ["WeaponSCAddRate"] = 40,
        ["WeaponMCAddRate"] = 40,
        ["WeaponHitSpeedAddValueMaxLimit"] = 12,
        ["WeaponHitSpeedAddValueRate"] = 15,
        ["WeaponHitSpeedAddRate"] = 40,
        ["DressDCAddRate"] = 40,
        ["DressDCAddValueMaxLimit"] = 6,
        ["DressDCAddValueRate"] = 20,
        ["DressMCAddRate"] = 40,
        ["DressMCAddValueMaxLimit"] = 6,
        ["DressMCAddValueRate"] = 20,
        ["DressSCAddRate"] = 40,
        ["DressSCAddValueMaxLimit"] = 6,
        ["DressSCAddValueRate"] = 20,
        ["DressACAddValueMaxLimit"] = 6,
        ["DressACAddValueRate"] = 20,
        ["DressACAddRate"] = 40,
        ["DressMACAddValueMaxLimit"] = 6,
        ["DressMACAddValueRate"] = 20,
        ["DressMACAddRate"] = 40,
        ["NeckLace19DCAddRate"] = 30,
        ["NeckLace19DCAddValueMaxLimit"] = 6,
        ["NeckLace19DCAddValueRate"] = 20,
        ["NeckLace19MCAddRate"] = 30,
        ["NeckLace19MCAddValueMaxLimit"] = 6,
        ["NeckLace19MCAddValueRate"] = 20,
        ["NeckLace19SCAddRate"] = 30,
        ["NeckLace19SCAddValueMaxLimit"] = 6,
        ["NeckLace19SCAddValueRate"] = 20,
        ["NeckLace19ACAddValueMaxLimit"] = 6,
        ["NeckLace19ACAddValueRate"] = 20,
        ["NeckLace19ACAddRate"] = 30,
        ["NeckLace19MACAddValueMaxLimit"] = 6,
        ["NeckLace19MACAddValueRate"] = 20,
        ["NeckLace19MACAddRate"] = 30,
        ["NeckLace202124DCAddRate"] = 40,
        ["NeckLace202124DCAddValueMaxLimit"] = 6,
        ["NeckLace202124DCAddValueRate"] = 20,
        ["NeckLace202124MCAddRate"] = 40,
        ["NeckLace202124MCAddValueMaxLimit"] = 6,
        ["NeckLace202124MCAddValueRate"] = 20,
        ["NeckLace202124SCAddRate"] = 40,
        ["NeckLace202124SCAddValueMaxLimit"] = 6,
        ["NeckLace202124SCAddValueRate"] = 20,
        ["NeckLace202124ACAddValueMaxLimit"] = 6,
        ["NeckLace202124ACAddValueRate"] = 20,
        ["NeckLace202124ACAddRate"] = 40,
        ["NeckLace202124MACAddValueMaxLimit"] = 6,
        ["NeckLace202124MACAddValueRate"] = 20,
        ["NeckLace202124MACAddRate"] = 40,
        ["Ring22DCAddValueMaxLimit"] = 6,
        ["Ring22DCAddValueRate"] = 20,
        ["Ring22DCAddRate"] = 30,
        ["Ring22MCAddValueMaxLimit"] = 6,
        ["Ring22MCAddValueRate"] = 20,
        ["Ring22MCAddRate"] = 30,
        ["Ring22SCAddValueMaxLimit"] = 6,
        ["Ring22SCAddValueRate"] = 20,
        ["Ring22SCAddRate"] = 30,
        ["Ring22ACAddValueMaxLimit"] = 6,
        ["Ring22ACAddValueRate"] = 20,
        ["Ring22ACAddRate"] = 30,
        ["Ring22MACAddValueMaxLimit"] = 6,
        ["Ring22MACAddValueRate"] = 20,
        ["Ring22MACAddRate"] = 30,
        ["ArmRing26DCAddRate"] = 30,
        ["ArmRing26DCAddValueMaxLimit"] = 6,
        ["ArmRing26DCAddValueRate"] = 20,
        ["ArmRing26MCAddRate"] = 30,
        ["ArmRing26MCAddValueMaxLimit"] = 6,
        ["ArmRing26MCAddValueRate"] = 20,
        ["ArmRing26SCAddRate"] = 30,
        ["ArmRing26SCAddValueMaxLimit"] = 6,
        ["ArmRing26SCAddValueRate"] = 20,
        ["ArmRing26ACAddValueMaxLimit"] = 6,
        ["ArmRing26ACAddValueRate"] = 20,
        ["ArmRing26ACAddRate"] = 30,
        ["ArmRing26MACAddValueMaxLimit"] = 6,
        ["ArmRing26MACAddValueRate"] = 20,
        ["ArmRing26MACAddRate"] = 30,
        ["Ring23DCAddRate"] = 30,
        ["Ring23DCAddValueMaxLimit"] = 6,
        ["Ring23DCAddValueRate"] = 20,
        ["Ring23MCAddRate"] = 30,
        ["Ring23MCAddValueMaxLimit"] = 6,
        ["Ring23MCAddValueRate"] = 20,
        ["Ring23SCAddRate"] = 30,
        ["Ring23SCAddValueMaxLimit"] = 6,
        ["Ring23SCAddValueRate"] = 20,
        ["Ring23ACAddValueMaxLimit"] = 6,
        ["Ring23ACAddValueRate"] = 20,
        ["Ring23ACAddRate"] = 30,
        ["Ring23MACAddValueMaxLimit"] = 6,
        ["Ring23MACAddValueRate"] = 20,
        ["Ring23MACAddRate"] = 30,
        ["BootsDCAddValueMaxLimit"] = 6,
        ["BootsDCAddValueRate"] = 20,
        ["BootsDCAddRate"] = 30,
        ["BootsSCAddValueMaxLimit"] = 6,
        ["BootsSCAddValueRate"] = 20,
        ["BootsSCAddRate"] = 30,
        ["BootsMCAddValueMaxLimit"] = 6,
        ["BootsMCAddValueRate"] = 20,
        ["BootsMCAddRate"] = 30,
        ["BootsACAddValueMaxLimit"] = 6,
        ["BootsACAddValueRate"] = 20,
        ["BootsACAddRate"] = 30,
        ["BootsMACAddValueMaxLimit"] = 6,
        ["BootsMACAddValueRate"] = 20,
        ["BootsMACAddRate"] = 30,
        ["HelMetDCAddRate"] = 30,
        ["HelMetDCAddValueMaxLimit"] = 6,
        ["HelMetDCAddValueRate"] = 20,
        ["HelMetMCAddRate"] = 30,
        ["HelMetMCAddValueMaxLimit"] = 6,
        ["HelMetMCAddValueRate"] = 20,
        ["HelMetSCAddRate"] = 30,
        ["HelMetSCAddValueMaxLimit"] = 6,
        ["HelMetSCAddValueRate"] = 20,
        ["HelMetACAddValueMaxLimit"] = 6,
        ["HelMetACAddValueRate"] = 20,
        ["HelMetACAddRate"] = 30,
        ["HelMetMACAddValueMaxLimit"] = 6,
        ["HelMetMACAddValueRate"] = 20,
        ["HelMetMACAddRate"] = 30,
        ["FashionWeaponDCAddValueMaxLimit"] = 0,
        ["FashionWeaponDCAddValueRate"] = 0,
        ["FashionWeaponMCAddValueMaxLimit"] = 0,
        ["FashionWeaponMCAddValueRate"] = 0,
        ["FashionWeaponSCAddValueMaxLimit"] = 0,
        ["FashionWeaponSCAddValueRate"] = 0,
        ["FashionWeaponDCAddRate"] = 0,
        ["FashionWeaponSCAddRate"] = 0,
        ["FashionWeaponMCAddRate"] = 0,
        ["FashionWeaponHitSpeedAddValueMaxLimit"] = 0,
        ["FashionWeaponHitSpeedAddValueRate"] = 0,
        ["FashionWeaponHitSpeedAddRate"] = 0,
        ["FashionDressDCAddRate"] = 0,
        ["FashionDressDCAddValueMaxLimit"] = 0,
        ["FashionDressDCAddValueRate"] = 0,
        ["FashionDressMCAddRate"] = 0,
        ["FashionDressMCAddValueMaxLimit"] = 0,
        ["FashionDressMCAddValueRate"] = 0,
        ["FashionDressSCAddRate"] = 0,
        ["FashionDressSCAddValueMaxLimit"] = 0,
        ["FashionDressSCAddValueRate"] = 0,
        ["FashionDressACAddValueMaxLimit"] = 0,
        ["FashionDressACAddValueRate"] = 0,
        ["FashionDressACAddRate"] = 0,
        ["FashionDressMACAddValueMaxLimit"] = 0,
        ["FashionDressMACAddValueRate"] = 0,
        ["FashionDressMACAddRate"] = 0,
        ["HorseDCAddRate"] = 0,
        ["HorseDCAddValueMaxLimit"] = 0,
        ["HorseDCAddValueRate"] = 0,
        ["HorseMCAddRate"] = 0,
        ["HorseMCAddValueMaxLimit"] = 0,
        ["HorseMCAddValueRate"] = 0,
        ["HorseSCAddRate"] = 0,
        ["HorseSCAddValueMaxLimit"] = 0,
        ["HorseSCAddValueRate"] = 0,
        ["HorseACAddValueMaxLimit"] = 0,
        ["HorseACAddValueRate"] = 0,
        ["HorseACAddRate"] = 0,
        ["HorseMACAddValueMaxLimit"] = 0,
        ["HorseMACAddValueRate"] = 0,
        ["HorseMACAddRate"] = 0,
        ["DrumDCAddRate"] = 0,
        ["DrumDCAddValueMaxLimit"] = 0,
        ["DrumDCAddValueRate"] = 0,
        ["DrumMCAddRate"] = 0,
        ["DrumMCAddValueMaxLimit"] = 0,
        ["DrumMCAddValueRate"] = 0,
        ["DrumSCAddRate"] = 0,
        ["DrumSCAddValueMaxLimit"] = 0,
        ["DrumSCAddValueRate"] = 0,
        ["DrumACAddValueMaxLimit"] = 0,
        ["DrumACAddValueRate"] = 0,
        ["DrumACAddRate"] = 0,
        ["DrumMACAddValueMaxLimit"] = 0,
        ["DrumMACAddValueRate"] = 0,
        ["DrumMACAddRate"] = 0,
        ["ShieldDCAddRate"] = 0,
        ["ShieldDCAddValueMaxLimit"] = 0,
        ["ShieldDCAddValueRate"] = 0,
        ["ShieldMCAddRate"] = 0,
        ["ShieldMCAddValueMaxLimit"] = 0,
        ["ShieldMCAddValueRate"] = 0,
        ["ShieldSCAddRate"] = 0,
        ["ShieldSCAddValueMaxLimit"] = 0,
        ["ShieldSCAddValueRate"] = 0,
        ["ShieldACAddValueMaxLimit"] = 0,
        ["ShieldACAddValueRate"] = 0,
        ["ShieldACAddRate"] = 0,
        ["ShieldMACAddValueMaxLimit"] = 0,
        ["ShieldMACAddValueRate"] = 0,
        ["ShieldMACAddRate"] = 0,
    };
}
