// <auto-generated>
//     由脚本从 Delphi 原文抽取，禁止手工转录。
//     源：Source\Client-HGE\GUI\NewStateWin\StateWindows.pas 第 48-1238 行（interface 段 TStateWindows 的 182 条方法声明）。
// </auto-generated>

namespace GXX.Client.GUI.NewStateWin;

/// <summary>原文 interface 段方法声明的可见性（Delphi 默认 published 段）。</summary>
public enum TStateWindowsVisibility
{
    Private,
    Protected,
    Public,
    Published,
}

/// <summary>一条 Delphi 方法声明记录。</summary>
public sealed class TStateWindowsDecl
{
    public int Line;
    public TStateWindowsVisibility Visibility;
    public string Name = "";
    public string Signature = "";
}

/// <summary>
/// TStateWindows 方法声明清单（原文 48-1238 行 interface 段，182 条）。
/// 用途：保证 1:1 移植不漏方法，并锁住声明顺序与可见性。
/// </summary>
public static class TStateWindowsSurface
{
    /// <summary>interface 段方法声明条数。</summary>
    public const int DeclCount = 182;

    /// <summary>可见性+名字按 \n 连接后 UTF-8 的 SHA-256。</summary>
    public const string DeclSha256 = "89e459061a4ab9e4e55c76803b25c157b69ad07abe15338ec1c90aa46d32ba0a";

    /// <summary>按原文声明顺序的方法清单。</summary>
    public static readonly TStateWindowsDecl[] Decls =
    {
        new TStateWindowsDecl { Line = 965, Visibility = TStateWindowsVisibility.Private, Name = "InitSelf", Signature = "procedure InitSelf" },
        new TStateWindowsDecl { Line = 966, Visibility = TStateWindowsVisibility.Private, Name = "InitHero", Signature = "procedure InitHero" },
        new TStateWindowsDecl { Line = 967, Visibility = TStateWindowsVisibility.Private, Name = "InitUserState1", Signature = "procedure InitUserState1" },
        new TStateWindowsDecl { Line = 969, Visibility = TStateWindowsVisibility.Private, Name = "DRecallDeputyHeroClick", Signature = "procedure DRecallDeputyHeroClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 971, Visibility = TStateWindowsVisibility.Private, Name = "DStateWinUpDate", Signature = "procedure DStateWinUpDate(Sender:TObject)" },
        new TStateWindowsDecl { Line = 972, Visibility = TStateWindowsVisibility.Private, Name = "OnDStateWinBringToFront", Signature = "procedure OnDStateWinBringToFront(Sender:TObject)" },
        new TStateWindowsDecl { Line = 973, Visibility = TStateWindowsVisibility.Private, Name = "DBotAcupointsClick", Signature = "procedure DBotAcupointsClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 974, Visibility = TStateWindowsVisibility.Private, Name = "DBotMeridiansClick", Signature = "procedure DBotMeridiansClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 975, Visibility = TStateWindowsVisibility.Private, Name = "DMeridiansLineDirectPaint", Signature = "procedure DMeridiansLineDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 976, Visibility = TStateWindowsVisibility.Private, Name = "DBotAcupointsMouseMove", Signature = "procedure DBotAcupointsMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 978, Visibility = TStateWindowsVisibility.Private, Name = "DTrainingMeridianClick", Signature = "procedure DTrainingMeridianClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 980, Visibility = TStateWindowsVisibility.Private, Name = "DStateWinDirectPaint", Signature = "procedure DStateWinDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 982, Visibility = TStateWindowsVisibility.Private, Name = "DStateWinFashionDirectPaint", Signature = "procedure DStateWinFashionDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 984, Visibility = TStateWindowsVisibility.Private, Name = "DSWWeaponMouseMove", Signature = "procedure DSWWeaponMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 987, Visibility = TStateWindowsVisibility.Private, Name = "DCloseStateClick", Signature = "procedure DCloseStateClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 989, Visibility = TStateWindowsVisibility.Private, Name = "DUserState1DirectPaint", Signature = "procedure DUserState1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 990, Visibility = TStateWindowsVisibility.Private, Name = "DUserState1FashionDirectPaint", Signature = "procedure DUserState1FashionDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 992, Visibility = TStateWindowsVisibility.Private, Name = "DWeaponUS1MouseMove", Signature = "procedure DWeaponUS1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 994, Visibility = TStateWindowsVisibility.Private, Name = "DCloseUS1Click", Signature = "procedure DCloseUS1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 997, Visibility = TStateWindowsVisibility.Private, Name = "DHeroCloseStateClick", Signature = "procedure DHeroCloseStateClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 998, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateWinUpDate", Signature = "procedure DHeroStateWinUpDate(Sender:TObject)" },
        new TStateWindowsDecl { Line = 999, Visibility = TStateWindowsVisibility.Private, Name = "DHeroBotAcupointsClick", Signature = "procedure DHeroBotAcupointsClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1000, Visibility = TStateWindowsVisibility.Private, Name = "DHeroBotMeridiansClick", Signature = "procedure DHeroBotMeridiansClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1001, Visibility = TStateWindowsVisibility.Private, Name = "DHeroMeridiansLineDirectPaint", Signature = "procedure DHeroMeridiansLineDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1002, Visibility = TStateWindowsVisibility.Private, Name = "DHeroBotAcupointsMouseMove", Signature = "procedure DHeroBotAcupointsMouseMove(Sender:TObject; Shift:TShiftState; X," },
        new TStateWindowsDecl { Line = 1005, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateWinDirectPaint", Signature = "procedure DHeroStateWinDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1006, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateWinFashionDirectPaint", Signature = "procedure DHeroStateWinFashionDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1008, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWWeaponMouseMove", Signature = "procedure DHeroSWWeaponMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1010, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWLightDirectPaint", Signature = "procedure DHeroSWLightDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1011, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWWeaponClick", Signature = "procedure DHeroSWWeaponClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1013, Visibility = TStateWindowsVisibility.Private, Name = "DHeroTrainingMeridianClick", Signature = "procedure DHeroTrainingMeridianClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1015, Visibility = TStateWindowsVisibility.Private, Name = "DStateMagicDirectPaint", Signature = "procedure DStateMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1016, Visibility = TStateWindowsVisibility.Private, Name = "DStMag1DirectPaint", Signature = "procedure DStMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1017, Visibility = TStateWindowsVisibility.Private, Name = "DStMag1Click", Signature = "procedure DStMag1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1018, Visibility = TStateWindowsVisibility.Private, Name = "DStMag1MouseDown", Signature = "procedure DStMag1MouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1019, Visibility = TStateWindowsVisibility.Private, Name = "DStMag1MouseUp", Signature = "procedure DStMag1MouseUp(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1021, Visibility = TStateWindowsVisibility.Private, Name = "DStPageUpClick", Signature = "procedure DStPageUpClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1022, Visibility = TStateWindowsVisibility.Private, Name = "DStMagMouseMove", Signature = "procedure DStMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1023, Visibility = TStateWindowsVisibility.Private, Name = "MagicPageChange", Signature = "procedure MagicPageChange" },
        new TStateWindowsDecl { Line = 1026, Visibility = TStateWindowsVisibility.Private, Name = "DStateNGMagicDirectPaint", Signature = "procedure DStateNGMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1027, Visibility = TStateWindowsVisibility.Private, Name = "DStNGMag1DirectPaint", Signature = "procedure DStNGMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1028, Visibility = TStateWindowsVisibility.Private, Name = "DStNGMag1Click", Signature = "procedure DStNGMag1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1029, Visibility = TStateWindowsVisibility.Private, Name = "DStNGPageUpClick", Signature = "procedure DStNGPageUpClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1030, Visibility = TStateWindowsVisibility.Private, Name = "DStNGMagMouseMove", Signature = "procedure DStNGMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1031, Visibility = TStateWindowsVisibility.Private, Name = "NGMagicPageChange", Signature = "procedure NGMagicPageChange" },
        new TStateWindowsDecl { Line = 1033, Visibility = TStateWindowsVisibility.Private, Name = "DStateLJMagicDirectPaint", Signature = "procedure DStateLJMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1034, Visibility = TStateWindowsVisibility.Private, Name = "DStLJMag1DirectPaint", Signature = "procedure DStLJMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1035, Visibility = TStateWindowsVisibility.Private, Name = "DStLJMagMouseMove", Signature = "procedure DStLJMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1036, Visibility = TStateWindowsVisibility.Private, Name = "DSMB1DirectPaint", Signature = "procedure DSMB1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1037, Visibility = TStateWindowsVisibility.Private, Name = "DSMB1Click", Signature = "procedure DSMB1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1038, Visibility = TStateWindowsVisibility.Private, Name = "ContinuousMagicMenuClick", Signature = "procedure ContinuousMagicMenuClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1040, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateMagicDirectPaint", Signature = "procedure DHeroStateMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1041, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStMag1DirectPaint", Signature = "procedure DHeroStMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1042, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStMag1Click", Signature = "procedure DHeroStMag1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1043, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStPageUpClick", Signature = "procedure DHeroStPageUpClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1044, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStMagMouseMove", Signature = "procedure DHeroStMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1045, Visibility = TStateWindowsVisibility.Private, Name = "HeroMagicPageChange", Signature = "procedure HeroMagicPageChange" },
        new TStateWindowsDecl { Line = 1047, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateNGMagicDirectPaint", Signature = "procedure DHeroStateNGMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1048, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStNGMag1DirectPaint", Signature = "procedure DHeroStNGMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1049, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStNGMag1Click", Signature = "procedure DHeroStNGMag1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1050, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStNGPageUpClick", Signature = "procedure DHeroStNGPageUpClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1051, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStNGMagMouseMove", Signature = "procedure DHeroStNGMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1052, Visibility = TStateWindowsVisibility.Private, Name = "HeroNGMagicPageChange", Signature = "procedure HeroNGMagicPageChange" },
        new TStateWindowsDecl { Line = 1054, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStateLJMagicDirectPaint", Signature = "procedure DHeroStateLJMagicDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1055, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStLJMag1DirectPaint", Signature = "procedure DHeroStLJMag1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1056, Visibility = TStateWindowsVisibility.Private, Name = "DHeroStLJMagMouseMove", Signature = "procedure DHeroStLJMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1057, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSMB1DirectPaint", Signature = "procedure DHeroSMB1DirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1058, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSMB1Click", Signature = "procedure DHeroSMB1Click(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1059, Visibility = TStateWindowsVisibility.Private, Name = "HeroContinuousMagicMenuClick", Signature = "procedure HeroContinuousMagicMenuClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1062, Visibility = TStateWindowsVisibility.Private, Name = "DSMBShortcutClick", Signature = "procedure DSMBShortcutClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1064, Visibility = TStateWindowsVisibility.Private, Name = "LabelDStateWinCharNameClick", Signature = "procedure LabelDStateWinCharNameClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1066, Visibility = TStateWindowsVisibility.Private, Name = "DSWJewelryBoxClick", Signature = "procedure DSWJewelryBoxClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1067, Visibility = TStateWindowsVisibility.Private, Name = "DSWJewelryBoxMouseMove", Signature = "procedure DSWJewelryBoxMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1069, Visibility = TStateWindowsVisibility.Private, Name = "DSWJewelryBoxItemClick", Signature = "procedure DSWJewelryBoxItemClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1070, Visibility = TStateWindowsVisibility.Private, Name = "DSWJewelryBoxItemMouseMove", Signature = "procedure DSWJewelryBoxItemMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1072, Visibility = TStateWindowsVisibility.Private, Name = "DSWJewelryBoxItemPaint", Signature = "procedure DSWJewelryBoxItemPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1074, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWJewelryBoxItemClick", Signature = "procedure DHeroSWJewelryBoxItemClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1075, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWJewelryBoxItemMouseMove", Signature = "procedure DHeroSWJewelryBoxItemMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1077, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWJewelryBoxItemPaint", Signature = "procedure DHeroSWJewelryBoxItemPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1079, Visibility = TStateWindowsVisibility.Private, Name = "DJewelryBoxItemUS1MouseMove", Signature = "procedure DJewelryBoxItemUS1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1081, Visibility = TStateWindowsVisibility.Private, Name = "DJewelryBoxItemPaintUS1", Signature = "procedure DJewelryBoxItemPaintUS1(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1083, Visibility = TStateWindowsVisibility.Private, Name = "DSWGodBlessClick", Signature = "procedure DSWGodBlessClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1084, Visibility = TStateWindowsVisibility.Private, Name = "DSWGodBlessItemClick", Signature = "procedure DSWGodBlessItemClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1085, Visibility = TStateWindowsVisibility.Private, Name = "DSWGodBlessItemMouseMove", Signature = "procedure DSWGodBlessItemMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1087, Visibility = TStateWindowsVisibility.Private, Name = "DSWGodBlessItemPaint", Signature = "procedure DSWGodBlessItemPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1089, Visibility = TStateWindowsVisibility.Private, Name = "DSWGodBlessUpgradeClick", Signature = "procedure DSWGodBlessUpgradeClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1091, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWGodBlessItemClick", Signature = "procedure DHeroSWGodBlessItemClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1092, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWGodBlessItemMouseMove", Signature = "procedure DHeroSWGodBlessItemMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1094, Visibility = TStateWindowsVisibility.Private, Name = "DHeroSWGodBlessItemPaint", Signature = "procedure DHeroSWGodBlessItemPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1096, Visibility = TStateWindowsVisibility.Private, Name = "DGodBlessItemUS1MouseMove", Signature = "procedure DGodBlessItemUS1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1098, Visibility = TStateWindowsVisibility.Private, Name = "DGodBlessItemUS1Paint", Signature = "procedure DGodBlessItemUS1Paint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1100, Visibility = TStateWindowsVisibility.Private, Name = "DSWShowFashionClick", Signature = "procedure DSWShowFashionClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1103, Visibility = TStateWindowsVisibility.Private, Name = "DStateTitleWinMouseMove", Signature = "procedure DStateTitleWinMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1105, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleItemDescOnPaint", Signature = "procedure DSTitleItemDescOnPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1107, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleActiveClick", Signature = "procedure DSTitleActiveClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1108, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleActiveMouseMove", Signature = "procedure DSTitleActiveMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1109, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleActiveDirectPaint", Signature = "procedure DSTitleActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1111, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleButtonClick", Signature = "procedure DSTitleButtonClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1112, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleButtonMouseMove", Signature = "procedure DSTitleButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1113, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleButtonDirectPaint", Signature = "procedure DSTitleButtonDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1115, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleNameActiveDirectPaint", Signature = "procedure DSTitleNameActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1116, Visibility = TStateWindowsVisibility.Private, Name = "DSTitleNameDirectPaint", Signature = "procedure DSTitleNameDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1117, Visibility = TStateWindowsVisibility.Private, Name = "DSTitlePageClick", Signature = "procedure DSTitlePageClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1119, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleItemDescOnPaint", Signature = "procedure DUSTitleItemDescOnPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1120, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleActiveDirectPaint", Signature = "procedure DUSTitleActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1121, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleAcitveMouseMove", Signature = "procedure DUSTitleAcitveMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1122, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleButtonMouseMove", Signature = "procedure DUSTitleButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1123, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleButtonDirectPaint", Signature = "procedure DUSTitleButtonDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1124, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleNameActiveDirectPaint", Signature = "procedure DUSTitleNameActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1125, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitleNameDirectPaint", Signature = "procedure DUSTitleNameDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1126, Visibility = TStateWindowsVisibility.Private, Name = "DUSTitlePageClick", Signature = "procedure DUSTitlePageClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1128, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleActiveClick", Signature = "procedure DSHeroTitleActiveClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1129, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleActiveMouseMove", Signature = "procedure DSHeroTitleActiveMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1130, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleActiveDirectPaint", Signature = "procedure DSHeroTitleActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1132, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleButtonClick", Signature = "procedure DSHeroTitleButtonClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1133, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleButtonMouseMove", Signature = "procedure DSHeroTitleButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1134, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleButtonDirectPaint", Signature = "procedure DSHeroTitleButtonDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1136, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleNameActiveDirectPaint", Signature = "procedure DSHeroTitleNameActiveDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1137, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitleNameDirectPaint", Signature = "procedure DSHeroTitleNameDirectPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1138, Visibility = TStateWindowsVisibility.Private, Name = "DSHeroTitlePageClick", Signature = "procedure DSHeroTitlePageClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1140, Visibility = TStateWindowsVisibility.Private, Name = "UpdateSelectPetsInfo", Signature = "procedure UpdateSelectPetsInfo" },
        new TStateWindowsDecl { Line = 1144, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsClick", Signature = "procedure DSWPetsClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1145, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsCloseClick", Signature = "procedure DSWPetsCloseClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1146, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsButtonClick", Signature = "procedure DSWPetsButtonClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1148, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsShowStopPaint", Signature = "procedure DSWPetsShowStopPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1150, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsListViewItemPaint", Signature = "procedure DSWPetsListViewItemPaint(Sender:TObject; ACol, ARow:Integer; ARect:TRect; ViewItem:Pointer; var PaintOverride:Boolean)" },
        new TStateWindowsDecl { Line = 1151, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsListViewItemClick", Signature = "procedure DSWPetsListViewItemClick(Sender:TObject; ARow, ACol:Integer; ListItem:TObject; ViewItem:Pointer)" },
        new TStateWindowsDecl { Line = 1154, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsItemMouseMove", Signature = "procedure DSWPetsItemMouseMove(Sender: TObject; Shift: TShiftState; X, Y: Integer)" },
        new TStateWindowsDecl { Line = 1155, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsItemClick", Signature = "procedure DSWPetsItemClick(Sender: TObject; X, Y: Integer)" },
        new TStateWindowsDecl { Line = 1156, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsItemPaint", Signature = "procedure DSWPetsItemPaint(Sender: TObject)" },
        new TStateWindowsDecl { Line = 1159, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsMagicMouseMove", Signature = "procedure DSWPetsMagicMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1160, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsMagicClick", Signature = "procedure DSWPetsMagicClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1161, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsMagicPaint", Signature = "procedure DSWPetsMagicPaint(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1163, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsBagCloseClick", Signature = "procedure DSWPetsBagCloseClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1165, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsGridGridSelect", Signature = "procedure DSWPetsGridGridSelect(Sender:TObject; ACol, ARow:Integer; Button:TMouseButton; Shift:TShiftState)" },
        new TStateWindowsDecl { Line = 1167, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsGridGridPaint", Signature = "procedure DSWPetsGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState)" },
        new TStateWindowsDecl { Line = 1169, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsGridDblClick", Signature = "procedure DSWPetsGridDblClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1170, Visibility = TStateWindowsVisibility.Private, Name = "DSWPetsGridGridMouseMove", Signature = "procedure DSWPetsGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState)" },
        new TStateWindowsDecl { Line = 1173, Visibility = TStateWindowsVisibility.Private, Name = "DControlMouseMoveShowHint", Signature = "procedure DControlMouseMoveShowHint(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1176, Visibility = TStateWindowsVisibility.Private, Name = "OnDStateWinExClick", Signature = "procedure OnDStateWinExClick(Sender:TObject; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1177, Visibility = TStateWindowsVisibility.Private, Name = "DStateWinMove", Signature = "procedure DStateWinMove(Sender:TObject)" },
        new TStateWindowsDecl { Line = 1178, Visibility = TStateWindowsVisibility.Private, Name = "RefreshDStateWinExInfo", Signature = "procedure RefreshDStateWinExInfo" },
        new TStateWindowsDecl { Line = 1180, Visibility = TStateWindowsVisibility.Protected, Name = "DSWPetsDlgMouseMove", Signature = "procedure DSWPetsDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer)" },
        new TStateWindowsDecl { Line = 1182, Visibility = TStateWindowsVisibility.Public, Name = "Create", Signature = "constructor Create()" },
        new TStateWindowsDecl { Line = 1183, Visibility = TStateWindowsVisibility.Public, Name = "Destroy", Signature = "destructor Destroy" },
        new TStateWindowsDecl { Line = 1184, Visibility = TStateWindowsVisibility.Public, Name = "Initialize", Signature = "procedure Initialize" },
        new TStateWindowsDecl { Line = 1185, Visibility = TStateWindowsVisibility.Public, Name = "Close", Signature = "procedure Close" },
        new TStateWindowsDecl { Line = 1186, Visibility = TStateWindowsVisibility.Public, Name = "UpDate", Signature = "procedure UpDate" },
        new TStateWindowsDecl { Line = 1187, Visibility = TStateWindowsVisibility.Public, Name = "LoadFromStream", Signature = "procedure LoadFromStream(MemoryStream:TMemoryStream)" },
        new TStateWindowsDecl { Line = 1188, Visibility = TStateWindowsVisibility.Public, Name = "MakeControlAddressList", Signature = "function MakeControlAddressList:THashedStringlist" },
        new TStateWindowsDecl { Line = 1190, Visibility = TStateWindowsVisibility.Public, Name = "RefreshGamePetList", Signature = "procedure RefreshGamePetList" },
        new TStateWindowsDecl { Line = 1192, Visibility = TStateWindowsVisibility.Public, Name = "OpenStateWinDlg", Signature = "procedure OpenStateWinDlg" },
        new TStateWindowsDecl { Line = 1193, Visibility = TStateWindowsVisibility.Public, Name = "CloseStateWinDlg", Signature = "procedure CloseStateWinDlg" },
        new TStateWindowsDecl { Line = 1195, Visibility = TStateWindowsVisibility.Public, Name = "OpenUserState1Dlg", Signature = "procedure OpenUserState1Dlg" },
        new TStateWindowsDecl { Line = 1196, Visibility = TStateWindowsVisibility.Public, Name = "CloseUserState1Dlg", Signature = "procedure CloseUserState1Dlg" },
        new TStateWindowsDecl { Line = 1198, Visibility = TStateWindowsVisibility.Public, Name = "OpenMyStatus", Signature = "procedure OpenMyStatus" },
        new TStateWindowsDecl { Line = 1199, Visibility = TStateWindowsVisibility.Public, Name = "OpenMyMagic", Signature = "procedure OpenMyMagic" },
        new TStateWindowsDecl { Line = 1200, Visibility = TStateWindowsVisibility.Public, Name = "OpenUserState", Signature = "procedure OpenUserState()" },
        new TStateWindowsDecl { Line = 1202, Visibility = TStateWindowsVisibility.Public, Name = "OpenGamePetDlg", Signature = "procedure OpenGamePetDlg()" },
        new TStateWindowsDecl { Line = 1204, Visibility = TStateWindowsVisibility.Public, Name = "MySelfAbilChange", Signature = "procedure MySelfAbilChange" },
        new TStateWindowsDecl { Line = 1206, Visibility = TStateWindowsVisibility.Public, Name = "MyHeroAbilChange", Signature = "procedure MyHeroAbilChange" },
        new TStateWindowsDecl { Line = 1208, Visibility = TStateWindowsVisibility.Public, Name = "OpenHeroStateWinDlg", Signature = "procedure OpenHeroStateWinDlg" },
        new TStateWindowsDecl { Line = 1209, Visibility = TStateWindowsVisibility.Public, Name = "CloseHeroStateWinDlg", Signature = "procedure CloseHeroStateWinDlg" },
        new TStateWindowsDecl { Line = 1211, Visibility = TStateWindowsVisibility.Public, Name = "SetMeridiansLevel", Signature = "procedure SetMeridiansLevel(Meridian, Level:Integer)" },
        new TStateWindowsDecl { Line = 1212, Visibility = TStateWindowsVisibility.Public, Name = "SetHeroMeridiansLevel", Signature = "procedure SetHeroMeridiansLevel(Meridian, Level:Integer)" },
        new TStateWindowsDecl { Line = 1214, Visibility = TStateWindowsVisibility.Public, Name = "RefreshMySelfMagicList", Signature = "procedure RefreshMySelfMagicList" },
        new TStateWindowsDecl { Line = 1215, Visibility = TStateWindowsVisibility.Public, Name = "RefreshMyHeroMagicList", Signature = "procedure RefreshMyHeroMagicList" },
        new TStateWindowsDecl { Line = 1217, Visibility = TStateWindowsVisibility.Public, Name = "SetDeputyHeroJob", Signature = "procedure SetDeputyHeroJob(btJob:Byte)" },
        new TStateWindowsDecl { Line = 1219, Visibility = TStateWindowsVisibility.Public, Name = "SetMySelfActivePageIndexCount", Signature = "procedure SetMySelfActivePageIndexCount" },
        new TStateWindowsDecl { Line = 1220, Visibility = TStateWindowsVisibility.Public, Name = "SetMyHeroActivePageIndexCount", Signature = "procedure SetMyHeroActivePageIndexCount" },
        new TStateWindowsDecl { Line = 1222, Visibility = TStateWindowsVisibility.Public, Name = "ChangeMySelfMeridiansctivePage", Signature = "procedure ChangeMySelfMeridiansctivePage" },
        new TStateWindowsDecl { Line = 1223, Visibility = TStateWindowsVisibility.Public, Name = "ChangeMyHeroMeridiansctivePage", Signature = "procedure ChangeMyHeroMeridiansctivePage" },
        new TStateWindowsDecl { Line = 1225, Visibility = TStateWindowsVisibility.Public, Name = "SetMySelfLastContinuousButton", Signature = "procedure SetMySelfLastContinuousButton" },
        new TStateWindowsDecl { Line = 1226, Visibility = TStateWindowsVisibility.Public, Name = "SetMyHeroLastContinuousButton", Signature = "procedure SetMyHeroLastContinuousButton" },
        new TStateWindowsDecl { Line = 1228, Visibility = TStateWindowsVisibility.Public, Name = "SetMySelfJewelryBoxButton", Signature = "procedure SetMySelfJewelryBoxButton" },
        new TStateWindowsDecl { Line = 1229, Visibility = TStateWindowsVisibility.Public, Name = "SetMyHeroJewelryBoxButton", Signature = "procedure SetMyHeroJewelryBoxButton" },
        new TStateWindowsDecl { Line = 1231, Visibility = TStateWindowsVisibility.Public, Name = "RefreshUpgradeButtons", Signature = "procedure RefreshUpgradeButtons" },
        new TStateWindowsDecl { Line = 1232, Visibility = TStateWindowsVisibility.Public, Name = "RefreshHeroUpgradeButtons", Signature = "procedure RefreshHeroUpgradeButtons" },
        new TStateWindowsDecl { Line = 1234, Visibility = TStateWindowsVisibility.Public, Name = "RefreshFashionJewelryInfo", Signature = "procedure RefreshFashionJewelryInfo" },
        new TStateWindowsDecl { Line = 1235, Visibility = TStateWindowsVisibility.Public, Name = "RefreshMyFashionJewelryInfo", Signature = "procedure RefreshMyFashionJewelryInfo" },
        new TStateWindowsDecl { Line = 1236, Visibility = TStateWindowsVisibility.Public, Name = "RefreshHeroFashionJewelryInfo", Signature = "procedure RefreshHeroFashionJewelryInfo" },
        new TStateWindowsDecl { Line = 1237, Visibility = TStateWindowsVisibility.Public, Name = "RefreshUserFashionJewelryInfo", Signature = "procedure RefreshUserFashionJewelryInfo" },
    };

    /// <summary>原文 1182-1237 行的 public 段方法名（39 条），供外部调用面审计。</summary>
    public static readonly string[] PublicNames =
    {
        "Create", // 行 1182
        "Destroy", // 行 1183
        "Initialize", // 行 1184
        "Close", // 行 1185
        "UpDate", // 行 1186
        "LoadFromStream", // 行 1187
        "MakeControlAddressList", // 行 1188
        "RefreshGamePetList", // 行 1190
        "OpenStateWinDlg", // 行 1192
        "CloseStateWinDlg", // 行 1193
        "OpenUserState1Dlg", // 行 1195
        "CloseUserState1Dlg", // 行 1196
        "OpenMyStatus", // 行 1198
        "OpenMyMagic", // 行 1199
        "OpenUserState", // 行 1200
        "OpenGamePetDlg", // 行 1202
        "MySelfAbilChange", // 行 1204
        "MyHeroAbilChange", // 行 1206
        "OpenHeroStateWinDlg", // 行 1208
        "CloseHeroStateWinDlg", // 行 1209
        "SetMeridiansLevel", // 行 1211
        "SetHeroMeridiansLevel", // 行 1212
        "RefreshMySelfMagicList", // 行 1214
        "RefreshMyHeroMagicList", // 行 1215
        "SetDeputyHeroJob", // 行 1217
        "SetMySelfActivePageIndexCount", // 行 1219
        "SetMyHeroActivePageIndexCount", // 行 1220
        "ChangeMySelfMeridiansctivePage", // 行 1222
        "ChangeMyHeroMeridiansctivePage", // 行 1223
        "SetMySelfLastContinuousButton", // 行 1225
        "SetMyHeroLastContinuousButton", // 行 1226
        "SetMySelfJewelryBoxButton", // 行 1228
        "SetMyHeroJewelryBoxButton", // 行 1229
        "RefreshUpgradeButtons", // 行 1231
        "RefreshHeroUpgradeButtons", // 行 1232
        "RefreshFashionJewelryInfo", // 行 1234
        "RefreshMyFashionJewelryInfo", // 行 1235
        "RefreshHeroFashionJewelryInfo", // 行 1236
        "RefreshUserFashionJewelryInfo", // 行 1237
    };

    /// <summary>原文 965-1178 行的 private 段方法名（142 条）。</summary>
    public static readonly string[] PrivateNames =
    {
        "InitSelf", // 行 965
        "InitHero", // 行 966
        "InitUserState1", // 行 967
        "DRecallDeputyHeroClick", // 行 969
        "DStateWinUpDate", // 行 971
        "OnDStateWinBringToFront", // 行 972
        "DBotAcupointsClick", // 行 973
        "DBotMeridiansClick", // 行 974
        "DMeridiansLineDirectPaint", // 行 975
        "DBotAcupointsMouseMove", // 行 976
        "DTrainingMeridianClick", // 行 978
        "DStateWinDirectPaint", // 行 980
        "DStateWinFashionDirectPaint", // 行 982
        "DSWWeaponMouseMove", // 行 984
        "DCloseStateClick", // 行 987
        "DUserState1DirectPaint", // 行 989
        "DUserState1FashionDirectPaint", // 行 990
        "DWeaponUS1MouseMove", // 行 992
        "DCloseUS1Click", // 行 994
        "DHeroCloseStateClick", // 行 997
        "DHeroStateWinUpDate", // 行 998
        "DHeroBotAcupointsClick", // 行 999
        "DHeroBotMeridiansClick", // 行 1000
        "DHeroMeridiansLineDirectPaint", // 行 1001
        "DHeroBotAcupointsMouseMove", // 行 1002
        "DHeroStateWinDirectPaint", // 行 1005
        "DHeroStateWinFashionDirectPaint", // 行 1006
        "DHeroSWWeaponMouseMove", // 行 1008
        "DHeroSWLightDirectPaint", // 行 1010
        "DHeroSWWeaponClick", // 行 1011
        "DHeroTrainingMeridianClick", // 行 1013
        "DStateMagicDirectPaint", // 行 1015
        "DStMag1DirectPaint", // 行 1016
        "DStMag1Click", // 行 1017
        "DStMag1MouseDown", // 行 1018
        "DStMag1MouseUp", // 行 1019
        "DStPageUpClick", // 行 1021
        "DStMagMouseMove", // 行 1022
        "MagicPageChange", // 行 1023
        "DStateNGMagicDirectPaint", // 行 1026
        "DStNGMag1DirectPaint", // 行 1027
        "DStNGMag1Click", // 行 1028
        "DStNGPageUpClick", // 行 1029
        "DStNGMagMouseMove", // 行 1030
        "NGMagicPageChange", // 行 1031
        "DStateLJMagicDirectPaint", // 行 1033
        "DStLJMag1DirectPaint", // 行 1034
        "DStLJMagMouseMove", // 行 1035
        "DSMB1DirectPaint", // 行 1036
        "DSMB1Click", // 行 1037
        "ContinuousMagicMenuClick", // 行 1038
        "DHeroStateMagicDirectPaint", // 行 1040
        "DHeroStMag1DirectPaint", // 行 1041
        "DHeroStMag1Click", // 行 1042
        "DHeroStPageUpClick", // 行 1043
        "DHeroStMagMouseMove", // 行 1044
        "HeroMagicPageChange", // 行 1045
        "DHeroStateNGMagicDirectPaint", // 行 1047
        "DHeroStNGMag1DirectPaint", // 行 1048
        "DHeroStNGMag1Click", // 行 1049
        "DHeroStNGPageUpClick", // 行 1050
        "DHeroStNGMagMouseMove", // 行 1051
        "HeroNGMagicPageChange", // 行 1052
        "DHeroStateLJMagicDirectPaint", // 行 1054
        "DHeroStLJMag1DirectPaint", // 行 1055
        "DHeroStLJMagMouseMove", // 行 1056
        "DHeroSMB1DirectPaint", // 行 1057
        "DHeroSMB1Click", // 行 1058
        "HeroContinuousMagicMenuClick", // 行 1059
        "DSMBShortcutClick", // 行 1062
        "LabelDStateWinCharNameClick", // 行 1064
        "DSWJewelryBoxClick", // 行 1066
        "DSWJewelryBoxMouseMove", // 行 1067
        "DSWJewelryBoxItemClick", // 行 1069
        "DSWJewelryBoxItemMouseMove", // 行 1070
        "DSWJewelryBoxItemPaint", // 行 1072
        "DHeroSWJewelryBoxItemClick", // 行 1074
        "DHeroSWJewelryBoxItemMouseMove", // 行 1075
        "DHeroSWJewelryBoxItemPaint", // 行 1077
        "DJewelryBoxItemUS1MouseMove", // 行 1079
        "DJewelryBoxItemPaintUS1", // 行 1081
        "DSWGodBlessClick", // 行 1083
        "DSWGodBlessItemClick", // 行 1084
        "DSWGodBlessItemMouseMove", // 行 1085
        "DSWGodBlessItemPaint", // 行 1087
        "DSWGodBlessUpgradeClick", // 行 1089
        "DHeroSWGodBlessItemClick", // 行 1091
        "DHeroSWGodBlessItemMouseMove", // 行 1092
        "DHeroSWGodBlessItemPaint", // 行 1094
        "DGodBlessItemUS1MouseMove", // 行 1096
        "DGodBlessItemUS1Paint", // 行 1098
        "DSWShowFashionClick", // 行 1100
        "DStateTitleWinMouseMove", // 行 1103
        "DSTitleItemDescOnPaint", // 行 1105
        "DSTitleActiveClick", // 行 1107
        "DSTitleActiveMouseMove", // 行 1108
        "DSTitleActiveDirectPaint", // 行 1109
        "DSTitleButtonClick", // 行 1111
        "DSTitleButtonMouseMove", // 行 1112
        "DSTitleButtonDirectPaint", // 行 1113
        "DSTitleNameActiveDirectPaint", // 行 1115
        "DSTitleNameDirectPaint", // 行 1116
        "DSTitlePageClick", // 行 1117
        "DUSTitleItemDescOnPaint", // 行 1119
        "DUSTitleActiveDirectPaint", // 行 1120
        "DUSTitleAcitveMouseMove", // 行 1121
        "DUSTitleButtonMouseMove", // 行 1122
        "DUSTitleButtonDirectPaint", // 行 1123
        "DUSTitleNameActiveDirectPaint", // 行 1124
        "DUSTitleNameDirectPaint", // 行 1125
        "DUSTitlePageClick", // 行 1126
        "DSHeroTitleActiveClick", // 行 1128
        "DSHeroTitleActiveMouseMove", // 行 1129
        "DSHeroTitleActiveDirectPaint", // 行 1130
        "DSHeroTitleButtonClick", // 行 1132
        "DSHeroTitleButtonMouseMove", // 行 1133
        "DSHeroTitleButtonDirectPaint", // 行 1134
        "DSHeroTitleNameActiveDirectPaint", // 行 1136
        "DSHeroTitleNameDirectPaint", // 行 1137
        "DSHeroTitlePageClick", // 行 1138
        "UpdateSelectPetsInfo", // 行 1140
        "DSWPetsClick", // 行 1144
        "DSWPetsCloseClick", // 行 1145
        "DSWPetsButtonClick", // 行 1146
        "DSWPetsShowStopPaint", // 行 1148
        "DSWPetsListViewItemPaint", // 行 1150
        "DSWPetsListViewItemClick", // 行 1151
        "DSWPetsItemMouseMove", // 行 1154
        "DSWPetsItemClick", // 行 1155
        "DSWPetsItemPaint", // 行 1156
        "DSWPetsMagicMouseMove", // 行 1159
        "DSWPetsMagicClick", // 行 1160
        "DSWPetsMagicPaint", // 行 1161
        "DSWPetsBagCloseClick", // 行 1163
        "DSWPetsGridGridSelect", // 行 1165
        "DSWPetsGridGridPaint", // 行 1167
        "DSWPetsGridDblClick", // 行 1169
        "DSWPetsGridGridMouseMove", // 行 1170
        "DControlMouseMoveShowHint", // 行 1173
        "OnDStateWinExClick", // 行 1176
        "DStateWinMove", // 行 1177
        "RefreshDStateWinExInfo", // 行 1178
    };

    /// <summary>原文 1180 行的 protected 段方法名（1 条）。</summary>
    public static readonly string[] ProtectedNames =
    {
        "DSWPetsDlgMouseMove", // 行 1180
    };
}
