// <auto-generated by tools/gen/GenMySqlRoleDbSql.ps1 - DO NOT EDIT BY HAND
// Source: Source\DBServer\MySqlRoleDB.pas (GBK). Extracted mechanically from the verbatim
// `FStatement*.Sql := ...` concatenations; every constant below is byte-identical to the source
// (spaces, case, backticks and CRLF included). The AddSQLStatement name is kept alongside.

namespace GXX.DBServer;

/// <summary>
/// SQL literals of MySqlRoleDB.pas (TMySqlHumanDB.DoInit / TMySqlHeroDB.DoInit, one per statement).
/// </summary>
public static class MySqlRoleDBStatements
{
    // ============================================================================
    // TMySqlHumanDB.DoInit  MySqlRoleDB.pas:256-644   (86 statements)
    // ============================================================================
    public static class Human
    {
        /// <summary>HumanGetID</summary>
        public const string FStatementGetID =
            "select HumanID from Human where HumanName = ?;";

        /// <summary>CheckHumanExists</summary>
        public const string FStatementCheckHumanExists =
            "select HumanID from Human where Account = ? and HumanName = ?;";

        /// <summary>HumanGetCount</summary>
        public const string FStatementGetHumanCount =
            "select count(*) from Human where (Account = ?) and (IsDelete = 0);";

        /// <summary>GetOtherHumanName</summary>
        public const string FStatementGetOtherHumanName =
            "select HumanName from Human where (Account = ?) and (HumanName <> ?) and (IsDelete = 0);";

        /// <summary>HumanGetHumanHeroName</summary>
        public const string FStatementGetHumanHeroName =
            "select HeroName, DeputyHeroName from Human where (HumanName = ?);";

        /// <summary>HumanGetHumanHeroID</summary>
        public const string FStatementGetHumanHeroID =
            "select HeroID from Hero where (HumanID = ?);";

        /// <summary>HumanGetHumanGoldInfo</summary>
        public const string FStatementGetHumanGoldInfo =
            "Select Gold, GameGold, GamePoint, GameDiamond, GameGird from Human where (HumanName = ?);";

        /// <summary>HumanUpdateHumanGoldInfo</summary>
        public const string FStatementUpdateHumanGoldInfo =
            "update Human set Gold = ?,GameGold = ?,GamePoint = ?,GameDiamond = ?, GameGird = ? where (HumanName = ?);";

        /// <summary>HumanGetBaseInfo</summary>
        public const string FStatementGetHumanBaseInfo =
            "select Sex, Job, Level, LoginDate from Human where HumanName = ?;";

        /// <summary>HumanQuery</summary>
        public const string FStatementQueryHumans =
            "select a.HumanName, a.IsSelect, a.Sex, a.Job, a.Hair, a.Level from Human a where (Account = ?) and (IsDelete = ?);";

        /// <summary>HumanSearchByAccount1</summary>
        public const string FStatementSearchByAccountMatchComplete =
            "select a.Account, a.HumanName, a.IsDelete, a.Sex, a.Job, a.Level from Human a where (Account = ?);";

        /// <summary>HumanSearchByAccount2</summary>
        public const string FStatementSearchByAccountMatchFuzzy =
            "select a.Account, a.HumanName, a.IsDelete, a.Sex, a.Job, a.Level from Human a where (Account like ?);";

        /// <summary>HumanSearchByName1</summary>
        public const string FStatementSearchByNameMatchComplete =
            "select a.Account, a.HumanName, a.IsDelete, a.Sex, a.Job, a.Level from Human a where (HumanName = ?);";

        /// <summary>HumanSearchByName2</summary>
        public const string FStatementSearchByNameMatchFuzzy =
            "select a.Account, a.HumanName, a.IsDelete, a.Sex, a.Job, a.Level from Human a where (HumanName like ?);";

        /// <summary>HumanSearchByLevel</summary>
        public const string FStatementSearchByLevel =
            "select a.Account, a.HumanName, a.IsDelete, a.Sex, a.Job, a.Level from Human a where (a.Level >= ?) LIMIT ?;";

        /// <summary>HumanGetMobileNumbers1</summary>
        public const string FStatementGetMobileNumbers1 =
            "SELECT DISTINCT MobileNumber FROM  Human WHERE Length(MobileNumber) > 0;";

        /// <summary>HumanGetMobileNumbers2</summary>
        public const string FStatementGetMobileNumbers2 =
            "select DISTINCT MobileNumber from Human where (Length(MobileNumber) > 0) and (IsMobileBind = 1);";

        /// <summary>HumanSetSelect</summary>
        public const string FStatementSelect =
            "update Human set IsSelect = 1 where (Account = ?) and (HumanName = ?);";

        /// <summary>HumanSetUnSelect</summary>
        public const string FStatementUnSelect =
            "update Human set IsSelect = 0 where (Account = ?) and (HumanName <> ?);";

        /// <summary>HumanSelect</summary>
        public const string FStatementGetHuman =
            "select HumanID,Account,HumanName,Sex,Job,Hair,Dir,Level,ReLevel,Map,X,Y,HomeMap,HomeX,HomeY,AttackMode,StoragePassword,CreditPoint,Gold,GameGold,GamePoint,GameDiamond,GameGird,GameGoldEx,GameGlory,PKPoint,PayMentPoint,MemberType,MemberLevel,IsMaster,MasterName,MasterCount,MarryCount,DearName,IncHP,IncMP,IncHP2,FightZoneDieCount,BodyLuck,Contribution,HungerStatus,KickCount,IsLockLogin,IsAllowGroup,IsAllowGroupRecall,GroupRecallTime,IsAllowGuildReCall,IsDisableTrading,IsDisableInviteHorseRiding,IsGameGoldTrading,IsNewServer,IsFilterGlobalDropItemMsg,IsFilterGlobalCenterMsg,IsFilterGolbalSendMsg,IsFixedHero,IsStorageHero,IsStorageDeputyHero,HeroName,DeputyHeroName,DeputyHeroJob,Nation,NationCredit,RevivalTime,InfinityStorageExtCount,IsSaveKillMonExpRate,KillMonExpRate,KillMonExpRateTime,IsSavePowerRate,PowerRate,PowerRateTime,IsAttackMonSavePowerRate,AttackMonPowerRate,AttackMonPowerRateTime,IsSaveKillMonBurstRate,KillMonBurstRate,KillMonBurstRateTime,FBCreateTime,JewelryBoxStatus,IsShowFashion,IsShowGodBless,ActiveFengHao,IsOpenStorage1,IsOpenStorage2,IsOpenStorage3,ExtBagPageCount,ExtBagOpenItemCount,AddMaxWeight,HighLevelKillMonFixExpTimeLeft,MobileNumber,IsMobileBind,MobileVerifyCode,MobileSendTick,MobileResendCount, ClearDayVarTime from Human where (Account = ?) and (HumanName = ?);";

        /// <summary>HumanSelectAbil</summary>
        public const string FStatementGetAbil =
            "select AC1,AC2,MAC1,MAC2,DC1,DC2,MC1,MC2,SC1,SC2,HP,MaxHP,MP,MaxMP,Exp,MaxExp,Weight,MaxWeight,WearWeight,MaxWearWeight,HandWeight,MaxHandWeight,AdjustAbilPoint,AdjustAbilDC,AdjustAbilMC,AdjustAbilSC,AdjustAbilAC,AdjustAbilMAC,AdjustAbilHP,AdjustAbilMP,AdjustAbilHit,AdjustAbilSpeed,AdjustAbilMaxRate from HumanAbil where HumanID = ?;";

        /// <summary>HumanSelectAbilNG</summary>
        public const string FStatementGetAbilNG =
            "select IsTrainingNG,IsTrainingXF,AbilNGLevel,AbilNGValue,AbilNGMaxValue,AbilNGExp,AbilNGMaxExp,ContinuousMagicOrder1,ContinuousMagicOrder2,ContinuousMagicOrder3,IsOpenLastContinuous,LastContinuousMagicOrder,Meridians1Level,Meridians1BlastHitRate1,Meridians1Acupoints1,Meridians1Acupoints2,Meridians1Acupoints3,Meridians1Acupoints4,Meridians1Acupoints5,Meridians2Level,Meridians2BlastHitRate,Meridians2Acupoints1,Meridians2Acupoints2,Meridians2Acupoints3,Meridians2Acupoints4,Meridians2Acupoints5,Meridians3Level,Meridians3BlastHitRate,Meridians3Acupoints1,Meridians3Acupoints2,Meridians3Acupoints3,Meridians3Acupoints4,Meridians3Acupoints5,Meridians4Level,Meridians4BlastHitRate,Meridians4Acupoints1,Meridians4Acupoints2,Meridians4Acupoints3,Meridians4Acupoints4,Meridians4Acupoints5,Meridians5Level,Meridians5BlastHitRate,Meridians5Acupoints1,Meridians5Acupoints2,Meridians5Acupoints3,Meridians5Acupoints4,Meridians5Acupoints5 from HumanAbilNG where HumanID = ?;";

        /// <summary>HumanSelectAbilWine</summary>
        public const string FStatementGetAbilWine =
            "select IsDrinkedWine,IsDrinkWineDrunk,DrinkWineQuality,DrinkWineAlcohol,AbilAlcohol,AbilMaxAlcohol,AbilDrinkValue,AbilMedicineLevel,AbilMedicineValue,AbilMaxMedicineValue from HumanAbilWine where HumanID = ?;";

        /// <summary>HumanSelectAbilNpcAdd</summary>
        public const string FStatementGetAbilNpcAdd =
            "select `Index`,`Value` from HumanAbilNpcAdd where HumanID = ?;";

        /// <summary>HumanSelectGamePetData</summary>
        public const string FStatementGetGamePetData =
            "select `Index`,Name,Level,HP,MP,Exp,Magic1,Magic2,Magic3,Magic4,Magic5,Magic6,Magic7,Magic8 from HumanGamePetData where HumanID = ?;";

        /// <summary>HumanSelectGodBlessState</summary>
        public const string FStatementGetGodBlessState =
            "select `Index`,`Value` from HumanGodBlessState where HumanID = ?;";

        /// <summary>HumanSelectMagic</summary>
        public const string FStatementGetMagic =
            "select MagicType,MagicIndex,MagicID,MagicAttr,MagicLevel,MagicNewLevel,MagicKey,MagicTranPoint,MagicIsUseItemAdd from HumanMagic where HumanID = ?;";

        /// <summary>HumanSelectMagicUseTick</summary>
        public const string FStatementGetMagicUseTick =
            "select MagicID,`Value` from HumanMagicUseTick where HumanID = ?;";

        /// <summary>HumanSelectStatusTime</summary>
        public const string FStatementGetStatusTime =
            "select `Index`,`Value` from HumanStatusTime where HumanID = ?;";

        /// <summary>HumanSelectQuestFlag</summary>
        public const string FStatementGetQuestFlag =
            "select `Index`,`Value` from HumanQuestFlag where HumanID = ?;";

        /// <summary>HumanSelectVariableU</summary>
        public const string FStatementGetVariableU =
            "select `Index`,`Value` from HumanVariableU where HumanID = ?;";

        /// <summary>HumanSelectVariableT</summary>
        public const string FStatementGetVariableT =
            "select `Index`,`Value` from HumanVariableT where HumanID = ?;";

        /// <summary>HumanSelectVariableJ</summary>
        public const string FStatementGetVariableJ =
            "select `Index`,`Value` from HumanVariableJ where HumanID = ?;";

        /// <summary>HumanSelectVariableZ</summary>
        public const string FStatementGetVariableZ =
            "select `Index`,`Value` from HumanVariableZ where HumanID = ?;";

        /// <summary>HumanSelectitems</summary>
        public const string FStatementGetItems =
            "select ItemType,ItemIndex,MakeIndex,DBIndex,Name,Dura,DuraMax,HeroM2DressEffect,UpgradeCount,IsStartTime,LimitTime,HeroM2Light,Color,IsBind,BindOption,Effect,NewLooks,NewShape,FluteCount,PropertyText,PropertyTextColor,ItemFrom,ItemFromMap,ItemFromMon,ItemFromMaker,ItemFromDate,InsuranceCount, NewExpand3, NewExpand4 from HumanItems where HumanID = ?;";

        /// <summary>HumanSelectitemValueAdd</summary>
        public const string FStatementGetItemValueAdd =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HumanItemValueAdd where HumanID = ?;";

        /// <summary>HumanSelectitemElementAdd</summary>
        public const string FStatementGetItemElementAdd =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HumanItemElementAdd where HumanID = ?;";

        /// <summary>HumanSelectitemAddDataByte</summary>
        public const string FStatementGetItemAddDataByte =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HumanItemAddDataByte where HumanID = ?;";

        /// <summary>HumanSelectItemAddDataInt</summary>
        public const string FStatementGetItemAddDataInt =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HumanItemAddDataInt where HumanID = ?;";

        /// <summary>HumanSelectitemAddDataText</summary>
        public const string FStatementGetItemAddDataText =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HumanItemAddDataText where HumanID = ?;";

        /// <summary>HumanSelectitemFlute</summary>
        public const string FStatementGetItemFlute =
            "select ItemType,ItemIndex,ValueIndex,`Value`,`OverlapCount` from HumanItemFlute where HumanID = ?;";

        /// <summary>HumanSelectItemProgress</summary>
        public const string FStatementGetItemProgress =
            "select ItemType,ItemIndex,ValueIndex,IsOpen,NameColor,Count,ShowType,Max,`Value`,Level,Name from HumanItemProgress where HumanID = ?;";

        /// <summary>HumanSelectItemProperty</summary>
        public const string FStatementGetItemProperty =
            "select ItemType,ItemIndex,ValueIndex,Color,BindType,ShowFlag,IsPercent,HintModule,`Value`,`Value2`,`Value3` from HumanItemProperty where HumanID = ?;";

        /// <summary>HumanSelectSkillPower</summary>
        public const string FStatementGetSkillPower =
            "select SkillID,HumanAttackPercent,HumanAttackValue,MonAttackPercent,MonAttackValue,DefensePercent,DefenseValue,RemainingTime  from HumanSkillPower where HumanID = ?;";

        /// <summary>HumanAdd</summary>
        public const string FStatementAddHuman =
            "insert into Human(Account, HumanName, IsDelete, IsSelect, CreateDate, Sex, Job, Hair) values(?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanDelOrRestore</summary>
        public const string FStatementDeleteOrRestore =
            "update Human set IsDelete = ? where (Account = ?) and (HumanName = ?);";

        /// <summary>HumanRecordLoginTime</summary>
        public const string FStatementRecordLoginTime =
            "update Human set LoginDate = ? where (Account = ?) and (HumanName = ?);";

        /// <summary>HumanRename</summary>
        public const string FStatementUpdateHumanName =
            "update Human set HumanName = ? where HumanID = ?;";

        /// <summary>HumanRenameSyncDearName</summary>
        public const string FStatementUpdateHumanNameDearName =
            "update Human set DearName = ? where DearName = ?;";

        /// <summary>HumanRenameSyncMasterName</summary>
        public const string FStatementUpdateHumanNameMasterName =
            "update Human set MasterName = ? where MasterName = ?;";

        /// <summary>HumanUpdate</summary>
        public const string FStatementUpdateHuman =
            "update Human set Sex = ?,Job = ?,Hair = ?,Dir = ?,Level = ?,ReLevel = ?,Map = ?,X = ?,Y = ?,HomeMap = ?,HomeX = ?,HomeY = ?,AttackMode = ?,StoragePassword = ?,CreditPoint = ?,Gold = ?,GameGold = ?,GamePoint = ?,GameDiamond = ?,GameGird = ?,GameGoldEx = ?,GameGlory = ?,PKPoint = ?,PayMentPoint = ?,MemberType = ?,MemberLevel = ?,IsMaster = ?,MasterName = ?,MasterCount = ?,MarryCount = ?,DearName = ?,IncHP = ?,IncMP = ?,IncHP2 = ?,FightZoneDieCount = ?,BodyLuck = ?,Contribution = ?,HungerStatus = ?,KickCount = ?,IsLockLogin = ?,IsAllowGroup = ?,IsAllowGroupRecall = ?,GroupRecallTime = ?,IsAllowGuildReCall = ?,IsDisableTrading = ?,IsDisableInviteHorseRiding = ?,IsGameGoldTrading = ?,IsNewServer = ?,IsFilterGlobalDropItemMsg = ?,IsFilterGlobalCenterMsg = ?,IsFilterGolbalSendMsg = ?,IsStorageHero = ?,IsStorageDeputyHero = ?,DeputyHeroJob = ?,Nation = ?,NationCredit = ?,RevivalTime = ?,InfinityStorageExtCount = ?,IsSaveKillMonExpRate = ?,KillMonExpRate = ?,KillMonExpRateTime = ?,IsSavePowerRate = ?,PowerRate = ?,PowerRateTime = ?,IsAttackMonSavePowerRate = ?,AttackMonPowerRate = ?,AttackMonPowerRateTime = ?,IsSaveKillMonBurstRate = ?,KillMonBurstRate = ?,KillMonBurstRateTime = ?,FBCreateTime = ?,JewelryBoxStatus = ?,IsShowFashion = ?,IsShowGodBless = ?,ActiveFengHao = ?,IsOpenStorage1 = ?,IsOpenStorage2 = ?,IsOpenStorage3 = ?,ExtBagPageCount = ?,ExtBagOpenItemCount = ?,AddMaxWeight = ?,HighLevelKillMonFixExpTimeLeft = ?, MobileNumber = ?, IsMobileBind = ?, MobileVerifyCode = ?, MobileSendTick = ?, MobileResendCount = ?, ClearDayVarTime = ? where HumanID = ?;";

        /// <summary>HumanInsertAbil</summary>
        public const string FStatementInsertAbil =
            "replace into HumanAbil(HumanID, AC1, AC2, MAC1, MAC2, DC1, DC2, MC1, MC2, SC1, SC2, HP, MaxHP,MP, MaxMP, Exp, MaxExp, Weight, MaxWeight, WearWeight, MaxWearWeight, HandWeight, MaxHandWeight,AdjustAbilPoint, AdjustAbilDC, AdjustAbilMC, AdjustAbilSC, AdjustAbilAC, AdjustAbilMAC, AdjustAbilHP,AdjustAbilMP, AdjustAbilHit, AdjustAbilSpeed, AdjustAbilMaxRate) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertAbilNG</summary>
        public const string FStatementInsertAbilNG =
            "replace into HumanAbilNG(HumanID, IsTrainingNG, IsTrainingXF, AbilNGLevel, AbilNGValue, AbilNGMaxValue, AbilNGExp, AbilNGMaxExp,ContinuousMagicOrder1, ContinuousMagicOrder2, ContinuousMagicOrder3, IsOpenLastContinuous, LastContinuousMagicOrder, Meridians1Level, Meridians1BlastHitRate1, Meridians1Acupoints1, Meridians1Acupoints2, Meridians1Acupoints3, Meridians1Acupoints4, Meridians1Acupoints5, Meridians2Level, Meridians2BlastHitRate, Meridians2Acupoints1, Meridians2Acupoints2, Meridians2Acupoints3, Meridians2Acupoints4, Meridians2Acupoints5, Meridians3Level, Meridians3BlastHitRate, Meridians3Acupoints1, Meridians3Acupoints2, Meridians3Acupoints3, Meridians3Acupoints4, Meridians3Acupoints5, Meridians4Level, Meridians4BlastHitRate, Meridians4Acupoints1, Meridians4Acupoints2, Meridians4Acupoints3, Meridians4Acupoints4, Meridians4Acupoints5, Meridians5Level, Meridians5BlastHitRate, Meridians5Acupoints1, Meridians5Acupoints2, Meridians5Acupoints3, Meridians5Acupoints4, Meridians5Acupoints5) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertAbilWine</summary>
        public const string FStatementInsertAbilWine =
            "replace into HumanAbilWine(HumanID, IsDrinkedWine, IsDrinkWineDrunk, DrinkWineQuality, DrinkWineAlcohol, AbilAlcohol, AbilMaxAlcohol, AbilDrinkValue, AbilMedicineLevel, AbilMedicineValue, AbilMaxMedicineValue) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertAbilNpcAdd</summary>
        public const string FStatementInsertAbilNpcAdd =
            "insert into HumanAbilNpcAdd(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertGamePetData</summary>
        public const string FStatementInsertGamePetData =
            "insert into HumanGamePetData(HumanID, `Index`, Name, Level, HP, MP, Exp, Magic1, Magic2, Magic3, Magic4, Magic5, Magic6, Magic7, Magic8) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertGodBlessState</summary>
        public const string FStatementInsertGodBlessState =
            "insert into HumanGodBlessState(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertMagic</summary>
        public const string FStatementInsertMagic =
            "insert into HumanMagic(HumanID, MagicType, MagicIndex, MagicID,MagicAttr, MagicLevel, MagicNewLevel, MagicKey, MagicTranPoint, MagicIsUseItemAdd) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertMagicUseTick</summary>
        public const string FStatementInsertMagicUseTick =
            "insert into HumanMagicUseTick(HumanID, MagicID, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertStatusTime</summary>
        public const string FStatementInsertStatusTime =
            "insert into HumanStatusTime(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertQuestFlag</summary>
        public const string FStatementInsertQuestFlag =
            "insert into HumanQuestFlag(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertVariableU</summary>
        public const string FStatementInsertVariableU =
            "insert into HumanVariableU(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertVariableT</summary>
        public const string FStatementInsertVariableT =
            "insert into HumanVariableT(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertVariableJ</summary>
        public const string FStatementInsertVariableJ =
            "insert into HumanVariableJ(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertVariableZ</summary>
        public const string FStatementInsertVariableZ =
            "insert into HumanVariableZ(HumanID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertCustomMoney</summary>
        public const string FStatementInsertCustomMoney =
            "insert into HumanMoney(HumanID, `MoneyName`, `Value`) values(?, ?, ?);";

        /// <summary>HumanInsertItems</summary>
        public const string FStatementInsertItems =
            "insert into HumanItems(HumanID, ItemType, ItemIndex, MakeIndex, DBIndex, Name, Dura, DuraMax, HeroM2DressEffect, UpgradeCount, IsStartTime, LimitTime, HeroM2Light, Color, IsBind, BindOption, Effect, NewLooks, NewShape, FluteCount, PropertyText, PropertyTextColor, ItemFrom, ItemFromMap, ItemFromMon, ItemFromMaker, ItemFromDate, InsuranceCount, NewExpand3, NewExpand4 ) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemValueAdd</summary>
        public const string FStatementInsertItemValueAdd =
            "insert into HumanItemValueAdd(HumanID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemElementAdd</summary>
        public const string FStatementInsertItemElementAdd =
            "insert into HumanItemElementAdd(HumanID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemAddDataByte</summary>
        public const string FStatementInsertItemAddDataByte =
            "insert into HumanItemAddDataByte(HumanID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemAddDataInt</summary>
        public const string FStatementInsertItemAddDataInt =
            "insert into HumanItemAddDataInt(HumanID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemAddDataText</summary>
        public const string FStatementInsertItemAddDataText =
            "insert into HumanItemAddDataText(HumanID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemFlute</summary>
        public const string FStatementInsertItemFlute =
            "insert into HumanItemFlute(HumanID, ItemType, ItemIndex, ValueIndex, `Value`,OverlapCount) values(?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemProgress</summary>
        public const string FStatementInsertItemProgress =
            "insert into HumanItemProgress(HumanID, ItemType, ItemIndex, ValueIndex, IsOpen, NameColor, Count, ShowType, Max, `Value`, Level, Name) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertItemProperty</summary>
        public const string FStatementInsertItemProperty =
            "insert into HumanItemProperty(HumanID, ItemType, ItemIndex, ValueIndex, Color, BindType, ShowFlag, IsPercent, HintModule, Value, Value2, Value3) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanInsertSkillPower</summary>
        public const string FStatementInsertSkillPower =
            "insert into HumanSkillPower(HumanID, SkillID, HumanAttackPercent,HumanAttackValue,MonAttackPercent,MonAttackValue,DefensePercent,DefenseValue,RemainingTime) values(?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HumanGetLevelRankCheckLevel</summary>
        public const string FStatementGetLevelRankCheckLevel =
            "select HumanName, Level from Human where (Job in (?,?,?)) and (Level >= ?) and (Level <= ?) order by Level desc";

        /// <summary>HumanGetLevelRankTopCount</summary>
        public const string FStatementGetLevelRankTopCount =
            "select HumanName, Level from Human where (Job in (?,?,?)) order by Level desc limit ?";

        /// <summary>HumanGetLevelRankCheckLevelAndCount</summary>
        public const string FStatementGetLevelRankCheckLevelAndCount =
            "select HumanName, Level from Human where (Job in (?,?,?)) and (Level >= ?) and (Level <= ?) order by Level desc  limit ?";

        /// <summary>HumanGetMasterRankCheckLevel</summary>
        public const string FStatementGetMasterRankCheckLevel =
            "select HumanName, MasterCount from Human where (Job in (?,?,?)) and (Level >= ?) and (Level <= ?) order by MasterCount desc";

        /// <summary>HumanGetMasterRankTopCount</summary>
        public const string FStatementGetMasterRankTopCount =
            "select HumanName, MasterCount from Human where (Job in (?,?,?)) order by MasterCount desc limit ?";

        /// <summary>GetMasterRankCheckLevelAndCount</summary>
        public const string FStatementGetMasterRankCheckLevelAndCount =
            "select HumanName, MasterCount from Human where (Job in (?,?,?)) and (Level >= ?) and (Level <= ?) order by MasterCount desc  limit ?";

        /// <summary>BuyPlayer</summary>
        public const string FStatementBuyPlayer =
            "update Human set Account = ?, IsDelete = 0 where Account = ? and HumanName = ?";

        /// <summary>GetCustomMoney</summary>
        public const string FStatementGetCustomMoney =
            "select `MoneyName`,`Value` from HumanMoney where HumanID = ?;";

        /// <summary>GetCustomMoneyByName</summary>
        public const string FStatementGetCustomMoneyByName =
            "select `Value` from HumanMoney where HumanID = ? and MoneyName = ?;";

        /// <summary>UpdateCustomMoney</summary>
        public const string FStatementUpdateCustomMoney =
            "update HumanMoney set Value = ?where HumanID = ? and MoneyName = ?;";

        /// <summary>Statement names (Stms.AddSQLStatement argument), keyed by constant name.</summary>
        public static readonly System.Collections.Generic.Dictionary<string, string> Names = new()
        {
            { "FStatementGetID", "HumanGetID" },
            { "FStatementCheckHumanExists", "CheckHumanExists" },
            { "FStatementGetHumanCount", "HumanGetCount" },
            { "FStatementGetOtherHumanName", "GetOtherHumanName" },
            { "FStatementGetHumanHeroName", "HumanGetHumanHeroName" },
            { "FStatementGetHumanHeroID", "HumanGetHumanHeroID" },
            { "FStatementGetHumanGoldInfo", "HumanGetHumanGoldInfo" },
            { "FStatementUpdateHumanGoldInfo", "HumanUpdateHumanGoldInfo" },
            { "FStatementGetHumanBaseInfo", "HumanGetBaseInfo" },
            { "FStatementQueryHumans", "HumanQuery" },
            { "FStatementSearchByAccountMatchComplete", "HumanSearchByAccount1" },
            { "FStatementSearchByAccountMatchFuzzy", "HumanSearchByAccount2" },
            { "FStatementSearchByNameMatchComplete", "HumanSearchByName1" },
            { "FStatementSearchByNameMatchFuzzy", "HumanSearchByName2" },
            { "FStatementSearchByLevel", "HumanSearchByLevel" },
            { "FStatementGetMobileNumbers1", "HumanGetMobileNumbers1" },
            { "FStatementGetMobileNumbers2", "HumanGetMobileNumbers2" },
            { "FStatementSelect", "HumanSetSelect" },
            { "FStatementUnSelect", "HumanSetUnSelect" },
            { "FStatementGetHuman", "HumanSelect" },
            { "FStatementGetAbil", "HumanSelectAbil" },
            { "FStatementGetAbilNG", "HumanSelectAbilNG" },
            { "FStatementGetAbilWine", "HumanSelectAbilWine" },
            { "FStatementGetAbilNpcAdd", "HumanSelectAbilNpcAdd" },
            { "FStatementGetGamePetData", "HumanSelectGamePetData" },
            { "FStatementGetGodBlessState", "HumanSelectGodBlessState" },
            { "FStatementGetMagic", "HumanSelectMagic" },
            { "FStatementGetMagicUseTick", "HumanSelectMagicUseTick" },
            { "FStatementGetStatusTime", "HumanSelectStatusTime" },
            { "FStatementGetQuestFlag", "HumanSelectQuestFlag" },
            { "FStatementGetVariableU", "HumanSelectVariableU" },
            { "FStatementGetVariableT", "HumanSelectVariableT" },
            { "FStatementGetVariableJ", "HumanSelectVariableJ" },
            { "FStatementGetVariableZ", "HumanSelectVariableZ" },
            { "FStatementGetItems", "HumanSelectitems" },
            { "FStatementGetItemValueAdd", "HumanSelectitemValueAdd" },
            { "FStatementGetItemElementAdd", "HumanSelectitemElementAdd" },
            { "FStatementGetItemAddDataByte", "HumanSelectitemAddDataByte" },
            { "FStatementGetItemAddDataInt", "HumanSelectItemAddDataInt" },
            { "FStatementGetItemAddDataText", "HumanSelectitemAddDataText" },
            { "FStatementGetItemFlute", "HumanSelectitemFlute" },
            { "FStatementGetItemProgress", "HumanSelectItemProgress" },
            { "FStatementGetItemProperty", "HumanSelectItemProperty" },
            { "FStatementGetSkillPower", "HumanSelectSkillPower" },
            { "FStatementAddHuman", "HumanAdd" },
            { "FStatementDeleteOrRestore", "HumanDelOrRestore" },
            { "FStatementRecordLoginTime", "HumanRecordLoginTime" },
            { "FStatementUpdateHumanName", "HumanRename" },
            { "FStatementUpdateHumanNameDearName", "HumanRenameSyncDearName" },
            { "FStatementUpdateHumanNameMasterName", "HumanRenameSyncMasterName" },
            { "FStatementUpdateHuman", "HumanUpdate" },
            { "FStatementInsertAbil", "HumanInsertAbil" },
            { "FStatementInsertAbilNG", "HumanInsertAbilNG" },
            { "FStatementInsertAbilWine", "HumanInsertAbilWine" },
            { "FStatementInsertAbilNpcAdd", "HumanInsertAbilNpcAdd" },
            { "FStatementInsertGamePetData", "HumanInsertGamePetData" },
            { "FStatementInsertGodBlessState", "HumanInsertGodBlessState" },
            { "FStatementInsertMagic", "HumanInsertMagic" },
            { "FStatementInsertMagicUseTick", "HumanInsertMagicUseTick" },
            { "FStatementInsertStatusTime", "HumanInsertStatusTime" },
            { "FStatementInsertQuestFlag", "HumanInsertQuestFlag" },
            { "FStatementInsertVariableU", "HumanInsertVariableU" },
            { "FStatementInsertVariableT", "HumanInsertVariableT" },
            { "FStatementInsertVariableJ", "HumanInsertVariableJ" },
            { "FStatementInsertVariableZ", "HumanInsertVariableZ" },
            { "FStatementInsertCustomMoney", "HumanInsertCustomMoney" },
            { "FStatementInsertItems", "HumanInsertItems" },
            { "FStatementInsertItemValueAdd", "HumanInsertItemValueAdd" },
            { "FStatementInsertItemElementAdd", "HumanInsertItemElementAdd" },
            { "FStatementInsertItemAddDataByte", "HumanInsertItemAddDataByte" },
            { "FStatementInsertItemAddDataInt", "HumanInsertItemAddDataInt" },
            { "FStatementInsertItemAddDataText", "HumanInsertItemAddDataText" },
            { "FStatementInsertItemFlute", "HumanInsertItemFlute" },
            { "FStatementInsertItemProgress", "HumanInsertItemProgress" },
            { "FStatementInsertItemProperty", "HumanInsertItemProperty" },
            { "FStatementInsertSkillPower", "HumanInsertSkillPower" },
            { "FStatementGetLevelRankCheckLevel", "HumanGetLevelRankCheckLevel" },
            { "FStatementGetLevelRankTopCount", "HumanGetLevelRankTopCount" },
            { "FStatementGetLevelRankCheckLevelAndCount", "HumanGetLevelRankCheckLevelAndCount" },
            { "FStatementGetMasterRankCheckLevel", "HumanGetMasterRankCheckLevel" },
            { "FStatementGetMasterRankTopCount", "HumanGetMasterRankTopCount" },
            { "FStatementGetMasterRankCheckLevelAndCount", "GetMasterRankCheckLevelAndCount" },
            { "FStatementBuyPlayer", "BuyPlayer" },
            { "FStatementGetCustomMoney", "GetCustomMoney" },
            { "FStatementGetCustomMoneyByName", "GetCustomMoneyByName" },
            { "FStatementUpdateCustomMoney", "UpdateCustomMoney" },
        };
    }

    // ============================================================================
    // TMySqlHeroDB.DoInit  MySqlRoleDB.pas:3463-3806   (54 statements)
    // ============================================================================
    public static class Hero
    {
        /// <summary>HeroGetID</summary>
        public const string FStatementGetID =
            "select HeroID from Hero where HeroName = ?;";

        /// <summary>HeroGetCount</summary>
        public const string FStatementGetHeroCount =
            "select count(*) from Hero where (HumanID = ?);";

        /// <summary>HeroGetHumanInfo</summary>
        public const string FStatementGetHumanInfo =
            "select b.Account, a.HumanID, b.HumanName, b.HeroName, b.DeputyHeroName from Hero a, Human b where (a.HumanID = b.HumanID) and (a.HeroID = ?);";

        /// <summary>HeroGetHumanInfo2</summary>
        public const string FStatementGetHumanInfo2 =
            "select a.HumanID, b.HumanName, b.IsStorageHero, b.IsStorageDeputyHero, b.HeroName, b.DeputyHeroName from Hero a, Human b where (a.HumanID = b.HumanID) and (a.HeroID = ?);";

        /// <summary>HeroSearchByAccount1</summary>
        public const string FStatementSearchByAccountMatchComplete =
            "select b.Account, a.HeroName, a.Sex, a.Job, a.Level level from Hero a, Human b where (a.HumanID = b.HumanID) and (b.Account = ?);";

        /// <summary>HeroSearchByAccount2</summary>
        public const string FStatementSearchByAccountMatchFuzzy =
            "select b.Account, a.HeroName, a.Sex, a.Job, a.Level from Hero a, Human b where (a.HumanID = b.HumanID) and (b.Account like ?);";

        /// <summary>HeroSearchByName1</summary>
        public const string FStatementSearchByNameMatchComplete =
            "select b.Account, a.HeroName, a.Sex, a.Job, a.Level from Hero a, Human b where (a.HumanID = b.HumanID) and (a.HeroName = ?);";

        /// <summary>HeroSearchByName2</summary>
        public const string FStatementSearchByNameMatchFuzzy =
            "select b.Account, a.HeroName, a.Sex, a.Job, a.Level from Hero a, Human b where (a.HumanID = b.HumanID) and (a.HeroName like ?);";

        /// <summary>HeroSelect</summary>
        public const string FStatementGetHero =
            "select a.HeroID,(select Account from Human where HumanID = a.HumanID) account,a.HeroName,a.Sex,a.Job,a.Hair,a.Status,a.Dir,a.Level,a.ReLevel,a.LoyalPoint,a.Map,a.X,a.Y,a.AttackMode,a.CreditPoint,a.PKPoint,a.IncHP,a.IncMP,a.IncHP2,a.FightZoneDieCount,a.BodyLuck,a.HungerStatus,a.RevivalTime,a.IsSaveKillMonExpRate,a.KillMonExpRate,a.KillMonExpRateTime,a.IsSavePowerRate,a.PowerRate,a.PowerRateTime,a.IsAttackMonSavePowerRate,a.AttackMonPowerRate,a.AttackMonPowerRateTime,a.IsSaveKillMonBurstRate,a.KillMonBurstRate,a.KillMonBurstRateTime,a.JewelryBoxStatus,a.IsShowFashion,a.IsShowGodBless,a.ActiveFengHao from Hero a where (a.HeroName = ?);";

        /// <summary>HeroSelectAbil</summary>
        public const string FStatementGetAbil =
            "select AC1,AC2,MAC1,MAC2,DC1,DC2,MC1,MC2,SC1,SC2,HP,MaxHP,MP,MaxMP,Exp,MaxExp,Weight,MaxWeight,WearWeight,MaxWearWeight,HandWeight,MaxHandWeight from HeroAbil where HeroID = ?;";

        /// <summary>HeroSelectAbilNG</summary>
        public const string FStatementGetAbilNG =
            "select IsTrainingNG,IsTrainingXF,AbilNGLevel,AbilNGValue,AbilNGMaxValue,AbilNGExp,AbilNGMaxExp,ContinuousMagicOrder1,ContinuousMagicOrder2,ContinuousMagicOrder3,IsOpenLastContinuous,LastContinuousMagicOrder,Meridians1Level,Meridians1BlastHitRate1,Meridians1Acupoints1,Meridians1Acupoints2,Meridians1Acupoints3,Meridians1Acupoints4,Meridians1Acupoints5,Meridians2Level,Meridians2BlastHitRate,Meridians2Acupoints1,Meridians2Acupoints2,Meridians2Acupoints3,Meridians2Acupoints4,Meridians2Acupoints5,Meridians3Level,Meridians3BlastHitRate,Meridians3Acupoints1,Meridians3Acupoints2,Meridians3Acupoints3,Meridians3Acupoints4,Meridians3Acupoints5,Meridians4Level,Meridians4BlastHitRate,Meridians4Acupoints1,Meridians4Acupoints2,Meridians4Acupoints3,Meridians4Acupoints4,Meridians4Acupoints5,Meridians5Level,Meridians5BlastHitRate,Meridians5Acupoints1,Meridians5Acupoints2,Meridians5Acupoints3,Meridians5Acupoints4,Meridians5Acupoints5 from HeroAbilNG where HeroID = ?;";

        /// <summary>HeroSelectAbilWine</summary>
        public const string FStatementGetAbilWine =
            "select IsDrinkWineDrunk,DrinkWineQuality,DrinkWineAlcohol,AbilAlcohol,AbilMaxAlcohol,AbilDrinkValue,AbilMedicineLevel,AbilMedicineValue,AbilMaxMedicineValue from HeroAbilWine where HeroID = ?;";

        /// <summary>HeroSelectAbilNpcAdd</summary>
        public const string FStatementGetAbilNpcAdd =
            "select `Index`,`Value` from HeroAbilNpcAdd where HeroID = ?;";

        /// <summary>HeroSelectGodBlessState</summary>
        public const string FStatementGetGodBlessState =
            "select `Index`,`Value` from HeroGodBlessState where HeroID = ?;";

        /// <summary>HeroSelectMagic</summary>
        public const string FStatementGetMagic =
            "select MagicType,MagicIndex,MagicID,MagicAttr,MagicLevel,MagicNewLevel,MagicKey,MagicTranPoint,MagicIsUseItemAdd from HeroMagic where HeroID = ?;";

        /// <summary>HeroSelectStatusTime</summary>
        public const string FStatementGetStatusTime =
            "select `Index`,`Value` from HeroStatusTime where HeroID = ?;";

        /// <summary>HeroSelectQuestFlag</summary>
        public const string FStatementGetQuestFlag =
            "select `Index`,`Value` from HeroQuestFlag where HeroID = ?;";

        /// <summary>HeroSelectitems</summary>
        public const string FStatementGetItems =
            "select ItemType,ItemIndex,MakeIndex,DBIndex,Name,Dura,DuraMax,HeroM2DressEffect,UpgradeCount,IsStartTime,LimitTime,HeroM2Light,Color,IsBind,BindOption,Effect,NewLooks,NewShape,FluteCount,PropertyText,PropertyTextColor,ItemFrom,ItemFromMap,ItemFromMon,ItemFromMaker,ItemFromDate,InsuranceCount, NewExpand3, NewExpand4 from HeroItems where HeroID = ?;";

        /// <summary>HeroSelectitemValueAdd</summary>
        public const string FStatementGetItemValueAdd =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HeroItemValueAdd where HeroID = ?;";

        /// <summary>HeroSelectitemElementAdd</summary>
        public const string FStatementGetItemElementAdd =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HeroItemElementAdd where HeroID = ?;";

        /// <summary>HeroSelectitemAddDataByte</summary>
        public const string FStatementGetItemAddDataByte =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HeroItemAddDataByte where HeroID = ?;";

        /// <summary>HeroSelectitemAddDataInt</summary>
        public const string FStatementGetItemAddDataInt =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HeroItemAddDataInt where HeroID = ?;";

        /// <summary>HeroSelectitemAddDataText</summary>
        public const string FStatementGetItemAddDataText =
            "select ItemType,ItemIndex,ValueIndex,`Value` from HeroItemAddDataText where HeroID = ?;";

        /// <summary>HeroSelectitemFlute</summary>
        public const string FStatementGetItemFlute =
            "select ItemType,ItemIndex,ValueIndex,`Value`,OverlapCount from HeroItemFlute where HeroID = ?;";

        /// <summary>HeroSelectItemProgress</summary>
        public const string FStatementGetItemProgress =
            "select ItemType,ItemIndex,ValueIndex,IsOpen,NameColor,Count,ShowType,Max,`Value`,Level,Name from HeroItemProgress where HeroID = ?;";

        /// <summary>HeroSelectItemProperty</summary>
        public const string FStatementGetItemProperty =
            "select ItemType,ItemIndex,ValueIndex,Color,BindType,ShowFlag,IsPercent,HintModule,`Value`,`Value2`,`Value3` from HeroItemProperty where HeroID = ?;";

        /// <summary>HeroSelectSkillPower</summary>
        public const string FStatementGetSkillPower =
            "select SkillID,HumanAttackPercent,HumanAttackValue,MonAttackPercent,MonAttackValue,DefensePercent,DefenseValue,RemainingTime  from HeroSkillPower where HeroID = ?;";

        /// <summary>HeroAdd</summary>
        public const string FStatementAddHero =
            "insert into Hero(HumanID, HeroName, IsDelete, CreateDate, Sex, Job, Hair) values(?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroDelOrRestore</summary>
        public const string FStatementDeleteOrRestore =
            "update Hero set IsDelete = ? where (HeroName = ?);";

        /// <summary>HeroRename</summary>
        public const string FStatementUpdateHeroName =
            "update Hero set HeroName = ? where HeroID = ?;";

        /// <summary>HeroRenameSyncHumanHero</summary>
        public const string FStatementUpdateHumanHeroName =
            "update Human set HeroName = ?, DeputyHeroName = ? where HumanID = ?;";

        /// <summary>HeroRenameSyncHumanHero2</summary>
        public const string FStatementUpdateHumanHeroName2 =
            "update Human set IsFixedHero = ?, IsStorageHero = ?, IsStorageDeputyHero = ?, HeroName = ?, DeputyHeroName = ? where HumanID = ?;";

        /// <summary>HeroUpdate</summary>
        public const string FStatementUpdateHero =
            "update Hero set Sex = ?,Job = ?,Hair = ?,Status = ?,Dir = ?,Level = ?,ReLevel = ?,LoyalPoint = ?,Map = ?,X = ?,Y = ?,AttackMode = ?,CreditPoint = ?,PKPoint = ?,IncHP = ?,IncMP = ?,IncHP2 = ?,FightZoneDieCount = ?,BodyLuck = ?,HungerStatus = ?,RevivalTime = ?,IsSaveKillMonExpRate = ?,KillMonExpRate = ?,KillMonExpRateTime = ?,IsSavePowerRate = ?,PowerRate = ?,PowerRateTime = ?,IsAttackMonSavePowerRate = ?,AttackMonPowerRate = ?,AttackMonPowerRateTime = ?,IsSaveKillMonBurstRate = ?,KillMonBurstRate = ?,KillMonBurstRateTime = ?,JewelryBoxStatus = ?,IsShowFashion = ?,IsShowGodBless = ?,ActiveFengHao = ? where HeroID = ?;";

        /// <summary>HeroInsertAbil</summary>
        public const string FStatementInsertAbil =
            "replace into HeroAbil(HeroID, AC1, AC2, MAC1, MAC2, DC1, DC2, MC1, MC2, SC1, SC2, HP, MaxHP,MP, MaxMP, Exp, MaxExp, Weight, MaxWeight, WearWeight, MaxWearWeight, HandWeight, MaxHandWeight) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertAbilNG</summary>
        public const string FStatementInsertAbilNG =
            "replace into HeroAbilNG(HeroID, IsTrainingNG, IsTrainingXF, AbilNGLevel, AbilNGValue, AbilNGMaxValue, AbilNGExp, AbilNGMaxExp,ContinuousMagicOrder1, ContinuousMagicOrder2, ContinuousMagicOrder3, IsOpenLastContinuous, LastContinuousMagicOrder, Meridians1Level, Meridians1BlastHitRate1, Meridians1Acupoints1, Meridians1Acupoints2, Meridians1Acupoints3, Meridians1Acupoints4, Meridians1Acupoints5, Meridians2Level, Meridians2BlastHitRate, Meridians2Acupoints1, Meridians2Acupoints2, Meridians2Acupoints3, Meridians2Acupoints4, Meridians2Acupoints5, Meridians3Level, Meridians3BlastHitRate, Meridians3Acupoints1, Meridians3Acupoints2, Meridians3Acupoints3, Meridians3Acupoints4, Meridians3Acupoints5, Meridians4Level, Meridians4BlastHitRate, Meridians4Acupoints1, Meridians4Acupoints2, Meridians4Acupoints3, Meridians4Acupoints4, Meridians4Acupoints5, Meridians5Level, Meridians5BlastHitRate, Meridians5Acupoints1, Meridians5Acupoints2, Meridians5Acupoints3, Meridians5Acupoints4, Meridians5Acupoints5) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertAbilWine</summary>
        public const string FStatementInsertAbilWine =
            "replace into HeroAbilWine(HeroID, IsDrinkWineDrunk, DrinkWineQuality, DrinkWineAlcohol, AbilAlcohol, AbilMaxAlcohol, AbilDrinkValue, AbilMedicineLevel, AbilMedicineValue, AbilMaxMedicineValue) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertAbilNpcAdd</summary>
        public const string FStatementInsertAbilNpcAdd =
            "insert into HeroAbilNpcAdd(HeroID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HeroInsertGodBlessState</summary>
        public const string FStatementInsertGodBlessState =
            "insert into HeroGodBlessState(HeroID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HeroInsertMagic</summary>
        public const string FStatementInsertMagic =
            "insert into HeroMagic(HeroID, MagicType, MagicIndex, MagicID,MagicAttr, MagicLevel, MagicNewLevel, MagicKey, MagicTranPoint, MagicIsUseItemAdd) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertStatusTime</summary>
        public const string FStatementInsertStatusTime =
            "insert into HeroStatusTime(HeroID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HeroInsertQuestFlag</summary>
        public const string FStatementInsertQuestFlag =
            "insert into HeroQuestFlag(HeroID, `Index`, `Value`) values(?, ?, ?);";

        /// <summary>HeroInsertItems</summary>
        public const string FStatementInsertItems =
            "insert into HeroItems(HeroID, ItemType, ItemIndex, MakeIndex, DBIndex, Name, Dura, DuraMax, HeroM2DressEffect, UpgradeCount, IsStartTime, LimitTime, HeroM2Light, Color, IsBind, BindOption, Effect, NewLooks, NewShape, FluteCount, PropertyText, PropertyTextColor, ItemFrom, ItemFromMap, ItemFromMon, ItemFromMaker, ItemFromDate, InsuranceCount, NewExpand3, NewExpand4 ) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemValueAdd</summary>
        public const string FStatementInsertItemValueAdd =
            "insert into HeroItemValueAdd(HeroID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemElementAdd</summary>
        public const string FStatementInsertItemElementAdd =
            "insert into HeroItemElementAdd(HeroID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemAddDataByte</summary>
        public const string FStatementInsertItemAddDataByte =
            "insert into HeroItemAddDataByte(HeroID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemAddDataInt</summary>
        public const string FStatementInsertItemAddDataInt =
            "insert into HeroItemAddDataInt(HeroID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemAddDataText</summary>
        public const string FStatementInsertItemAddDataText =
            "insert into HeroItemAddDataText(HeroID, ItemType, ItemIndex, ValueIndex, `Value`) values(?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemFlute</summary>
        public const string FStatementInsertItemFlute =
            "insert into HeroItemFlute(HeroID, ItemType, ItemIndex, ValueIndex, `Value`, OverlapCount) values(?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemProgress</summary>
        public const string FStatementInsertItemProgress =
            "insert into HeroItemProgress(HeroID, ItemType, ItemIndex, ValueIndex, IsOpen, NameColor, Count, ShowType, Max, `Value`, Level, Name) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertItemProperty</summary>
        public const string FStatementInsertItemProperty =
            "insert into HeroItemProperty(HeroID, ItemType, ItemIndex, ValueIndex, Color, BindType, ShowFlag, IsPercent, HintModule, Value, Value2, Value3) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroInsertSkillPower</summary>
        public const string FStatementInsertSkillPower =
            "insert into HeroSkillPower(HeroID, SkillID, HumanAttackPercent,HumanAttackValue,MonAttackPercent,MonAttackValue,DefensePercent,DefenseValue,RemainingTime) values(?, ?, ?, ?, ?, ?, ?, ?, ?);";

        /// <summary>HeroGetLevelRankCheckLevel</summary>
        public const string FStatementGetLevelRankCheckLevel =
            "select (select HumanName from Human where HumanID = a.HumanID) as HumanName, a.HeroName, a.Level from Hero a where (a.Job in (?,?,?)) and (a.Level >= ?) and (a.Level <= ?) order by a.Level desc";

        /// <summary>HeroGetLevelRankTopCount</summary>
        public const string FStatementGetLevelRankTopCount =
            "select (select HumanName from Human where HumanID = a.HumanID) as HumanName,a.HeroName, a.Level from Hero a where (a.Job in (?,?,?)) order by a.Level desc limit ?";

        /// <summary>HeroGetLevelRankCheckLevelAndCount</summary>
        public const string FStatementGetLevelRankCheckLevelAndCount =
            "select (select HumanName from Human where HumanID = a.HumanID) as HumanName, a.HeroName, a.Level from Hero a where (a.Job in (?,?,?)) and (a.Level >= ?) and (a.Level <= ?) order by a.Level desc  limit ?";

        /// <summary>Statement names (Stms.AddSQLStatement argument), keyed by constant name.</summary>
        public static readonly System.Collections.Generic.Dictionary<string, string> Names = new()
        {
            { "FStatementGetID", "HeroGetID" },
            { "FStatementGetHeroCount", "HeroGetCount" },
            { "FStatementGetHumanInfo", "HeroGetHumanInfo" },
            { "FStatementGetHumanInfo2", "HeroGetHumanInfo2" },
            { "FStatementSearchByAccountMatchComplete", "HeroSearchByAccount1" },
            { "FStatementSearchByAccountMatchFuzzy", "HeroSearchByAccount2" },
            { "FStatementSearchByNameMatchComplete", "HeroSearchByName1" },
            { "FStatementSearchByNameMatchFuzzy", "HeroSearchByName2" },
            { "FStatementGetHero", "HeroSelect" },
            { "FStatementGetAbil", "HeroSelectAbil" },
            { "FStatementGetAbilNG", "HeroSelectAbilNG" },
            { "FStatementGetAbilWine", "HeroSelectAbilWine" },
            { "FStatementGetAbilNpcAdd", "HeroSelectAbilNpcAdd" },
            { "FStatementGetGodBlessState", "HeroSelectGodBlessState" },
            { "FStatementGetMagic", "HeroSelectMagic" },
            { "FStatementGetStatusTime", "HeroSelectStatusTime" },
            { "FStatementGetQuestFlag", "HeroSelectQuestFlag" },
            { "FStatementGetItems", "HeroSelectitems" },
            { "FStatementGetItemValueAdd", "HeroSelectitemValueAdd" },
            { "FStatementGetItemElementAdd", "HeroSelectitemElementAdd" },
            { "FStatementGetItemAddDataByte", "HeroSelectitemAddDataByte" },
            { "FStatementGetItemAddDataInt", "HeroSelectitemAddDataInt" },
            { "FStatementGetItemAddDataText", "HeroSelectitemAddDataText" },
            { "FStatementGetItemFlute", "HeroSelectitemFlute" },
            { "FStatementGetItemProgress", "HeroSelectItemProgress" },
            { "FStatementGetItemProperty", "HeroSelectItemProperty" },
            { "FStatementGetSkillPower", "HeroSelectSkillPower" },
            { "FStatementAddHero", "HeroAdd" },
            { "FStatementDeleteOrRestore", "HeroDelOrRestore" },
            { "FStatementUpdateHeroName", "HeroRename" },
            { "FStatementUpdateHumanHeroName", "HeroRenameSyncHumanHero" },
            { "FStatementUpdateHumanHeroName2", "HeroRenameSyncHumanHero2" },
            { "FStatementUpdateHero", "HeroUpdate" },
            { "FStatementInsertAbil", "HeroInsertAbil" },
            { "FStatementInsertAbilNG", "HeroInsertAbilNG" },
            { "FStatementInsertAbilWine", "HeroInsertAbilWine" },
            { "FStatementInsertAbilNpcAdd", "HeroInsertAbilNpcAdd" },
            { "FStatementInsertGodBlessState", "HeroInsertGodBlessState" },
            { "FStatementInsertMagic", "HeroInsertMagic" },
            { "FStatementInsertStatusTime", "HeroInsertStatusTime" },
            { "FStatementInsertQuestFlag", "HeroInsertQuestFlag" },
            { "FStatementInsertItems", "HeroInsertItems" },
            { "FStatementInsertItemValueAdd", "HeroInsertItemValueAdd" },
            { "FStatementInsertItemElementAdd", "HeroInsertItemElementAdd" },
            { "FStatementInsertItemAddDataByte", "HeroInsertItemAddDataByte" },
            { "FStatementInsertItemAddDataInt", "HeroInsertItemAddDataInt" },
            { "FStatementInsertItemAddDataText", "HeroInsertItemAddDataText" },
            { "FStatementInsertItemFlute", "HeroInsertItemFlute" },
            { "FStatementInsertItemProgress", "HeroInsertItemProgress" },
            { "FStatementInsertItemProperty", "HeroInsertItemProperty" },
            { "FStatementInsertSkillPower", "HeroInsertSkillPower" },
            { "FStatementGetLevelRankCheckLevel", "HeroGetLevelRankCheckLevel" },
            { "FStatementGetLevelRankTopCount", "HeroGetLevelRankTopCount" },
            { "FStatementGetLevelRankCheckLevelAndCount", "HeroGetLevelRankCheckLevelAndCount" },
        };
    }

}
