// <auto-generated />
// 生成器：_scratch/gen_weathereffect.py（从原文抽取 + 回读逐字段比对，禁止手工转录）
// 源单元：Source/Client-HGE/uWeatherEffectDef.pas（49 行 / CRLF 计入则 49；无同名 .dfm）
using System;
using System.Runtime.InteropServices;

namespace GXX.Client.Tail;

/// <summary>
/// uWeatherEffectDef.pas 1:1 移植 —— 天气特效定义表。
/// <para>原文 <c>TWeateherEffect = packed record</c>（注意原单元拼写就是 <c>Weateher</c>，非 <c>Weather</c>），
/// 保留 <c>Pack = 1</c> 布局与 <c>string[50]</c> 短字符串字段。</para>
/// <para><b>边界观察（已断言）</b>：数组声明 <c>array[0..21]</c>（22 槽）与初始化列表的 22 项**恰好填满**，
/// 不存在隐式零初始化槽。原文第 44 行另有一条**被注释掉**的第 23 项
/// （<c>dwStartOffset:600; dwEndOffset:209</c> —— 注意 <c>end &lt; start</c>，且与上一项区间重叠，原文如此），
/// 该行不参与初始化，本移植同样不采纳。</para>
/// <para>另外注意 <c>dwEndOffset</c> 在原文里是**闭区间上界**且各段并非等长：
/// 下标 0/1 都是 <c>0..9</c>（10 帧），下标 13 是 <c>300..359</c>（60 帧），其余多为 30 帧。</para>
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct TWeateherEffect
{
    /// <summary>是否使用特效（原文：boIsUsed:Boolean）</summary>
    public byte BoIsUsed;
    /// <summary>是否黑暗（原文：boIsDark:Boolean；Delphi Boolean 为 1 字节）</summary>
    public byte BoIsDark;
    /// <summary>当前帧序（原文：dwIndex:LongWord）</summary>
    public uint DwIndex;
    /// <summary>文件名称（原文：sMusic:string[50]，长度字节 + 最多 50 个 GBK 字节）</summary>
    public ShortString50 SMusic;
    /// <summary>起始图片偏移（原文：dwStartOffset:LongWord）</summary>
    public uint DwStartOffset;
    /// <summary>结束图片偏移（原文：dwEndOffset:LongWord）</summary>
    public uint DwEndOffset;
    /// <summary>当前时间（原文：dwTick:LongWord）</summary>
    public uint DwTick;
}

/// <summary>
/// Delphi <c>string[50]</c> 短字符串：1 字节长度 + 50 字节 GBK 定长缓冲。
/// <para>布局与 <c>GXX.Core.Protocol.ShortStr</c> 的容量语义一致（容量 50，长度字节计**字节数**）。
/// 需要一个可 Marshal 的定长字段时用 <see cref="ToBytes"/> 取 <c>1 + 50 = 51</c> 字节线格式。</para>
/// </summary>
public struct ShortString50
{
    /// <summary>原文 <c>string[50]</c> 的容量常量。</summary>
    public const int Capacity = 50;

    /// <summary>GBK 字节（最多 <see cref="Capacity"/> 个；不足部分为 0）。</summary>
    public byte[] Bytes;

    /// <summary>按 <c>GXX.Core.Protocol.ShortStr</c> 的规则读取（GBK → string）。</summary>
    public static string Get(byte[] buf, int offset)
        => GXX.Core.Protocol.ShortStr.Get(buf ?? Array.Empty<byte>(), offset, Capacity);

    /// <summary>按 <c>GXX.Core.Protocol.ShortStr</c> 的规则写入（string → GBK，超容量截断）。</summary>
    public static void Set(byte[] buf, int offset, string value)
        => GXX.Core.Protocol.ShortStr.Set(buf, offset, Capacity, value ?? string.Empty);

    /// <summary>写出 51 字节线格式（长度字节 + 50 字节数据）。</summary>
    public byte[] ToBytes()
    {
        var buf = new byte[1 + Capacity];
        byte[] src = Bytes ?? Array.Empty<byte>();
        int n = Math.Min(src.Length, Capacity);
        buf[0] = (byte)n;
        Array.Copy(src, 0, buf, 1, n);
        return buf;
    }
}

/// <summary>uWeatherEffectDef.pas 的 <c>g_WeateherEffect: array[0..21] of TWeateherEffect</c>。</summary>
public static class WeatherEffectDef
{
    /// <summary>原文 21 行：<c>g_WeateherEffect:array[0..21] of TWeateherEffect</c> —— 声明 22 个槽位。</summary>
    public const int DeclaredSlots = 22;
    /// <summary>原文初始化列表实际给出的项数（与声明槽数一致 = 22）。</summary>
    public const int InitializedSlots = 22;

    /// <summary>原文行号 -&gt; 表项序号对照（供审计）。</summary>
    public static readonly int[] SourceLines = new[] {
        22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43
    };

    /// <summary>
    /// 原文 21-45 行逐项照抄（22 项，D1:22 .. D1:43；原文 :44 的注释项不采纳）。
    /// </summary>
    public static TWeateherEffect[] CreateDefaultTable()
    {
        var t = new TWeateherEffect[DeclaredSlots];
        t[0] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 0u, DwEndOffset = 9u, DwTick = 0u }; // 原文:22
        t[1] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 0u, DwEndOffset = 9u, DwTick = 0u }; // 原文:23
        t[2] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 110u, DwEndOffset = 149u, DwTick = 0u }; // 原文:24
        t[3] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 0u, DwEndOffset = 29u, DwTick = 0u }; // 原文:25
        t[4] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 30u, DwEndOffset = 59u, DwTick = 0u }; // 原文:26
        t[5] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 60u, DwEndOffset = 89u, DwTick = 0u }; // 原文:27
        t[6] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 90u, DwEndOffset = 119u, DwTick = 0u }; // 原文:28
        t[7] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 120u, DwEndOffset = 149u, DwTick = 0u }; // 原文:29
        t[8] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 150u, DwEndOffset = 179u, DwTick = 0u }; // 原文:30
        t[9] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 180u, DwEndOffset = 209u, DwTick = 0u }; // 原文:31
        t[10] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 210u, DwEndOffset = 239u, DwTick = 0u }; // 原文:32
        t[11] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 240u, DwEndOffset = 269u, DwTick = 0u }; // 原文:33
        t[12] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 270u, DwEndOffset = 299u, DwTick = 0u }; // 原文:34
        t[13] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 300u, DwEndOffset = 359u, DwTick = 0u }; // 原文:35
        t[14] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 360u, DwEndOffset = 389u, DwTick = 0u }; // 原文:36
        t[15] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 390u, DwEndOffset = 419u, DwTick = 0u }; // 原文:37
        t[16] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 420u, DwEndOffset = 449u, DwTick = 0u }; // 原文:38
        t[17] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 450u, DwEndOffset = 479u, DwTick = 0u }; // 原文:39
        t[18] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 480u, DwEndOffset = 509u, DwTick = 0u }; // 原文:40
        t[19] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 510u, DwEndOffset = 539u, DwTick = 0u }; // 原文:41
        t[20] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 540u, DwEndOffset = 569u, DwTick = 0u }; // 原文:42
        t[21] = new TWeateherEffect { BoIsUsed = 0, BoIsDark = 0, DwIndex = 0u, DwStartOffset = 570u, DwEndOffset = 599u, DwTick = 0u }; // 原文:43
        // 原文如此（uWeatherEffectDef.pas:44）：以下项在原文中被 // 注释掉，本移植同样不采纳。
        // (boIsUsed: False; boIsDark: False; dwIndex: 0; sMusic : '';dwStartOffset: 600; dwEndOffset: 209; dwTick: 0),
        return t;
    }
}
