// <auto-generated />
// 生成器：_scratch/gen_weathereffect.py —— uWeatherEffectDef.pas 金标。
// 普通 .cs 源文件，随 SDK 风格测试工程自动编译；不占用共享 csproj，也不挂资源。
using System;

namespace GXX.Client.Tests;

/// <summary>g_WeateherEffect 金标（22 项 × 7 字段，原文顺序）。</summary>
public static class TailWeatherEffectGolden
{
    /// <summary>(下标, boIsUsed, boIsDark, dwIndex, dwStartOffset, dwEndOffset, dwTick)；原文 sMusic 全为空串。</summary>
    public static readonly int[][] Rows =
    {
        new[] { 0, 0, 0, 0, 0, 9, 0 }, // 原文:22
        new[] { 1, 0, 0, 0, 0, 9, 0 }, // 原文:23
        new[] { 2, 0, 0, 0, 110, 149, 0 }, // 原文:24
        new[] { 3, 0, 0, 0, 0, 29, 0 }, // 原文:25
        new[] { 4, 0, 0, 0, 30, 59, 0 }, // 原文:26
        new[] { 5, 0, 0, 0, 60, 89, 0 }, // 原文:27
        new[] { 6, 0, 0, 0, 90, 119, 0 }, // 原文:28
        new[] { 7, 0, 0, 0, 120, 149, 0 }, // 原文:29
        new[] { 8, 0, 0, 0, 150, 179, 0 }, // 原文:30
        new[] { 9, 0, 0, 0, 180, 209, 0 }, // 原文:31
        new[] { 10, 0, 0, 0, 210, 239, 0 }, // 原文:32
        new[] { 11, 0, 0, 0, 240, 269, 0 }, // 原文:33
        new[] { 12, 0, 0, 0, 270, 299, 0 }, // 原文:34
        new[] { 13, 0, 0, 0, 300, 359, 0 }, // 原文:35
        new[] { 14, 0, 0, 0, 360, 389, 0 }, // 原文:36
        new[] { 15, 0, 0, 0, 390, 419, 0 }, // 原文:37
        new[] { 16, 0, 0, 0, 420, 449, 0 }, // 原文:38
        new[] { 17, 0, 0, 0, 450, 479, 0 }, // 原文:39
        new[] { 18, 0, 0, 0, 480, 509, 0 }, // 原文:40
        new[] { 19, 0, 0, 0, 510, 539, 0 }, // 原文:41
        new[] { 20, 0, 0, 0, 540, 569, 0 }, // 原文:42
        new[] { 21, 0, 0, 0, 570, 599, 0 }, // 原文:43
    };

    /// <summary>每项在原文里的声明行号（:22..:43）。</summary>
    public static readonly int[] SourceLines = { 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43 };
}
