// 源单元: Source/Client-HGE/GameConfig/Mir/MirConfigDlg.pas (GBK, 8355 lines, CRLF)
// ** 本文件由脚本生成，禁止手工编辑 **
//    生成器: GXX.CSharp/src/GXX.Client/GUI/GameConfig/Mir/Gen/gen-mir-bindings.ps1
//
// 覆盖: 原文 4621-5044 的 279 条 `X.OnY := Handler;`（逐行，行号即原文行号）。
// 对账: 本表条数 = IMirConfigDlgControls.BindEvents 的挂接条数 = 原文绑定数。

namespace GXX.Client.GUI.GameConfig.Mir;

/// <summary>原文 Initialize 的 279 条事件绑定（数据表，逐行可回溯到原文）。</summary>
public static class TMirConfigDlgEventBindings_Data
{
    public static readonly TMirConfigDlgEventBinding[] All = new TMirConfigDlgEventBinding[]
    {
        new TMirConfigDlgEventBinding { Line = 4621, Ctrl = "PlugConfigDlgClose", Event = "OnClick", Handler = "PlugConfigDlgCloseClickEx" },   // 原文 4621
        new TMirConfigDlgEventBinding { Line = 4623, Ctrl = "PlugPageControlConfig", Event = "OnInRealArea", Handler = "PlugPageControlConfigInRealArea" },   // 原文 4623
        new TMirConfigDlgEventBinding { Line = 4626, Ctrl = "PlugCheckBoxHideMonsterIcons", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4626
        new TMirConfigDlgEventBinding { Line = 4627, Ctrl = "PlugCheckBoxAutoDetourPath", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4627
        new TMirConfigDlgEventBinding { Line = 4628, Ctrl = "PlugCheckBoxDimFireEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4628
        new TMirConfigDlgEventBinding { Line = 4630, Ctrl = "PlugCheckBoxShowHPLabel", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4630
        new TMirConfigDlgEventBinding { Line = 4631, Ctrl = "PlugCheckBoxNumberLable", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4631
        new TMirConfigDlgEventBinding { Line = 4632, Ctrl = "PlugCheckBoxJobAndLevel", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4632
        new TMirConfigDlgEventBinding { Line = 4633, Ctrl = "PlugCheckBoxShowGreenHint", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4633
        new TMirConfigDlgEventBinding { Line = 4634, Ctrl = "PlugCheckBoxDisableSelfStruck", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4634
        new TMirConfigDlgEventBinding { Line = 4635, Ctrl = "PlugCheckBoxSpeedSlow", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4635
        new TMirConfigDlgEventBinding { Line = 4636, Ctrl = "PlugCheckBoxBGMusic", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4636
        new TMirConfigDlgEventBinding { Line = 4637, Ctrl = "PlugCheckBoxRepeatBGMusic", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4637
        new TMirConfigDlgEventBinding { Line = 4639, Ctrl = "PlugCheckBoxShowActorName", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4639
        new TMirConfigDlgEventBinding { Line = 4640, Ctrl = "PlugCheckBoxHideDescUserName", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4640
        new TMirConfigDlgEventBinding { Line = 4641, Ctrl = "PlugCheckBoxDuraWarning", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4641
        new TMirConfigDlgEventBinding { Line = 4642, Ctrl = "PlugCheckBoxNoShift", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4642
        new TMirConfigDlgEventBinding { Line = 4643, Ctrl = "PlugCheckBoxShiftSwitch", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4643
        new TMirConfigDlgEventBinding { Line = 4644, Ctrl = "PlugCheckBoxExpFilter", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4644
        new TMirConfigDlgEventBinding { Line = 4645, Ctrl = "PlugCheckBoxShowMimiMapDesc", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4645
        new TMirConfigDlgEventBinding { Line = 4646, Ctrl = "PlugCheckBoxShowHighlightHPLabel", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4646
        new TMirConfigDlgEventBinding { Line = 4647, Ctrl = "PlugCheckBoxHideGhost", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4647
        new TMirConfigDlgEventBinding { Line = 4648, Ctrl = "PlugCheckBoxShowHealthNumber", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4648
        new TMirConfigDlgEventBinding { Line = 4649, Ctrl = "PlugCheckBoxHideDescUserName", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4649
        new TMirConfigDlgEventBinding { Line = 4650, Ctrl = "PlugCheckBoxHideHumEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4650
        new TMirConfigDlgEventBinding { Line = 4651, Ctrl = "PlugCheckBoxHideWeaponEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4651
        new TMirConfigDlgEventBinding { Line = 4652, Ctrl = "PlugCheckBoxHideActorIcons", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4652
        new TMirConfigDlgEventBinding { Line = 4653, Ctrl = "PlugCheckBoxShowMonName", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4653
        new TMirConfigDlgEventBinding { Line = 4654, Ctrl = "PlugCheckBoxShowNpcName", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4654
        new TMirConfigDlgEventBinding { Line = 4655, Ctrl = "PlugCheckBoxShowNpcHPLabel", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4655
        new TMirConfigDlgEventBinding { Line = 4656, Ctrl = "PlugCheckBoxShowNGLabel", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4656
        new TMirConfigDlgEventBinding { Line = 4657, Ctrl = "PlugCheckBoxAutoPickUpItem", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4657
        new TMirConfigDlgEventBinding { Line = 4658, Ctrl = "PlugCheckBoxAutoPickUpItem", Event = "OnMouseMove", Handler = "DControlMouseMoveShowHint" },   // 原文 4658
        new TMirConfigDlgEventBinding { Line = 4659, Ctrl = "PlugCheckBoxNoCaton", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4659
        new TMirConfigDlgEventBinding { Line = 4661, Ctrl = "PlugCheckBoxAutoOrderItem", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4661
        new TMirConfigDlgEventBinding { Line = 4662, Ctrl = "PlugCheckBoxMagicLock", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4662
        new TMirConfigDlgEventBinding { Line = 4664, Ctrl = "PlugCheckBoxPickAll", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4664
        new TMirConfigDlgEventBinding { Line = 4665, Ctrl = "PlugCheckBoxPickAll", Event = "OnMouseMove", Handler = "DControlMouseMoveShowHint" },   // 原文 4665
        new TMirConfigDlgEventBinding { Line = 4667, Ctrl = "PlugCheckBoxShowValueItemEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4667
        new TMirConfigDlgEventBinding { Line = 4668, Ctrl = "PlugCheckBoxShowValueItemEffect", Event = "OnMouseMove", Handler = "DControlMouseMoveShowHint" },   // 原文 4668
        new TMirConfigDlgEventBinding { Line = 4670, Ctrl = "PlugCheckBoxNotParaly", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4670
        new TMirConfigDlgEventBinding { Line = 4671, Ctrl = "PlugCheckBoxHideTitle", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4671
        new TMirConfigDlgEventBinding { Line = 4672, Ctrl = "PlugCheckBoxContinueButchItem", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4672
        new TMirConfigDlgEventBinding { Line = 4673, Ctrl = "PlugCheckBoxUpdateStatus", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4673
        new TMirConfigDlgEventBinding { Line = 4675, Ctrl = "PlugCheckBoxSmartLongHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4675
        new TMirConfigDlgEventBinding { Line = 4676, Ctrl = "PlugCheckBoxSmartPosLongHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4676
        new TMirConfigDlgEventBinding { Line = 4677, Ctrl = "PlugCheckBoxSmartWalkLongHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4677
        new TMirConfigDlgEventBinding { Line = 4678, Ctrl = "PlugCheckBoxSmartWideHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4678
        new TMirConfigDlgEventBinding { Line = 4679, Ctrl = "PlugCheckBoxSmartFireHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4679
        new TMirConfigDlgEventBinding { Line = 4680, Ctrl = "PlugCheckBoxSmartSwordHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4680
        new TMirConfigDlgEventBinding { Line = 4681, Ctrl = "PlugCheckBoxSmartKTZHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4681
        new TMirConfigDlgEventBinding { Line = 4682, Ctrl = "PlugCheckBoxSmartCRSHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4682
        new TMirConfigDlgEventBinding { Line = 4683, Ctrl = "PlugCheckBoxSmartTWNHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4683
        new TMirConfigDlgEventBinding { Line = 4684, Ctrl = "PlugCheckBoxAutoHideMode", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4684
        new TMirConfigDlgEventBinding { Line = 4685, Ctrl = "PlugCheckBoxAutoCHangePoison", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4685
        new TMirConfigDlgEventBinding { Line = 4686, Ctrl = "PlugCheckBoxHumAutoShield", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4686
        new TMirConfigDlgEventBinding { Line = 4687, Ctrl = "PlugCheckBoxHumStruckShield", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4687
        new TMirConfigDlgEventBinding { Line = 4688, Ctrl = "PlugCheckBoxHeroAutoShield", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4688
        new TMirConfigDlgEventBinding { Line = 4689, Ctrl = "PlugCheckBoxAssistantHeroAutoShield", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4689
        new TMirConfigDlgEventBinding { Line = 4690, Ctrl = "PlugCheckBoxHumManuallySnowWind", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4690
        new TMirConfigDlgEventBinding { Line = 4691, Ctrl = "PlugCheckBoxHumManuallyFireBoom", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4691
        new TMirConfigDlgEventBinding { Line = 4692, Ctrl = "PlugCheckBoxHumShootLightenLockTarget", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4692
        new TMirConfigDlgEventBinding { Line = 4693, Ctrl = "PlugCheckBoxHumManuallyMeteorShower", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4693
        new TMirConfigDlgEventBinding { Line = 4694, Ctrl = "PlugCheckBoxHumManuallyMove10Attack", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4694
        new TMirConfigDlgEventBinding { Line = 4695, Ctrl = "PlugCheckBoxHumManuallyFire", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4695
        new TMirConfigDlgEventBinding { Line = 4696, Ctrl = "PlugCheckBoxHeroContinuousNoHitMon", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4696
        new TMirConfigDlgEventBinding { Line = 4697, Ctrl = "PlugCheckBoxHeroShowNumberState", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4697
        new TMirConfigDlgEventBinding { Line = 4698, Ctrl = "PlugCheckBoxAutoMagic", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4698
        new TMirConfigDlgEventBinding { Line = 4699, Ctrl = "PlugCheckBoxUseKeyBoard", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4699
        new TMirConfigDlgEventBinding { Line = 4700, Ctrl = "PlugCheckBoxShowHPUnit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4700
        new TMirConfigDlgEventBinding { Line = 4701, Ctrl = "PlugCheckBoxSmart113Hit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4701
        new TMirConfigDlgEventBinding { Line = 4703, Ctrl = "PlugCheckBoxAutoCustomHit1", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4703
        new TMirConfigDlgEventBinding { Line = 4704, Ctrl = "PlugCheckBoxAutoCustomHit2", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4704
        new TMirConfigDlgEventBinding { Line = 4705, Ctrl = "PlugCheckBoxAutoCustomHit3", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4705
        new TMirConfigDlgEventBinding { Line = 4706, Ctrl = "PlugCheckBoxAutoCustomHit4", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4706
        new TMirConfigDlgEventBinding { Line = 4707, Ctrl = "PlugCheckBoxAutoCustomHit5", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4707
        new TMirConfigDlgEventBinding { Line = 4708, Ctrl = "PlugCheckBoxAutoCustomHit6", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4708
        new TMirConfigDlgEventBinding { Line = 4709, Ctrl = "PlugCheckBoxAutoCustomHit7", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4709
        new TMirConfigDlgEventBinding { Line = 4710, Ctrl = "PlugCheckBoxAutoCustomHit8", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4710
        new TMirConfigDlgEventBinding { Line = 4712, Ctrl = "PlugCheckBoxHumManuallyCustomHit1", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4712
        new TMirConfigDlgEventBinding { Line = 4713, Ctrl = "PlugCheckBoxHumManuallyCustomHit2", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4713
        new TMirConfigDlgEventBinding { Line = 4714, Ctrl = "PlugCheckBoxHumManuallyCustomHit3", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4714
        new TMirConfigDlgEventBinding { Line = 4715, Ctrl = "PlugCheckBoxHumManuallyCustomHit4", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4715
        new TMirConfigDlgEventBinding { Line = 4716, Ctrl = "PlugCheckBoxHumManuallyCustomHit5", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4716
        new TMirConfigDlgEventBinding { Line = 4718, Ctrl = "PlugCheckBoxAutoOpenSpell", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4718
        new TMirConfigDlgEventBinding { Line = 4719, Ctrl = "PlugCheckBoxAutoContinueAttack", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4719
        new TMirConfigDlgEventBinding { Line = 4721, Ctrl = "PlugCheckBoxAutoGroupAttack", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4721
        new TMirConfigDlgEventBinding { Line = 4722, Ctrl = "PlugCheckBoxAutoGroupNoAttackMon", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4722
        new TMirConfigDlgEventBinding { Line = 4724, Ctrl = "PlugCheckBoxNearEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4724
        new TMirConfigDlgEventBinding { Line = 4725, Ctrl = "PlugCheckBoxNearHint", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4725
        new TMirConfigDlgEventBinding { Line = 4726, Ctrl = "PlugCheckBoxAutoLock", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4726
        new TMirConfigDlgEventBinding { Line = 4727, Ctrl = "PlugCheckBoxColorShow", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4727
        new TMirConfigDlgEventBinding { Line = 4728, Ctrl = "PlugCheckBoxSpecialQuickFlashing", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4728
        new TMirConfigDlgEventBinding { Line = 4729, Ctrl = "PlugCheckBoxBlacklistHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4729
        new TMirConfigDlgEventBinding { Line = 4730, Ctrl = "PlugCheckBoxFriendHit", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4730
        new TMirConfigDlgEventBinding { Line = 4731, Ctrl = "PlugCheckBoxSceneShake", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4731
        new TMirConfigDlgEventBinding { Line = 4732, Ctrl = "PlugCheckBoxAutoDownHorse", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4732
        new TMirConfigDlgEventBinding { Line = 4734, Ctrl = "PlugCheckDisableChartMemoSize", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4734
        new TMirConfigDlgEventBinding { Line = 4735, Ctrl = "PlugCheckBoxItemCmp", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4735
        new TMirConfigDlgEventBinding { Line = 4736, Ctrl = "PlugCheckBoxItemCmp", Event = "OnMouseMove", Handler = "DControlMouseMoveShowHint" },   // 原文 4736
        new TMirConfigDlgEventBinding { Line = 4738, Ctrl = "PlugCheckBoxBagFastItemCmp", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4738
        new TMirConfigDlgEventBinding { Line = 4739, Ctrl = "PlugCheckBoxBagFastItemCmp", Event = "OnMouseMove", Handler = "DControlMouseMoveShowHint" },   // 原文 4739
        new TMirConfigDlgEventBinding { Line = 4741, Ctrl = "PlugCheckBoxHideItemEffect", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4741
        new TMirConfigDlgEventBinding { Line = 4742, Ctrl = "PlugCheckBoxVolume", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4742
        new TMirConfigDlgEventBinding { Line = 4743, Ctrl = "PlugCheckBoxDisableDeal", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4743
        new TMirConfigDlgEventBinding { Line = 4744, Ctrl = "PlugCheckBoxHideBigHPProgress", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4744
        new TMirConfigDlgEventBinding { Line = 4746, Ctrl = "PlugCheckBoxShowTargetAperture", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4746
        new TMirConfigDlgEventBinding { Line = 4748, Ctrl = "TrackBarVolume", Event = "OnChanggingPosition", Handler = "OnChanggingVolumePosition" },   // 原文 4748
        new TMirConfigDlgEventBinding { Line = 4749, Ctrl = "TrackBarVolume", Event = "OnChangedPosition", Handler = "OnChangedVolumePosition" },   // 原文 4749
        new TMirConfigDlgEventBinding { Line = 4751, Ctrl = "PlugComboBoxColorShow", Event = "OnSelect", Handler = "DComboBoxColorShow" },   // 原文 4751
        new TMirConfigDlgEventBinding { Line = 4754, Ctrl = "PlugComboBoxItemStdMode", Event = "OnSelect", Handler = "DComboBoxItemStdModeSelect" },   // 原文 4754
        new TMirConfigDlgEventBinding { Line = 4755, Ctrl = "PlugEditSearchItem", Event = "OnChange", Handler = "DEditSearchItemChange" },   // 原文 4755
        new TMirConfigDlgEventBinding { Line = 4756, Ctrl = "PlugLabelDefaultItem", Event = "OnClick", Handler = "DLabelDefaultItemClick" },   // 原文 4756
        new TMirConfigDlgEventBinding { Line = 4757, Ctrl = "PlugMemoConfig2", Event = "OnListItemClick", Handler = "ListViewItemClick" },   // 原文 4757
        new TMirConfigDlgEventBinding { Line = 4759, Ctrl = "PlugMemoConfig4Button1", Event = "OnClick", Handler = "RefUseItemConfigClick" },   // 原文 4759
        new TMirConfigDlgEventBinding { Line = 4760, Ctrl = "PlugMemoConfig4Button2", Event = "OnClick", Handler = "RefUseItemConfigClick" },   // 原文 4760
        new TMirConfigDlgEventBinding { Line = 4761, Ctrl = "PlugMemoConfig4Button3", Event = "OnClick", Handler = "RefUseItemConfigClick" },   // 原文 4761
        new TMirConfigDlgEventBinding { Line = 4762, Ctrl = "PlugMemoConfig4Button4", Event = "OnClick", Handler = "RefUseItemConfigClick" },   // 原文 4762
        new TMirConfigDlgEventBinding { Line = 4763, Ctrl = "PlugMemoConfig4Button5", Event = "OnClick", Handler = "RefUseItemConfigClick" },   // 原文 4763
        new TMirConfigDlgEventBinding { Line = 4765, Ctrl = "PlugEditExpFilter", Event = "OnChange", Handler = "DEditChange" },   // 原文 4765
        new TMirConfigDlgEventBinding { Line = 4766, Ctrl = "PlugEditAutoMagicTime", Event = "OnChange", Handler = "DEditChange" },   // 原文 4766
        new TMirConfigDlgEventBinding { Line = 4768, Ctrl = "PlugCheckBoxAutoPercent", Event = "OnClick", Handler = "DCheckBoxAutoPercentClick" },   // 原文 4768
        new TMirConfigDlgEventBinding { Line = 4769, Ctrl = "PlugCheckBoxRenewAutoPercent", Event = "OnClick", Handler = "DCheckBoxRenewAutoPercentClick" },   // 原文 4769
        new TMirConfigDlgEventBinding { Line = 4770, Ctrl = "PlugCheckBoxSuperMedicaPercent", Event = "OnClick", Handler = "DCheckBoxSuperMedicaPercentClick" },   // 原文 4770
        new TMirConfigDlgEventBinding { Line = 4772, Ctrl = "PlugCheckBoxCheckHPIsAuto", Event = "OnClick", Handler = "DCheckBoxCheckHPIsAutoClick" },   // 原文 4772
        new TMirConfigDlgEventBinding { Line = 4773, Ctrl = "PlugCheckBoxCheckMPIsAuto", Event = "OnClick", Handler = "DCheckBoxCheckMPIsAutoClick" },   // 原文 4773
        new TMirConfigDlgEventBinding { Line = 4774, Ctrl = "PlugEditCheckHPPercent", Event = "OnChange", Handler = "DEditCheckHPPercentChange" },   // 原文 4774
        new TMirConfigDlgEventBinding { Line = 4775, Ctrl = "PlugEditCheckMPPercent", Event = "OnChange", Handler = "DEditCheckMPPercentChange" },   // 原文 4775
        new TMirConfigDlgEventBinding { Line = 4776, Ctrl = "PlugComboBoxCheckHPValue", Event = "OnSelect", Handler = "ComboBoxCheckHPValueChange" },   // 原文 4776
        new TMirConfigDlgEventBinding { Line = 4777, Ctrl = "PlugComboBoxCheckMPValue", Event = "OnSelect", Handler = "ComboBoxCheckMPValueChange" },   // 原文 4777
        new TMirConfigDlgEventBinding { Line = 4779, Ctrl = "PlugCheckBoxCheckDuraIsAuto", Event = "OnClick", Handler = "DCheckBoxCheckDuraIsAuto" },   // 原文 4779
        new TMirConfigDlgEventBinding { Line = 4780, Ctrl = "PlugEditCheckDura", Event = "OnUnFocused", Handler = "DEditCheckDuraChange" },   // 原文 4780
        new TMirConfigDlgEventBinding { Line = 4781, Ctrl = "PlugEditCheckDura", Event = "OnChange", Handler = "DEditCheckDuraChange" },   // 原文 4781
        new TMirConfigDlgEventBinding { Line = 4782, Ctrl = "PlugEditCheckDuraValue", Event = "OnChange", Handler = "DEditCheckDuraValueChange" },   // 原文 4782
        new TMirConfigDlgEventBinding { Line = 4783, Ctrl = "PlugEditCheckDuraTime", Event = "OnUnFocused", Handler = "DEditCheckDuraTimeChange" },   // 原文 4783
        new TMirConfigDlgEventBinding { Line = 4788, Ctrl = "PlugCheckBoxRenewHPIsAuto", Event = "OnClick", Handler = "DCheckBoxRenewHPIsAutoClick" },   // 原文 4788
        new TMirConfigDlgEventBinding { Line = 4789, Ctrl = "PlugCheckBoxRenewMPIsAuto", Event = "OnClick", Handler = "DCheckBoxRenewMPIsAutoClick" },   // 原文 4789
        new TMirConfigDlgEventBinding { Line = 4790, Ctrl = "PlugCheckBoxRenewSpecialHPIsAuto", Event = "OnClick", Handler = "DCheckBoxRenewSpecialHPIsAutoClick" },   // 原文 4790
        new TMirConfigDlgEventBinding { Line = 4791, Ctrl = "PlugCheckBoxRenewSpecialMPIsAuto", Event = "OnClick", Handler = "DCheckBoxRenewSpecialMPIsAutoClick" },   // 原文 4791
        new TMirConfigDlgEventBinding { Line = 4793, Ctrl = "PlugEditRenewHPPercent", Event = "OnChange", Handler = "DEditRenewHPPercentChange" },   // 原文 4793
        new TMirConfigDlgEventBinding { Line = 4794, Ctrl = "PlugEditRenewMPPercent", Event = "OnChange", Handler = "DEditRenewMPPercentChange" },   // 原文 4794
        new TMirConfigDlgEventBinding { Line = 4795, Ctrl = "PlugEditRenewHPTime", Event = "OnUnFocused", Handler = "DEditRenewHPTimeChange" },   // 原文 4795
        new TMirConfigDlgEventBinding { Line = 4796, Ctrl = "PlugEditRenewMPTime", Event = "OnUnFocused", Handler = "DEditRenewMPTimeChange" },   // 原文 4796
        new TMirConfigDlgEventBinding { Line = 4798, Ctrl = "PlugEditRenewSpecialHPPercent", Event = "OnChange", Handler = "DEditRenewSpecialHPPercentChange" },   // 原文 4798
        new TMirConfigDlgEventBinding { Line = 4799, Ctrl = "PlugEditRenewSpecialMPPercent", Event = "OnChange", Handler = "DEditRenewSpecialMPPercentChange" },   // 原文 4799
        new TMirConfigDlgEventBinding { Line = 4800, Ctrl = "PlugEditRenewSpecialHPTime", Event = "OnUnFocused", Handler = "DEditRenewSpecialHPTimeChange" },   // 原文 4800
        new TMirConfigDlgEventBinding { Line = 4801, Ctrl = "PlugEditRenewSpecialMPTime", Event = "OnUnFocused", Handler = "DEditRenewSpecialMPTimeChange" },   // 原文 4801
        new TMirConfigDlgEventBinding { Line = 4803, Ctrl = "PlugCheckBoxUseSuperMedica", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4803
        new TMirConfigDlgEventBinding { Line = 4817, Ctrl = "PlugCheckBoxUseSuperMedicaItemName0", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4817
        new TMirConfigDlgEventBinding { Line = 4818, Ctrl = "PlugCheckBoxUseSuperMedicaItemName1", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4818
        new TMirConfigDlgEventBinding { Line = 4819, Ctrl = "PlugCheckBoxUseSuperMedicaItemName2", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4819
        new TMirConfigDlgEventBinding { Line = 4820, Ctrl = "PlugCheckBoxUseSuperMedicaItemName3", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4820
        new TMirConfigDlgEventBinding { Line = 4821, Ctrl = "PlugCheckBoxUseSuperMedicaItemName4", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4821
        new TMirConfigDlgEventBinding { Line = 4822, Ctrl = "PlugCheckBoxUseSuperMedicaItemName5", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4822
        new TMirConfigDlgEventBinding { Line = 4823, Ctrl = "PlugCheckBoxUseSuperMedicaItemName6", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4823
        new TMirConfigDlgEventBinding { Line = 4824, Ctrl = "PlugCheckBoxUseSuperMedicaItemName7", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4824
        new TMirConfigDlgEventBinding { Line = 4825, Ctrl = "PlugCheckBoxUseSuperMedicaItemName8", Event = "OnClick", Handler = "DCheckBoxUseSuperMedicaItemNameClick" },   // 原文 4825
        new TMirConfigDlgEventBinding { Line = 4827, Ctrl = "PlugEditSuperMedicaHP0", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4827
        new TMirConfigDlgEventBinding { Line = 4828, Ctrl = "PlugEditSuperMedicaHP1", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4828
        new TMirConfigDlgEventBinding { Line = 4829, Ctrl = "PlugEditSuperMedicaHP2", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4829
        new TMirConfigDlgEventBinding { Line = 4830, Ctrl = "PlugEditSuperMedicaHP3", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4830
        new TMirConfigDlgEventBinding { Line = 4831, Ctrl = "PlugEditSuperMedicaHP4", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4831
        new TMirConfigDlgEventBinding { Line = 4832, Ctrl = "PlugEditSuperMedicaHP5", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4832
        new TMirConfigDlgEventBinding { Line = 4833, Ctrl = "PlugEditSuperMedicaHP6", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4833
        new TMirConfigDlgEventBinding { Line = 4834, Ctrl = "PlugEditSuperMedicaHP7", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4834
        new TMirConfigDlgEventBinding { Line = 4835, Ctrl = "PlugEditSuperMedicaHP8", Event = "OnChange", Handler = "DEditSuperMedicaHPChange" },   // 原文 4835
        new TMirConfigDlgEventBinding { Line = 4837, Ctrl = "PlugEditSuperMedicaHPTime0", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4837
        new TMirConfigDlgEventBinding { Line = 4838, Ctrl = "PlugEditSuperMedicaHPTime1", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4838
        new TMirConfigDlgEventBinding { Line = 4839, Ctrl = "PlugEditSuperMedicaHPTime2", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4839
        new TMirConfigDlgEventBinding { Line = 4840, Ctrl = "PlugEditSuperMedicaHPTime3", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4840
        new TMirConfigDlgEventBinding { Line = 4841, Ctrl = "PlugEditSuperMedicaHPTime4", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4841
        new TMirConfigDlgEventBinding { Line = 4842, Ctrl = "PlugEditSuperMedicaHPTime5", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4842
        new TMirConfigDlgEventBinding { Line = 4843, Ctrl = "PlugEditSuperMedicaHPTime6", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4843
        new TMirConfigDlgEventBinding { Line = 4844, Ctrl = "PlugEditSuperMedicaHPTime7", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4844
        new TMirConfigDlgEventBinding { Line = 4845, Ctrl = "PlugEditSuperMedicaHPTime8", Event = "OnUnFocused", Handler = "DEditSuperMedicaHPTimeChange" },   // 原文 4845
        new TMirConfigDlgEventBinding { Line = 4847, Ctrl = "PlugEditSuperMedicaMP0", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4847
        new TMirConfigDlgEventBinding { Line = 4848, Ctrl = "PlugEditSuperMedicaMP1", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4848
        new TMirConfigDlgEventBinding { Line = 4849, Ctrl = "PlugEditSuperMedicaMP2", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4849
        new TMirConfigDlgEventBinding { Line = 4850, Ctrl = "PlugEditSuperMedicaMP3", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4850
        new TMirConfigDlgEventBinding { Line = 4851, Ctrl = "PlugEditSuperMedicaMP4", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4851
        new TMirConfigDlgEventBinding { Line = 4852, Ctrl = "PlugEditSuperMedicaMP5", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4852
        new TMirConfigDlgEventBinding { Line = 4853, Ctrl = "PlugEditSuperMedicaMP6", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4853
        new TMirConfigDlgEventBinding { Line = 4854, Ctrl = "PlugEditSuperMedicaMP7", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4854
        new TMirConfigDlgEventBinding { Line = 4855, Ctrl = "PlugEditSuperMedicaMP8", Event = "OnChange", Handler = "DEditSuperMedicaMPChange" },   // 原文 4855
        new TMirConfigDlgEventBinding { Line = 4857, Ctrl = "PlugEditSuperMedicaMPTime0", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4857
        new TMirConfigDlgEventBinding { Line = 4858, Ctrl = "PlugEditSuperMedicaMPTime1", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4858
        new TMirConfigDlgEventBinding { Line = 4859, Ctrl = "PlugEditSuperMedicaMPTime2", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4859
        new TMirConfigDlgEventBinding { Line = 4860, Ctrl = "PlugEditSuperMedicaMPTime3", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4860
        new TMirConfigDlgEventBinding { Line = 4861, Ctrl = "PlugEditSuperMedicaMPTime4", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4861
        new TMirConfigDlgEventBinding { Line = 4862, Ctrl = "PlugEditSuperMedicaMPTime5", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4862
        new TMirConfigDlgEventBinding { Line = 4863, Ctrl = "PlugEditSuperMedicaMPTime6", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4863
        new TMirConfigDlgEventBinding { Line = 4864, Ctrl = "PlugEditSuperMedicaMPTime7", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4864
        new TMirConfigDlgEventBinding { Line = 4865, Ctrl = "PlugEditSuperMedicaMPTime8", Event = "OnUnFocused", Handler = "DEditSuperMedicaMPTimeChange" },   // 原文 4865
        new TMirConfigDlgEventBinding { Line = 4867, Ctrl = "PlugEditHeroDodgeHPPercent", Event = "OnChange", Handler = "PlugEditHeroDodgeHPPercentChange" },   // 原文 4867
        new TMirConfigDlgEventBinding { Line = 4870, Ctrl = "PlugMemoConfig6LabelKeyBoard1", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4870
        new TMirConfigDlgEventBinding { Line = 4871, Ctrl = "PlugMemoConfig6LabelKeyBoard2", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4871
        new TMirConfigDlgEventBinding { Line = 4872, Ctrl = "PlugMemoConfig6LabelKeyBoard3", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4872
        new TMirConfigDlgEventBinding { Line = 4873, Ctrl = "PlugMemoConfig6LabelKeyBoard4", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4873
        new TMirConfigDlgEventBinding { Line = 4874, Ctrl = "PlugMemoConfig6LabelKeyBoard5", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4874
        new TMirConfigDlgEventBinding { Line = 4875, Ctrl = "PlugMemoConfig6LabelKeyBoard6", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4875
        new TMirConfigDlgEventBinding { Line = 4876, Ctrl = "PlugMemoConfig6LabelKeyBoard7", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4876
        new TMirConfigDlgEventBinding { Line = 4877, Ctrl = "PlugMemoConfig6LabelKeyBoard8", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4877
        new TMirConfigDlgEventBinding { Line = 4878, Ctrl = "PlugMemoConfig6LabelKeyBoard9", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4878
        new TMirConfigDlgEventBinding { Line = 4879, Ctrl = "PlugMemoConfig6LabelKeyBoard10", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4879
        new TMirConfigDlgEventBinding { Line = 4880, Ctrl = "PlugMemoConfig6LabelKeyBoard11", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4880
        new TMirConfigDlgEventBinding { Line = 4881, Ctrl = "PlugMemoConfig6LabelKeyBoard12", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4881
        new TMirConfigDlgEventBinding { Line = 4882, Ctrl = "PlugMemoConfig6LabelKeyBoard13", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4882
        new TMirConfigDlgEventBinding { Line = 4883, Ctrl = "PlugMemoConfig6LabelKeyBoard14", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4883
        new TMirConfigDlgEventBinding { Line = 4884, Ctrl = "PlugMemoConfig6LabelKeyBoard15", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4884
        new TMirConfigDlgEventBinding { Line = 4885, Ctrl = "PlugMemoConfig6LabelKeyBoard16", Event = "OnKeyDown", Handler = "DLabelKeyBoardKeyDown" },   // 原文 4885
        new TMirConfigDlgEventBinding { Line = 4887, Ctrl = "PlugMemoConfig6LabelKeyBoard1", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4887
        new TMirConfigDlgEventBinding { Line = 4888, Ctrl = "PlugMemoConfig6LabelKeyBoard2", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4888
        new TMirConfigDlgEventBinding { Line = 4889, Ctrl = "PlugMemoConfig6LabelKeyBoard3", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4889
        new TMirConfigDlgEventBinding { Line = 4890, Ctrl = "PlugMemoConfig6LabelKeyBoard4", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4890
        new TMirConfigDlgEventBinding { Line = 4891, Ctrl = "PlugMemoConfig6LabelKeyBoard5", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4891
        new TMirConfigDlgEventBinding { Line = 4892, Ctrl = "PlugMemoConfig6LabelKeyBoard6", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4892
        new TMirConfigDlgEventBinding { Line = 4893, Ctrl = "PlugMemoConfig6LabelKeyBoard7", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4893
        new TMirConfigDlgEventBinding { Line = 4894, Ctrl = "PlugMemoConfig6LabelKeyBoard8", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4894
        new TMirConfigDlgEventBinding { Line = 4895, Ctrl = "PlugMemoConfig6LabelKeyBoard9", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4895
        new TMirConfigDlgEventBinding { Line = 4896, Ctrl = "PlugMemoConfig6LabelKeyBoard10", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4896
        new TMirConfigDlgEventBinding { Line = 4897, Ctrl = "PlugMemoConfig6LabelKeyBoard11", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4897
        new TMirConfigDlgEventBinding { Line = 4898, Ctrl = "PlugMemoConfig6LabelKeyBoard12", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4898
        new TMirConfigDlgEventBinding { Line = 4899, Ctrl = "PlugMemoConfig6LabelKeyBoard13", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4899
        new TMirConfigDlgEventBinding { Line = 4900, Ctrl = "PlugMemoConfig6LabelKeyBoard14", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4900
        new TMirConfigDlgEventBinding { Line = 4901, Ctrl = "PlugMemoConfig6LabelKeyBoard15", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4901
        new TMirConfigDlgEventBinding { Line = 4902, Ctrl = "PlugMemoConfig6LabelKeyBoard16", Event = "OnMouseDown", Handler = "DLabelKeyBoardMouseDown" },   // 原文 4902
        new TMirConfigDlgEventBinding { Line = 4939, Ctrl = "PlugScrollBoxBoss", Event = "OnClick", Handler = "DMemoBossListClick" },   // 原文 4939
        new TMirConfigDlgEventBinding { Line = 4940, Ctrl = "PlugBtnBossAdd", Event = "OnClick", Handler = "DBtnBossAddClick" },   // 原文 4940
        new TMirConfigDlgEventBinding { Line = 4941, Ctrl = "PlugBtnBossModify", Event = "OnClick", Handler = "DBtnBossModifyClick" },   // 原文 4941
        new TMirConfigDlgEventBinding { Line = 4942, Ctrl = "PlugBtnBossDel", Event = "OnClick", Handler = "DBtnBossDelClick" },   // 原文 4942
        new TMirConfigDlgEventBinding { Line = 4944, Ctrl = "PlugEditSpecialColor", Event = "OnChange", Handler = "DEditSpecialColorChange" },   // 原文 4944
        new TMirConfigDlgEventBinding { Line = 4945, Ctrl = "PlugBtnDiyAdd", Event = "OnClick", Handler = "DBtnDiyAddClick" },   // 原文 4945
        new TMirConfigDlgEventBinding { Line = 4946, Ctrl = "PlugBtnDiyDel", Event = "OnClick", Handler = "DBtnDiyDelClick" },   // 原文 4946
        new TMirConfigDlgEventBinding { Line = 4947, Ctrl = "PlugBtnDiyImport", Event = "OnClick", Handler = "DBtnItemsImportOrExportClick" },   // 原文 4947
        new TMirConfigDlgEventBinding { Line = 4948, Ctrl = "PlugBtnDiyExport", Event = "OnClick", Handler = "DBtnItemsImportOrExportClick" },   // 原文 4948
        new TMirConfigDlgEventBinding { Line = 4949, Ctrl = "PlugBtnDiyEdit", Event = "OnClick", Handler = "PlugBtnDiyEditClick" },   // 原文 4949
        new TMirConfigDlgEventBinding { Line = 4952, Ctrl = "PlugPageControlConfig", Event = "OnActivePageChange", Handler = "PlugPageControlConfigActivePageChange" },   // 原文 4952
        new TMirConfigDlgEventBinding { Line = 4957, Ctrl = "PlugScrollBoxMons", Event = "OnClick", Handler = "DMemoGJMonListClick" },   // 原文 4957
        new TMirConfigDlgEventBinding { Line = 4963, Ctrl = "PlugMemoConfig8Button1", Event = "OnClick", Handler = "DBtnGJPageControlClick" },   // 原文 4963
        new TMirConfigDlgEventBinding { Line = 4964, Ctrl = "PlugMemoConfig8Button2", Event = "OnClick", Handler = "DBtnGJPageControlClick" },   // 原文 4964
        new TMirConfigDlgEventBinding { Line = 4965, Ctrl = "PlugMemoConfig8Button3", Event = "OnClick", Handler = "DBtnGJPageControlClick" },   // 原文 4965
        new TMirConfigDlgEventBinding { Line = 4967, Ctrl = "PlugButtonMonNameAdd", Event = "OnClick", Handler = "DBtnGJMonNameAddClick" },   // 原文 4967
        new TMirConfigDlgEventBinding { Line = 4968, Ctrl = "PlugButtonMonNameEdit", Event = "OnClick", Handler = "DBtnGJMonNameEditClick" },   // 原文 4968
        new TMirConfigDlgEventBinding { Line = 4969, Ctrl = "PlugButtonMonNameDel", Event = "OnClick", Handler = "DBtnGJMonNameDelClick" },   // 原文 4969
        new TMirConfigDlgEventBinding { Line = 4971, Ctrl = "PlugCheckBoxNoRedPoison", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4971
        new TMirConfigDlgEventBinding { Line = 4972, Ctrl = "PlugCheckBoxNoBluePoison", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4972
        new TMirConfigDlgEventBinding { Line = 4974, Ctrl = "PlugCheckBoxPlayAttack", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4974
        new TMirConfigDlgEventBinding { Line = 4975, Ctrl = "PlugCheckBoxNotRushMon", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4975
        new TMirConfigDlgEventBinding { Line = 4976, Ctrl = "PlugCheckBoxNoDuFu", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4976
        new TMirConfigDlgEventBinding { Line = 4977, Ctrl = "PlugCheckBoxBagFull", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4977
        new TMirConfigDlgEventBinding { Line = 4978, Ctrl = "PlugCheckBoxAutoPickup", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4978
        new TMirConfigDlgEventBinding { Line = 4979, Ctrl = "PlugCheckBoxLimitScreen", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4979
        new TMirConfigDlgEventBinding { Line = 4980, Ctrl = "PlugCheckBoxDFAvoid", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4980
        new TMirConfigDlgEventBinding { Line = 4981, Ctrl = "PlugCheckSimpleShowActor", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4981
        new TMirConfigDlgEventBinding { Line = 4982, Ctrl = "PlugCheckSimpleShowHumanDress", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4982
        new TMirConfigDlgEventBinding { Line = 4983, Ctrl = "PlugCheckSimpleShowHumanWeapon", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4983
        new TMirConfigDlgEventBinding { Line = 4984, Ctrl = "PlugCheckSimpleShowBB", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4984
        new TMirConfigDlgEventBinding { Line = 4986, Ctrl = "PlugEditNotRushMonRange", Event = "OnChange", Handler = "DEditNotRushMonRangeChange" },   // 原文 4986
        new TMirConfigDlgEventBinding { Line = 4987, Ctrl = "PlugComboBoxPlayAttackValue", Event = "OnSelect", Handler = "ComboBoxPlayAttackValueSelect" },   // 原文 4987
        new TMirConfigDlgEventBinding { Line = 4988, Ctrl = "PlugComboBoxNoRedPoisonValue", Event = "OnSelect", Handler = "ComboBoxPlayAttackValueSelect" },   // 原文 4988
        new TMirConfigDlgEventBinding { Line = 4989, Ctrl = "PlugComboBoxNoBluePoisonValue", Event = "OnSelect", Handler = "ComboBoxPlayAttackValueSelect" },   // 原文 4989
        new TMirConfigDlgEventBinding { Line = 4990, Ctrl = "PlugComboBoxNoDuFuValue", Event = "OnSelect", Handler = "ComboBoxPlayAttackValueSelect" },   // 原文 4990
        new TMirConfigDlgEventBinding { Line = 4991, Ctrl = "PlugComboBoxBagFullValue", Event = "OnSelect", Handler = "ComboBoxPlayAttackValueSelect" },   // 原文 4991
        new TMirConfigDlgEventBinding { Line = 4993, Ctrl = "PlugMemoConfig82", Event = "OnListItemClick", Handler = "ListViewGJMagicItemClick" },   // 原文 4993
        new TMirConfigDlgEventBinding { Line = 4994, Ctrl = "PlugMemoConfig83", Event = "OnListItemClick", Handler = "ListViewGJMagicItemClick" },   // 原文 4994
        new TMirConfigDlgEventBinding { Line = 4996, Ctrl = "PlugCheckBoxGroupAttack", Event = "OnClick", Handler = "CheckBoxClickEx" },   // 原文 4996
        new TMirConfigDlgEventBinding { Line = 4997, Ctrl = "PlugEditNotGroupAttackCount", Event = "OnChange", Handler = "DEditGroupAttackCountChanged" },   // 原文 4997
        new TMirConfigDlgEventBinding { Line = 4998, Ctrl = "PlugButtonGJRun", Event = "OnClick", Handler = "DBtnGJRunClick" },   // 原文 4998
        new TMirConfigDlgEventBinding { Line = 5000, Ctrl = "PlugBtnGJPoint", Event = "OnClick", Handler = "PlugBtnGJPointClick" },   // 原文 5000
        new TMirConfigDlgEventBinding { Line = 5002, Ctrl = "PlugMemoConfig10ButtonEdit", Event = "OnClick", Handler = "OnPlugMemoConfig10ButtonEditClick" },   // 原文 5002
        new TMirConfigDlgEventBinding { Line = 5003, Ctrl = "PlugMemoConfig10ButtonSave", Event = "OnClick", Handler = "OnPlugMemoConfig10ButtonEditClick" },   // 原文 5003
        new TMirConfigDlgEventBinding { Line = 5004, Ctrl = "PlugMemoConfig10ButtonCancel", Event = "OnClick", Handler = "OnPlugMemoConfig10ButtonEditClick" },   // 原文 5004
        new TMirConfigDlgEventBinding { Line = 5009, Ctrl = "PlugPageControlConfig", Event = "OnActivePageChange", Handler = "OnPlugPageControlConfigActivePageChange" },   // 原文 5009
        new TMirConfigDlgEventBinding { Line = 5013, Ctrl = "PopupMenuItems", Event = "OnClick", Handler = "OnPopupMenuItemsClick" },   // 原文 5013
        new TMirConfigDlgEventBinding { Line = 5034, Ctrl = "PlugScrollBoxUnbindItems", Event = "OnClick", Handler = "PlugScrollBoxUnbindItemsClick" },   // 原文 5034
        new TMirConfigDlgEventBinding { Line = 5035, Ctrl = "PlugBtnUnbindItemAdd", Event = "OnClick", Handler = "PlugBtnUnbindItemClick" },   // 原文 5035
        new TMirConfigDlgEventBinding { Line = 5036, Ctrl = "PlugBtnUnbindItemDel", Event = "OnClick", Handler = "PlugBtnUnbindItemClick" },   // 原文 5036
        new TMirConfigDlgEventBinding { Line = 5037, Ctrl = "PlugBtnUnbindItemEdit", Event = "OnClick", Handler = "PlugBtnUnbindItemClick" },   // 原文 5037
        new TMirConfigDlgEventBinding { Line = 5038, Ctrl = "PlugBtnUnbindItemSave", Event = "OnClick", Handler = "PlugBtnUnbindItemClick" },   // 原文 5038
    };
}

