// ============================================================================
// uFrmCustomMagic.pas 事件处理器**逐条来源表**（脚本从 Delphi 原文抽取，非手工转录）
//
// 生成脚本：对 Source\M2Engine\Forms\uFrmCustomMagic.pas（GBK→UTF-8 后）逐个
// procedure TFrmCustomMagic.*(Sender: TObject); 取"去空行/去 // 注释"后的规范体，
// 匹配 7 行形状者登记为"单字段写回"处理器；行号即原文物理行号（该文件 4800 行、
// 全 CRLF、无裸 LF，故行号稳定）。测试用本表驱动 151 个处理器 × 3 分支。
// ============================================================================

using System.Collections.Generic;

namespace GXX.M2Server.Tests;

/// <summary>一个"单字段写回"处理器的抽取行。</summary>
public sealed class CustomMagicHandlerRow
{
    /// <summary>托管方法名（去掉 TFrmCustomMagic. 前缀，首字母大写）。</summary>
    public string Method = "";
    /// <summary>Delphi 原方法名。</summary>
    public string DelphiName = "";
    /// <summary>原文行号区间起。</summary>
    public int StartLine;
    /// <summary>原文行号区间止。</summary>
    public int EndLine;
    /// <summary>守卫字段：0=FCurrentCustomConfig、1=FCurrentClientConfig、2=FCurrentServerConfig。</summary>
    public int Guard;
    /// <summary>目标路径（FCurrent* 之后的原文文本）。</summary>
    public string TargetPath = "";
    /// <summary>来源控件名。</summary>
    public string Control = "";
    /// <summary>来源控件种类：spin/check/edit/combo。</summary>
    public string ControlKind = "";
    /// <summary>原文右侧表达式（逐字）。</summary>
    public string Rhs = "";
}

/// <summary>抽取表（151 行）。</summary>
public static class CustomMagicHandlerTable
{
    /// <summary>全部"单字段写回"处理器。</summary>
    public static readonly IReadOnlyList<CustomMagicHandlerRow> Rows = new CustomMagicHandlerRow[]
    {
        new CustomMagicHandlerRow { Method = "ChkClientLockClick", DelphiName = "chkClientLockClick", StartLine = 2510, EndLine = 2518, Guard = 0, TargetPath = "ClientBaseConfig.MagicLock", Control = "chkClientLock", ControlKind = "check", Rhs = "chkClientLock.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientLockSelfClick", DelphiName = "chkClientLockSelfClick", StartLine = 2533, EndLine = 2541, Guard = 0, TargetPath = "ClientBaseConfig.MagicLockSelf", Control = "chkClientLockSelf", ControlKind = "check", Rhs = "chkClientLockSelf.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientNotRaiseHandClick", DelphiName = "chkClientNotRaiseHandClick", StartLine = 2542, EndLine = 2550, Guard = 0, TargetPath = "ClientBaseConfig.NotRaiseHand", Control = "chkClientNotRaiseHand", ControlKind = "check", Rhs = "chkClientNotRaiseHand.Checked" },
        new CustomMagicHandlerRow { Method = "CbbClientIconFileChange", DelphiName = "cbbClientIconFileChange", StartLine = 2551, EndLine = 2559, Guard = 1, TargetPath = "Icon_File", Control = "cbbClientIconFile", ControlKind = "combo", Rhs = "cbbClientIconFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientIconIndexChange", DelphiName = "seClientIconIndexChange", StartLine = 2560, EndLine = 2568, Guard = 1, TargetPath = "Icon_Index", Control = "seClientIconIndex", ControlKind = "spin", Rhs = "seClientIconIndex.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientFlyFileChange", DelphiName = "cbbClientFlyFileChange", StartLine = 2569, EndLine = 2577, Guard = 1, TargetPath = "Fly_File", Control = "cbbClientFlyFile", ControlKind = "combo", Rhs = "cbbClientFlyFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientFlyStartIndexChange", DelphiName = "seClientFlyStartIndexChange", StartLine = 2578, EndLine = 2586, Guard = 1, TargetPath = "Fly_StartIndex", Control = "seClientFlyStartIndex", ControlKind = "spin", Rhs = "seClientFlyStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFlyPlayCountChange", DelphiName = "seClientFlyPlayCountChange", StartLine = 2587, EndLine = 2595, Guard = 1, TargetPath = "Fly_PlayCount", Control = "seClientFlyPlayCount", ControlKind = "spin", Rhs = "seClientFlyPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFlyEmptyCountChange", DelphiName = "seClientFlyEmptyCountChange", StartLine = 2596, EndLine = 2604, Guard = 1, TargetPath = "Fly_EmptyCount", Control = "seClientFlyEmptyCount", ControlKind = "spin", Rhs = "seClientFlyEmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFlyPlayTimeChange", DelphiName = "seClientFlyPlayTimeChange", StartLine = 2605, EndLine = 2613, Guard = 1, TargetPath = "Fly_PlayTime", Control = "seClientFlyPlayTime", ControlKind = "spin", Rhs = "seClientFlyPlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientFlyDrawModeChange", DelphiName = "cbbClientFlyDrawModeChange", StartLine = 2614, EndLine = 2622, Guard = 1, TargetPath = "Fly_DrawMode", Control = "cbbClientFlyDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientFlyDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientFlyDirCountChange", DelphiName = "cbbClientFlyDirCountChange", StartLine = 2623, EndLine = 2631, Guard = 1, TargetPath = "Fly_DirCount", Control = "cbbClientFlyDirCount", ControlKind = "combo", Rhs = "TCustomDirCount(cbbClientFlyDirCount.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkClientFlyCalcDirClick", DelphiName = "chkClientFlyCalcDirClick", StartLine = 2632, EndLine = 2640, Guard = 1, TargetPath = "Fly_CalcDir", Control = "chkClientFlyCalcDir", ControlKind = "check", Rhs = "chkClientFlyCalcDir.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientFlyFireGunModeClick", DelphiName = "chkClientFlyFireGunModeClick", StartLine = 2641, EndLine = 2649, Guard = 1, TargetPath = "Fly_FireGunMode", Control = "chkClientFlyFireGunMode", ControlKind = "check", Rhs = "chkClientFlyFireGunMode.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientFlyLightRangeChange", DelphiName = "seClientFlyLightRangeChange", StartLine = 2650, EndLine = 2658, Guard = 1, TargetPath = "Fly_LightRange", Control = "seClientFlyLightRange", ControlKind = "spin", Rhs = "seClientFlyLightRange.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientFlyEffFileChange", DelphiName = "cbbClientFlyEffFileChange", StartLine = 2659, EndLine = 2667, Guard = 1, TargetPath = "FlyEff_File", Control = "cbbClientFlyEffFile", ControlKind = "combo", Rhs = "cbbClientFlyEffFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientFlyEffStartIndexChange", DelphiName = "seClientFlyEffStartIndexChange", StartLine = 2668, EndLine = 2676, Guard = 1, TargetPath = "FlyEff_StartIndex", Control = "seClientFlyEffStartIndex", ControlKind = "spin", Rhs = "seClientFlyEffStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientFlyEffDrawModeChange", DelphiName = "cbbClientFlyEffDrawModeChange", StartLine = 2677, EndLine = 2685, Guard = 1, TargetPath = "FlyEff_DrawMode", Control = "cbbClientFlyEffDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientFlyEffDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfFileChange", DelphiName = "cbbClientSelfFileChange", StartLine = 2686, EndLine = 2694, Guard = 1, TargetPath = "Self_File", Control = "cbbClientSelfFile", ControlKind = "combo", Rhs = "cbbClientSelfFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientSelfStartIndexChange", DelphiName = "seClientSelfStartIndexChange", StartLine = 2695, EndLine = 2703, Guard = 1, TargetPath = "Self_StartIndex", Control = "seClientSelfStartIndex", ControlKind = "spin", Rhs = "seClientSelfStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfPlayCountChange", DelphiName = "seClientSelfPlayCountChange", StartLine = 2704, EndLine = 2712, Guard = 1, TargetPath = "Self_PlayCount", Control = "seClientSelfPlayCount", ControlKind = "spin", Rhs = "seClientSelfPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfEmptyCountChange", DelphiName = "seClientSelfEmptyCountChange", StartLine = 2713, EndLine = 2721, Guard = 1, TargetPath = "Self_EmptyCount", Control = "seClientSelfEmptyCount", ControlKind = "spin", Rhs = "seClientSelfEmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfPlayTimeChange", DelphiName = "seClientSelfPlayTimeChange", StartLine = 2722, EndLine = 2730, Guard = 1, TargetPath = "Self_PlayTime", Control = "seClientSelfPlayTime", ControlKind = "spin", Rhs = "seClientSelfPlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfDrawOrderChange", DelphiName = "cbbClientSelfDrawOrderChange", StartLine = 2731, EndLine = 2739, Guard = 1, TargetPath = "Self_DrawOrder", Control = "cbbClientSelfDrawOrder", ControlKind = "combo", Rhs = "TCustomDrawOrder(cbbClientSelfDrawOrder.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfDrawModeChange", DelphiName = "cbbClientSelfDrawModeChange", StartLine = 2740, EndLine = 2748, Guard = 1, TargetPath = "Self_DrawMode", Control = "cbbClientSelfDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientSelfDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfDirCountChange", DelphiName = "cbbClientSelfDirCountChange", StartLine = 2749, EndLine = 2757, Guard = 1, TargetPath = "Self_DirCount", Control = "cbbClientSelfDirCount", ControlKind = "combo", Rhs = "TCustomDirCount(cbbClientSelfDirCount.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfDirCalcTypeChange", DelphiName = "cbbClientSelfDirCalcTypeChange", StartLine = 2758, EndLine = 2766, Guard = 1, TargetPath = "Self_DirCalcType", Control = "cbbClientSelfDirCalcType", ControlKind = "combo", Rhs = "TCustomDirCalcType(cbbClientSelfDirCalcType.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkClientSelfPlayDelayActionClick", DelphiName = "chkClientSelfPlayDelayActionClick", StartLine = 2767, EndLine = 2775, Guard = 1, TargetPath = "Self_PlayDelayAction", Control = "chkClientSelfPlayDelayAction", ControlKind = "check", Rhs = "chkClientSelfPlayDelayAction.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientSelfPlayFailNoDrawClick", DelphiName = "chkClientSelfPlayFailNoDrawClick", StartLine = 2776, EndLine = 2784, Guard = 1, TargetPath = "Self_PlayFailNoDraw", Control = "chkClientSelfPlayFailNoDraw", ControlKind = "check", Rhs = "chkClientSelfPlayFailNoDraw.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientSelfLightRangeChange", DelphiName = "seClientSelfLightRangeChange", StartLine = 2785, EndLine = 2793, Guard = 1, TargetPath = "Self_LightRange", Control = "seClientSelfLightRange", ControlKind = "spin", Rhs = "seClientSelfLightRange.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientPreTargetFileChange", DelphiName = "cbbClientPreTargetFileChange", StartLine = 2794, EndLine = 2802, Guard = 1, TargetPath = "PreTarget_File", Control = "cbbClientPreTargetFile", ControlKind = "combo", Rhs = "cbbClientPreTargetFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetStartIndexChange", DelphiName = "seClientPreTargetStartIndexChange", StartLine = 2803, EndLine = 2811, Guard = 1, TargetPath = "PreTarget_StartIndex", Control = "seClientPreTargetStartIndex", ControlKind = "spin", Rhs = "seClientPreTargetStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetStartIndex2Change", DelphiName = "seClientPreTargetStartIndex2Change", StartLine = 2812, EndLine = 2820, Guard = 1, TargetPath = "PreTarget_StartIndex2", Control = "seClientPreTargetStartIndex2", ControlKind = "spin", Rhs = "seClientPreTargetStartIndex2.Value" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetPlayCountChange", DelphiName = "seClientPreTargetPlayCountChange", StartLine = 2821, EndLine = 2829, Guard = 1, TargetPath = "PreTarget_PlayCount", Control = "seClientPreTargetPlayCount", ControlKind = "spin", Rhs = "seClientPreTargetPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetEmptyCountChange", DelphiName = "seClientPreTargetEmptyCountChange", StartLine = 2830, EndLine = 2838, Guard = 1, TargetPath = "PreTarget_EmptyCount", Control = "seClientPreTargetEmptyCount", ControlKind = "spin", Rhs = "seClientPreTargetEmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "ChkClientPreTargetCalcDirClick", DelphiName = "chkClientPreTargetCalcDirClick", StartLine = 2839, EndLine = 2847, Guard = 1, TargetPath = "PreTarget_CalcDir", Control = "chkClientPreTargetCalcDir", ControlKind = "check", Rhs = "chkClientPreTargetCalcDir.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetPlayTimeChange", DelphiName = "seClientPreTargetPlayTimeChange", StartLine = 2848, EndLine = 2856, Guard = 1, TargetPath = "PreTarget_PlayTime", Control = "seClientPreTargetPlayTime", ControlKind = "spin", Rhs = "seClientPreTargetPlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientPreTargetDrawModeChange", DelphiName = "cbbClientPreTargetDrawModeChange", StartLine = 2857, EndLine = 2865, Guard = 1, TargetPath = "PreTarget_DrawMode", Control = "cbbClientPreTargetDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientPreTargetDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientPreTargetDrawMode2Change", DelphiName = "cbbClientPreTargetDrawMode2Change", StartLine = 2866, EndLine = 2874, Guard = 1, TargetPath = "PreTarget_DrawMode2", Control = "cbbClientPreTargetDrawMode2", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientPreTargetDrawMode2.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkClientPreTargetLockDrawClick", DelphiName = "chkClientPreTargetLockDrawClick", StartLine = 2875, EndLine = 2883, Guard = 1, TargetPath = "PreTarget_LockDraw", Control = "chkClientPreTargetLockDraw", ControlKind = "check", Rhs = "chkClientPreTargetLockDraw.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientPreTargetLightRangeChange", DelphiName = "seClientPreTargetLightRangeChange", StartLine = 2884, EndLine = 2892, Guard = 1, TargetPath = "PreTarget_LightRange", Control = "seClientPreTargetLightRange", ControlKind = "spin", Rhs = "seClientPreTargetLightRange.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientTargetFileChange", DelphiName = "cbbClientTargetFileChange", StartLine = 2893, EndLine = 2901, Guard = 1, TargetPath = "Target_File", Control = "cbbClientTargetFile", ControlKind = "combo", Rhs = "cbbClientTargetFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientTargetStartIndexChange", DelphiName = "seClientTargetStartIndexChange", StartLine = 2902, EndLine = 2910, Guard = 1, TargetPath = "Target_StartIndex", Control = "seClientTargetStartIndex", ControlKind = "spin", Rhs = "seClientTargetStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetStartIndex2Change", DelphiName = "seClientTargetStartIndex2Change", StartLine = 2911, EndLine = 2919, Guard = 1, TargetPath = "Target_StartIndex2", Control = "seClientTargetStartIndex2", ControlKind = "spin", Rhs = "seClientTargetStartIndex2.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetPlayCountChange", DelphiName = "seClientTargetPlayCountChange", StartLine = 2920, EndLine = 2928, Guard = 1, TargetPath = "Target_PlayCount", Control = "seClientTargetPlayCount", ControlKind = "spin", Rhs = "seClientTargetPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetPlayTimeChange", DelphiName = "seClientTargetPlayTimeChange", StartLine = 2929, EndLine = 2937, Guard = 1, TargetPath = "Target_PlayTime", Control = "seClientTargetPlayTime", ControlKind = "spin", Rhs = "seClientTargetPlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientTargetDrawModeChange", DelphiName = "cbbClientTargetDrawModeChange", StartLine = 2938, EndLine = 2946, Guard = 1, TargetPath = "Target_DrawMode", Control = "cbbClientTargetDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientTargetDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "CbbClientTargetDrawMode2Change", DelphiName = "cbbClientTargetDrawMode2Change", StartLine = 2947, EndLine = 2955, Guard = 1, TargetPath = "Target_DrawMode2", Control = "cbbClientTargetDrawMode2", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientTargetDrawMode2.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkClientTargetMultiPlayClick", DelphiName = "chkClientTargetMultiPlayClick", StartLine = 2956, EndLine = 2964, Guard = 1, TargetPath = "Target_MultiPlay", Control = "chkClientTargetMultiPlay", ControlKind = "check", Rhs = "chkClientTargetMultiPlay.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientTargetLockDrawClick", DelphiName = "chkClientTargetLockDrawClick", StartLine = 2965, EndLine = 2973, Guard = 1, TargetPath = "Target_LockDraw", Control = "chkClientTargetLockDraw", ControlKind = "check", Rhs = "chkClientTargetLockDraw.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientTargetLightRangeChange", DelphiName = "seClientTargetLightRangeChange", StartLine = 2974, EndLine = 2982, Guard = 1, TargetPath = "Target_LightRange", Control = "seClientTargetLightRange", ControlKind = "spin", Rhs = "seClientTargetLightRange.Value" },
        new CustomMagicHandlerRow { Method = "ChkClientTargetKeepPlayClick", DelphiName = "chkClientTargetKeepPlayClick", StartLine = 2983, EndLine = 2991, Guard = 1, TargetPath = "Target_KeepPlay", Control = "chkClientTargetKeepPlay", ControlKind = "check", Rhs = "chkClientTargetKeepPlay.Checked" },
        new CustomMagicHandlerRow { Method = "SeClientTargetKeepTimeChange", DelphiName = "seClientTargetKeepTimeChange", StartLine = 2992, EndLine = 3000, Guard = 1, TargetPath = "Target_KeepTime", Control = "seClientTargetKeepTime", ControlKind = "spin", Rhs = "seClientTargetKeepTime.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetKeepTime2Change", DelphiName = "seClientTargetKeepTime2Change", StartLine = 3001, EndLine = 3009, Guard = 1, TargetPath = "Target_KeepTime2", Control = "seClientTargetKeepTime2", ControlKind = "spin", Rhs = "seClientTargetKeepTime2.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetKeepAttackIntervalChange", DelphiName = "seClientTargetKeepAttackIntervalChange", StartLine = 3010, EndLine = 3018, Guard = 1, TargetPath = "Target_KeepAttackInterval", Control = "seClientTargetKeepAttackInterval", ControlKind = "spin", Rhs = "seClientTargetKeepAttackInterval.Value" },
        new CustomMagicHandlerRow { Method = "SeClientTargetKeepAttackRangeChange", DelphiName = "seClientTargetKeepAttackRangeChange", StartLine = 3019, EndLine = 3027, Guard = 1, TargetPath = "Target_KeepAttackRange", Control = "seClientTargetKeepAttackRange", ControlKind = "spin", Rhs = "seClientTargetKeepAttackRange.Value" },
        new CustomMagicHandlerRow { Method = "SeTargetKeepLightRangeChange", DelphiName = "seTargetKeepLightRangeChange", StartLine = 3028, EndLine = 3036, Guard = 1, TargetPath = "Target_KeepLightRange", Control = "seTargetKeepLightRange", ControlKind = "spin", Rhs = "seTargetKeepLightRange.Value" },
        new CustomMagicHandlerRow { Method = "ChkClientTargetKeepMultiPlayClick", DelphiName = "chkClientTargetKeepMultiPlayClick", StartLine = 3037, EndLine = 3045, Guard = 1, TargetPath = "Target_KeepMultiPlay", Control = "chkClientTargetKeepMultiPlay", ControlKind = "check", Rhs = "chkClientTargetKeepMultiPlay.Checked" },
        new CustomMagicHandlerRow { Method = "CbbTargetStatus1_FileChange", DelphiName = "cbbTargetStatus1_FileChange", StartLine = 3046, EndLine = 3054, Guard = 1, TargetPath = "TargetStatus1_File", Control = "cbbTargetStatus1_File", ControlKind = "combo", Rhs = "cbbTargetStatus1_File.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus1_StartIndexChange", DelphiName = "seTargetStatus1_StartIndexChange", StartLine = 3055, EndLine = 3063, Guard = 1, TargetPath = "TargetStatus1_StartIndex", Control = "seTargetStatus1_StartIndex", ControlKind = "spin", Rhs = "seTargetStatus1_StartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus1_PlayCountChange", DelphiName = "seTargetStatus1_PlayCountChange", StartLine = 3064, EndLine = 3072, Guard = 1, TargetPath = "TargetStatus1_PlayCount", Control = "seTargetStatus1_PlayCount", ControlKind = "spin", Rhs = "seTargetStatus1_PlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus1_EmptyCountChange", DelphiName = "seTargetStatus1_EmptyCountChange", StartLine = 3073, EndLine = 3081, Guard = 1, TargetPath = "TargetStatus1_EmptyCount", Control = "seTargetStatus1_EmptyCount", ControlKind = "spin", Rhs = "seTargetStatus1_EmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "CbbTargetStatus1_DrawModeChange", DelphiName = "cbbTargetStatus1_DrawModeChange", StartLine = 3091, EndLine = 3099, Guard = 1, TargetPath = "TargetStatus1_DrawMode", Control = "cbbTargetStatus1_DrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbTargetStatus1_DrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkTargetStatus1_CalcDirClick", DelphiName = "chkTargetStatus1_CalcDirClick", StartLine = 3100, EndLine = 3108, Guard = 1, TargetPath = "TargetStatus1_CalcDir", Control = "chkTargetStatus1_CalcDir", ControlKind = "check", Rhs = "chkTargetStatus1_CalcDir.Checked" },
        new CustomMagicHandlerRow { Method = "CbbTargetStatus2_FileChange", DelphiName = "cbbTargetStatus2_FileChange", StartLine = 3109, EndLine = 3117, Guard = 1, TargetPath = "TargetStatus2_File", Control = "cbbTargetStatus2_File", ControlKind = "combo", Rhs = "cbbTargetStatus2_File.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus2_StartIndexChange", DelphiName = "seTargetStatus2_StartIndexChange", StartLine = 3118, EndLine = 3126, Guard = 1, TargetPath = "TargetStatus2_StartIndex", Control = "seTargetStatus2_StartIndex", ControlKind = "spin", Rhs = "seTargetStatus2_StartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus2_PlayCountChange", DelphiName = "seTargetStatus2_PlayCountChange", StartLine = 3127, EndLine = 3135, Guard = 1, TargetPath = "TargetStatus2_PlayCount", Control = "seTargetStatus2_PlayCount", ControlKind = "spin", Rhs = "seTargetStatus2_PlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeTargetStatus2_EmptyCountChange", DelphiName = "seTargetStatus2_EmptyCountChange", StartLine = 3136, EndLine = 3144, Guard = 1, TargetPath = "TargetStatus2_EmptyCount", Control = "seTargetStatus2_EmptyCount", ControlKind = "spin", Rhs = "seTargetStatus2_EmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "CbbTargetStatus2_DrawModeChange", DelphiName = "cbbTargetStatus2_DrawModeChange", StartLine = 3154, EndLine = 3162, Guard = 1, TargetPath = "TargetStatus2_DrawMode", Control = "cbbTargetStatus2_DrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbTargetStatus2_DrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkTargetStatus2_CalcDirClick", DelphiName = "chkTargetStatus2_CalcDirClick", StartLine = 3163, EndLine = 3171, Guard = 1, TargetPath = "TargetStatus2_CalcDir", Control = "chkTargetStatus2_CalcDir", ControlKind = "check", Rhs = "chkTargetStatus2_CalcDir.Checked" },
        new CustomMagicHandlerRow { Method = "SeUseIntervalChange", DelphiName = "seUseIntervalChange", StartLine = 3196, EndLine = 3204, Guard = 2, TargetPath = "UseInterval", Control = "seUseInterval", ControlKind = "spin", Rhs = "seUseInterval.Value" },
        new CustomMagicHandlerRow { Method = "EdtFailMsgChange", DelphiName = "edtFailMsgChange", StartLine = 3216, EndLine = 3224, Guard = 2, TargetPath = "FailMsg", Control = "edtFailMsg", ControlKind = "edit", Rhs = "edtFailMsg.Text" },
        new CustomMagicHandlerRow { Method = "EdtSucceedMsgChange", DelphiName = "edtSucceedMsgChange", StartLine = 3225, EndLine = 3233, Guard = 2, TargetPath = "SucceedMsg", Control = "edtSucceedMsg", ControlKind = "edit", Rhs = "edtSucceedMsg.Text" },
        new CustomMagicHandlerRow { Method = "EdtCloseMsgChange", DelphiName = "edtCloseMsgChange", StartLine = 3234, EndLine = 3242, Guard = 2, TargetPath = "CloseMsg", Control = "edtCloseMsg", ControlKind = "edit", Rhs = "edtCloseMsg.Text" },
        new CustomMagicHandlerRow { Method = "SeAttackNearRangeChange", DelphiName = "seAttackNearRangeChange", StartLine = 3260, EndLine = 3268, Guard = 2, TargetPath = "AttackNearRange", Control = "seAttackNearRange", ControlKind = "spin", Rhs = "seAttackNearRange.Value" },
        new CustomMagicHandlerRow { Method = "SeAttackGroupRangeChange", DelphiName = "seAttackGroupRangeChange", StartLine = 3269, EndLine = 3277, Guard = 2, TargetPath = "AttackGroupRange", Control = "seAttackGroupRange", ControlKind = "spin", Rhs = "seAttackGroupRange.Value" },
        new CustomMagicHandlerRow { Method = "CbbAttackPowerCalcChange", DelphiName = "cbbAttackPowerCalcChange", StartLine = 3287, EndLine = 3295, Guard = 2, TargetPath = "AttackPowerCalc", Control = "cbbAttackPowerCalc", ControlKind = "combo", Rhs = "TCustomAttackPowerCalc(cbbAttackPowerCalc.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "SeAttackPowerRateChange", DelphiName = "seAttackPowerRateChange", StartLine = 3304, EndLine = 3312, Guard = 2, TargetPath = "AttackPowerRates[cbbAttackPowerLevel.ItemIndex]", Control = "seAttackPowerRate", ControlKind = "spin", Rhs = "seAttackPowerRate.Value" },
        new CustomMagicHandlerRow { Method = "SeLineAttackAddPowerChange", DelphiName = "seLineAttackAddPowerChange", StartLine = 3313, EndLine = 3321, Guard = 2, TargetPath = "AttackPowerLineAdd", Control = "seLineAttackAddPower", ControlKind = "spin", Rhs = "seLineAttackAddPower.Value" },
        new CustomMagicHandlerRow { Method = "SeAttackPowerUndeadAddChange", DelphiName = "seAttackPowerUndeadAddChange", StartLine = 3322, EndLine = 3330, Guard = 2, TargetPath = "AttackPowerUndeadAdd", Control = "seAttackPowerUndeadAdd", ControlKind = "spin", Rhs = "seAttackPowerUndeadAdd.Value" },
        new CustomMagicHandlerRow { Method = "CbbNeedItemChange", DelphiName = "cbbNeedItemChange", StartLine = 3331, EndLine = 3339, Guard = 2, TargetPath = "NeedItem", Control = "cbbNeedItem", ControlKind = "combo", Rhs = "TMagicNeedItem(cbbNeedItem.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "SeNeedItemCountChange", DelphiName = "seNeedItemCountChange", StartLine = 3340, EndLine = 3348, Guard = 2, TargetPath = "NeedItemCount", Control = "seNeedItemCount", ControlKind = "spin", Rhs = "seNeedItemCount.Value" },
        new CustomMagicHandlerRow { Method = "EdtNeedItemCustomItemNameChange", DelphiName = "edtNeedItemCustomItemNameChange", StartLine = 3349, EndLine = 3357, Guard = 2, TargetPath = "NeedItemCustomItemName", Control = "edtNeedItemCustomItemName", ControlKind = "edit", Rhs = "edtNeedItemCustomItemName.Text" },
        new CustomMagicHandlerRow { Method = "ChkNeedItemUseBagItemClick", DelphiName = "chkNeedItemUseBagItemClick", StartLine = 3358, EndLine = 3366, Guard = 2, TargetPath = "NeedItemUseBagItem", Control = "chkNeedItemUseBagItem", ControlKind = "check", Rhs = "chkNeedItemUseBagItem.Checked" },
        new CustomMagicHandlerRow { Method = "SeProtectTargetRangeChange", DelphiName = "seProtectTargetRangeChange", StartLine = 3367, EndLine = 3375, Guard = 2, TargetPath = "ProtectTargetRange", Control = "seProtectTargetRange", ControlKind = "spin", Rhs = "seProtectTargetRange.Value" },
        new CustomMagicHandlerRow { Method = "SeAdditionaHP0Change", DelphiName = "seAdditionaHP0Change", StartLine = 3460, EndLine = 3468, Guard = 2, TargetPath = "AdditionalHP0", Control = "seAdditionaHP0", ControlKind = "spin", Rhs = "seAdditionaHP0.Value" },
        new CustomMagicHandlerRow { Method = "ChkseAdditionaHighLevel4Click", DelphiName = "chkseAdditionaHighLevel4Click", StartLine = 3469, EndLine = 3477, Guard = 2, TargetPath = "AdditionalHighLevel4", Control = "chkseAdditionaHighLevel4", ControlKind = "check", Rhs = "chkseAdditionaHighLevel4.Checked" },
        new CustomMagicHandlerRow { Method = "CbbPushedType4Change", DelphiName = "cbbPushedType4Change", StartLine = 3478, EndLine = 3486, Guard = 2, TargetPath = "AdditionalPushedType4", Control = "cbbPushedType4", ControlKind = "combo", Rhs = "cbbPushedType4.ItemIndex" },
        new CustomMagicHandlerRow { Method = "ChkAttackTargetStatusClick", DelphiName = "chkAttackTargetStatusClick", StartLine = 3487, EndLine = 3495, Guard = 2, TargetPath = "AttackTargetStatus", Control = "chkAttackTargetStatus", ControlKind = "check", Rhs = "chkAttackTargetStatus.Checked" },
        new CustomMagicHandlerRow { Method = "SeAttackTargetStatusTimeChange", DelphiName = "seAttackTargetStatusTimeChange", StartLine = 3496, EndLine = 3504, Guard = 2, TargetPath = "AttackTargetStatusTime", Control = "seAttackTargetStatusTime", ControlKind = "spin", Rhs = "seAttackTargetStatusTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbAttackTargetStatusTime_1Change", DelphiName = "cbbAttackTargetStatusTime_1Change", StartLine = 3505, EndLine = 3513, Guard = 2, TargetPath = "AttackTargetStatusTimeUnit", Control = "cbbAttackTargetStatusTime_1", ControlKind = "combo", Rhs = "cbbAttackTargetStatusTime_1.ItemIndex" },
        new CustomMagicHandlerRow { Method = "SeAttackTargetStatusTime_2Change", DelphiName = "seAttackTargetStatusTime_2Change", StartLine = 3514, EndLine = 3522, Guard = 2, TargetPath = "AttackTargetStatusTime2", Control = "seAttackTargetStatusTime_2", ControlKind = "spin", Rhs = "seAttackTargetStatusTime_2.Value" },
        new CustomMagicHandlerRow { Method = "SeAttackTargetStatusDelayChange", DelphiName = "seAttackTargetStatusDelayChange", StartLine = 3523, EndLine = 3531, Guard = 2, TargetPath = "AttackTargetStatusDelay", Control = "seAttackTargetStatusDelay", ControlKind = "spin", Rhs = "seAttackTargetStatusDelay.Value" },
        new CustomMagicHandlerRow { Method = "SeCallMonstersRateChange", DelphiName = "seCallMonstersRateChange", StartLine = 3701, EndLine = 3709, Guard = 2, TargetPath = "CallMonstersRate", Control = "seCallMonstersRate", ControlKind = "spin", Rhs = "seCallMonstersRate.Value" },
        new CustomMagicHandlerRow { Method = "SeCallMonstersLevelChange", DelphiName = "seCallMonstersLevelChange", StartLine = 3710, EndLine = 3718, Guard = 2, TargetPath = "CallMonstersLevel", Control = "seCallMonstersLevel", ControlKind = "spin", Rhs = "seCallMonstersLevel.Value" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportAfterDamageClick", DelphiName = "chkAttackTeleportAfterDamageClick", StartLine = 3719, EndLine = 3727, Guard = 2, TargetPath = "AttackTeleportAfterDamage", Control = "chkAttackTeleportAfterDamage", ControlKind = "check", Rhs = "chkAttackTeleportAfterDamage.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportAttackClick", DelphiName = "chkAttackTeleportAttackClick", StartLine = 3728, EndLine = 3736, Guard = 2, TargetPath = "AttackTeleportAttack", Control = "chkAttackTeleportAttack", ControlKind = "check", Rhs = "chkAttackTeleportAttack.Checked" },
        new CustomMagicHandlerRow { Method = "SeAttackTeleportRateChange", DelphiName = "seAttackTeleportRateChange", StartLine = 3737, EndLine = 3745, Guard = 2, TargetPath = "AttackTeleportRate", Control = "seAttackTeleportRate", ControlKind = "spin", Rhs = "seAttackTeleportRate.Value" },
        new CustomMagicHandlerRow { Method = "SeAttackTeleportRushCountChange", DelphiName = "seAttackTeleportRushCountChange", StartLine = 3746, EndLine = 3754, Guard = 2, TargetPath = "AttackTeleportRushCount", Control = "seAttackTeleportRushCount", ControlKind = "spin", Rhs = "seAttackTeleportRushCount.Value" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRunHumClick", DelphiName = "chkAttackTeleportRunHumClick", StartLine = 3755, EndLine = 3763, Guard = 2, TargetPath = "AttackTeleportRunHum", Control = "chkAttackTeleportRunHum", ControlKind = "check", Rhs = "chkAttackTeleportRunHum.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRunMonClick", DelphiName = "chkAttackTeleportRunMonClick", StartLine = 3764, EndLine = 3772, Guard = 2, TargetPath = "AttackTeleportRunMon", Control = "chkAttackTeleportRunMon", ControlKind = "check", Rhs = "chkAttackTeleportRunMon.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRunNpcClick", DelphiName = "chkAttackTeleportRunNpcClick", StartLine = 3773, EndLine = 3781, Guard = 2, TargetPath = "AttackTeleportRunNpc", Control = "chkAttackTeleportRunNpc", ControlKind = "check", Rhs = "chkAttackTeleportRunNpc.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRunGuardClick", DelphiName = "chkAttackTeleportRunGuardClick", StartLine = 3782, EndLine = 3790, Guard = 2, TargetPath = "AttackTeleportRunGuard", Control = "chkAttackTeleportRunGuard", ControlKind = "check", Rhs = "chkAttackTeleportRunGuard.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRunObstacleClick", DelphiName = "chkAttackTeleportRunObstacleClick", StartLine = 3791, EndLine = 3799, Guard = 2, TargetPath = "AttackTeleportRunObstacle", Control = "chkAttackTeleportRunObstacle", ControlKind = "check", Rhs = "chkAttackTeleportRunObstacle.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportRushClick", DelphiName = "chkAttackTeleportRushClick", StartLine = 3800, EndLine = 3808, Guard = 2, TargetPath = "AttackTeleportRush", Control = "chkAttackTeleportRush", ControlKind = "check", Rhs = "chkAttackTeleportRush.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportWarDisHumRunClick", DelphiName = "chkAttackTeleportWarDisHumRunClick", StartLine = 3809, EndLine = 3817, Guard = 2, TargetPath = "AttackTeleportWarDisHumRun", Control = "chkAttackTeleportWarDisHumRun", ControlKind = "check", Rhs = "chkAttackTeleportWarDisHumRun.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackTeleportCannotRunItemClick", DelphiName = "chkAttackTeleportCannotRunItemClick", StartLine = 3818, EndLine = 3826, Guard = 2, TargetPath = "AttackTeleportCannotRunItem", Control = "chkAttackTeleportCannotRunItem", ControlKind = "check", Rhs = "chkAttackTeleportCannotRunItem.Checked" },
        new CustomMagicHandlerRow { Method = "ChkEnabledCallMonsterClick", DelphiName = "chkEnabledCallMonsterClick", StartLine = 3827, EndLine = 3835, Guard = 2, TargetPath = "EnabledCallMonster", Control = "chkEnabledCallMonster", ControlKind = "check", Rhs = "chkEnabledCallMonster.Checked" },
        new CustomMagicHandlerRow { Method = "CbbClientFastMoveFileChange", DelphiName = "cbbClientFastMoveFileChange", StartLine = 3836, EndLine = 3844, Guard = 1, TargetPath = "FastMove_File", Control = "cbbClientFastMoveFile", ControlKind = "combo", Rhs = "cbbClientFastMoveFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientFastMoveStartIndexChange", DelphiName = "seClientFastMoveStartIndexChange", StartLine = 3845, EndLine = 3853, Guard = 1, TargetPath = "FastMove_StartIndex", Control = "seClientFastMoveStartIndex", ControlKind = "spin", Rhs = "seClientFastMoveStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFastMovePlayCountChange", DelphiName = "seClientFastMovePlayCountChange", StartLine = 3854, EndLine = 3862, Guard = 1, TargetPath = "FastMove_PlayCount", Control = "seClientFastMovePlayCount", ControlKind = "spin", Rhs = "seClientFastMovePlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFastMoveEmptyCountChange", DelphiName = "seClientFastMoveEmptyCountChange", StartLine = 3863, EndLine = 3871, Guard = 1, TargetPath = "FastMove_EmptyCount", Control = "seClientFastMoveEmptyCount", ControlKind = "spin", Rhs = "seClientFastMoveEmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientFastMovePlayTimeChange", DelphiName = "seClientFastMovePlayTimeChange", StartLine = 3872, EndLine = 3880, Guard = 1, TargetPath = "FastMove_PlayTime", Control = "seClientFastMovePlayTime", ControlKind = "spin", Rhs = "seClientFastMovePlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientFastMoveDrawModeChange", DelphiName = "cbbClientFastMoveDrawModeChange", StartLine = 3881, EndLine = 3889, Guard = 1, TargetPath = "FastMove_DrawMode", Control = "cbbClientFastMoveDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientFastMoveDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "ChkClientFastMoveCalcDirClick", DelphiName = "chkClientFastMoveCalcDirClick", StartLine = 3890, EndLine = 3898, Guard = 1, TargetPath = "FastMove_CalcDir", Control = "chkClientFastMoveCalcDir", ControlKind = "check", Rhs = "chkClientFastMoveCalcDir.Checked" },
        new CustomMagicHandlerRow { Method = "ChkClientFastMoveNoHitActionClick", DelphiName = "chkClientFastMoveNoHitActionClick", StartLine = 3899, EndLine = 3907, Guard = 1, TargetPath = "FastMove_NoHitAction", Control = "chkClientFastMoveNoHitAction", ControlKind = "check", Rhs = "chkClientFastMoveNoHitAction.Checked" },
        new CustomMagicHandlerRow { Method = "SeFastMoveLightRangeChange", DelphiName = "seFastMoveLightRangeChange", StartLine = 3908, EndLine = 3916, Guard = 1, TargetPath = "FastMove_LightRange", Control = "seFastMoveLightRange", ControlKind = "spin", Rhs = "seFastMoveLightRange.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfKeepFileChange", DelphiName = "cbbClientSelfKeepFileChange", StartLine = 3935, EndLine = 3943, Guard = 1, TargetPath = "SelfKeep_File", Control = "cbbClientSelfKeepFile", ControlKind = "combo", Rhs = "cbbClientSelfKeepFile.ItemIndex - 1" },
        new CustomMagicHandlerRow { Method = "SeClientSelfKeepStartIndexChange", DelphiName = "seClientSelfKeepStartIndexChange", StartLine = 3944, EndLine = 3952, Guard = 1, TargetPath = "SelfKeep_StartIndex", Control = "seClientSelfKeepStartIndex", ControlKind = "spin", Rhs = "seClientSelfKeepStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfKeepPlayCountChange", DelphiName = "seClientSelfKeepPlayCountChange", StartLine = 3953, EndLine = 3961, Guard = 1, TargetPath = "SelfKeep_PlayCount", Control = "seClientSelfKeepPlayCount", ControlKind = "spin", Rhs = "seClientSelfKeepPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfKeepPlayTimeChange", DelphiName = "seClientSelfKeepPlayTimeChange", StartLine = 3962, EndLine = 3970, Guard = 1, TargetPath = "SelfKeep_PlayTime", Control = "seClientSelfKeepPlayTime", ControlKind = "spin", Rhs = "seClientSelfKeepPlayTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbClientSelfKeepDrawModeChange", DelphiName = "cbbClientSelfKeepDrawModeChange", StartLine = 3971, EndLine = 3979, Guard = 1, TargetPath = "SelfKeep_DrawMode", Control = "cbbClientSelfKeepDrawMode", ControlKind = "combo", Rhs = "TCustomDrawMode(cbbClientSelfKeepDrawMode.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "SeClientSelfKeepTimeChange", DelphiName = "seClientSelfKeepTimeChange", StartLine = 3980, EndLine = 3988, Guard = 1, TargetPath = "SelfKeep_KeepTime", Control = "seClientSelfKeepTime", ControlKind = "spin", Rhs = "seClientSelfKeepTime.Value" },
        new CustomMagicHandlerRow { Method = "SeClientSelfKeepTime2Change", DelphiName = "seClientSelfKeepTime2Change", StartLine = 3989, EndLine = 3997, Guard = 1, TargetPath = "SelfKeep_KeepTime2", Control = "seClientSelfKeepTime2", ControlKind = "spin", Rhs = "seClientSelfKeepTime2.Value" },
        new CustomMagicHandlerRow { Method = "SeCallMonstersRoyaltySecChange", DelphiName = "seCallMonstersRoyaltySecChange", StartLine = 3998, EndLine = 4006, Guard = 2, TargetPath = "CallMonstersRoyaltySec", Control = "seCallMonstersRoyaltySec", ControlKind = "spin", Rhs = "seCallMonstersRoyaltySec.Value" },
        new CustomMagicHandlerRow { Method = "ChkSwitchModeNoCloseClick", DelphiName = "chkSwitchModeNoCloseClick", StartLine = 4019, EndLine = 4027, Guard = 0, TargetPath = "ClientBaseConfig.SwitchModeNoClose", Control = "chkSwitchModeNoClose", ControlKind = "check", Rhs = "chkSwitchModeNoClose.Checked" },
        new CustomMagicHandlerRow { Method = "ChkMagicAutoOpenClick", DelphiName = "chkMagicAutoOpenClick", StartLine = 4028, EndLine = 4036, Guard = 0, TargetPath = "ClientBaseConfig.MagicAutoOpen", Control = "chkMagicAutoOpen", ControlKind = "check", Rhs = "chkMagicAutoOpen.Checked" },
        new CustomMagicHandlerRow { Method = "CbbMagicWarrNGOptionChange", DelphiName = "cbbMagicWarrNGOptionChange", StartLine = 4037, EndLine = 4045, Guard = 0, TargetPath = "ClientBaseConfig.MagicWarrNGOption", Control = "cbbMagicWarrNGOption", ControlKind = "combo", Rhs = "TMagicWarrNGOption(cbbMagicWarrNGOption.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "SeClientActionStartIndexChange", DelphiName = "seClientActionStartIndexChange", StartLine = 4057, EndLine = 4065, Guard = 0, TargetPath = "ClientBaseConfig.MagicActionStartIndex", Control = "seClientActionStartIndex", ControlKind = "spin", Rhs = "seClientActionStartIndex.Value" },
        new CustomMagicHandlerRow { Method = "SeClientActionPlayCountChange", DelphiName = "seClientActionPlayCountChange", StartLine = 4066, EndLine = 4074, Guard = 0, TargetPath = "ClientBaseConfig.MagicActionPlayCount", Control = "seClientActionPlayCount", ControlKind = "spin", Rhs = "seClientActionPlayCount.Value" },
        new CustomMagicHandlerRow { Method = "SeClientActionEmptyCountChange", DelphiName = "seClientActionEmptyCountChange", StartLine = 4075, EndLine = 4083, Guard = 0, TargetPath = "ClientBaseConfig.MagicActionEmptyCount", Control = "seClientActionEmptyCount", ControlKind = "spin", Rhs = "seClientActionEmptyCount.Value" },
        new CustomMagicHandlerRow { Method = "ChkClientActionContinueClick", DelphiName = "chkClientActionContinueClick", StartLine = 4084, EndLine = 4092, Guard = 0, TargetPath = "ClientBaseConfig.MagicActionContinue", Control = "chkClientActionContinue", ControlKind = "check", Rhs = "chkClientActionContinue.Checked" },
        new CustomMagicHandlerRow { Method = "ChkEnableAntiMagicClick", DelphiName = "chkEnableAntiMagicClick", StartLine = 4093, EndLine = 4101, Guard = 2, TargetPath = "EnableAntiMagic", Control = "chkEnableAntiMagic", ControlKind = "check", Rhs = "chkEnableAntiMagic.Checked" },
        new CustomMagicHandlerRow { Method = "ChkProtectAddHPSlowClick", DelphiName = "chkProtectAddHPSlowClick", StartLine = 4102, EndLine = 4110, Guard = 2, TargetPath = "ProtectAddHPSlow", Control = "chkProtectAddHPSlow", ControlKind = "check", Rhs = "chkProtectAddHPSlow.Checked" },
        new CustomMagicHandlerRow { Method = "SeProtectAddHPSlowCountChange", DelphiName = "seProtectAddHPSlowCountChange", StartLine = 4111, EndLine = 4119, Guard = 2, TargetPath = "ProtectAddHpSlowCount", Control = "seProtectAddHPSlowCount", ControlKind = "spin", Rhs = "seProtectAddHPSlowCount.Value" },
        new CustomMagicHandlerRow { Method = "SeAttackDelayTimeChange", DelphiName = "seAttackDelayTimeChange", StartLine = 4120, EndLine = 4128, Guard = 2, TargetPath = "AttackDelayTime", Control = "seAttackDelayTime", ControlKind = "spin", Rhs = "seAttackDelayTime.Value" },
        new CustomMagicHandlerRow { Method = "ChkEnableHitPointClick", DelphiName = "chkEnableHitPointClick", StartLine = 4129, EndLine = 4137, Guard = 2, TargetPath = "EnableHitPoint", Control = "chkEnableHitPoint", ControlKind = "check", Rhs = "chkEnableHitPoint.Checked" },
        new CustomMagicHandlerRow { Method = "ChkProtectTargetStatusClick", DelphiName = "chkProtectTargetStatusClick", StartLine = 4138, EndLine = 4146, Guard = 2, TargetPath = "ProtectTargetStatus", Control = "chkProtectTargetStatus", ControlKind = "check", Rhs = "chkProtectTargetStatus.Checked" },
        new CustomMagicHandlerRow { Method = "SeProtectTargetStatusTimeChange", DelphiName = "seProtectTargetStatusTimeChange", StartLine = 4147, EndLine = 4155, Guard = 2, TargetPath = "ProtectTargetStatusTime", Control = "seProtectTargetStatusTime", ControlKind = "spin", Rhs = "seProtectTargetStatusTime.Value" },
        new CustomMagicHandlerRow { Method = "CbbProtectTargetStatusTime_1Change", DelphiName = "cbbProtectTargetStatusTime_1Change", StartLine = 4156, EndLine = 4164, Guard = 2, TargetPath = "ProtectTargetStatusTimeUnit", Control = "cbbProtectTargetStatusTime_1", ControlKind = "combo", Rhs = "cbbProtectTargetStatusTime_1.ItemIndex" },
        new CustomMagicHandlerRow { Method = "SeProtectTargetStatusTime_2Change", DelphiName = "seProtectTargetStatusTime_2Change", StartLine = 4165, EndLine = 4173, Guard = 2, TargetPath = "ProtectTargetStatusTime2", Control = "seProtectTargetStatusTime_2", ControlKind = "spin", Rhs = "seProtectTargetStatusTime_2.Value" },
        new CustomMagicHandlerRow { Method = "SeProtectTargetStatusTimeDelayChange", DelphiName = "seProtectTargetStatusTimeDelayChange", StartLine = 4174, EndLine = 4182, Guard = 2, TargetPath = "ProtectTargetStatusDelay", Control = "seProtectTargetStatusTimeDelay", ControlKind = "spin", Rhs = "seProtectTargetStatusTimeDelay.Value" },
        new CustomMagicHandlerRow { Method = "EdtCheckVarNameChange", DelphiName = "edtCheckVarNameChange", StartLine = 4209, EndLine = 4217, Guard = 2, TargetPath = "CheckVarName", Control = "edtCheckVarName", ControlKind = "edit", Rhs = "edtCheckVarName.Text" },
        new CustomMagicHandlerRow { Method = "CbbCheckVarTypeChange", DelphiName = "cbbCheckVarTypeChange", StartLine = 4218, EndLine = 4226, Guard = 2, TargetPath = "CheckVarType", Control = "cbbCheckVarType", ControlKind = "combo", Rhs = "TCheckVarType(cbbCheckVarType.ItemIndex)" },
        new CustomMagicHandlerRow { Method = "SeCheckVarValueChange", DelphiName = "seCheckVarValueChange", StartLine = 4227, EndLine = 4235, Guard = 2, TargetPath = "CheckVarValue", Control = "seCheckVarValue", ControlKind = "spin", Rhs = "seCheckVarValue.Value" },
        new CustomMagicHandlerRow { Method = "SeCheckVarAddChange", DelphiName = "seCheckVarAddChange", StartLine = 4236, EndLine = 4244, Guard = 2, TargetPath = "CheckVarAdd", Control = "seCheckVarAdd", ControlKind = "spin", Rhs = "seCheckVarAdd.Value" },
        new CustomMagicHandlerRow { Method = "ChkNoTeleportNoAttackClick", DelphiName = "chkNoTeleportNoAttackClick", StartLine = 4245, EndLine = 4253, Guard = 2, TargetPath = "IsNoTeleportNoAttack", Control = "chkNoTeleportNoAttack", ControlKind = "check", Rhs = "chkNoTeleportNoAttack.Checked" },
        new CustomMagicHandlerRow { Method = "ChkSelf_SyncHumActionClick", DelphiName = "chkSelf_SyncHumActionClick", StartLine = 4254, EndLine = 4262, Guard = 1, TargetPath = "Self_SyncHumAction", Control = "chkSelf_SyncHumAction", ControlKind = "check", Rhs = "chkSelf_SyncHumAction.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackUseNGClick", DelphiName = "chkAttackUseNGClick", StartLine = 4263, EndLine = 4271, Guard = 2, TargetPath = "IsAttackUseNG", Control = "chkAttackUseNG", ControlKind = "check", Rhs = "chkAttackUseNG.Checked" },
        new CustomMagicHandlerRow { Method = "ChkAttackNoChangeDirClick", DelphiName = "chkAttackNoChangeDirClick", StartLine = 4272, EndLine = 4280, Guard = 2, TargetPath = "NoChangeDir", Control = "chkAttackNoChangeDir", ControlKind = "check", Rhs = "chkAttackNoChangeDir.Checked" },
        new CustomMagicHandlerRow { Method = "ChkDisableInSafeZoneClick", DelphiName = "chkDisableInSafeZoneClick", StartLine = 4281, EndLine = 4289, Guard = 2, TargetPath = "DisableInSafeZone", Control = "chkDisableInSafeZone", ControlKind = "check", Rhs = "chkDisableInSafeZone.Checked" },
    };

    /// <summary>行数（=151，测试锁定）。</summary>
    public static int Count => Rows.Count;
}
