// ============================================================================
// uFrmCustomMagic.pas **全部方法名逐条来源表**（脚本从 Delphi 原文抽取）
//
// 抽取规则：把 Source\M2Engine\Forms\uFrmCustomMagic.pas 里所有
//   procedure|function|destructor|constructor <Owner>.<Name>...  
// 声明逐条登记（Owner ∈ {TFrmCustomMagic, TDecAttribPropertyEditLink,
// TElementPropertyEditLink}，外加单元级 SetControlEnabled / ShowCustomMagic /
// RebuildCustomMagicListText）。行号为原文物理行号（4800 行、全 CRLF）。
// 接口段重复的那条 ShowCustomMagic（:849）已排除，真正的实现是 :1625。
//
// 用途：CustomMagicMethodParityTests 逐条断言托管侧存在同名公开成员 ⇒ 方法名 1:1 覆盖率门禁。
// ============================================================================

using System.Collections.Generic;

namespace GXX.M2Server.Tests;

/// <summary>一个原文方法声明。</summary>
public sealed class CustomMagicMethodRow
{
    /// <summary>原文所属类型（Delphi 名）。</summary>
    public string Owner = "";
    /// <summary>原文方法名。</summary>
    public string DelphiName = "";
    /// <summary>托管侧应有的方法名（首字母大写）。</summary>
    public string Method = "";
    /// <summary>原文行号区间起。</summary>
    public int StartLine;
    /// <summary>原文行号区间止。</summary>
    public int EndLine;
}

/// <summary>全部方法声明（
public static class CustomMagicMethodTable
{
    /// <summary>逐条方法声明。</summary>
    public static readonly IReadOnlyList<CustomMagicMethodRow> Rows = new CustomMagicMethodRow[]
    {
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "Destroy", Method = "Destroy", StartLine = 932, EndLine = 941 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "EditKeyDown", Method = "EditKeyDown", StartLine = 942, EndLine = 976 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "EditKeyUp", Method = "EditKeyUp", StartLine = 977, EndLine = 989 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "BeginEdit", Method = "BeginEdit", StartLine = 990, EndLine = 998 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "CancelEdit", Method = "CancelEdit", StartLine = 999, EndLine = 1006 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "EndEdit", Method = "EndEdit", StartLine = 1007, EndLine = 1148 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "GetBounds", Method = "GetBounds", StartLine = 1149, EndLine = 1155 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "PrepareEdit", Method = "PrepareEdit", StartLine = 1156, EndLine = 1266 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "ProcessMessage", Method = "ProcessMessage", StartLine = 1267, EndLine = 1273 },
        new CustomMagicMethodRow { Owner = "TDecAttribPropertyEditLink", DelphiName = "SetBounds", Method = "SetBounds", StartLine = 1274, EndLine = 1285 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "Destroy", Method = "Destroy", StartLine = 1286, EndLine = 1295 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "EditKeyDown", Method = "EditKeyDown", StartLine = 1296, EndLine = 1330 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "EditKeyUp", Method = "EditKeyUp", StartLine = 1331, EndLine = 1343 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "BeginEdit", Method = "BeginEdit", StartLine = 1344, EndLine = 1352 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "CancelEdit", Method = "CancelEdit", StartLine = 1353, EndLine = 1360 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "EndEdit", Method = "EndEdit", StartLine = 1361, EndLine = 1478 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "GetBounds", Method = "GetBounds", StartLine = 1479, EndLine = 1485 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "PrepareEdit", Method = "PrepareEdit", StartLine = 1486, EndLine = 1587 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "ProcessMessage", Method = "ProcessMessage", StartLine = 1588, EndLine = 1594 },
        new CustomMagicMethodRow { Owner = "TElementPropertyEditLink", DelphiName = "SetBounds", Method = "SetBounds", StartLine = 1595, EndLine = 1604 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "SetControlEnabled", Method = "SetControlEnabled", StartLine = 1605, EndLine = 1624 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "ShowCustomMagic", Method = "ShowCustomMagic", StartLine = 1625, EndLine = 1637 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "DoOpen", Method = "DoOpen", StartLine = 1638, EndLine = 1667 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "FormCreate", Method = "FormCreate", StartLine = 1668, EndLine = 1862 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "SetConfigChanged", Method = "SetConfigChanged", StartLine = 1863, EndLine = 1876 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstCustomMagicDrawText", Method = "VstCustomMagicDrawText", StartLine = 1877, EndLine = 1894 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstCustomMagicGetNodeDataSize", Method = "VstCustomMagicGetNodeDataSize", StartLine = 1895, EndLine = 1899 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstCustomMagicGetText", Method = "VstCustomMagicGetText", StartLine = 1900, EndLine = 1909 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstCustomMagicNodeClick", Method = "VstCustomMagicNodeClick", StartLine = 1910, EndLine = 2377 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientLevelChange", Method = "CbbClientLevelChange", StartLine = 2378, EndLine = 2509 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientLockClick", Method = "ChkClientLockClick", StartLine = 2510, EndLine = 2518 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientActionTypeChange", Method = "CbbClientActionTypeChange", StartLine = 2519, EndLine = 2532 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientLockSelfClick", Method = "ChkClientLockSelfClick", StartLine = 2533, EndLine = 2541 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientNotRaiseHandClick", Method = "ChkClientNotRaiseHandClick", StartLine = 2542, EndLine = 2550 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientIconFileChange", Method = "CbbClientIconFileChange", StartLine = 2551, EndLine = 2559 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientIconIndexChange", Method = "SeClientIconIndexChange", StartLine = 2560, EndLine = 2568 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFlyFileChange", Method = "CbbClientFlyFileChange", StartLine = 2569, EndLine = 2577 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyStartIndexChange", Method = "SeClientFlyStartIndexChange", StartLine = 2578, EndLine = 2586 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyPlayCountChange", Method = "SeClientFlyPlayCountChange", StartLine = 2587, EndLine = 2595 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyEmptyCountChange", Method = "SeClientFlyEmptyCountChange", StartLine = 2596, EndLine = 2604 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyPlayTimeChange", Method = "SeClientFlyPlayTimeChange", StartLine = 2605, EndLine = 2613 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFlyDrawModeChange", Method = "CbbClientFlyDrawModeChange", StartLine = 2614, EndLine = 2622 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFlyDirCountChange", Method = "CbbClientFlyDirCountChange", StartLine = 2623, EndLine = 2631 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientFlyCalcDirClick", Method = "ChkClientFlyCalcDirClick", StartLine = 2632, EndLine = 2640 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientFlyFireGunModeClick", Method = "ChkClientFlyFireGunModeClick", StartLine = 2641, EndLine = 2649 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyLightRangeChange", Method = "SeClientFlyLightRangeChange", StartLine = 2650, EndLine = 2658 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFlyEffFileChange", Method = "CbbClientFlyEffFileChange", StartLine = 2659, EndLine = 2667 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFlyEffStartIndexChange", Method = "SeClientFlyEffStartIndexChange", StartLine = 2668, EndLine = 2676 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFlyEffDrawModeChange", Method = "CbbClientFlyEffDrawModeChange", StartLine = 2677, EndLine = 2685 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfFileChange", Method = "CbbClientSelfFileChange", StartLine = 2686, EndLine = 2694 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfStartIndexChange", Method = "SeClientSelfStartIndexChange", StartLine = 2695, EndLine = 2703 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfPlayCountChange", Method = "SeClientSelfPlayCountChange", StartLine = 2704, EndLine = 2712 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfEmptyCountChange", Method = "SeClientSelfEmptyCountChange", StartLine = 2713, EndLine = 2721 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfPlayTimeChange", Method = "SeClientSelfPlayTimeChange", StartLine = 2722, EndLine = 2730 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfDrawOrderChange", Method = "CbbClientSelfDrawOrderChange", StartLine = 2731, EndLine = 2739 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfDrawModeChange", Method = "CbbClientSelfDrawModeChange", StartLine = 2740, EndLine = 2748 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfDirCountChange", Method = "CbbClientSelfDirCountChange", StartLine = 2749, EndLine = 2757 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfDirCalcTypeChange", Method = "CbbClientSelfDirCalcTypeChange", StartLine = 2758, EndLine = 2766 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientSelfPlayDelayActionClick", Method = "ChkClientSelfPlayDelayActionClick", StartLine = 2767, EndLine = 2775 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientSelfPlayFailNoDrawClick", Method = "ChkClientSelfPlayFailNoDrawClick", StartLine = 2776, EndLine = 2784 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfLightRangeChange", Method = "SeClientSelfLightRangeChange", StartLine = 2785, EndLine = 2793 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientPreTargetFileChange", Method = "CbbClientPreTargetFileChange", StartLine = 2794, EndLine = 2802 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetStartIndexChange", Method = "SeClientPreTargetStartIndexChange", StartLine = 2803, EndLine = 2811 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetStartIndex2Change", Method = "SeClientPreTargetStartIndex2Change", StartLine = 2812, EndLine = 2820 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetPlayCountChange", Method = "SeClientPreTargetPlayCountChange", StartLine = 2821, EndLine = 2829 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetEmptyCountChange", Method = "SeClientPreTargetEmptyCountChange", StartLine = 2830, EndLine = 2838 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientPreTargetCalcDirClick", Method = "ChkClientPreTargetCalcDirClick", StartLine = 2839, EndLine = 2847 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetPlayTimeChange", Method = "SeClientPreTargetPlayTimeChange", StartLine = 2848, EndLine = 2856 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientPreTargetDrawModeChange", Method = "CbbClientPreTargetDrawModeChange", StartLine = 2857, EndLine = 2865 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientPreTargetDrawMode2Change", Method = "CbbClientPreTargetDrawMode2Change", StartLine = 2866, EndLine = 2874 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientPreTargetLockDrawClick", Method = "ChkClientPreTargetLockDrawClick", StartLine = 2875, EndLine = 2883 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientPreTargetLightRangeChange", Method = "SeClientPreTargetLightRangeChange", StartLine = 2884, EndLine = 2892 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientTargetFileChange", Method = "CbbClientTargetFileChange", StartLine = 2893, EndLine = 2901 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetStartIndexChange", Method = "SeClientTargetStartIndexChange", StartLine = 2902, EndLine = 2910 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetStartIndex2Change", Method = "SeClientTargetStartIndex2Change", StartLine = 2911, EndLine = 2919 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetPlayCountChange", Method = "SeClientTargetPlayCountChange", StartLine = 2920, EndLine = 2928 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetPlayTimeChange", Method = "SeClientTargetPlayTimeChange", StartLine = 2929, EndLine = 2937 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientTargetDrawModeChange", Method = "CbbClientTargetDrawModeChange", StartLine = 2938, EndLine = 2946 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientTargetDrawMode2Change", Method = "CbbClientTargetDrawMode2Change", StartLine = 2947, EndLine = 2955 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientTargetMultiPlayClick", Method = "ChkClientTargetMultiPlayClick", StartLine = 2956, EndLine = 2964 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientTargetLockDrawClick", Method = "ChkClientTargetLockDrawClick", StartLine = 2965, EndLine = 2973 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetLightRangeChange", Method = "SeClientTargetLightRangeChange", StartLine = 2974, EndLine = 2982 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientTargetKeepPlayClick", Method = "ChkClientTargetKeepPlayClick", StartLine = 2983, EndLine = 2991 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetKeepTimeChange", Method = "SeClientTargetKeepTimeChange", StartLine = 2992, EndLine = 3000 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetKeepTime2Change", Method = "SeClientTargetKeepTime2Change", StartLine = 3001, EndLine = 3009 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetKeepAttackIntervalChange", Method = "SeClientTargetKeepAttackIntervalChange", StartLine = 3010, EndLine = 3018 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientTargetKeepAttackRangeChange", Method = "SeClientTargetKeepAttackRangeChange", StartLine = 3019, EndLine = 3027 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetKeepLightRangeChange", Method = "SeTargetKeepLightRangeChange", StartLine = 3028, EndLine = 3036 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientTargetKeepMultiPlayClick", Method = "ChkClientTargetKeepMultiPlayClick", StartLine = 3037, EndLine = 3045 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbTargetStatus1_FileChange", Method = "CbbTargetStatus1_FileChange", StartLine = 3046, EndLine = 3054 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus1_StartIndexChange", Method = "SeTargetStatus1_StartIndexChange", StartLine = 3055, EndLine = 3063 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus1_PlayCountChange", Method = "SeTargetStatus1_PlayCountChange", StartLine = 3064, EndLine = 3072 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus1_EmptyCountChange", Method = "SeTargetStatus1_EmptyCountChange", StartLine = 3073, EndLine = 3081 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus1_PlayTimeChange", Method = "SeTargetStatus1_PlayTimeChange", StartLine = 3082, EndLine = 3090 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbTargetStatus1_DrawModeChange", Method = "CbbTargetStatus1_DrawModeChange", StartLine = 3091, EndLine = 3099 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkTargetStatus1_CalcDirClick", Method = "ChkTargetStatus1_CalcDirClick", StartLine = 3100, EndLine = 3108 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbTargetStatus2_FileChange", Method = "CbbTargetStatus2_FileChange", StartLine = 3109, EndLine = 3117 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus2_StartIndexChange", Method = "SeTargetStatus2_StartIndexChange", StartLine = 3118, EndLine = 3126 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus2_PlayCountChange", Method = "SeTargetStatus2_PlayCountChange", StartLine = 3127, EndLine = 3135 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus2_EmptyCountChange", Method = "SeTargetStatus2_EmptyCountChange", StartLine = 3136, EndLine = 3144 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seTargetStatus2_PlayTimeChange", Method = "SeTargetStatus2_PlayTimeChange", StartLine = 3145, EndLine = 3153 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbTargetStatus2_DrawModeChange", Method = "CbbTargetStatus2_DrawModeChange", StartLine = 3154, EndLine = 3162 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkTargetStatus2_CalcDirClick", Method = "ChkTargetStatus2_CalcDirClick", StartLine = 3163, EndLine = 3171 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbOperateModeChange", Method = "CbbOperateModeChange", StartLine = 3172, EndLine = 3195 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seUseIntervalChange", Method = "SeUseIntervalChange", StartLine = 3196, EndLine = 3204 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkFailNoShowEffClick", Method = "ChkFailNoShowEffClick", StartLine = 3205, EndLine = 3215 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtFailMsgChange", Method = "EdtFailMsgChange", StartLine = 3216, EndLine = 3224 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtSucceedMsgChange", Method = "EdtSucceedMsgChange", StartLine = 3225, EndLine = 3233 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtCloseMsgChange", Method = "EdtCloseMsgChange", StartLine = 3234, EndLine = 3242 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbAttackTargetChange", Method = "CbbAttackTargetChange", StartLine = 3243, EndLine = 3259 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackNearRangeChange", Method = "SeAttackNearRangeChange", StartLine = 3260, EndLine = 3268 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackGroupRangeChange", Method = "SeAttackGroupRangeChange", StartLine = 3269, EndLine = 3277 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackLineWidthChange", Method = "SeAttackLineWidthChange", StartLine = 3278, EndLine = 3286 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbAttackPowerCalcChange", Method = "CbbAttackPowerCalcChange", StartLine = 3287, EndLine = 3295 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbAttackPowerLevelChange", Method = "CbbAttackPowerLevelChange", StartLine = 3296, EndLine = 3303 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackPowerRateChange", Method = "SeAttackPowerRateChange", StartLine = 3304, EndLine = 3312 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seLineAttackAddPowerChange", Method = "SeLineAttackAddPowerChange", StartLine = 3313, EndLine = 3321 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackPowerUndeadAddChange", Method = "SeAttackPowerUndeadAddChange", StartLine = 3322, EndLine = 3330 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbNeedItemChange", Method = "CbbNeedItemChange", StartLine = 3331, EndLine = 3339 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seNeedItemCountChange", Method = "SeNeedItemCountChange", StartLine = 3340, EndLine = 3348 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtNeedItemCustomItemNameChange", Method = "EdtNeedItemCustomItemNameChange", StartLine = 3349, EndLine = 3357 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkNeedItemUseBagItemClick", Method = "ChkNeedItemUseBagItemClick", StartLine = 3358, EndLine = 3366 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seProtectTargetRangeChange", Method = "SeProtectTargetRangeChange", StartLine = 3367, EndLine = 3375 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAdditional0Click", Method = "ChkAdditional0Click", StartLine = 3376, EndLine = 3389 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAdditionalRate0Change", Method = "SeAdditionalRate0Change", StartLine = 3390, EndLine = 3403 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAdditionalRate0_2Change", Method = "SeAdditionalRate0_2Change", StartLine = 3404, EndLine = 3417 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAdditionalTime0Change", Method = "SeAdditionalTime0Change", StartLine = 3418, EndLine = 3431 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbAdditionalTime0_1Change", Method = "CbbAdditionalTime0_1Change", StartLine = 3432, EndLine = 3445 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAdditionalTime0_2Change", Method = "SeAdditionalTime0_2Change", StartLine = 3446, EndLine = 3459 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAdditionaHP0Change", Method = "SeAdditionaHP0Change", StartLine = 3460, EndLine = 3468 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkseAdditionaHighLevel4Click", Method = "ChkseAdditionaHighLevel4Click", StartLine = 3469, EndLine = 3477 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbPushedType4Change", Method = "CbbPushedType4Change", StartLine = 3478, EndLine = 3486 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTargetStatusClick", Method = "ChkAttackTargetStatusClick", StartLine = 3487, EndLine = 3495 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackTargetStatusTimeChange", Method = "SeAttackTargetStatusTimeChange", StartLine = 3496, EndLine = 3504 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbAttackTargetStatusTime_1Change", Method = "CbbAttackTargetStatusTime_1Change", StartLine = 3505, EndLine = 3513 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackTargetStatusTime_2Change", Method = "SeAttackTargetStatusTime_2Change", StartLine = 3514, EndLine = 3522 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackTargetStatusDelayChange", Method = "SeAttackTargetStatusDelayChange", StartLine = 3523, EndLine = 3531 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "RebuildCustomMagicListText", Method = "RebuildCustomMagicListText", StartLine = 3532, EndLine = 3600 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "btnSaveClick", Method = "BtnSaveClick", StartLine = 3601, EndLine = 3627 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "btnMakeConfigDataClick", Method = "BtnMakeConfigDataClick", StartLine = 3628, EndLine = 3665 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkSendCustomMagicConfigClick", Method = "ChkSendCustomMagicConfigClick", StartLine = 3666, EndLine = 3671 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtCallMonster1Change", Method = "EdtCallMonster1Change", StartLine = 3672, EndLine = 3685 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCallMonsterNum1Change", Method = "SeCallMonsterNum1Change", StartLine = 3686, EndLine = 3700 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCallMonstersRateChange", Method = "SeCallMonstersRateChange", StartLine = 3701, EndLine = 3709 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCallMonstersLevelChange", Method = "SeCallMonstersLevelChange", StartLine = 3710, EndLine = 3718 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportAfterDamageClick", Method = "ChkAttackTeleportAfterDamageClick", StartLine = 3719, EndLine = 3727 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportAttackClick", Method = "ChkAttackTeleportAttackClick", StartLine = 3728, EndLine = 3736 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackTeleportRateChange", Method = "SeAttackTeleportRateChange", StartLine = 3737, EndLine = 3745 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackTeleportRushCountChange", Method = "SeAttackTeleportRushCountChange", StartLine = 3746, EndLine = 3754 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRunHumClick", Method = "ChkAttackTeleportRunHumClick", StartLine = 3755, EndLine = 3763 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRunMonClick", Method = "ChkAttackTeleportRunMonClick", StartLine = 3764, EndLine = 3772 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRunNpcClick", Method = "ChkAttackTeleportRunNpcClick", StartLine = 3773, EndLine = 3781 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRunGuardClick", Method = "ChkAttackTeleportRunGuardClick", StartLine = 3782, EndLine = 3790 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRunObstacleClick", Method = "ChkAttackTeleportRunObstacleClick", StartLine = 3791, EndLine = 3799 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportRushClick", Method = "ChkAttackTeleportRushClick", StartLine = 3800, EndLine = 3808 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportWarDisHumRunClick", Method = "ChkAttackTeleportWarDisHumRunClick", StartLine = 3809, EndLine = 3817 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackTeleportCannotRunItemClick", Method = "ChkAttackTeleportCannotRunItemClick", StartLine = 3818, EndLine = 3826 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkEnabledCallMonsterClick", Method = "ChkEnabledCallMonsterClick", StartLine = 3827, EndLine = 3835 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFastMoveFileChange", Method = "CbbClientFastMoveFileChange", StartLine = 3836, EndLine = 3844 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFastMoveStartIndexChange", Method = "SeClientFastMoveStartIndexChange", StartLine = 3845, EndLine = 3853 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFastMovePlayCountChange", Method = "SeClientFastMovePlayCountChange", StartLine = 3854, EndLine = 3862 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFastMoveEmptyCountChange", Method = "SeClientFastMoveEmptyCountChange", StartLine = 3863, EndLine = 3871 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientFastMovePlayTimeChange", Method = "SeClientFastMovePlayTimeChange", StartLine = 3872, EndLine = 3880 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientFastMoveDrawModeChange", Method = "CbbClientFastMoveDrawModeChange", StartLine = 3881, EndLine = 3889 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientFastMoveCalcDirClick", Method = "ChkClientFastMoveCalcDirClick", StartLine = 3890, EndLine = 3898 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientFastMoveNoHitActionClick", Method = "ChkClientFastMoveNoHitActionClick", StartLine = 3899, EndLine = 3907 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seFastMoveLightRangeChange", Method = "SeFastMoveLightRangeChange", StartLine = 3908, EndLine = 3916 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtSound1Change", Method = "EdtSound1Change", StartLine = 3917, EndLine = 3934 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfKeepFileChange", Method = "CbbClientSelfKeepFileChange", StartLine = 3935, EndLine = 3943 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfKeepStartIndexChange", Method = "SeClientSelfKeepStartIndexChange", StartLine = 3944, EndLine = 3952 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfKeepPlayCountChange", Method = "SeClientSelfKeepPlayCountChange", StartLine = 3953, EndLine = 3961 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfKeepPlayTimeChange", Method = "SeClientSelfKeepPlayTimeChange", StartLine = 3962, EndLine = 3970 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbClientSelfKeepDrawModeChange", Method = "CbbClientSelfKeepDrawModeChange", StartLine = 3971, EndLine = 3979 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfKeepTimeChange", Method = "SeClientSelfKeepTimeChange", StartLine = 3980, EndLine = 3988 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientSelfKeepTime2Change", Method = "SeClientSelfKeepTime2Change", StartLine = 3989, EndLine = 3997 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCallMonstersRoyaltySecChange", Method = "SeCallMonstersRoyaltySecChange", StartLine = 3998, EndLine = 4006 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbMagicSwitchModeChange", Method = "CbbMagicSwitchModeChange", StartLine = 4007, EndLine = 4018 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkSwitchModeNoCloseClick", Method = "ChkSwitchModeNoCloseClick", StartLine = 4019, EndLine = 4027 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkMagicAutoOpenClick", Method = "ChkMagicAutoOpenClick", StartLine = 4028, EndLine = 4036 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbMagicWarrNGOptionChange", Method = "CbbMagicWarrNGOptionChange", StartLine = 4037, EndLine = 4045 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "btnCopyConfigClick", Method = "BtnCopyConfigClick", StartLine = 4046, EndLine = 4056 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientActionStartIndexChange", Method = "SeClientActionStartIndexChange", StartLine = 4057, EndLine = 4065 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientActionPlayCountChange", Method = "SeClientActionPlayCountChange", StartLine = 4066, EndLine = 4074 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seClientActionEmptyCountChange", Method = "SeClientActionEmptyCountChange", StartLine = 4075, EndLine = 4083 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkClientActionContinueClick", Method = "ChkClientActionContinueClick", StartLine = 4084, EndLine = 4092 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkEnableAntiMagicClick", Method = "ChkEnableAntiMagicClick", StartLine = 4093, EndLine = 4101 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkProtectAddHPSlowClick", Method = "ChkProtectAddHPSlowClick", StartLine = 4102, EndLine = 4110 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seProtectAddHPSlowCountChange", Method = "SeProtectAddHPSlowCountChange", StartLine = 4111, EndLine = 4119 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seAttackDelayTimeChange", Method = "SeAttackDelayTimeChange", StartLine = 4120, EndLine = 4128 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkEnableHitPointClick", Method = "ChkEnableHitPointClick", StartLine = 4129, EndLine = 4137 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkProtectTargetStatusClick", Method = "ChkProtectTargetStatusClick", StartLine = 4138, EndLine = 4146 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seProtectTargetStatusTimeChange", Method = "SeProtectTargetStatusTimeChange", StartLine = 4147, EndLine = 4155 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbProtectTargetStatusTime_1Change", Method = "CbbProtectTargetStatusTime_1Change", StartLine = 4156, EndLine = 4164 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seProtectTargetStatusTime_2Change", Method = "SeProtectTargetStatusTime_2Change", StartLine = 4165, EndLine = 4173 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seProtectTargetStatusTimeDelayChange", Method = "SeProtectTargetStatusTimeDelayChange", StartLine = 4174, EndLine = 4182 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkCheckVarValueClick", Method = "ChkCheckVarValueClick", StartLine = 4183, EndLine = 4208 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "edtCheckVarNameChange", Method = "EdtCheckVarNameChange", StartLine = 4209, EndLine = 4217 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "cbbCheckVarTypeChange", Method = "CbbCheckVarTypeChange", StartLine = 4218, EndLine = 4226 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCheckVarValueChange", Method = "SeCheckVarValueChange", StartLine = 4227, EndLine = 4235 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seCheckVarAddChange", Method = "SeCheckVarAddChange", StartLine = 4236, EndLine = 4244 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkNoTeleportNoAttackClick", Method = "ChkNoTeleportNoAttackClick", StartLine = 4245, EndLine = 4253 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkSelf_SyncHumActionClick", Method = "ChkSelf_SyncHumActionClick", StartLine = 4254, EndLine = 4262 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackUseNGClick", Method = "ChkAttackUseNGClick", StartLine = 4263, EndLine = 4271 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkAttackNoChangeDirClick", Method = "ChkAttackNoChangeDirClick", StartLine = 4272, EndLine = 4280 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkDisableInSafeZoneClick", Method = "ChkDisableInSafeZoneClick", StartLine = 4281, EndLine = 4289 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrChecked", Method = "VstAttackDecAttrChecked", StartLine = 4290, EndLine = 4305 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrNodeClick", Method = "VstAttackDecAttrNodeClick", StartLine = 4306, EndLine = 4325 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrAfterCellPaint", Method = "VstAttackDecAttrAfterCellPaint", StartLine = 4326, EndLine = 4346 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrGetText", Method = "VstAttackDecAttrGetText", StartLine = 4347, EndLine = 4399 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrEditing", Method = "VstAttackDecAttrEditing", StartLine = 4400, EndLine = 4413 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstAttackDecAttrCreateEditor", Method = "VstAttackDecAttrCreateEditor", StartLine = 4414, EndLine = 4419 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "WMStartEditingDecAttrib", Method = "WMStartEditingDecAttrib", StartLine = 4420, EndLine = 4428 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementChecked", Method = "VstDecElementChecked", StartLine = 4429, EndLine = 4444 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementNodeClick", Method = "VstDecElementNodeClick", StartLine = 4445, EndLine = 4467 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementAfterCellPaint", Method = "VstDecElementAfterCellPaint", StartLine = 4468, EndLine = 4488 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementGetText", Method = "VstDecElementGetText", StartLine = 4489, EndLine = 4520 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementEditing", Method = "VstDecElementEditing", StartLine = 4521, EndLine = 4526 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstDecElementCreateEditor", Method = "VstDecElementCreateEditor", StartLine = 4527, EndLine = 4532 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "WMStartEditingDecElement", Method = "WMStartEditingDecElement", StartLine = 4533, EndLine = 4541 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "WMStartEditingIncElement", Method = "WMStartEditingIncElement", StartLine = 4542, EndLine = 4550 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrChecked", Method = "VstProtectedAddAttrChecked", StartLine = 4551, EndLine = 4566 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrNodeClick", Method = "VstProtectedAddAttrNodeClick", StartLine = 4567, EndLine = 4586 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrAfterCellPaint", Method = "VstProtectedAddAttrAfterCellPaint", StartLine = 4587, EndLine = 4607 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrGetText", Method = "VstProtectedAddAttrGetText", StartLine = 4608, EndLine = 4690 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrEditing", Method = "VstProtectedAddAttrEditing", StartLine = 4691, EndLine = 4708 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "vstProtectedAddAttrCreateEditor", Method = "VstProtectedAddAttrCreateEditor", StartLine = 4709, EndLine = 4714 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "WMStartEditingIncAttrib", Method = "WMStartEditingIncAttrib", StartLine = 4715, EndLine = 4723 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "chkMagicACHumClick", Method = "ChkMagicACHumClick", StartLine = 4724, EndLine = 4738 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seMagicACHumRateChange", Method = "SeMagicACHumRateChange", StartLine = 4739, EndLine = 4753 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seMagicACHumRateAddChange", Method = "SeMagicACHumRateAddChange", StartLine = 4754, EndLine = 4768 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seMagicACHumValueChange", Method = "SeMagicACHumValueChange", StartLine = 4769, EndLine = 4783 },
        new CustomMagicMethodRow { Owner = "TFrmCustomMagic", DelphiName = "seMagicACHumValueAddChange", Method = "SeMagicACHumValueAddChange", StartLine = 4784, EndLine = 4799 },
    };

    /// <summary>条数（测试锁定）。</summary>
    public static int Count => Rows.Count;
}
