// Source unit: Source/M2Engine/SqliteAuctionDB.pas
// Generated by _recon/p3-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from the
// GBK source (independent of the C# constant-generation step).
// DbLayerM2DataSqlFidelityTests / DbLayerAuctionSqlFidelityTests assert that the SQL this
// port actually binds hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>SqliteAuctionDB.pas fixed-statement SQL fingerprints.</summary>
public static class SqliteAuctionDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("Auction_UpdateAuctionItemFail", "7ad4fd90557844bf2662a763b79b1171cbd4b3e39effb0ba1a7e1cce0123467c"),   // SqliteAuctionDB.pas:206-207 (FStatementUpdateAuctionItemFail), len=191
        ("Auction_UpdateAuctionItemSuccess", "a45fa030b3e622a84decc6140348b0f4bf26db6c98c7e31991f67fb2073388c4"),   // SqliteAuctionDB.pas:210-210 (FStatementUpdateAuctionItemSuccess), len=61
        ("Auction_QueryAuctionItemSuccess", "97c2467b2d1713598d296259c79974fc02725d46b128e5596afcb1a30027acac"),   // SqliteAuctionDB.pas:213-216 (FStatementQueryAuctionItemSuccess), len=375
        ("Auction_QueryAuctionItems", "d6e2bda1d85ef5abf34456381a7a7c079931feb29ecd397187e02131312c1fdf"),   // SqliteAuctionDB.pas:221-224 (FStatementQueryMyItems), len=302
        ("Auction_GetMyItemsCount", "11f537eda51aa40b67cb507fb489d8e34fba41b37fa012b1d1294d5a331eb2a8"),   // SqliteAuctionDB.pas:228-228 (FStatementGetMyItemsCount), len=53
        ("Auction_QueryAttentionItems", "2ce300e73fc63ca8d20ae1676f5ce4fb1fbac4c410064324d132eea322455b55"),   // SqliteAuctionDB.pas:232-233 (FStatementQueryMyAttentionItems), len=95
        ("Auction_GetMyAttentionItemsCount", "31fbb2afde40082974e2acbbf54e6e46b08f6aebe8166cd99fc1a23c359fb674"),   // SqliteAuctionDB.pas:237-237 (FStatementQueryMyAttentionItemsCount), len=58
        ("Auction_QueryOneItem", "454f4cbd2f65d60f484a7c51e3d28e76d1cdda64128342106230c906ed36dcfa"),   // SqliteAuctionDB.pas:242-245 (FStatementQueryOneItem), len=250
        ("Auction_GetMyAuctioningItemsCount", "2cca06a806cb5d35bfbd131e3493f52bf63bbf3ba20bb7e4c3532c1f51f49803"),   // SqliteAuctionDB.pas:249-250 (FStatementGetMyAuctioningItemsCount), len=159
        ("Auction_GetMySellFailItemsCount", "f31a0841d43817f2c59017e1aa12a8b9f29940a3c369502efdc14831353a4fbc"),   // SqliteAuctionDB.pas:254-255 (FStatementGetMySellFailItemsCount), len=257
        ("Auction_GetMyBuyOKItemsCount", "addea4844c44d267abe1d0c7a3b27867ac7ece80560cba6f962e8b02fb6c516d"),   // SqliteAuctionDB.pas:259-260 (FStatementGetMyBuyOKItemsCount), len=107
        ("Auction_GetMaxAuctionID", "ccf5c16824a541ceeb1e07702198bae18a97090f923a7c447493d487868c6765"),   // SqliteAuctionDB.pas:263-263 (FStatementGetMaxAuctionID), len=53
        ("Auction_InsertAuctionItem", "192bfaed01a3883f96eb928ed177dea6576fecb270724f63d101a5da6dd07e47"),   // SqliteAuctionDB.pas:267-269 (FStatementInsertAuctionItem), len=182
        ("Auction_JoinItemBid", "f6de45543a41316320bb70139707bd49cfce3f6203da69dfbd7c9fb8b87fd361"),   // SqliteAuctionDB.pas:273-274 (FStatementJoinItemBid), len=112
        ("Auction_BuyItem", "7fe22a9fbccecb0057e329a2cda78a5e00c8ea26e59a66cc5205de8f331dd353"),   // SqliteAuctionDB.pas:278-279 (FStatementBuyItem), len=131
        ("Auction_AddAttentionItem", "3ed835a50f3a130814f07739032daa13fbab5d8940ae8d564c12890d234356d4"),   // SqliteAuctionDB.pas:283-284 (FStatementInsertAttentionItem), len=64
        ("Auction_CheckInAttentionItem", "7be3ec69f52ca4fe50bd7e1c3753e36c64228943568a660f46557079e67b4905"),   // SqliteAuctionDB.pas:286-286 (FStatementCheckInAttentionItem), len=69
        ("Auction_DeleteAuctionItem", "d477e7889479f65c6e24732b43fb4d6ed6763c70df509e386fe7285dc825fd09"),   // SqliteAuctionDB.pas:290-290 (FStatementDeleteAttentionItem), len=66
        ("Auction_HumanRename", "7436f0cd654c616d1365cae1acf6608a23bdc786760f7add33cc02b30e4e76e1"),   // SqliteAuctionDB.pas:293-293 (FStatementAuctionDataHumanRename), len=56
        ("Auction_LastBidderRename", "7cba3758561b073bb4f338ac4395c68907a0281a1bd58ad8140f65fbd8a8c2c4"),   // SqliteAuctionDB.pas:296-296 (FStatementAuctionDataLastBidderRename), len=58
        ("Auction_AttentionRename", "719b7d1fc7adf3bf3bf0393d32b64b19a59a4dd82c5bf06bde6f923f5862ba18"),   // SqliteAuctionDB.pas:299-299 (FStatementAuctionAttentionRename), len=61
    };
}