// Source unit: Source/M2Engine/SqliteM2DataDB.pas
// Generated by _recon/p3-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from the
// GBK source (independent of the C# constant-generation step).
// DbLayerM2DataSqlFidelityTests / DbLayerAuctionSqlFidelityTests assert that the SQL this
// port actually binds hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>SqliteM2DataDB.pas fixed-statement SQL fingerprints.</summary>
public static class SqliteM2DataDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("InsertItems", "b3f223cbbd7eaabdcfe209f05e561cc42ec84afac8182cc6a8fd426c9961c736"),   // SqliteM2DataDB.pas:223-228 (FStatementInsertItems), len=463
        ("InsertItemValueAdd", "d9441dce2f1bf911acb9f0856a9618b0e0906c8dad679553ff8e25f44ba3f1a9"),   // SqliteM2DataDB.pas:232-233 (FStatementInsertItemValueAdd), len=97
        ("InsertItemElementAdd", "5fb0c0749f11106667c149c5be34570402f7d44794cf0236a97e5916a5d533dd"),   // SqliteM2DataDB.pas:237-238 (FStatementInsertItemElementAdd), len=99
        ("InsertItemAddDataByte", "f1f235af0aadaad1fee63ad2ea82b66c13fe494e4bf9b497512740c90f946c59"),   // SqliteM2DataDB.pas:242-243 (FStatementInsertItemAddDataByte), len=100
        ("InsertItemAddDataInt", "9b67e1ff8a2bdd36b494c468e3f5fe23d31ac7b8e533cae0f0dfe38159fd9166"),   // SqliteM2DataDB.pas:247-248 (FStatementInsertItemAddDataInt), len=99
        ("InsertItemAddDataText", "9d0be6021627b5b35d6710f5cd0155cea005c892b0355efb3f2bda2433052328"),   // SqliteM2DataDB.pas:252-253 (FStatementInsertItemAddDataText), len=100
        ("InsertItemFlute", "ed8554330e2126e989dc983bce06615a02764cc1476ee1757a223f722cce1868"),   // SqliteM2DataDB.pas:257-258 (FStatementInsertItemFlute), len=111
        ("InsertItemProgress", "7ab4a525f77b3193346c312422e868a139b8a8d2246fcd7f6c1dfa608032987e"),   // SqliteM2DataDB.pas:262-264 (FStatementInsertItemProgress), len=172
        ("InsertItemProperty", "73844068d1580d594c79014ef02eafccfb7fd3dc27735aadb2861cfc80bcdad8"),   // SqliteM2DataDB.pas:268-270 (FStatementInsertItemProperty), len=184
        ("SelectItems", "6d4ff429b2bbac8e3538c920f10147201ec28cfef15503866baa03e87de1d775"),   // SqliteM2DataDB.pas:274-278 (FStatementGetItems), len=355
        ("SelectItems_Sort", "5c18a66f8b22d33870d68eaaaf3ad341ba779de3c9078212397e099210146efe"),   // SqliteM2DataDB.pas:282-286 (FStatementGetItems_Sort), len=372
        ("SelectItem", "e6ff2a886f241809b08666a0b9f0533787f884a073ca6c64e5f69ffd814f2def"),   // SqliteM2DataDB.pas:290-294 (FStatementGetItem), len=363
        ("SelectitemValueAdd", "0b4e7643ee22fe80d2d813d5974ea060e6453b9e1636075c3407025c16dc75ba"),   // SqliteM2DataDB.pas:298-299 (FStatementGetItemValueAdd), len=96
        ("SelectitemElementAdd", "7e970cbad5d33a71a9237784126c58dc660fd9a51f769467a2ea4cb26488abd6"),   // SqliteM2DataDB.pas:303-304 (FStatementGetItemElementAdd), len=98
        ("SelectitemAddDataByte", "e505fa4cc5b37428fcdf892d8058962c1729de23da85395c7e1ee74e61381502"),   // SqliteM2DataDB.pas:308-309 (FStatementGetItemAddDataByte), len=99
        ("SelectitemAddDataInt", "9936b67d0d6133aa2633566102fcb0e2e8849f879e75f9a491854e8b6c34217a"),   // SqliteM2DataDB.pas:313-314 (FStatementGetItemAddDataInt), len=98
        ("SelectitemAddDataText", "5bd84b54e681fb64c448fcaeb18c2dad772261d06fe62d4f7d7701e6ddddc48f"),   // SqliteM2DataDB.pas:318-319 (FStatementGetItemAddDataText), len=99
        ("SelectitemFlute", "eb3a391f1fbae7cc6ed9e0a03628c05e9f828c37effb6478231bfde73c1f6809"),   // SqliteM2DataDB.pas:323-324 (FStatementGetItemFlute), len=107
        ("SelectItemProgress", "2fb7df97401dbd53c045e34af4cffb0d1447944be7f761ec67aefefd963cac18"),   // SqliteM2DataDB.pas:328-329 (FStatementGetItemProgress), len=143
        ("SelectItemProperty", "1ff5113aa2ad29f69e6c7c37e3f68d488891a25d799f94ebc03ec09252910fd2"),   // SqliteM2DataDB.pas:333-334 (FStatementGetItemProperty), len=155
    };
}