// Source unit: Source/M2Engine/MySqlM2DataDB.pas
// Generated by _recon/p3-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from the
// GBK source (independent of the C# constant-generation step).
// DbLayerM2DataSqlFidelityTests / DbLayerAuctionSqlFidelityTests assert that the SQL this
// port actually binds hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>MySqlM2DataDB.pas fixed-statement SQL fingerprints.</summary>
public static class MySqlM2DataDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("InsertItems", "b3f223cbbd7eaabdcfe209f05e561cc42ec84afac8182cc6a8fd426c9961c736"),   // MySqlM2DataDB.pas:294-328 (FStatementInsertItems), len=463
        ("InsertItemValueAdd", "d9441dce2f1bf911acb9f0856a9618b0e0906c8dad679553ff8e25f44ba3f1a9"),   // MySqlM2DataDB.pas:333-340 (FStatementInsertItemValueAdd), len=97
        ("InsertItemElementAdd", "5fb0c0749f11106667c149c5be34570402f7d44794cf0236a97e5916a5d533dd"),   // MySqlM2DataDB.pas:344-351 (FStatementInsertItemElementAdd), len=99
        ("InsertItemAddDataByte", "f1f235af0aadaad1fee63ad2ea82b66c13fe494e4bf9b497512740c90f946c59"),   // MySqlM2DataDB.pas:355-362 (FStatementInsertItemAddDataByte), len=100
        ("InsertItemAddDataInt", "9b67e1ff8a2bdd36b494c468e3f5fe23d31ac7b8e533cae0f0dfe38159fd9166"),   // MySqlM2DataDB.pas:366-373 (FStatementInsertItemAddDataInt), len=99
        ("InsertItemAddDataText", "9d0be6021627b5b35d6710f5cd0155cea005c892b0355efb3f2bda2433052328"),   // MySqlM2DataDB.pas:377-384 (FStatementInsertItemAddDataText), len=100
        ("InsertItemFlute", "ed8554330e2126e989dc983bce06615a02764cc1476ee1757a223f722cce1868"),   // MySqlM2DataDB.pas:388-396 (FStatementInsertItemFlute), len=111
        ("InsertItemProgress", "7ab4a525f77b3193346c312422e868a139b8a8d2246fcd7f6c1dfa608032987e"),   // MySqlM2DataDB.pas:400-414 (FStatementInsertItemProgress), len=172
        ("InsertItemProperty", "491fdedec3e12d9a75b1ea9615f61d477259c9878e49f3a2dc456f4f1c2f0b30"),   // MySqlM2DataDB.pas:418-432 (FStatementInsertItemProperty), len=184
        ("SelectItems", "6d4ff429b2bbac8e3538c920f10147201ec28cfef15503866baa03e87de1d775"),   // MySqlM2DataDB.pas:436-467 (FStatementGetItems), len=355
        ("SelectItems_Sort", "5c18a66f8b22d33870d68eaaaf3ad341ba779de3c9078212397e099210146efe"),   // MySqlM2DataDB.pas:471-502 (FStatementGetItems_Sort), len=372
        ("SelectItem", "e6ff2a886f241809b08666a0b9f0533787f884a073ca6c64e5f69ffd814f2def"),   // MySqlM2DataDB.pas:507-537 (FStatementGetItem), len=363
        ("SelectitemValueAdd", "0b4e7643ee22fe80d2d813d5974ea060e6453b9e1636075c3407025c16dc75ba"),   // MySqlM2DataDB.pas:541-546 (FStatementGetItemValueAdd), len=96
        ("SelectitemElementAdd", "7e970cbad5d33a71a9237784126c58dc660fd9a51f769467a2ea4cb26488abd6"),   // MySqlM2DataDB.pas:550-555 (FStatementGetItemElementAdd), len=98
        ("SelectitemAddDataByte", "e505fa4cc5b37428fcdf892d8058962c1729de23da85395c7e1ee74e61381502"),   // MySqlM2DataDB.pas:559-564 (FStatementGetItemAddDataByte), len=99
        ("SelectitemAddDataInt", "9936b67d0d6133aa2633566102fcb0e2e8849f879e75f9a491854e8b6c34217a"),   // MySqlM2DataDB.pas:568-573 (FStatementGetItemAddDataInt), len=98
        ("SelectitemAddDataText", "5bd84b54e681fb64c448fcaeb18c2dad772261d06fe62d4f7d7701e6ddddc48f"),   // MySqlM2DataDB.pas:577-582 (FStatementGetItemAddDataText), len=99
        ("SelectitemFlute", "eb3a391f1fbae7cc6ed9e0a03628c05e9f828c37effb6478231bfde73c1f6809"),   // MySqlM2DataDB.pas:586-592 (FStatementGetItemFlute), len=107
        ("SelectItemProgress", "2fb7df97401dbd53c045e34af4cffb0d1447944be7f761ec67aefefd963cac18"),   // MySqlM2DataDB.pas:596-608 (FStatementGetItemProgress), len=143
        ("SelectItemProperty", "40c3a84478dd201d9cc163a849321e61829f68ecbbe95a9e27fb5c91e58ab179"),   // MySqlM2DataDB.pas:612-624 (FStatementGetItemProperty), len=155
    };
}