// Source unit: Source/M2Engine/MySqlUserShopDB.pas
// Generated by _recon/gen-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from
// the GBK source. DbLayerSqlFidelityTests asserts that the SQL this port actually binds
// hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>MySqlUserShopDB.pas fixed-statement SQL fingerprints.</summary>
public static class MySqlUserShopDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("UserShop_UpdateAllBusiness", "194c6986dc950e300937fc482ff3a2124accc93e3b1d58e07ab31f0fe2891b3e"),   // MySqlUserShopDB.pas:238 (FStatementUpdateAllBusiness), len=35
        ("UserShop_UpdateHumanBusiness", "96f6268d7e32667b23aaf9fb63f49efb15debc111b403398bf8481f0721b7671"),   // MySqlUserShopDB.pas:243 (FStatementUpdateHumanBusiness), len=55
        ("UserShop_CheckHumanNameExists", "ceaf8d8ede513092691e8ab2fa8eee28824152cc0d2d96606cc57133056588c8"),   // MySqlUserShopDB.pas:247 (FStatementHumanNameExists), len=43
        ("UserShop_CheckShopNameExists", "b8beb3c98c8fe6c7df0577c58fce199960e2079146b3fbff1f8b6beae2cf73e4"),   // MySqlUserShopDB.pas:251 (FStatementShopNameExists), len=42
        ("UserShop_InsertUserShop", "75a8cd5f705903aa47a12b7ac15d57ff1ebaec9f0ea63e708a53434cd213f2d8"),   // MySqlUserShopDB.pas:255 (FStatementInsertUserShop), len=70
        ("UserShop_UpdateShopName", "74c627c55f10393e9b80c5e4572408f8f9fac8a200bd3e0da21aebe087932fed"),   // MySqlUserShopDB.pas:259 (FStatementUserShopRename), len=50
        ("UserShop_UpdateShopName2", "e9c6b34f5978a567e02cb4a2aa8b15cbb2fb55d73605e3add4c24e8fb55b6ddd"),   // MySqlUserShopDB.pas:263 (FStatementUserShopRename2), len=53
        ("UserShop_ShopItemBuyerRenameName", "2755f89873f1ae2a03f216b542d280267975c71eea046bffbfff67fdd70a86ae"),   // MySqlUserShopDB.pas:267 (FStatementShopItemBuyerRenameName), len=57
        ("UserShop_GetUserShopInfo", "babbedd6e7c659e32e0665094a17c820cc4d5370881c473bb268a66bbced4c22"),   // MySqlUserShopDB.pas:271 (FStatementGetUserShopInfo), len=511
        ("UserShop_IncUserShopCareValue", "29568fcf4972851fbe3e3a64836cb992a37ad4fb408f6c445fad39dbbb94263a"),   // MySqlUserShopDB.pas:280 (FStatementIncUserShopCareValue), len=65
        ("UserShop_GetMaxShopItemID", "e5d854bfbe586199b17d0d884ff0e8dfbb93f78bcfb1c8c36772ce42d11f147c"),   // MySqlUserShopDB.pas:284 (FStatementGetMaxShopItemID), len=69
        ("UserShop_InsertShopItem", "dc753beca55a073eaad5fd30e8703e44c8d550b9a60b89f5611950b448fe6266"),   // MySqlUserShopDB.pas:288 (FStatementInsertUserShopItem), len=173
        ("UserShop_UpdateShopItem", "991b56b81a6e007fecb9e33f0b5acf53b08a121cacd41a8ab19e5f2079b423d5"),   // MySqlUserShopDB.pas:294 (FStatementUpdateUserShopItem), len=187
        ("UserShop_BuyShopItem", "ace43463f8827a78b9ad0439da02ab5a8254d422f4de20d125b67e29bb4cc69a"),   // MySqlUserShopDB.pas:299 (FStatementBuyUserShopItem), len=141
        ("UserShop_GetMoneyShopItem", "93ab6847fe55502e4f20a57f67e68f1ef803c5aa3f56f21d937ff9e7e12eb057"),   // MySqlUserShopDB.pas:304 (FStatementGetMoneyShopItem), len=110
        ("UserShop_GetSelledAndNoGetMoneyTotal", "47fcbfc6cfcb07a0347f1bf32fdd2b1e64975744122edaee8b1a19430b394933"),   // MySqlUserShopDB.pas:309 (FStatementGetSelledAndNoGetMoneyTotal), len=232
        ("UserShop_GetTimeHasArrivedSellItems", "8e08ed0fd0af83e2f584789788a30d90ab74ba15394aa1b9a9ba3647eaf01386"),   // MySqlUserShopDB.pas:316 (FStatementGetTimeHasArrivedSellItems), len=464
        ("UserShop_SetTimeHasArrivedSellItems", "7e0cd9a49195e397a3a80c11e2865e83b5eb9748ecf2c54f4ab442eb115b98d9"),   // MySqlUserShopDB.pas:325 (FStatementSetTimeHasArrivedSellItems), len=164
        ("UserShop_GetSellingItem_ASC", "139afb6c361362dea8519bd3a2364ed8b5a3759104082eeac0cfb08f2d663a4a"),   // MySqlUserShopDB.pas:330 (FStatementGetShopSellingItem_ASC), len=558
        ("UserShop_GetSellingItem_DESC", "15e36f7d3ea006ead883ef21b98bea21c85c3bb0d740b03171352532a2362968"),   // MySqlUserShopDB.pas:336 (FStatementGetShopSellingItem_DESC), len=563
        ("UserShop_GetSelledItem_ASC", "2c2dcc945390686bdb0803c2af10b3ccaf7475e5d2263f84121095f57ae3d159"),   // MySqlUserShopDB.pas:342 (FStatementGetShopSelledItem_ASC), len=508
        ("UserShop_GetSelledItem_DESC", "dde12036f39f2d51059b4fc308e61849563120e660fd55814f90adf361e209cd"),   // MySqlUserShopDB.pas:347 (FStatementGetShopSelledItem_DESC), len=513
        ("UserShop_GetStorageItem_ASC", "96d65efa9caaa775def906e43952548880056b9e2aa817981a6ea3870d06791c"),   // MySqlUserShopDB.pas:352 (FStatementGetShopStorageItem_ASC), len=532
        ("UserShop_GetStorageItem_DESC", "250a5f06469690ada2f052564d93b830da3d8ccdeb0048482d8512b50a7b650e"),   // MySqlUserShopDB.pas:358 (FStatementGetShopStorageItem_DESC), len=537
        ("UserShop_GetSellingAndStorageItem_ASC", "2f0fb330bd0f8c1daeb931eb369447b8410f4ea672896af460cea10b527d92ed"),   // MySqlUserShopDB.pas:364 (FStatementGetShopSellingAndStorageItem_ASC), len=508
        ("UserShop_GetSellingAndStorageItem_DESC", "63a6ae22727294fcc1d9ab65d65d1b2f0f37aba6dcb86d5e2b614968e4e8c65a"),   // MySqlUserShopDB.pas:369 (FStatementGetShopSellingAndStorageItem_DESC), len=513
        ("UserShop_GetSellingItem_Count", "0e8e45555d8480a16eda07f7be157bcd42862a9a9be57eef98b12282152e7192"),   // MySqlUserShopDB.pas:374 (FStatementGetShopSellingItem_Count), len=398
        ("UserShop_GetSelledItem_Count", "83842d74912c657e243aeddca13400b5d29c157f0050994469f5019f0c574b34"),   // MySqlUserShopDB.pas:379 (FStatementGetShopSelledItem_Count), len=348
        ("UserShop_GetStorageItem_Count", "6e6f03df1bbc1c42df1d5bf72d1b79c39617669e7791a7afd83315834a13cbca"),   // MySqlUserShopDB.pas:384 (FStatementGetShopStorageItem_Count), len=372
        ("UserShop_GetSellingAndStorageItem_Count", "bda0ba61b329db160077b785e2ee56c5ee69490a7120ea39fd5e5ea70420faf7"),   // MySqlUserShopDB.pas:389 (FStatementGetShopSellingAndStorageItem_Count), len=348
        ("UserShop_GetAllShop_S0", "832c0cb9857ba4b89fe6b214d670f124e778f926e0d18b07099b39d3c63efe21"),   // MySqlUserShopDB.pas:394 (FStatementGetAllShop_Sort0), len=587
        ("UserShop_GetAllShop_S1", "d19a92de9c7c255b0bf76c5316a4284c6d90f6a6ad65b84be0ebce834da6b975"),   // MySqlUserShopDB.pas:398 (FStatementGetAllShop_Sort1), len=582
        ("UserShop_GetAllShop_S2", "c4c805fe6c8c22fe978091bd2af28c8d86c988a068709d1fd2ca406a594b0107"),   // MySqlUserShopDB.pas:402 (FStatementGetAllShop_Sort2), len=589
        ("UserShop_GetAllShop_S3", "ebb9bdeb226c2ed5c5472d50e3e7c504e318a400e3fe6c2bcb46606cf01f6f05"),   // MySqlUserShopDB.pas:406 (FStatementGetAllShop_Sort3), len=584
        ("UserShop_GetAllShop_S4", "f9387c48087b4f32ea4ab494c866a7734995d7636aa1682ea7a3fca0dbdeb06f"),   // MySqlUserShopDB.pas:410 (FStatementGetAllShop_Sort4), len=583
        ("UserShop_GetAllShop_S5", "6673894d3b4d4014eae592016747c07b2eb6c88c1a67dd3718b774b44d8b2b3b"),   // MySqlUserShopDB.pas:414 (FStatementGetAllShop_Sort5), len=578
        ("UserShop_GetAllShop_Count_S", "845c6bfead74ac86c6371862eed5036847148cbb2b7b87fbab11d074d193ce85"),   // MySqlUserShopDB.pas:417 (FStatementGetAllShop_Count), len=77
        ("UserShop_GetAllShop_Ex", "2c9512157be5f872ddcc44f8df30a2576330d8c6fb767536e3e342f7f83bbbdc"),   // MySqlUserShopDB.pas:423 (FStatementGetAllShop_Ex), len=93
        ("UserShop_GetHumanSellingItem_MakeIndex", "c5b39a04a44e6490cd9e44f47994d160cedcf2f6ec2aa67781ba0d33a36b90ad"),   // MySqlUserShopDB.pas:463 (FStatementGetHumanSellingItem_MakeIndex), len=541
        ("UserShop_GetHumanSelledItem_MakeIndex", "d374b8682d1feff7e1cdb268f669c57e4640f34359f053cda1e9fb3dac0a975d"),   // MySqlUserShopDB.pas:470 (FStatementGetHumanSelledItem_MakeIndex), len=446
        ("UserShop_GetHumanStorageItem_MakeIndex", "31d14142928c9a1ba7b62e3180c29bbceaf4862a5f0de90c5ecf93ce1f97c645"),   // MySqlUserShopDB.pas:476 (FStatementGetHumanStorageItem_MakeIndex), len=470
        ("UserShop_GetHumanSellingAndStorageItem_MakeIndex", "821cc17c202ec6b09d45ee1caeb3303cf0d79d552fc8ef6822b95a4fcba8303c"),   // MySqlUserShopDB.pas:483 (FStatementGetHumanSellingAndStorageItem_MakeIndex), len=446
        ("UserShop_GetItemBindOption", "fd7c17c3b2950411348333fcb8da633cc1dc67492ea796de8fe638e693c58f89"),   // MySqlUserShopDB.pas:489 (FStatementGetItemBindOption), len=100
    };
}