// Source unit: Source/M2Engine/SqliteUserShopDB.pas
// Generated by _recon/gen-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from
// the GBK source. DbLayerSqlFidelityTests asserts that the SQL this port actually binds
// hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>SqliteUserShopDB.pas fixed-statement SQL fingerprints.</summary>
public static class SqliteUserShopDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("UserShop_UpdateAllBusiness", "194c6986dc950e300937fc482ff3a2124accc93e3b1d58e07ab31f0fe2891b3e"),   // SqliteUserShopDB.pas:232 (FStatementUpdateAllBusiness), len=35
        ("UserShop_UpdateHumanBusiness", "96f6268d7e32667b23aaf9fb63f49efb15debc111b403398bf8481f0721b7671"),   // SqliteUserShopDB.pas:237 (FStatementUpdateHumanBusiness), len=55
        ("UserShop_CheckHumanNameExists", "ceaf8d8ede513092691e8ab2fa8eee28824152cc0d2d96606cc57133056588c8"),   // SqliteUserShopDB.pas:241 (FStatementHumanNameExists), len=43
        ("UserShop_CheckShopNameExists", "b8beb3c98c8fe6c7df0577c58fce199960e2079146b3fbff1f8b6beae2cf73e4"),   // SqliteUserShopDB.pas:245 (FStatementShopNameExists), len=42
        ("UserShop_InsertUserShop", "75a8cd5f705903aa47a12b7ac15d57ff1ebaec9f0ea63e708a53434cd213f2d8"),   // SqliteUserShopDB.pas:249 (FStatementInsertUserShop), len=70
        ("UserShop_UpdateShopName", "74c627c55f10393e9b80c5e4572408f8f9fac8a200bd3e0da21aebe087932fed"),   // SqliteUserShopDB.pas:253 (FStatementUserShopRename), len=50
        ("UserShop_UpdateShopName2", "e9c6b34f5978a567e02cb4a2aa8b15cbb2fb55d73605e3add4c24e8fb55b6ddd"),   // SqliteUserShopDB.pas:257 (FStatementUserShopRename2), len=53
        ("UserShop_ShopItemBuyerRenameName", "2755f89873f1ae2a03f216b542d280267975c71eea046bffbfff67fdd70a86ae"),   // SqliteUserShopDB.pas:261 (FStatementShopItemBuyerRenameName), len=57
        ("UserShop_GetUserShopInfo", "269a6b3c0e61d684ae09d43a16b22bc397f74828240c32436142304699c39b28"),   // SqliteUserShopDB.pas:265 (FStatementGetUserShopInfo), len=505
        ("UserShop_IncUserShopCareValue", "29568fcf4972851fbe3e3a64836cb992a37ad4fb408f6c445fad39dbbb94263a"),   // SqliteUserShopDB.pas:274 (FStatementIncUserShopCareValue), len=65
        ("UserShop_GetMaxShopItemID", "e5d854bfbe586199b17d0d884ff0e8dfbb93f78bcfb1c8c36772ce42d11f147c"),   // SqliteUserShopDB.pas:278 (FStatementGetMaxShopItemID), len=69
        ("UserShop_InsertShopItem", "dc753beca55a073eaad5fd30e8703e44c8d550b9a60b89f5611950b448fe6266"),   // SqliteUserShopDB.pas:282 (FStatementInsertUserShopItem), len=173
        ("UserShop_UpdateShopItem", "67b5ab94697558923364b5cb3b86770de78ae967847ea903bab66b8a69854e03"),   // SqliteUserShopDB.pas:288 (FStatementUpdateUserShopItem), len=191
        ("UserShop_BuyShopItem", "57edf9360f3f3b4e82f0d82eb31e8f222f8d6cd6f5a55a836e7ae68dee6b620e"),   // SqliteUserShopDB.pas:293 (FStatementBuyUserShopItem), len=145
        ("UserShop_GetMoneyShopItem", "bac3cc769066f2ae1f47a26f9d59f786ca542f33941db50aec627e5935cdeb1d"),   // SqliteUserShopDB.pas:298 (FStatementGetMoneyShopItem), len=108
        ("UserShop_GetSelledAndNoGetMoneyTotal", "25a71ebb6043017540973f1ecad41c33359c52f4f7f0935eff8c977cd7b2daa8"),   // SqliteUserShopDB.pas:303 (FStatementGetSelledAndNoGetMoneyTotal), len=230
        ("UserShop_GetTimeHasArrivedSellItems", "33039e63cf0b57910a92724eed11572d3c9665b2fe5e0c55850bf4e26cb7b5c3"),   // SqliteUserShopDB.pas:310 (FStatementGetTimeHasArrivedSellItems), len=446
        ("UserShop_GetSellingItem_ASC", "fc76cf101e8c0ffd642dfc3e66c37242577798d72845d0317fe637e51dd04feb"),   // SqliteUserShopDB.pas:320 (FStatementGetShopSellingItem_ASC), len=556
        ("UserShop_GetSellingItem_DESC", "f0b87c5d715acc30b9338ba22f569b4e5f148be42b673b0765566eddd83be65f"),   // SqliteUserShopDB.pas:326 (FStatementGetShopSellingItem_DESC), len=561
        ("UserShop_GetSelledItem_ASC", "73730d39b0de58609bec9c3b5e63b8085a0287b0499afbd9f8438f33a1ada1f6"),   // SqliteUserShopDB.pas:332 (FStatementGetShopSelledItem_ASC), len=506
        ("UserShop_GetSelledItem_DESC", "97d47c16c69f3d50a25927cf5a8d48650ba091a2b5a6803e637c4b193edcee91"),   // SqliteUserShopDB.pas:337 (FStatementGetShopSelledItem_DESC), len=511
        ("UserShop_GetStorageItem_ASC", "eff3dfb387c955b6a4b7313856c4cd02f563f2aa295da93afa7576df7f868574"),   // SqliteUserShopDB.pas:342 (FStatementGetShopStorageItem_ASC), len=530
        ("UserShop_GetStorageItem_DESC", "041bd0b38e0a48261492d40269945a55b245c4742ab8f67cfda723a98e93e15c"),   // SqliteUserShopDB.pas:348 (FStatementGetShopStorageItem_DESC), len=535
        ("UserShop_GetSellingAndStorageItem_ASC", "b077bd8577e8b46007c8e01fd5e2349dfa84c7c79ba68e4695a0e5a6c6936a1b"),   // SqliteUserShopDB.pas:354 (FStatementGetShopSellingAndStorageItem_ASC), len=506
        ("UserShop_GetSellingAndStorageItem_DESC", "8ba0c676055239b220f1be738de4beea2154f088c0c232c94d3a367fdace23f6"),   // SqliteUserShopDB.pas:359 (FStatementGetShopSellingAndStorageItem_DESC), len=511
        ("UserShop_GetSellingItem_Count", "b8579d619b5d94ec6458489eb5211f385b2c6b85c7f47fb8a13e6528ec85a8eb"),   // SqliteUserShopDB.pas:364 (FStatementGetShopSellingItem_Count), len=396
        ("UserShop_GetSelledItem_Count", "d4e4db32fde928d9e01fa2a2cc1ef9d9fcf11531b7abbe39c8eed48a1ae798a8"),   // SqliteUserShopDB.pas:369 (FStatementGetShopSelledItem_Count), len=346
        ("UserShop_GetStorageItem_Count", "2b1c1213bdaa3339c78b44d0ff345aaa2b0be43f1a7f2cdf9a5aa5f685bd23dc"),   // SqliteUserShopDB.pas:374 (FStatementGetShopStorageItem_Count), len=370
        ("UserShop_GetSellingAndStorageItem_Count", "c756fdd7e5309fcaa6856e8831b445ba46ffd2fbd8e125cf368876b29861326a"),   // SqliteUserShopDB.pas:379 (FStatementGetShopSellingAndStorageItem_Count), len=346
        ("UserShop_GetAllShop_S0", "8ae864d4b4081a9698477aa1247b1eebfaa3c3ab6eb9bd499a889eebd2f6e2aa"),   // SqliteUserShopDB.pas:384 (FStatementGetAllShop_Sort0), len=581
        ("UserShop_GetAllShop_S1", "db2e4b223605196bcd475ba82ce6f97cc7ec8bde22d313f82469aba602844545"),   // SqliteUserShopDB.pas:388 (FStatementGetAllShop_Sort1), len=576
        ("UserShop_GetAllShop_S2", "d4c2d7bbf1ea8b1ea80167fbcbb0004f99f389315c6b68f1b864603b516b9618"),   // SqliteUserShopDB.pas:392 (FStatementGetAllShop_Sort2), len=583
        ("UserShop_GetAllShop_S3", "57c4580ddfbc08a8a9aa94ddfd2ce6c8e69fa77f17186ef3aadf8a5ede0d8221"),   // SqliteUserShopDB.pas:396 (FStatementGetAllShop_Sort3), len=578
        ("UserShop_GetAllShop_S4", "1a5a388d94d9f6bf0dcc991ec6fc1ff29928ac6f8f6b9e43d08b2c0b314b34d5"),   // SqliteUserShopDB.pas:400 (FStatementGetAllShop_Sort4), len=577
        ("UserShop_GetAllShop_S5", "5a91125dd6605b6937e027c70df32bfc578c42b505a268100be6f27219bba196"),   // SqliteUserShopDB.pas:404 (FStatementGetAllShop_Sort5), len=572
        ("UserShop_GetAllShop_Count_S", "845c6bfead74ac86c6371862eed5036847148cbb2b7b87fbab11d074d193ce85"),   // SqliteUserShopDB.pas:407 (FStatementGetAllShop_Count), len=77
        ("UserShop_GetAllShop_Ex", "2c9512157be5f872ddcc44f8df30a2576330d8c6fb767536e3e342f7f83bbbdc"),   // SqliteUserShopDB.pas:413 (FStatementGetAllShop_Ex), len=93
        ("UserShop_GetHumanSellingItem_MakeIndex", "411a6e1089959fa3d740bcccb092a831fa9cb2a33e35bb29d7a8014248172b0b"),   // SqliteUserShopDB.pas:453 (FStatementGetHumanSellingItem_MakeIndex), len=539
        ("UserShop_GetHumanSelledItem_MakeIndex", "64d3fe8619b965aa3c37532341d32f4ebb1da6f81d7233e033dd6ef7c4d6f972"),   // SqliteUserShopDB.pas:459 (FStatementGetHumanSelledItem_MakeIndex), len=444
        ("UserShop_GetHumanStorageItem_MakeIndex", "552584408da12329e6dbf932c9d1551c78714ddaac55879e92b3a5168a95c90d"),   // SqliteUserShopDB.pas:464 (FStatementGetHumanStorageItem_MakeIndex), len=468
        ("UserShop_GetHumanSellingAndStorageItem_MakeIndex", "1c505e5306e62d25a52ad961e2c084b50c2972f56b1fa1e4331aa6af54f06401"),   // SqliteUserShopDB.pas:470 (FStatementGetHumanSellingAndStorageItem_MakeIndex), len=444
    };
}