// Source unit: Source/M2Engine/SqliteUserShopDB.pas
// Generated by _recon/gen-fingerprints.mjs — SHA-256 of the verbatim SQL extracted from
// the GBK source. DbLayerSqlFidelityTests asserts that the SQL this port actually binds
// hashes to these values, i.e. no hand transcription drifted.

namespace GXX.M2Server.Tests;

/// <summary>SqliteUserShopDB.pas fixed-statement SQL fingerprints.</summary>
public static class SqliteUserShopDbFingerprints
{
    /// <summary>Delphi statement field name → SHA-256 of the SQL text bound to it (lower-case hex).</summary>
    public static readonly (string Label, string Sha256)[] Statements =
    {
        ("UserShop_UpdateAllBusiness", "194c6986dc950e300937fc482ff3a2124accc93e3b1d58e07ab31f0fe2891b3e"),   // SqliteUserShopDB.pas:232 (FStatementUpdateAllBusiness), len=35
        ("UserShop_UpdateHumanBusiness", "96f6268d7e32667b23aaf9fb63f49efb15debc111b403398bf8481f0721b7671"),   // SqliteUserShopDB.pas:237 (FStatementUpdateHumanBusiness), len=55
        ("UserShop_CheckHumanNameExists", "ceaf8d8ede513092691e8ab2fa8eee28824152cc0d2d96606cc57133056588c8"),   // SqliteUserShopDB.pas:241 (FStatementHumanNameExists), len=43
        ("UserShop_CheckShopNameExists", "b8beb3c98c8fe6c7df0577c58fce199960e2079146b3fbff1f8b6beae2cf73e4"),   // SqliteUserShopDB.pas:245 (FStatementShopNameExists), len=42
        ("UserShop_InsertUserShop", "75a8cd5f705903aa47a12b7ac15d57ff1ebaec9f0ea63e708a53434cd213f2d8"),   // SqliteUserShopDB.pas:249 (FStatementInsertUserShop), len=70
        ("UserShop_UpdateShopName", "74c627c55f10393e9b80c5e4572408f8f9fac8a200bd3e0da21aebe087932fed"),   // SqliteUserShopDB.pas:253 (FStatementUserShopRename), len=50
        ("UserShop_UpdateShopName2", "e9c6b34f5978a567e02cb4a2aa8b15cbb2fb55d73605e3add4c24e8fb55b6ddd"),   // SqliteUserShopDB.pas:257 (FStatementUserShopRename2), len=53
        ("UserShop_ShopItemBuyerRenameName", "2755f89873f1ae2a03f216b542d280267975c71eea046bffbfff67fdd70a86ae"),   // SqliteUserShopDB.pas:261 (FStatementShopItemBuyerRenameName), len=57
        ("UserShop_GetUserShopInfo", "9471c6f9603618b1a88e4f4187a413b6a583e93c07adab9bea7211128f232e9d"),   // SqliteUserShopDB.pas:265 (FStatementGetUserShopInfo), len=511
        ("UserShop_IncUserShopCareValue", "29568fcf4972851fbe3e3a64836cb992a37ad4fb408f6c445fad39dbbb94263a"),   // SqliteUserShopDB.pas:274 (FStatementIncUserShopCareValue), len=65
        ("UserShop_GetMaxShopItemID", "e5d854bfbe586199b17d0d884ff0e8dfbb93f78bcfb1c8c36772ce42d11f147c"),   // SqliteUserShopDB.pas:278 (FStatementGetMaxShopItemID), len=69
        ("UserShop_InsertShopItem", "dc753beca55a073eaad5fd30e8703e44c8d550b9a60b89f5611950b448fe6266"),   // SqliteUserShopDB.pas:282 (FStatementInsertUserShopItem), len=173
        ("UserShop_UpdateShopItem", "d2e6ea8527bf7457d55f5d066f407a7cf7010a13a71667a65fccb02ab6685d3b"),   // SqliteUserShopDB.pas:288 (FStatementUpdateUserShopItem), len=197
        ("UserShop_BuyShopItem", "e5b5a2da22ecd5b4d99b90873f9a9c51654c03c2a062fda47502299dccde6aa4"),   // SqliteUserShopDB.pas:293 (FStatementBuyUserShopItem), len=151
        ("UserShop_GetMoneyShopItem", "93ab6847fe55502e4f20a57f67e68f1ef803c5aa3f56f21d937ff9e7e12eb057"),   // SqliteUserShopDB.pas:298 (FStatementGetMoneyShopItem), len=110
        ("UserShop_GetSelledAndNoGetMoneyTotal", "47fcbfc6cfcb07a0347f1bf32fdd2b1e64975744122edaee8b1a19430b394933"),   // SqliteUserShopDB.pas:303 (FStatementGetSelledAndNoGetMoneyTotal), len=232
        ("UserShop_GetTimeHasArrivedSellItems", "0b185393a08aeb977a3c6c3fbadcc1930ac6eafd213b2dddd2cfac6dfc3f67c1"),   // SqliteUserShopDB.pas:310 (FStatementGetTimeHasArrivedSellItems), len=448
        ("UserShop_GetSellingItem_ASC", "139afb6c361362dea8519bd3a2364ed8b5a3759104082eeac0cfb08f2d663a4a"),   // SqliteUserShopDB.pas:320 (FStatementGetShopSellingItem_ASC), len=558
        ("UserShop_GetSellingItem_DESC", "15e36f7d3ea006ead883ef21b98bea21c85c3bb0d740b03171352532a2362968"),   // SqliteUserShopDB.pas:326 (FStatementGetShopSellingItem_DESC), len=563
        ("UserShop_GetSelledItem_ASC", "2c2dcc945390686bdb0803c2af10b3ccaf7475e5d2263f84121095f57ae3d159"),   // SqliteUserShopDB.pas:332 (FStatementGetShopSelledItem_ASC), len=508
        ("UserShop_GetSelledItem_DESC", "dde12036f39f2d51059b4fc308e61849563120e660fd55814f90adf361e209cd"),   // SqliteUserShopDB.pas:337 (FStatementGetShopSelledItem_DESC), len=513
        ("UserShop_GetStorageItem_ASC", "96d65efa9caaa775def906e43952548880056b9e2aa817981a6ea3870d06791c"),   // SqliteUserShopDB.pas:342 (FStatementGetShopStorageItem_ASC), len=532
        ("UserShop_GetStorageItem_DESC", "250a5f06469690ada2f052564d93b830da3d8ccdeb0048482d8512b50a7b650e"),   // SqliteUserShopDB.pas:348 (FStatementGetShopStorageItem_DESC), len=537
        ("UserShop_GetSellingAndStorageItem_ASC", "2f0fb330bd0f8c1daeb931eb369447b8410f4ea672896af460cea10b527d92ed"),   // SqliteUserShopDB.pas:354 (FStatementGetShopSellingAndStorageItem_ASC), len=508
        ("UserShop_GetSellingAndStorageItem_DESC", "63a6ae22727294fcc1d9ab65d65d1b2f0f37aba6dcb86d5e2b614968e4e8c65a"),   // SqliteUserShopDB.pas:359 (FStatementGetShopSellingAndStorageItem_DESC), len=513
        ("UserShop_GetSellingItem_Count", "0e8e45555d8480a16eda07f7be157bcd42862a9a9be57eef98b12282152e7192"),   // SqliteUserShopDB.pas:364 (FStatementGetShopSellingItem_Count), len=398
        ("UserShop_GetSelledItem_Count", "83842d74912c657e243aeddca13400b5d29c157f0050994469f5019f0c574b34"),   // SqliteUserShopDB.pas:369 (FStatementGetShopSelledItem_Count), len=348
        ("UserShop_GetStorageItem_Count", "6e6f03df1bbc1c42df1d5bf72d1b79c39617669e7791a7afd83315834a13cbca"),   // SqliteUserShopDB.pas:374 (FStatementGetShopStorageItem_Count), len=372
        ("UserShop_GetSellingAndStorageItem_Count", "bda0ba61b329db160077b785e2ee56c5ee69490a7120ea39fd5e5ea70420faf7"),   // SqliteUserShopDB.pas:379 (FStatementGetShopSellingAndStorageItem_Count), len=348
        ("UserShop_GetAllShop_S0", "c3cc6a7845187b176f46fedb7c3bae3616441ff8cdd72cf866df4daa37828253"),   // SqliteUserShopDB.pas:384 (FStatementGetAllShop_Sort0), len=587
        ("UserShop_GetAllShop_S1", "997f8db9641e08027d1ae68229783a83d162e6da1054f5ec6d640e4dec36f17f"),   // SqliteUserShopDB.pas:388 (FStatementGetAllShop_Sort1), len=582
        ("UserShop_GetAllShop_S2", "db8e9f8042a283b2c95fe8523bc5c3a28928dc969a451fde6723f74d4367695d"),   // SqliteUserShopDB.pas:392 (FStatementGetAllShop_Sort2), len=589
        ("UserShop_GetAllShop_S3", "7d78a7787d722fa3038e865a556bb3656adf9b856c9bbb0c8f588d249eca2dde"),   // SqliteUserShopDB.pas:396 (FStatementGetAllShop_Sort3), len=584
        ("UserShop_GetAllShop_S4", "d3b356d68f793bec425987168a16a35ab39668137e5966c6bcca7d18a7401b53"),   // SqliteUserShopDB.pas:400 (FStatementGetAllShop_Sort4), len=583
        ("UserShop_GetAllShop_S5", "b2585e7409dea7bdb0bff656b33039cf0650c991ec2716db2a2fa9b8ab68052d"),   // SqliteUserShopDB.pas:404 (FStatementGetAllShop_Sort5), len=578
        ("UserShop_GetAllShop_Count_S", "845c6bfead74ac86c6371862eed5036847148cbb2b7b87fbab11d074d193ce85"),   // SqliteUserShopDB.pas:407 (FStatementGetAllShop_Count), len=77
        ("UserShop_GetAllShop_Ex", "2c9512157be5f872ddcc44f8df30a2576330d8c6fb767536e3e342f7f83bbbdc"),   // SqliteUserShopDB.pas:413 (FStatementGetAllShop_Ex), len=93
        ("UserShop_GetHumanSellingItem_MakeIndex", "c5b39a04a44e6490cd9e44f47994d160cedcf2f6ec2aa67781ba0d33a36b90ad"),   // SqliteUserShopDB.pas:453 (FStatementGetHumanSellingItem_MakeIndex), len=541
        ("UserShop_GetHumanSelledItem_MakeIndex", "d374b8682d1feff7e1cdb268f669c57e4640f34359f053cda1e9fb3dac0a975d"),   // SqliteUserShopDB.pas:459 (FStatementGetHumanSelledItem_MakeIndex), len=446
        ("UserShop_GetHumanStorageItem_MakeIndex", "31d14142928c9a1ba7b62e3180c29bbceaf4862a5f0de90c5ecf93ce1f97c645"),   // SqliteUserShopDB.pas:464 (FStatementGetHumanStorageItem_MakeIndex), len=470
        ("UserShop_GetHumanSellingAndStorageItem_MakeIndex", "821cc17c202ec6b09d45ee1caeb3303cf0d79d552fc8ef6822b95a4fcba8303c"),   // SqliteUserShopDB.pas:470 (FStatementGetHumanSellingAndStorageItem_MakeIndex), len=446
    };
}