unit LogDataMain;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, IniFiles, Menus, Common,
  IdSocketHandle, IdBaseComponent, IdComponent, IdGlobal, IdUDPBase,
  IdUDPServer, FileSearchPool, ComCtrls, ToolWin, ImgList, JSocket,
  uFrmRemoteQuerySetting, MD5Util, LDShare, StrUtils;

const
  WM_SET_PARENT_WINDOW = WM_USER + 123;

type
  TProcessUserSessionThread = class(TThread)
  private
    FErrorMessage: string;
    procedure ProcessSearchAndSend(
      UserSession: PControlSessionInfo;
      SearchInfo: PTControlSearchInfo;
      LogFileName: string;
      SendBufStart: pTControlLogData;
      var SendBufCurrent: pTControlLogData;
      var SendAllCount, SendCurrCount: Integer);

    procedure ShowError;
    procedure ProcessUserSession(UserSession: PControlSessionInfo);
  protected
    procedure Execute; override;
  public
    property Terminated;
  end;

  TFrmLogData = class(TForm)
    Timer1: TTimer;
    StartTimer: TTimer;
    CloseTimer: TTimer;
    IdUDPServerLog: TIdUDPServer;
    statMain: TStatusBar;
    mm1: TMainMenu;
    N1: TMenuItem;
    mmoLog: TMemo;
    N2: TMenuItem;
    N3: TMenuItem;
    srvrsckt1: TServerSocket;
    tmr1: TTimer;

    procedure FormCreate(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
    procedure Timer1Timer(Sender: TObject);
    procedure WriteLogFile();

    procedure FormCloseQuery(Sender: TObject; var CanClose: Boolean);
    procedure StartTimerTimer(Sender: TObject);
    procedure CloseTimerTimer(Sender: TObject);
    //procedure IdUDPServerLogUDPRead(Sender: TObject; AData: TStream; ABinding: TIdSocketHandle);
    procedure IdUDPServerLogUDPRead(Sender: TObject; AData: TBytes; ABinding: TIdSocketHandle);
    procedure N1Click(Sender: TObject);
    procedure N3Click(Sender: TObject);
    procedure srvrsckt1Accept(Sender: TObject; Socket: TCustomWinSocket);
    procedure srvrsckt1ClientConnect(Sender: TObject;
      Socket: TCustomWinSocket);
    procedure srvrsckt1ClientDisconnect(Sender: TObject;
      Socket: TCustomWinSocket);
    procedure srvrsckt1ClientError(Sender: TObject;
      Socket: TCustomWinSocket; ErrorEvent: TErrorEvent;
      var ErrorCode: Integer);
    procedure srvrsckt1ClientRead(Sender: TObject;
      Socket: TCustomWinSocket);
    procedure tmr1Timer(Sender: TObject);

    //procedure IdUDPServerLogUDPRead(Sender: TObject; AData: TBytes;
    //  ABinding: TIdSocketHandle);
  private
    FIsEmbeddedGameCenter: Boolean;

    FLogFileName: string;
    FFileHandle: THandle;

    LogMsgList: TStringList;
    TempLogMsgList: TStringList;
    FCS: TRTLCriticalSection;

    FBuffer: array[0..40960] of Byte;

    m_boRemoteClose: Boolean;

    FProcessUserSessionThread: TProcessUserSessionThread;

    FControlIndex: Integer;

    procedure WMSysCommand(var Message: TWMSysCommand); message WM_SYSCOMMAND;
    procedure WMSetParentWindow(var Message: TMessage); message WM_SET_PARENT_WINDOW;

    procedure OnAppModalBegin(Sender: TObject);
    procedure OnAppOnModalEnd(Sender: TObject);

    procedure ShowMainLog(S: string; IsAddDateTime: Boolean = True);
    { Private declarations }
  public
    procedure MyMessage(var MsgData: TWmCopyData); message WM_COPYDATA;
    { Public declarations }
  end;

var
  FrmLogData: TFrmLogData;
  {This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

uses Grobal2, HUtil32, LogManage;

{$R *.DFM}

{ TProcessUserSessionThread }

function GetActionChecked(SearchInfo: PTControlSearchInfo; nAction: LongWord): Boolean;
var
  W1: Word;
  B1, B2: Byte;
begin
  // 日志类型暂时只用了Word
  W1 := LoWord(nAction);
  B1 := LoByte(W1);
  B2 := HiByte(W1);

  Result := SearchInfo.SearchActions[B1] or SearchInfo.SearchActions[B2];
end;

function GetSearch(nWhere: Integer; sObjName, sActObjName, sItemName: string; nActObjType: Integer; nItemID: Integer; LogData: pTControlLogData): Boolean;
//var
  //I: Integer;
begin
  Result := True;
  if nWhere <= 0 then Exit;

  if nWhere and 1 = 1 then
    Result := AnsiContainsText(LogData.sObjectName, sObjName);
  if not Result then Exit;

  if nWhere and 2 = 2 then
    Result := Integer(LogData.ObjectType) = nActObjType;
  if not Result then Exit;
  
  if nWhere and 4 = 4 then
    Result := AnsiContainsText(LogData.sActObjectName, sActObjName);
  if not Result then Exit;

  if nWhere and 8 = 8 then
    Result := AnsiContainsText(LogData.sItemName, sItemName);
  if not Result then Exit;

  if nWhere and 16 = 16 then
    Result := LogData.nItemIndex = nItemID;
end;

procedure TProcessUserSessionThread.ProcessSearchAndSend(
  UserSession: PControlSessionInfo;
  SearchInfo: PTControlSearchInfo;
  LogFileName: string;
  SendBufStart: pTControlLogData;
  var SendBufCurrent: pTControlLogData;
  var SendAllCount, SendCurrCount: Integer);
var
  nLen: Integer;
  nServerNumber: Integer;
  nServerIndex: Integer;
  nAction: LongWord;
  sMapName: string;
  nX, nY: Integer;
  sObjectName: string;
  sItemName: string;
  nItemIndex: Integer;
  sActObjectName: string;
  nData1, nData2: Integer;
  sLogDesc: string;
  Dt: TDateTime;
  btActorType: Byte;
  LogData: TControlLogData;

  FileStream: TFileStream;
begin
  FileStream := TFileStream.Create(LogFileName, fmOpenRead or fmShareDenyNone);
  try
    FileStream.Seek(0, soFromBeginning);
    while FileStream.Position < FileStream.Size do
    begin
      if FileStream.Read(nServerNumber, SizeOf(nServerNumber)) <> SizeOf(nServerNumber) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if FileStream.Read(nServerIndex, SizeOf(nServerIndex)) <> SizeOf(nServerIndex) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if FileStream.Read(nAction, SizeOf(nAction)) <> SizeOf(nAction) then
      begin
        // FileStream.Free;
        Exit;
      end;

      sMapName := '';
      if FileStream.Read(nLen, SizeOf(nLen)) <> SizeOf(nLen) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if nLen > 0 then
      begin
        SetLength(sMapName, nLen);

        if FileStream.Read(sMapName[1], nLen) <> nLen then
        begin
          // FileStream.Free;
          Exit;
        end;
      end;

      if FileStream.Read(nX, SizeOf(nX)) <> SizeOf(nX) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if FileStream.Read(nY, SizeOf(nY)) <> SizeOf(nY) then
      begin
        // FileStream.Free;
        Exit;
      end;

      sObjectName := '';
      if FileStream.Read(nLen, SizeOf(nLen)) <> SizeOf(nLen) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if nLen > 0 then
      begin
        SetLength(sObjectName, nLen);
        if FileStream.Read(sObjectName[1], nLen) <> nLen then
        begin
          // FileStream.Free;
          Exit;
        end;
      end;

      if FileStream.Read(btActorType, SizeOf(btActorType)) <> SizeOf(btActorType) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if (btActorType < Integer(Low(TLogActorType))) or (btActorType > Integer(High(TLogActorType))) then
      begin
        btActorType := Integer(latNone);
      end;

      sItemName := '';
      if FileStream.Read(nLen, SizeOf(nLen)) <> SizeOf(nLen) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if nLen > 0 then
      begin
        SetLength(sItemName, nLen);
        if FileStream.Read(sItemName[1], nLen) <> nLen then
        begin
          // FileStream.Free;
          Exit;
        end;
      end;

      if FileStream.Read(nItemIndex, SizeOf(nItemIndex)) <> SizeOf(nItemIndex) then
      begin
        // FileStream.Free;
        Exit;
      end;

      sActObjectName := '';
      if FileStream.Read(nLen, SizeOf(nLen)) <> SizeOf(nLen) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if nLen > 0 then
      begin
        SetLength(sActObjectName, nLen);
        if FileStream.Read(sActObjectName[1], nLen) <> nLen then
        begin
          // FileStream.Free;
          Exit;
        end;
      end;

      if FileStream.Read(nData1, SizeOf(nData1)) <> SizeOf(nData1) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if FileStream.Read(nData2, SizeOf(nData2)) <> SizeOf(nData2) then
      begin
        // FileStream.Free;
        Exit;
      end;

      sLogDesc := '';
      if FileStream.Read(nLen, SizeOf(nLen)) <> SizeOf(nLen) then
      begin
        // FileStream.Free;
        Exit;
      end;

      if nLen > 0 then
      begin
        SetLength(sLogDesc, nLen);
        if FileStream.Read(sLogDesc[1], nLen) <> nLen then
        begin
          // FileStream.Free;
          Exit;
        end;
      end;

      if FileStream.Read(Dt, SizeOf(Dt)) <> SizeOf(Dt) then
      begin
        // FileStream.Free;
        Exit;
      end;

      EnterCriticalSection(g_ControlSessionCS);
      try
        if UserSession.Socket = nil then
        begin
          // FileStream.Free;
          Exit;
        end;
      finally
        LeaveCriticalSection(g_ControlSessionCS);
      end;

      if not UserSession.IsRunning then Exit;

      LogData.nAct := nAction;
      LogData.sMapName := sMapName;
      LogData.nX := nX;
      LogData.nY := nY;
      LogData.sObjectName := sObjectName;
      LogData.ObjectType := TLogActorType(btActorType);
      LogData.sItemName := sItemName;
      LogData.nItemIndex := nItemIndex;
      LogData.sActObjectName := sActObjectName;
      LogData.nData1 := nData1;
      LogData.nData2 := nData2;
      LogData.LogDesc := sLogDesc;
      LogData.Date := Dt;

      if GetActionChecked(SearchInfo, nAction) and
        GetSearch(SearchInfo.SearchWhere, SearchInfo.SearchObjName, SearchInfo.SearchActObjName, SearchInfo.SearchItemName, SearchInfo.SearchActObjType, SearchInfo.SearchItemID, @LogData) then
      begin
        LogData.nIndx := SendAllCount;
        Inc(SendAllCount);

        if SendCurrCount < 200 then
        begin
          SendBufCurrent^ := LogData;
        end
        else
        begin
          EnterCriticalSection(g_ControlSessionCS);
          try
            if (UserSession.Socket <> nil) and (UserSession.IsRunning) then
            begin
              SendControlMsg(UserSession.Socket, SMSG_SEARCH_LOG, PAnsiChar(SendBufStart), SendCurrCount * SizeOf(TControlLogData));
            end
            else
            begin
              Exit;
            end;
          finally
            LeaveCriticalSection(g_ControlSessionCS);
          end;

          Sleep(300);
          SendBufCurrent := SendBufStart;
          SendCurrCount := 0;
          SendBufCurrent^ := LogData;
        end;

        Inc(SendCurrCount);
        Inc(SendBufCurrent);
      end;
    end;
  finally
    FileStream.Free;
  end;
end;

procedure TProcessUserSessionThread.ShowError;
begin
  FrmLogData.ShowMainLog('ThreadError, ' + FErrorMessage);
end;

procedure TProcessUserSessionThread.ProcessUserSession(
  UserSession: PControlSessionInfo);
var
  I, UserCmd, nDay: Integer;
  UserData, sLogDir: string;
  SearchDay: TDate;
  Year, Month, Day: Word;

  SR: TSearchRec;
  sFileName: string;
  SearchInfo: PTControlSearchInfo;

  SendBuf: array[0..500] of TControlLogData;
  SendCurrent: pTControlLogData;
  SendAllCount, SendCurrCount: Integer;
begin
  UserCmd := 0;
  UserData := '';

  UserSession.MsgList.Lock;
  try
    if UserSession.MsgList.Count > 0 then
    begin
      UserCmd := Integer(UserSession.MsgList.Objects[0]);
      UserData := UserSession.MsgList.Strings[0];

      UserSession.MsgList.Delete(0);
    end;
  finally
    UserSession.MsgList.UnLock;
  end;

  if (UserCmd = 0) or (UserData = '') then Exit;

  if UserCmd <> CMSG_SEARCH_LOG then Exit;
  if Length(UserData) <> SizeOf(TControlSearchInfo) then Exit;

  SendAllCount := 0;
  SendCurrCount := 0;
  SendCurrent := @SendBuf[0];

  SearchInfo := PTControlSearchInfo(UserData);

  EnterCriticalSection(g_ControlSessionCS);
  try
    if UserSession.Socket <> nil then
    begin
      SendControlMsg(UserSession.Socket, SMSG_SEARCH_START, nil, 0);
    end;
  finally
    LeaveCriticalSection(g_ControlSessionCS);
  end;

  if not UserSession.IsRunning then Exit;
                                                 
  nDay := GetDayCount(SearchInfo.SearchEndDay, SearchInfo.SearchStartDay);
  if nDay > 30 then nDay := 30;

  OutputDebugString(PChar('远程查询数据;' + FormatDateTime('yyyy-mm-dd', SearchInfo.SearchStartDay)));

  for I := 0 to nDay do
  begin
    SearchDay := SearchInfo.SearchStartDay + I;
    DecodeDate(SearchDay, Year, Month, Day);
    sLogDir := IncludeTrailingBackslash(sBaseDir) + IntToStr(Year) + '-' + IntToString(Month) + '-' + IntToString(Day);

    if not UserSession.IsRunning then Exit;
    if DirectoryExists(sLogDir) then
    begin
      if FindFirst(sLogDir + '\*.nlf', faAnyFile, SR) = 0 then
      begin
        repeat
          if not UserSession.IsRunning then
          begin
            FindClose(SR);
            Exit;
          end;

          EnterCriticalSection(g_ControlSessionCS);
          try
            if UserSession.Socket = nil then Exit;
          finally
            LeaveCriticalSection(g_ControlSessionCS);
          end;

          if SR.Attr and faDirectory = faDirectory then Continue;
          if not SameText(Copy(SR.Name, 1, 4), 'log-') then Continue;

          sFileName := sLogDir + '\' + SR.Name;
          try
            ProcessSearchAndSend(UserSession, SearchInfo, sFileName, @SendBuf[0], SendCurrent, SendAllCount, SendCurrCount);
          except
            on E: Exception do
            begin
              FErrorMessage := E.Message;
              Synchronize(ShowError);
            end;
          end;
        until FindNext(SR) <> 0;   

        FindClose(SR);
      end;
    end;

    EnterCriticalSection(g_ControlSessionCS);
    try
      if UserSession.Socket = nil then Exit;
    finally
      LeaveCriticalSection(g_ControlSessionCS);
    end;
  end;

  EnterCriticalSection(g_ControlSessionCS);
  try
    if UserSession.Socket <> nil then
    begin
      if SendCurrCount > 0 then
      begin
        SendControlMsg(UserSession.Socket, SMSG_SEARCH_LOG, PAnsiChar(@SendBuf[0]), SendCurrCount * SizeOf(TControlLogData));
      end;

      SendControlMsg(UserSession.Socket, SMSG_SEARCH_LOG_END, nil, 0);
    end;
  finally
    LeaveCriticalSection(g_ControlSessionCS);
  end;

  if SendCurrCount > 0 then
  begin
    Sleep(300);
  end;
end;


procedure TProcessUserSessionThread.Execute;
var
  I: Integer;
  UserSession: PControlSessionInfo;
begin
  inherited;

  while not Terminated do
  begin
    for I := 0 to Length(g_ControlSessionArray) - 1 do
    begin
      UserSession := @g_ControlSessionArray[I];
      ProcessUserSession(UserSession);
    end;
    Sleep(1);
  end;
end;


procedure TFrmLogData.FormCreate(Sender: TObject);
var
  //Conf: TIniFile;
  nX, nY, I: Integer;
  UserSession: PControlSessionInfo;
begin
  {
  asm
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  end;
  }
  FIsEmbeddedGameCenter := False;
  
  g_dwGameCenterHandle := Str_ToInt(ParamStr(1), 0);
  nX := Str_ToInt(ParamStr(2), -1);
  nY := Str_ToInt(ParamStr(3), -1);
  if (nX >= 0) or (nY >= 0) then
  begin
    Left := nX;
    Top := nY;
  end;

  m_boRemoteClose := False;
  SendGameCenterMsg(SG_FORMHANDLE, IntToStr(Self.Handle));

  Application.OnModalBegin := OnAppModalBegin;
  Application.OnModalEnd := OnAppOnModalEnd;

  FLogFileName := '';
  FFileHandle := INVALID_HANDLE_VALUE;

  g_ControlIPFile := ExtractFilePath(Application.ExeName) + 'ControlIP.txt';
  g_ControlIPList := TSafeHashStringList.Create;
  if FileExists(g_ControlIPFile) then
  begin
    g_ControlIPList.LoadFromFile(g_ControlIPFile);
  end;

  FControlIndex := 0;
  InitializeCriticalSection(g_ControlSessionCS);
  for I := 0 to Length(g_ControlSessionArray) - 1 do
  begin
    UserSession := @g_ControlSessionArray[I];
    UserSession.Socket := nil;
    UserSession.RecvText := '';
    UserSession.RecvTick := GetTickCount;
    UserSession.SendHeartbeatTick := GetTickCount;
    UserSession.IsPasswordOK := False;
    UserSession.DelayCloseTick := GetTickCount;
    UserSession.DelayClose := False;
    UserSession.MsgList := TLockStringList.Create;
  end;

  FProcessUserSessionThread := nil;
  SendGameCenterMsg(SG_STARTNOW, '正在启动日志服务器...');
  LogMsgList := TStringList.Create;
  TempLogMsgList := TStringList.Create;
  InitializeCriticalSection(FCS);
  StartTimer.Enabled := True;

  g_SearchManager := TSearchManager.Create(1);
end;

procedure TFrmLogData.FormDestroy(Sender: TObject);
var
  I: Integer;
  UserSession: PControlSessionInfo;
begin
  tmr1.Enabled := False;
  
  if FProcessUserSessionThread <> nil then
  begin
    FProcessUserSessionThread.Terminate;
    FProcessUserSessionThread.WaitFor;
    FProcessUserSessionThread.Free;
  end;

  if (FFileHandle <> INVALID_HANDLE_VALUE) then
  begin
    CloseHandle(FFileHandle);
  end;

  for I := 0 to Length(g_ControlSessionArray) - 1 do
  begin
    UserSession := @g_ControlSessionArray[I];
    UserSession.Socket := nil;
    UserSession.RecvText := '';
    UserSession.RecvTick := GetTickCount;
    UserSession.SendHeartbeatTick := GetTickCount;
    UserSession.IsPasswordOK := False;
    UserSession.DelayCloseTick := GetTickCount;
    UserSession.DelayClose := False;
    UserSession.MsgList.Free;
  end;

  DeleteCriticalSection(g_ControlSessionCS);

  DeleteCriticalSection(FCS);
  LogMsgList.Free;
  TempLogMsgList.Free;
  g_SearchManager.Free;
end;

procedure TFrmLogData.CloseTimerTimer(Sender: TObject);
begin
  //Caption := '正在关闭...';
  ShowMainLog('正在关闭...');
  g_SearchManager.CancelAndClearAllTask;
end;

procedure TFrmLogData.FormCloseQuery(Sender: TObject;
  var CanClose: Boolean);
begin
  if m_boRemoteClose then exit;
  if Application.MessageBox('是否确认退出服务器？',
    '提示信息',
    MB_YESNO + MB_ICONQUESTION) = IDYES then begin
    m_boRemoteClose := True;
    CloseTimer.Enabled := True;
  end else CanClose := False;
end;

procedure TFrmLogData.Timer1Timer(Sender: TObject);
begin
  try
    WriteLogFile();
  except
    on E: Exception do
    begin
      ShowMainLog(E.Message);
    end;
  end;
end;

procedure TFrmLogData.WriteLogFile();
var
  Year, Month, Day, Hour, Min, Sec, MSec: Word;
  sLogDir, sLogFile: string;
  //s2E8: string;

  sText: string;
  s01, s02, s03, s04, s05, s06, s07, s08, s09, s10, s11, s12, s13, s14, s15: string;
  B: Byte;
  N: Integer;
  Dt: TDateTime;
  Action: LongWord;

  P, P2: PByte;
  Len: Integer;
begin
  EnterCriticalSection(FCS);
  try
    if LogMsgList.Count <= 0 then exit;

    TempLogMsgList.AddStrings(LogMsgList);
    LogMsgList.Clear;
  finally
    LeaveCriticalSection(FCS);
  end;

  DecodeDate(Date, Year, Month, Day);
  DecodeTime(Time, Hour, Min, Sec, MSec); //ExtractFilePath(ParamStr(0)) +
  sLogDir := sBaseDir + IntToStr(Year) + '-' + IntToString(Month) + '-' + IntToString(Day);

  if not DirectoryExists(sLogDir) then
  begin
    ForceDirectories(sLogDir);
  end;

  sLogFile := sLogDir + '\Log-' + IntToString(Hour) + 'h' + IntToString((Min div 10) * 2) + 'm.nlf';
  statMain.Panels[0].Text := sLogFile;

  if not SameText(sLogFile, FLogFileName) then
  begin
    if (FFileHandle <> INVALID_HANDLE_VALUE) then
    begin
      CloseHandle(FFileHandle);
    end;

    FLogFileName := sLogFile;

    if not FileExists(FLogFileName) then
      FFileHandle := CreateFile(PChar(FLogFileName), GENERIC_WRITE, FILE_SHARE_READ, nil, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, 0)
    else
      FFileHandle := CreateFile(PChar(FLogFileName), GENERIC_WRITE, FILE_SHARE_READ, nil, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);

    FileSeek(FFileHandle, 0, soFromEnd);
  end
  else if (FFileHandle = INVALID_HANDLE_VALUE) then
  begin
    if (FFileHandle <> INVALID_HANDLE_VALUE) then
    begin
      CloseHandle(FFileHandle);
    end;
    
    if not FileExists(sLogFile) then
      FFileHandle := CreateFile(PChar(sLogFile), GENERIC_WRITE, FILE_SHARE_READ, nil, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, 0)
    else
      FFileHandle := CreateFile(PChar(sLogFile), GENERIC_WRITE, FILE_SHARE_READ, nil, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);

    FileSeek(FFileHandle, 0, soFromEnd);
  end;

  if (FFileHandle <> INVALID_HANDLE_VALUE) then begin
    P2 := @FBuffer[0];
    P := P2;

    while TempLogMsgList.Count > 0 do begin
      sText := TempLogMsgList.Strings[0];
      TempLogMsgList.Delete(0);

      sText := GetValidStr3_Ex(sText, s01, #9);
      sText := GetValidStr3_Ex(sText, s02, #9);
      sText := GetValidStr3_Ex(sText, s03, #9);
      sText := GetValidStr3_Ex(sText, s04, #9);
      sText := GetValidStr3_Ex(sText, s05, #9);
      sText := GetValidStr3_Ex(sText, s06, #9);
      sText := GetValidStr3_Ex(sText, s07, #9);
      sText := GetValidStr3_Ex(sText, s08, #9);
      sText := GetValidStr3_Ex(sText, s09, #9);
      sText := GetValidStr3_Ex(sText, s10, #9);
      sText := GetValidStr3_Ex(sText, s11, #9);
      sText := GetValidStr3_Ex(sText, s12, #9);
      sText := GetValidStr3_Ex(sText, s13, #9);
      sText := GetValidStr3_Ex(sText, s14, #9);
      sText := GetValidStr3_Ex(sText, s15, #9);

      Action := StrToIntDef(S04, 0);
      if Action = 0 then Continue;

      N := StrToIntDef(S02, 0);     // nServerNumber
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := StrToIntDef(S03, 0);     // nServerIndex
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := Action;                  // nAction
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := Length(S05);             // sMapName
      if N >= 200 then N := 200;

      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));
      if N > 0 then
      begin
        Move(S05[1], P^, N);
        Inc(P, N);
      end;

      N := StrToIntDef(S06, -1);    // nMapX
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := StrToIntDef(S07, -1);    // nMapY
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := Length(S08);             // sObjectName
      if N >= 200 then N := 200;

      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));
      if N > 0 then
      begin
        Move(S08[1], P^, N);
        Inc(P, N);
      end;

      B := StrToIntDef(S09, 0);     // ActorType
      if (B < Integer(Low(TLogActorType))) or (B > Integer(High(TLogActorType))) then
      begin
        B := Integer(latNone);
      end;
      Move(B, P^, SizeOf(B));
      Inc(P, SizeOf(B));

      N := Length(S10);             // sItemName
      if N >= 200 then N := 200;

      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));
      if N > 0 then
      begin
        Move(S10[1], P^, N);
        Inc(P, N);
      end;

      N := StrToIntDef(S11, -1);    // nItemIndex
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := Length(S12);             // sActObjectName
      if N >= 200 then N := 200;
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));
      if N > 0 then
      begin
        Move(S12[1], P^, N);
        Inc(P, N);
      end;

      N := StrToIntDef(S13, -1);    // nData1
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := StrToIntDef(S14, -1);    // nData2
      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));

      N := Length(S15);             // sLogDesc
      if N >= 200 then N := 200;

      Move(N, P^, SizeOf(N));
      Inc(P, SizeOf(N));
      if N > 0 then
      begin
        Move(S15[1], P^, N);
        Inc(P, N);
      end;

      Dt := Now;                    // LogDataTime
      Move(Dt, P^, SizeOf(Dt));
      Inc(P, SizeOf(Dt));

      Len := Integer(P) - Integer(P2);

      if Len >= SizeOf(FBuffer) - 2000 then
      begin
        FileWrite(FFileHandle, FBuffer[0], Len);
        P2 := @FBuffer[0];
        P := P2;
      end;
    end;

    Len := Integer(P) - Integer(P2);
    if Len >= 0 then begin
      FileWrite(FFileHandle, FBuffer[0], Len);
      //P2 := @FBuffer[0];
      //P := P2;
    end;
    
  end;
end;

procedure TFrmLogData.MyMessage(var MsgData: TWmCopyData);
var
  sData: string;
  //ProgramType: TProgamType;
  wIdent: Word;
begin
  wIdent := HiWord(MsgData.From);
  //  ProgramType:=TProgamType(LoWord(MsgData.From));
  sData := StrPas(MsgData.CopyDataStruct^.lpData);
  case wIdent of //
    GS_QUIT: begin
        m_boRemoteClose := True;
        CloseTimer.Enabled := True;
        Close();
      end;
    1: ;
    2: ;
    3: ;
  end; // case
end;

procedure TFrmLogData.StartTimerTimer(Sender: TObject);
var
  Conf: TIniFile;
  //boMinimize: Boolean;
begin
  StartTimer.Enabled := False;
  Conf := TIniFile.Create('.\LogData.ini');
  if Conf <> nil then begin
    sBaseDir := Conf.ReadString('Setup', 'BaseDir', sBaseDir);
    sServerName := Conf.ReadString('Setup', 'Caption', sServerName);
    sServerName := Conf.ReadString('Setup', 'ServerName', sServerName);
    nServerPort := Conf.ReadInteger('Setup', 'Port', nServerPort);

    g_nControlPort := Conf.ReadInteger('Setup', 'ControlPort', g_nControlPort);
    g_sControlPassword := Conf.ReadString('Setup', 'ControlPassword', g_sControlPassword);

    Conf.Free;
  end;

  if sServerName <> '' then begin
      Caption := Format('%s - [%s]', [sCaption, sServerName]);
  end else begin
      Caption := sCaption;
  end;
  
  ShowMainLog('日志服务正在启动...');
  IdUDPServerLog.DefaultPort := nServerPort;
  try
    IdUDPServerLog.Active := True;
    SendGameCenterMsg(SG_STARTOK, '日志服务器启动完成...');
    ShowMainLog('日志服务器启动完成...');
  except
    on E: Exception do
    begin
      ShowMainLog('日志服务器启动失败; ' + E.Message);
    end;
  end;

  if (g_nControlPort > 0) then
  begin
    ShowMainLog('远程查询端口[' + IntToStr(g_nControlPort) + ']正在启动...');
    srvrsckt1.Address := '0.0.0.0';
    srvrsckt1.Port := g_nControlPort;
    try
      srvrsckt1.Active := True;
      ShowMainLog('远程查询端口[' + IntToStr(g_nControlPort) + ']启动完成...');

      FProcessUserSessionThread := TProcessUserSessionThread.Create(False);
      FProcessUserSessionThread.FreeOnTerminate := False;
    except
      on E: Exception do
      begin
        ShowMainLog('远程查询端口[' + IntToStr(g_nControlPort) + ']启动失败; ' + E.Message);
      end;
    end;
  end;
end;

(*
procedure TFrmLogData.IdUDPServerLogUDPRead(Sender: TObject;
  AData: TStream; ABinding: TIdSocketHandle);
var
  LogStr: string;
begin
  EnterCriticalSection(FCS);
  try
    try
      SetLength(LogStr, AData.Size);
      AData.Read(LogStr[1], AData.Size);
      LogMsgList.Add(LogStr);
    except
      on E: Exception do
      begin
        ShowMainLog(E.Message);
      end;
    end;
  finally
    LeaveCriticalSection(FCS);
  end;
end;
*)

procedure TFrmLogData.IdUDPServerLogUDPRead(Sender: TObject; AData: TBytes; ABinding: TIdSocketHandle);
var
  LogStr: string;
begin
  EnterCriticalSection(FCS);
  try
    try
      SetLength(LogStr, Length(AData));
      //AData.Read(LogStr[1], AData.Size);
      CopyMemory(@LogStr[1], @AData[0], Length(AData));
      LogMsgList.Add(LogStr);
    except
      on E: Exception do
      begin
        ShowMainLog(E.Message);
      end;
    end;
  finally
    LeaveCriticalSection(FCS);
  end;
end;

procedure TFrmLogData.WMSetParentWindow(var Message: TMessage);
begin
  if Message.WParam = 1 then begin
    Windows.SetParent(Handle, Message.LParam);
    SetWindowLong(Application.Handle, GWL_EXSTYLE, GetWindowLong(Application.Handle, GWL_EXSTYLE) or WS_EX_TOOLWINDOW);
    FIsEmbeddedGameCenter := True;
    Self.Hide;
    Self.Show;
  end else begin
    Windows.SetParent(Handle, 0);
    SetWindowLong(Application.Handle, GWL_EXSTYLE, GetWindowLong(Application.Handle, GWL_EXSTYLE) and (not WS_EX_TOOLWINDOW));
    FIsEmbeddedGameCenter := False;
  end;
end;

procedure TFrmLogData.WMSysCommand(var Message: TWMSysCommand);
const
  GWW_HWNDPARENT = -8;
begin
  if FIsEmbeddedGameCenter and (Message.CmdType and $FFF0 = SC_MINIMIZE) then begin
    DefaultHandler(Message);
  end else begin
    inherited;
  end;
end;

procedure TFrmLogData.OnAppModalBegin(Sender: TObject);
begin
  if FIsEmbeddedGameCenter then
  begin
    Enabled := False;
  end;
end;

procedure TFrmLogData.OnAppOnModalEnd(Sender: TObject);
begin
  if FIsEmbeddedGameCenter then
  begin
    Enabled := True;
  end;
end;

procedure TFrmLogData.N1Click(Sender: TObject);
begin
  FrmLogManage.Show;
end;

procedure TFrmLogData.ShowMainLog(S: string; IsAddDateTime: Boolean);
begin
  if mmoLog.Lines.Count > 100 then
    mmoLog.Clear;

  if IsAddDateTime then
    S := '[' + FormatDateTime('hh:nn:ss', Now) + ']' + S;
  mmoLog.Lines.Add(S);
end;

procedure TFrmLogData.N3Click(Sender: TObject);
begin
  ShowFrmRemoteQuerySetting;
end;

procedure TFrmLogData.srvrsckt1Accept(Sender: TObject;
  Socket: TCustomWinSocket);
var
  RemoteAddr: string;
  IsPassIP: Boolean;
begin
  RemoteAddr := Socket.RemoteAddress;

  g_ControlIPList.Lock;
  try
    if g_ControlIPList.Count = 0 then
    begin
      IsPassIP := True;
    end
    else
    begin
      IsPassIP := g_ControlIPList.IndexOf(RemoteAddr) >= 0;
    end;
  finally
    g_ControlIPList.UnLock;
  end;

  if not IsPassIP then
  begin
    ShowMainLog('远程控制过滤连接: ' + RemoteAddr);
    Socket.Close;
  end;
end;

procedure TFrmLogData.srvrsckt1ClientConnect(Sender: TObject;
  Socket: TCustomWinSocket);
var
  I: Integer;
  UserSession: PControlSessionInfo;
begin
  Socket.nIndex := -1;
  EnterCriticalSection(g_ControlSessionCS);
  try
    for I := FControlIndex to Length(g_ControlSessionArray) - 1 do
    begin
      UserSession := @g_ControlSessionArray[I];
      if UserSession.Socket = nil then
      begin
        UserSession.Socket := Socket;
        UserSession.ConnectTick := GetTickCount;
        UserSession.RecvText := '';
        UserSession.RecvTick := GetTickCount;
        UserSession.SendHeartbeatTick := GetTickCount;
        UserSession.IsPasswordOK := False;
        UserSession.DelayCloseTick := GetTickCount;
        UserSession.DelayClose := False;
        UserSession.IsRunning := False;

        UserSession.MsgList.Lock;
        try
          UserSession.MsgList.Clear;
        finally
          UserSession.MsgList.UnLock;
        end;

        Socket.nIndex := I;
        ShowMainLog('远程控制开始连接: ' + Socket.RemoteAddress);

        FControlIndex := I + 1;
        Exit;
      end;
    end;

    for I := 0 to Length(g_ControlSessionArray) - 1 do
    begin
      UserSession := @g_ControlSessionArray[I];
      if UserSession.Socket = nil then
      begin
        UserSession.Socket := Socket;
        UserSession.ConnectTick := GetTickCount;
        UserSession.RecvText := '';
        UserSession.RecvTick := GetTickCount;
        UserSession.SendHeartbeatTick := GetTickCount;
        UserSession.IsPasswordOK := False;
        UserSession.DelayCloseTick := GetTickCount;
        UserSession.DelayClose := False;
        UserSession.IsRunning := False;

        UserSession.MsgList.Lock;
        try
          UserSession.MsgList.Clear;
        finally
          UserSession.MsgList.UnLock;
        end;

        Socket.nIndex := I;
        ShowMainLog('远程控制开始连接: ' + Socket.RemoteAddress);

        FControlIndex := I + 1;
        Exit;
      end;
    end;
  finally
    LeaveCriticalSection(g_ControlSessionCS);
  end;

  ShowMainLog('远程控制数量已满: ' + Socket.RemoteAddress);
  Socket.Close;
end;

procedure TFrmLogData.srvrsckt1ClientDisconnect(Sender: TObject;
  Socket: TCustomWinSocket);
var
  nSockIndex: Integer;
  UserSession: PControlSessionInfo;
begin
  nSockIndex := Socket.nIndex;

  EnterCriticalSection(g_ControlSessionCS);
  try
    if (nSockIndex >= 0) and (nSockIndex < Length(g_ControlSessionArray)) then
    begin
      UserSession := @g_ControlSessionArray[nSockIndex];
      UserSession.Socket := nil;
      UserSession.RecvText := '';
      UserSession.RecvTick := GetTickCount;
      UserSession.SendHeartbeatTick := GetTickCount;
      UserSession.IsPasswordOK := False;
      UserSession.DelayCloseTick := GetTickCount;
      UserSession.DelayClose := False;
      UserSession.IsRunning := False;

      UserSession.MsgList.Lock;
      try
        UserSession.MsgList.Clear;
      finally
        UserSession.MsgList.UnLock;
      end;

      ShowMainLog('远程控制断开连接: ' + Socket.RemoteAddress);

      Socket.nIndex := -1;
    end;
  finally
    LeaveCriticalSection(g_ControlSessionCS);
  end;
end;

procedure TFrmLogData.srvrsckt1ClientError(Sender: TObject;
  Socket: TCustomWinSocket; ErrorEvent: TErrorEvent;
  var ErrorCode: Integer);
begin
  ErrorCode := 0;
  Socket.Close;
end;

procedure TFrmLogData.srvrsckt1ClientRead(Sender: TObject; Socket: TCustomWinSocket);
var
  {I, nCount,} nSockIndex: Integer;
  UserSession: PControlSessionInfo;
  ControlMsgHeader: PControlMsgHeader;
  dwCmd: LongWord;
  sData: string;
begin
  nSockIndex := Socket.nIndex;
  if (nSockIndex >= 0) and (nSockIndex < Length(g_ControlSessionArray)) then
  begin
    UserSession := @g_ControlSessionArray[nSockIndex];
    UserSession.RecvText := UserSession.RecvText + Socket.ReceiveText;
    UserSession.RecvTick := GetTickCount;

    while Length(UserSession.RecvText) >= SizeOf(TControlMsgHeader) do
    begin
      ControlMsgHeader := @UserSession.RecvText[1];
      if ControlMsgHeader.dwCode <> ControlMsgHeaderIdent then
      begin
        UserSession.RecvText := '';
        Break;
      end;

      if Length(UserSession.RecvText) < SizeOf(TControlMsgHeader) + ControlMsgHeader.nLength then Break;

      if ControlMsgHeader.nLength = 0 then
        sData := ''
      else
        sData := Copy(UserSession.RecvText, SizeOf(TControlMsgHeader) + 1, ControlMsgHeader.nLength);

      UserSession.RecvText := Copy(UserSession.RecvText, SizeOf(TControlMsgHeader) + ControlMsgHeader.nLength + 1, MaxInt);

      case ControlMsgHeader.dwCmd of
        CMSG_CHECK_PASSWORD:
          begin
            if SameText(sData, MD5Print(MD5String(g_sControlPassword))) then
            begin
              dwCmd := SMSG_CHECK_PASSWORD_OK;
              UserSession.IsPasswordOK := True;
            end
            else
            begin
              dwCmd := SMSG_CHECK_PASSWORD_FAIL;
              UserSession.DelayCloseTick := GetTickCount + 1000;
              UserSession.DelayClose := True;
            end;
            SendControlMsg(Socket, dwCmd, nil, 0);
          end;
        CMSG_SEARCH_LOG:
          begin
            if UserSession.IsPasswordOK and (ControlMsgHeader.nLength > 0) then
            begin
              UserSession.IsRunning := True;
              
              UserSession.MsgList.Lock;
              try
                UserSession.MsgList.AddObject(sData, TObject(ControlMsgHeader.dwCmd));
              finally
                UserSession.MsgList.UnLock;
              end;
            end;
          end;
        CMSG_HEARTBEAT:
          begin
            // 心跳包不处理
          end;
      end;
    end;
  end;
end;


procedure TFrmLogData.tmr1Timer(Sender: TObject);
var
  I: Integer;
  UserSession: PControlSessionInfo;
begin
  EnterCriticalSection(g_ControlSessionCS);
  try
    for I := 0 to Length(g_ControlSessionArray) - 1 do
    begin
      UserSession := @g_ControlSessionArray[I];

      if UserSession.Socket <> nil then
      begin
        if (tick_diff(UserSession.ConnectTick, GetTickCount) >= 5000) and (not UserSession.IsPasswordOK) then
        begin
          UserSession.ConnectTick := GetTickCount;
          UserSession.Socket.Close;
        end
        else if UserSession.DelayClose and (tick_diff(UserSession.DelayCloseTick, GetTickCount) >= 0) then
        begin
          UserSession.ConnectTick := GetTickCount;
          UserSession.Socket.Close;
        end
        else if tick_diff(UserSession.RecvTick, GetTickCount) >= 120000 then     // 120秒钟没有收到数据包，连接超时，断开
        begin
          UserSession.ConnectTick := GetTickCount;
          UserSession.Socket.Close;
        end
        else if tick_diff(UserSession.RecvTick, GetTickCount) >= 60000 then     // 60秒钟没有收到数据包，发一个包过去
        begin
          if tick_diff(UserSession.SendHeartbeatTick, GetTickCount) >= 50000 then
          begin
            UserSession.SendHeartbeatTick := GetTickCount;
            SendControlMsg(UserSession.Socket, SMSG_HEARTBEAT, nil, 0);
          end;
        end;
      end;
    end;
  finally
    LeaveCriticalSection(g_ControlSessionCS);
  end;
end;

end.

