// Source unit: Source/M2Engine/MySqlAuctionDB.pas
// Generated by _recon/p3-sql.mjs + p3-gen.mjs from the GBK source (see docs/并行报告-p3-m2-dbdata.md).
// Every value is the verbatim SQL text the driver receives on this dialect, after Delphi
// "' + '" concatenation; doubled quotes are preserved exactly.  Do NOT hand-edit.

namespace GXX.M2Server.DbLayer;

/// <summary>MySqlAuctionDB.pas 的全部 <c>AddSQLStatement</c> 语句逐字 SQL（顺序 = 原文 DoInit 顺序）。</summary>
public static class MySqlAuctionDbStatements
{
    /// <summary>MySqlAuctionDB.pas:181-182 — field FStatementUpdateAuctionItemFail，label 'Auction_UpdateAuctionItemFail'。</summary>
    public const string Auction_UpdateAuctionItemFail = "update AuctionData set TradingStatus = 1 where (length(ifnull(LastBidder, '')) = 0) and (ifnull(TradingStatus, 0) = 0) and (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(AddDateTime, interval AuctionTime hour)) <= 0);";

    /// <summary>MySqlAuctionDB.pas:185-185 — field FStatementUpdateAuctionItemSuccess，label 'Auction_UpdateAuctionItemSuccess'。</summary>
    public const string Auction_UpdateAuctionItemSuccess = "update AuctionData set TradingStatus = 2 where AuctionID = ?;";

    /// <summary>MySqlAuctionDB.pas:188-191 — field FStatementQueryAuctionItemSuccess，label 'Auction_QueryAuctionItemSuccess'。</summary>
    public const string Auction_QueryAuctionItemSuccess = "select A.AuctionID, A.HumanName, A.CurrencyType, A.StartingPrice, A.SellingPrice, A.LastBidder, A.LastBidPrice, B.DBIndex, B.MakeIndex from AuctionData A, Items B  where (A.AuctionID = B.ParentID) and (B.ItemType = 5) and  (length(ifnull(A.LastBidder, '')) > 0) and (ifnull(A.TradingStatus, 0) = 0) and (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(A.AddDateTime, interval A.AuctionTime hour)) <= 0);";

    /// <summary>MySqlAuctionDB.pas:195-198 — field FStatementQueryMyItems，label 'Auction_QueryAuctionItems'。</summary>
    public const string Auction_QueryAuctionItems = "select AuctionID, HumanName, AddDateTime, AuctionTime, (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(AddDateTime, interval AuctionTime hour))) as TimeLeft, StartingPrice, SellingPrice, CurrencyType, LastBidPrice, LastBidder, TradingStatus, IsItemGive from AuctionData where HumanName = ? order by auctionid desc limit ? offset ?;";

    /// <summary>MySqlAuctionDB.pas:202-202 — field FStatementGetMyItemsCount，label 'Auction_GetMyItemsCount'。</summary>
    public const string Auction_GetMyItemsCount = "select Count(*) from AuctionData where HumanName = ?;";

    /// <summary>MySqlAuctionDB.pas:206-207 — field FStatementQueryMyAttentionItems，label 'Auction_QueryAttentionItems'。</summary>
    public const string Auction_QueryAttentionItems = "select AuctionID from AuctionAttention where HumanName = ? order by Time desc limit ? offset ?;";

    /// <summary>MySqlAuctionDB.pas:211-211 — field FStatementQueryMyAttentionItemsCount，label 'Auction_GetMyAttentionItemsCount'。</summary>
    public const string Auction_GetMyAttentionItemsCount = "select Count(*) from AuctionAttention where HumanName = ?;";

    /// <summary>MySqlAuctionDB.pas:215-218 — field FStatementQueryOneItem，label 'Auction_QueryOneItem'。</summary>
    public const string Auction_QueryOneItem = "select HumanName, AddDateTime, AuctionTime, (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(AddDateTime, interval AuctionTime hour))) as TimeLeft, StartingPrice, SellingPrice, CurrencyType, LastBidPrice, LastBidder, TradingStatus, IsItemGive from AuctionData where AuctionID = ?;";

    /// <summary>MySqlAuctionDB.pas:222-223 — field FStatementGetMyAuctioningItemsCount，label 'Auction_GetMyAuctioningItemsCount'。</summary>
    public const string Auction_GetMyAuctioningItemsCount = "select Count(*) from AuctionData where HumanName = ? and (ifnull(TradingStatus, 0) = 0) and (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(AddDateTime, interval AuctionTime hour)) > 0);";

    /// <summary>MySqlAuctionDB.pas:227-228 — field FStatementGetMySellFailItemsCount，label 'Auction_GetMySellFailItemsCount'。</summary>
    public const string Auction_GetMySellFailItemsCount = "select Count(*) from AuctionData where HumanName = ? and IsItemGive = 0 and ((length(ifnull(LastBidder, '')) = 0) and (ifnull(TradingStatus, 0) = 0) and (TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP, date_add(AddDateTime, interval AuctionTime hour)) <= 0) or (ifnull(TradingStatus, 0) = 1))";

    /// <summary>MySqlAuctionDB.pas:232-233 — field FStatementGetMyBuyOKItemsCount，label 'Auction_GetMyBuyOKItemsCount'。</summary>
    public const string Auction_GetMyBuyOKItemsCount = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 2) and IsItemGive = 0 and LastBidder = ?";

    /// <summary>MySqlAuctionDB.pas:236-236 — field FStatementGetMaxAuctionID，label 'Auction_GetMaxAuctionID'。</summary>
    public const string Auction_GetMaxAuctionID = "select ifnull(Max(AuctionID), 0) + 1 from AuctionData";

    /// <summary>MySqlAuctionDB.pas:240-242 — field FStatementInsertAuctionItem，label 'Auction_InsertAuctionItem'。</summary>
    public const string Auction_InsertAuctionItem = "insert into AuctionData(AuctionID, HumanName, ItemGroup, ItemColor, AuctionTime, StartingPrice, SellingPrice, CurrencyType, ItemDBName,ItemName) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlAuctionDB.pas:246-247 — field FStatementJoinItemBid，label 'Auction_JoinItemBid'。</summary>
    public const string Auction_JoinItemBid = "UPDATE AuctionData set LastBidder = ?, LastBidPrice = ?, LastBidTime = CURRENT_TIMESTAMP where AuctionID = ?";

    /// <summary>MySqlAuctionDB.pas:251-252 — field FStatementBuyItem，label 'Auction_BuyItem'。</summary>
    public const string Auction_BuyItem = "UPDATE AuctionData set LastBidder = ?, LastBidPrice = ?, LastBidTime = CURRENT_TIMESTAMP, TradingStatus = 2 where AuctionID = ?";

    /// <summary>MySqlAuctionDB.pas:256-257 — field FStatementInsertAttentionItem，label 'Auction_AddAttentionItem'。</summary>
    public const string Auction_AddAttentionItem = "INSERT INTO AuctionAttention(HumanName, AuctionID) values(?, ?);";

    /// <summary>MySqlAuctionDB.pas:259-259 — field FStatementCheckInAttentionItem，label 'Auction_CheckInAttentionItem'。</summary>
    public const string Auction_CheckInAttentionItem = "SELECT 1 FROM AuctionAttention where HumanName = ? and AuctionID = ?;";

    /// <summary>MySqlAuctionDB.pas:263-263 — field FStatementDeleteAttentionItem，label 'Auction_DeleteAuctionItem'。</summary>
    public const string Auction_DeleteAuctionItem = "delete from AuctionAttention where HumanName = ? and AuctionID = ?";

    /// <summary>MySqlAuctionDB.pas:266-266 — field FStatementAuctionDataHumanRename，label 'Auction_HumanRename'。</summary>
    public const string Auction_HumanRename = "update AuctionData set HumanName = ? where HumanName = ?";

    /// <summary>MySqlAuctionDB.pas:269-269 — field FStatementAuctionDataLastBidderRename，label 'Auction_LastBidderRename'。</summary>
    public const string Auction_LastBidderRename = "update AuctionData set LastBidder = ? where LastBidder = ?";

    /// <summary>MySqlAuctionDB.pas:272-272 — field FStatementAuctionAttentionRename，label 'Auction_AttentionRename'。</summary>
    public const string Auction_AttentionRename = "update AuctionAttention set HumanName = ? where HumanName = ?";

}