// Source unit: Source/M2Engine/SqliteAuctionDB.pas
// Generated by _recon/p3-sql.mjs + p3-gen.mjs — method-level SQL scripts (migration DDL and
// dynamic SQL templates).  Verbatim after Delphi "' + '" concatenation; `sLineBreak` is
// Delphi 7 SysUtils on Windows = #13#10, rendered as \r\n.  Do NOT hand-edit.

namespace GXX.M2Server.DbLayer;

/// <summary>SqliteAuctionDB.pas 方法级 SQL 脚本 / 动态 SQL 模板（逐字）。</summary>
public static class SqliteAuctionDbScripts
{
    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #0）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P0 = "DELETE FROM ItemElementAdd";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #1 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P1 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #2）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P2 = "\r\nDELETE FROM ItemAddDataByte";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #3 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P3 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #4）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P4 = "\r\nDELETE FROM ItemAddDataInt";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #5 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P5 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #6）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P6 = "\r\nDELETE FROM ItemAddDataText";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #7 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P7 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #8）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P8 = "\r\nDELETE FROM ItemFlute";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #9 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P9 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #10）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P10 = "\r\nDELETE FROM ItemProgress";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #11 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P11 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #12）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P12 = "\r\nDELETE FROM ItemProperty";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #13 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P13 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #14）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P14 = "\r\nDELETE FROM ItemValueAdd";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #15 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P15 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #16）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P16 = "\r\nDELETE FROM Items";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #17 → sWhere）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P17 = "@@sWhere@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #18）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P18 = "\r\nDELETE FROM AuctionAttention WHERE AuctionID = ";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #19 → IntToStr(AuctionID)）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P19 = "@@IntToStr(AuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #20）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P20 = ";\r\nDELETE FROM AuctionData WHERE AuctionID = ";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（runtime value #21 → IntToStr(AuctionID)）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P21 = "@@IntToStr(AuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:635-640 — TSqliteAuctionDB.DoDeleteAuctionItem <c>Sql</c>（literal run #22）。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_P22 = ";\r\n";

    /// <summary>SqliteAuctionDB.pas:635-640 的运行时值个数（拼接点顺序）。</summary>
    public const int DoDeleteAuctionItem_L635_Sql_RuntimeValueCount = 11;

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>sWhere</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_sWhere = "@@sWhere@@";

    /// <summary>拼接点运行时值：<c>IntToStr(AuctionID)</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_IntToStr_AuctionID_ = "@@IntToStr(AuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(AuctionID)</c>。</summary>
    public const string DoDeleteAuctionItem_L635_Sql_RuntimeValue_IntToStr_AuctionID_ = "@@IntToStr(AuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:775-781 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L775_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:775-781 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L775_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:775-781 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L775_sm_Sql_P2 = ") ";

    /// <summary>SqliteAuctionDB.pas:775-781 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L775_sm_Sql_RuntimeValueCount = 1;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L775_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:785-785 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:785-785 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:785-785 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:785-785 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:785-785 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_P4 = ")";

    /// <summary>SqliteAuctionDB.pas:785-785 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L785_sm_Sql_RuntimeValueCount = 2;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L785_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P4 = ") and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #5 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P5 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:822-822 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_P6 = ")";

    /// <summary>SqliteAuctionDB.pas:822-822 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L822_sm_Sql_RuntimeValueCount = 3;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoQueryAllItems_L822_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P4 = ") and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #5 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P5 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P6 = ") and A.CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:828-828 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #7 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_P7 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:828-828 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L828_sm_Sql_RuntimeValueCount = 4;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoQueryAllItems_L828_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P4 = ") and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #5 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P5 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P6 = ") and A.CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #7 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P7 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #8）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P8 = " and A.SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:833-833 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #9 → IntToStr(MinPrices)）。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_P9 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:833-833 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L833_sm_Sql_RuntimeValueCount = 5;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoQueryAllItems_L833_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P4 = ") and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #5 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P5 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P6 = ") and A.CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #7 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P7 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #8）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P8 = " and A.SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #9 → IntToStr(MinPrices)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P9 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #10）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P10 = " and A.SellingPrice <= ";

    /// <summary>SqliteAuctionDB.pas:838-838 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #11 → IntToStr(MaxPrices)）。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_P11 = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:838-838 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L838_sm_Sql_RuntimeValueCount = 6;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MaxPrices)</c>。</summary>
    public const string DoQueryAllItems_L838_sm_Sql_RuntimeValue_IntToStr_MaxPrices_ = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P0 = "select A.AuctionID, A.HumanName, A.AddDateTime, A.AuctionTime, ((A.AddDateTime + A.AuctionTime * 3600) - strftime(\"%s\", \"now\")) as TimeLeft, A.StartingPrice, A.SellingPrice, A.CurrencyType, A.LastBidPrice, A.LastBidder, A.TradingStatus, A.IsItemGive, ifnull((select 1 from AuctionAttention where AuctionID = A.AuctionID and HumanName = ?), 0) as IsAttention from AuctionData A where (ifnull(A.TradingStatus, 0) = 0) and ((A.AddDateTime + A.AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and (A.AuctionID <> ";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #1 → IntToStr(TopmostAuctionID)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P1 = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P2 = ")  and (ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #3 → IntToStr(ItemGroup)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P3 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P4 = ") and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #5 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P5 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P6 = ") and A.CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #7 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P7 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #8）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P8 = " and A.SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #9 → IntToStr(MinPrices)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P9 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #10）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P10 = " and A.SellingPrice <= ";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #11 → IntToStr(MaxPrices)）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P11 = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #12）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P12 = " and ((A.ItemDBName like \"%";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #13 → ItemName）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P13 = "@@ItemName@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #14）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P14 = "%\") or (A.ItemName like \"%";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（runtime value #15 → ItemName）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P15 = "@@ItemName@@";

    /// <summary>SqliteAuctionDB.pas:843-843 — TSqliteAuctionDB.DoQueryAllItems <c>sm.Sql</c>（literal run #16）。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_P16 = "%\"))";

    /// <summary>SqliteAuctionDB.pas:843-843 的运行时值个数（拼接点顺序）。</summary>
    public const int DoQueryAllItems_L843_sm_Sql_RuntimeValueCount = 8;

    /// <summary>拼接点运行时值：<c>IntToStr(TopmostAuctionID)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_IntToStr_TopmostAuctionID_ = "@@IntToStr(TopmostAuctionID)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MaxPrices)</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_IntToStr_MaxPrices_ = "@@IntToStr(MaxPrices)@@";

    /// <summary>拼接点运行时值：<c>ItemName</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_ItemName = "@@ItemName@@";

    /// <summary>拼接点运行时值：<c>ItemName</c>。</summary>
    public const string DoQueryAllItems_L843_sm_Sql_RuntimeValue_ItemName = "@@ItemName@@";

    /// <summary>SqliteAuctionDB.pas:869-869 — TSqliteAuctionDB.DoQueryAllItems <c>sOrderBy</c>。</summary>
    public const string DoQueryAllItems_L869_sOrderBy = " order by AuctionID desc";

    /// <summary>SqliteAuctionDB.pas:1103-1104 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>。</summary>
    public const string DoGetAllItemsPageCount_L1103_sm_Sql = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0)";

    /// <summary>SqliteAuctionDB.pas:1108-1108 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1108_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1108-1108 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1108_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1108-1108 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1108_sm_Sql_RuntimeValueCount = 1;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1108_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1145-1145 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1145-1145 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1145-1145 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_P2 = " and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:1145-1145 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #3 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_P3 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1145-1145 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_P4 = ")";

    /// <summary>SqliteAuctionDB.pas:1145-1145 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1145_sm_Sql_RuntimeValueCount = 2;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1145_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P2 = " and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #3 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P3 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P4 = ") and CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:1151-1151 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #5 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_P5 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1151-1151 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1151_sm_Sql_RuntimeValueCount = 3;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1151_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P2 = " and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #3 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P3 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P4 = ") and CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #5 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P5 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P6 = " and SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:1156-1156 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #7 → IntToStr(MinPrices)）。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_P7 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1156-1156 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1156_sm_Sql_RuntimeValueCount = 4;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1156_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P2 = " and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #3 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P3 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P4 = ") and CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #5 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P5 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P6 = " and SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #7 → IntToStr(MinPrices)）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P7 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #8）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P8 = " and SellingPrice <= ";

    /// <summary>SqliteAuctionDB.pas:1161-1161 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #9 → IntToStr(MaxPrices)）。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_P9 = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1161-1161 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValueCount = 5;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MaxPrices)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1161_sm_Sql_RuntimeValue_IntToStr_MaxPrices_ = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #0）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P0 = "select Count(*) from AuctionData where (ifnull(TradingStatus, 0) = 0) and ((AddDateTime + AuctionTime * 3600) - (strftime(\"%s\", \"now\")) > 0) and ItemGroup = ";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #1 → IntToStr(ItemGroup)）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P1 = "@@IntToStr(ItemGroup)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #2）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P2 = " and ItemColor in (";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #3 → Copy(sColors, 1, Length(sColors) - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P3 = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #4）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P4 = ") and CurrencyType = ";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #5 → IntToStr(MoneyType - 1)）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P5 = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #6）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P6 = " and SellingPrice >= ";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #7 → IntToStr(MinPrices)）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P7 = "@@IntToStr(MinPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #8）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P8 = " and SellingPrice <= ";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #9 → IntToStr(MaxPrices)）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P9 = "@@IntToStr(MaxPrices)@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #10）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P10 = " and ((ItemDBName like \"%";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #11 → ItemName）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P11 = "@@ItemName@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #12）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P12 = "%\") or (ItemName like \"%";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（runtime value #13 → ItemName）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P13 = "@@ItemName@@";

    /// <summary>SqliteAuctionDB.pas:1166-1166 — TSqliteAuctionDB.DoGetAllItemsPageCount <c>sm.Sql</c>（literal run #14）。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_P14 = "%\"))";

    /// <summary>SqliteAuctionDB.pas:1166-1166 的运行时值个数（拼接点顺序）。</summary>
    public const int DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValueCount = 7;

    /// <summary>拼接点运行时值：<c>IntToStr(ItemGroup)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_IntToStr_ItemGroup_ = "@@IntToStr(ItemGroup)@@";

    /// <summary>拼接点运行时值：<c>Copy(sColors, 1, Length(sColors) - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_Copy_sColors__1__Length_sColors____1_ = "@@Copy(sColors, 1, Length(sColors) - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MoneyType - 1)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_IntToStr_MoneyType___1_ = "@@IntToStr(MoneyType - 1)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MinPrices)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_IntToStr_MinPrices_ = "@@IntToStr(MinPrices)@@";

    /// <summary>拼接点运行时值：<c>IntToStr(MaxPrices)</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_IntToStr_MaxPrices_ = "@@IntToStr(MaxPrices)@@";

    /// <summary>拼接点运行时值：<c>ItemName</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_ItemName = "@@ItemName@@";

    /// <summary>拼接点运行时值：<c>ItemName</c>。</summary>
    public const string DoGetAllItemsPageCount_L1166_sm_Sql_RuntimeValue_ItemName = "@@ItemName@@";

}