// Source unit: Source/M2Engine/MySqlM2DataDB.pas
// Generated by _recon/p3-sql.mjs + p3-gen.mjs from the GBK source (see docs/并行报告-p3-m2-dbdata.md).
// Every value is the verbatim SQL text the driver receives on this dialect, after Delphi
// "' + '" concatenation; doubled quotes are preserved exactly.  Do NOT hand-edit.

namespace GXX.M2Server.DbLayer;

/// <summary>MySqlM2DataDB.pas 的全部 <c>AddSQLStatement</c> 语句逐字 SQL（顺序 = 原文 DoInit 顺序）。</summary>
public static class MySqlM2DataDbStatements
{
    /// <summary>MySqlM2DataDB.pas:294-328 — field FStatementInsertItems，label 'InsertItems'。</summary>
    public const string InsertItems = "insert into Items(ParentID, ItemType, ItemIndex, MakeIndex, DBIndex, Name, Dura, DuraMax, HeroM2DressEffect, UpgradeCount, IsStartTime, LimitTime, HeroM2Light, Color, IsBind, BindOption, Effect, NewLooks, NewShape, FluteCount, PropertyText, PropertyTextColor, ItemFrom, ItemFromMap, ItemFromMon, ItemFromMaker, ItemFromDate, InsuranceCount, NewExpand3, NewExpand4 ) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:333-340 — field FStatementInsertItemValueAdd，label 'InsertItemValueAdd'。</summary>
    public const string InsertItemValueAdd = "insert into ItemValueAdd(ParentID, ItemType, ItemIndex, ValueIndex, Value) values(?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:344-351 — field FStatementInsertItemElementAdd，label 'InsertItemElementAdd'。</summary>
    public const string InsertItemElementAdd = "insert into ItemElementAdd(ParentID, ItemType, ItemIndex, ValueIndex, Value) values(?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:355-362 — field FStatementInsertItemAddDataByte，label 'InsertItemAddDataByte'。</summary>
    public const string InsertItemAddDataByte = "insert into ItemAddDataByte(ParentID, ItemType, ItemIndex, ValueIndex, Value) values(?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:366-373 — field FStatementInsertItemAddDataInt，label 'InsertItemAddDataInt'。</summary>
    public const string InsertItemAddDataInt = "insert into ItemAddDataInt(ParentID, ItemType, ItemIndex, ValueIndex, Value) values(?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:377-384 — field FStatementInsertItemAddDataText，label 'InsertItemAddDataText'。</summary>
    public const string InsertItemAddDataText = "insert into ItemAddDataText(ParentID, ItemType, ItemIndex, ValueIndex, Value) values(?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:388-396 — field FStatementInsertItemFlute，label 'InsertItemFlute'。</summary>
    public const string InsertItemFlute = "insert into ItemFlute(ParentID, ItemType, ItemIndex, ValueIndex, Value, OverlapCount) values(?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:400-414 — field FStatementInsertItemProgress，label 'InsertItemProgress'。</summary>
    public const string InsertItemProgress = "insert into ItemProgress(ParentID, ItemType, ItemIndex, ValueIndex, IsOpen, NameColor, Count, ShowType, Max, Value, Level, Name) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:418-432 — field FStatementInsertItemProperty，label 'InsertItemProperty'。</summary>
    public const string InsertItemProperty = "insert into ItemProperty(ParentID, ItemType, ItemIndex, ValueIndex, Color, BindType, ShowFlag, IsPercent, Hintmodule, Value, Value2, Value3) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlM2DataDB.pas:436-467 — field FStatementGetItems，label 'SelectItems'。</summary>
    public const string SelectItems = "select ItemIndex,MakeIndex,DBIndex,Name,Dura,DuraMax,HeroM2DressEffect,UpgradeCount,IsStartTime,LimitTime,HeroM2Light,Color,IsBind,BindOption,Effect,NewLooks,NewShape,FluteCount,PropertyText,PropertyTextColor,ItemFrom,ItemFromMap,ItemFromMon,ItemFromMaker,ItemFromDate,InsuranceCount, NewExpand3, NewExpand4 from Items where ParentID = ? and ItemType = ?;";

    /// <summary>MySqlM2DataDB.pas:471-502 — field FStatementGetItems_Sort，label 'SelectItems_Sort'。</summary>
    public const string SelectItems_Sort = "select ItemIndex,MakeIndex,DBIndex,Name,Dura,DuraMax,HeroM2DressEffect,UpgradeCount,IsStartTime,LimitTime,HeroM2Light,Color,IsBind,BindOption,Effect,NewLooks,NewShape,FluteCount,PropertyText,PropertyTextColor,ItemFrom,ItemFromMap,ItemFromMon,ItemFromMaker,ItemFromDate,InsuranceCount, NewExpand3, NewExpand4 from Items where ParentID = ? and ItemType = ? order by DBIndex;";

    /// <summary>MySqlM2DataDB.pas:507-537 — field FStatementGetItem，label 'SelectItem'。</summary>
    public const string SelectItem = "select MakeIndex,DBIndex,Name,Dura,DuraMax,HeroM2DressEffect,UpgradeCount,IsStartTime,LimitTime,HeroM2Light,Color,IsBind,BindOption,Effect,NewLooks,NewShape,FluteCount,PropertyText,PropertyTextColor,ItemFrom,ItemFromMap,ItemFromMon,ItemFromMaker,ItemFromDate,InsuranceCount, NewExpand3, NewExpand4 from Items where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:541-546 — field FStatementGetItemValueAdd，label 'SelectitemValueAdd'。</summary>
    public const string SelectitemValueAdd = "select ValueIndex,Value from ItemValueAdd where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:550-555 — field FStatementGetItemElementAdd，label 'SelectitemElementAdd'。</summary>
    public const string SelectitemElementAdd = "select ValueIndex,Value from ItemElementAdd where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:559-564 — field FStatementGetItemAddDataByte，label 'SelectitemAddDataByte'。</summary>
    public const string SelectitemAddDataByte = "select ValueIndex,Value from ItemAddDataByte where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:568-573 — field FStatementGetItemAddDataInt，label 'SelectitemAddDataInt'。</summary>
    public const string SelectitemAddDataInt = "select ValueIndex,Value from ItemAddDataInt where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:577-582 — field FStatementGetItemAddDataText，label 'SelectitemAddDataText'。</summary>
    public const string SelectitemAddDataText = "select ValueIndex,Value from ItemAddDataText where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:586-592 — field FStatementGetItemFlute，label 'SelectitemFlute'。</summary>
    public const string SelectitemFlute = "select ValueIndex,Value, OverlapCount from ItemFlute where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:596-608 — field FStatementGetItemProgress，label 'SelectItemProgress'。</summary>
    public const string SelectItemProgress = "select ValueIndex,IsOpen,NameColor,Count,ShowType,Max,Value,Level,Name from ItemProgress where ParentID = ? and ItemType = ? and ItemIndex = ?;";

    /// <summary>MySqlM2DataDB.pas:612-624 — field FStatementGetItemProperty，label 'SelectItemProperty'。</summary>
    public const string SelectItemProperty = "select ValueIndex,Color,BindType,ShowFlag,IsPercent,Hintmodule,Value,Value2,Value3 from ItemProperty where ParentID = ? and ItemType = ? and ItemIndex = ?;";

}