// Source unit: Source/M2Engine/SqliteUserShopDB.pas
// Generated by _recon/delphi-sql-extract.mjs + gen-statements.mjs from the GBK source:
// every value is the verbatim final SQL text after Delphi "' + '" concatenation.
// Delphi string-literal `''` is decoded to a single `'` (compile-time folding) — the SQL the
// driver receives, NOT the source spelling.  Do NOT hand-edit: regenerate and re-diff.
// (see docs/并行报告-p3-m2-dbdata.md for the quote-decoding fix)

namespace GXX.M2Server.DbLayer;

/// <summary>SqliteUserShopDB.pas method-level const block (shared SQL prefix/suffix), verbatim.</summary>
public static class SqliteUserShopDbSql
{
    /// <summary>SqliteUserShopDB.pas:205.</summary>
    public const string SGetShopItemQueryField = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID ";

    /// <summary>SqliteUserShopDB.pas:208.</summary>
    public const string SGetShopItemQueryField_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID ";

    /// <summary>SqliteUserShopDB.pas:213.</summary>
    public const string SGetShopItemQueryCount = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID ";

    /// <summary>SqliteUserShopDB.pas:214.</summary>
    public const string SGetShopItemWhere = " and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:218.</summary>
    public const string SGetAllShopQueryField = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?) ";

}

/// <summary>SqliteUserShopDB.pas 全部静态语句的逐字 SQL（顺序 = 原文 DoInit 顺序）。</summary>
public static class SqliteUserShopStatements
{
    /// <summary>SqliteUserShopDB.pas:232 — field FStatementUpdateAllBusiness.</summary>
    public const string UserShop_UpdateAllBusiness = "update UserShop set IsBusiness = 0;";

    /// <summary>SqliteUserShopDB.pas:237 — field FStatementUpdateHumanBusiness.</summary>
    public const string UserShop_UpdateHumanBusiness = "update UserShop set IsBusiness = ? where HumanName = ?;";

    /// <summary>SqliteUserShopDB.pas:241 — field FStatementHumanNameExists.</summary>
    public const string UserShop_CheckHumanNameExists = "select 1 FROM UserShop where HumanName = ?;";

    /// <summary>SqliteUserShopDB.pas:245 — field FStatementShopNameExists.</summary>
    public const string UserShop_CheckShopNameExists = "select 1 FROM UserShop where ShopName = ?;";

    /// <summary>SqliteUserShopDB.pas:249 — field FStatementInsertUserShop.</summary>
    public const string UserShop_InsertUserShop = "insert into UserShop(HumanName, ShopName, IsBusiness) values(?, ?, 1);";

    /// <summary>SqliteUserShopDB.pas:253 — field FStatementUserShopRename.</summary>
    public const string UserShop_UpdateShopName = "update UserShop set ShopName = ? where ShopID = ?;";

    /// <summary>SqliteUserShopDB.pas:257 — field FStatementUserShopRename2.</summary>
    public const string UserShop_UpdateShopName2 = "update UserShop set HumanName = ? where HumanName = ?";

    /// <summary>SqliteUserShopDB.pas:261 — field FStatementShopItemBuyerRenameName.</summary>
    public const string UserShop_ShopItemBuyerRenameName = "update UserShopItem set BuyerName = ? where BuyerName = ?";

    /// <summary>SqliteUserShopDB.pas:265 — field FStatementGetUserShopInfo.</summary>
    public const string UserShop_GetUserShopInfo = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE A.HumanName = ?;";

    /// <summary>SqliteUserShopDB.pas:274 — field FStatementIncUserShopCareValue.</summary>
    public const string UserShop_IncUserShopCareValue = "UPDATE UserShop SET CareValue = CareValue + 1 where HumanName = ?";

    /// <summary>SqliteUserShopDB.pas:278 — field FStatementGetMaxShopItemID.</summary>
    public const string UserShop_GetMaxShopItemID = "select ifnull(Max(ItemID), 0) + 1 from UserShopItem where ShopID = ?;";

    /// <summary>SqliteUserShopDB.pas:282 — field FStatementInsertUserShopItem.</summary>
    public const string UserShop_InsertShopItem = "insert into UserShopItem(ShopID,ItemID,ItemType,CreateDate,IsAllowSell,MoneyType,ItemPrice,IsGetMoney,BuyerName,ItemDBName,ItemName) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>SqliteUserShopDB.pas:288 — field FStatementUpdateUserShopItem.</summary>
    public const string UserShop_UpdateShopItem = "update UserShopItem set CreateDate = (strftime('%s', 'now')), ItemType = ?, IsAllowSell = ?, MoneyType = ?, ItemPrice = ? where length(ifnull(BuyerName, '')) = 0 and ShopID = ? and ItemID = ?";

    /// <summary>SqliteUserShopDB.pas:293 — field FStatementBuyUserShopItem.</summary>
    public const string UserShop_BuyShopItem = "update UserShopItem set CreateDate = (strftime('%s', 'now')), BuyerName = ? where length(ifnull(BuyerName, '')) = 0 and ShopID = ? and ItemID = ?";

    /// <summary>SqliteUserShopDB.pas:298 — field FStatementGetMoneyShopItem.</summary>
    public const string UserShop_GetMoneyShopItem = "update UserShopItem set IsGetMoney = 1 where length(ifnull(BuyerName, '')) > 0 and ShopID = ? and ItemID = ?";

    /// <summary>SqliteUserShopDB.pas:303 — field FStatementGetSelledAndNoGetMoneyTotal.</summary>
    public const string UserShop_GetSelledAndNoGetMoneyTotal = "SELECT B.HumanName, A.MoneyType, Sum(A.ItemPrice) SumPrice FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID and length(ifnull(A.BuyerName, '')) > 0 and IsGetMoney = 0 GROUP BY B.HumanName, A.MoneyType ORDER BY B.HumanName";

    /// <summary>SqliteUserShopDB.pas:310 — field FStatementGetTimeHasArrivedSellItems.</summary>
    public const string UserShop_GetTimeHasArrivedSellItems = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName, C.MakeIndex,C.DBIndex,C.IsBind,C.BindOption, C.Dura FROM UserShopItem A, UserShop B, Items C WHERE A.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID AND (A.IsAllowSell = 1) and length(ifnull(A.BuyerName, '')) = 0 and (strftime(\"%s\", \"now\")) - A.createdate > ?";

    /// <summary>SqliteUserShopDB.pas:320 — field FStatementGetShopSellingItem_ASC.</summary>
    public const string UserShop_GetSellingItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:326 — field FStatementGetShopSellingItem_DESC.</summary>
    public const string UserShop_GetSellingItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:332 — field FStatementGetShopSelledItem_ASC.</summary>
    public const string UserShop_GetSelledItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:337 — field FStatementGetShopSelledItem_DESC.</summary>
    public const string UserShop_GetSelledItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:342 — field FStatementGetShopStorageItem_ASC.</summary>
    public const string UserShop_GetStorageItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:348 — field FStatementGetShopStorageItem_DESC.</summary>
    public const string UserShop_GetStorageItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:354 — field FStatementGetShopSellingAndStorageItem_ASC.</summary>
    public const string UserShop_GetSellingAndStorageItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:359 — field FStatementGetShopSellingAndStorageItem_DESC.</summary>
    public const string UserShop_GetSellingAndStorageItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>SqliteUserShopDB.pas:364 — field FStatementGetShopSellingItem_Count.</summary>
    public const string UserShop_GetSellingItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:369 — field FStatementGetShopSelledItem_Count.</summary>
    public const string UserShop_GetSelledItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:374 — field FStatementGetShopStorageItem_Count.</summary>
    public const string UserShop_GetStorageItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:379 — field FStatementGetShopSellingAndStorageItem_Count.</summary>
    public const string UserShop_GetSellingAndStorageItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:384 — field FStatementGetAllShop_Sort0.</summary>
    public const string UserShop_GetAllShop_S0 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SellItemCount desc  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:388 — field FStatementGetAllShop_Sort1.</summary>
    public const string UserShop_GetAllShop_S1 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SellItemCount  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:392 — field FStatementGetAllShop_Sort2.</summary>
    public const string UserShop_GetAllShop_S2 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SelledItemCount desc  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:396 — field FStatementGetAllShop_Sort3.</summary>
    public const string UserShop_GetAllShop_S3 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SelledItemCount  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:400 — field FStatementGetAllShop_Sort4.</summary>
    public const string UserShop_GetAllShop_S4 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by CareValue desc  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:404 — field FStatementGetAllShop_Sort5.</summary>
    public const string UserShop_GetAllShop_S5 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 1 and length(ifnull(BuyerName, '')) = 0) as SellItemCount,(select count(*) from UserShopItem where shopid = a.shopid and length(ifnull(BuyerName, '')) > 0) as SelledItemCount,(select count(*) from UserShopItem where shopid = a.shopid and IsAllowSell = 0 and length(ifnull(BuyerName, '')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by CareValue  limit 8 offset ?";

    /// <summary>SqliteUserShopDB.pas:407 — field FStatementGetAllShop_Count.</summary>
    public const string UserShop_GetAllShop_Count_S = "SELECT Count(*) FROM UserShop WHERE  (IsBusiness >= ?) and (IsBusiness <= ?) ";

    /// <summary>SqliteUserShopDB.pas:413 — field FStatementGetAllShop_Ex.</summary>
    public const string UserShop_GetAllShop_Ex = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue FROM UserShop A ";

    /// <summary>SqliteUserShopDB.pas:453 — field FStatementGetHumanSellingItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSellingItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '')) = 0  and B.IsBusiness >= ? and B.IsBusiness <= ?  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>SqliteUserShopDB.pas:459 — field FStatementGetHumanSelledItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSelledItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and length(ifnull(A.BuyerName, '')) > 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>SqliteUserShopDB.pas:464 — field FStatementGetHumanStorageItem_MakeIndex.</summary>
    public const string UserShop_GetHumanStorageItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '')) = 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>SqliteUserShopDB.pas:470 — field FStatementGetHumanSellingAndStorageItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSellingAndStorageItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and length(ifnull(A.BuyerName, '')) = 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

}