// Source unit: Source/M2Engine/MySqlUserShopDB.pas
// Generated by _recon/delphi-sql-extract.mjs + gen-statements.mjs from the GBK source:
// every value is the verbatim final SQL text after Delphi "' + '" concatenation,
// with doubled quotes preserved exactly as Delphi passes them to the driver.
// Do NOT hand-edit: regenerate and re-diff (see docs/并行报告-p2b-m2-dblayer.md).

namespace GXX.M2Server.DbLayer;

/// <summary>MySqlUserShopDB.pas method-level const block (shared SQL prefix/suffix), verbatim.</summary>
public static class MySqlUserShopDbSql
{
    /// <summary>MySqlUserShopDB.pas:211.</summary>
    public const string SGetShopItemQueryField = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID ";

    /// <summary>MySqlUserShopDB.pas:214.</summary>
    public const string SGetShopItemQueryField_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID ";

    /// <summary>MySqlUserShopDB.pas:219.</summary>
    public const string SGetShopItemQueryCount = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID ";

    /// <summary>MySqlUserShopDB.pas:220.</summary>
    public const string SGetShopItemWhere = " and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:224.</summary>
    public const string SGetAllShopQueryField = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?) ";

}

/// <summary>MySqlUserShopDB.pas 全部静态语句的逐字 SQL（顺序 = 原文 DoInit 顺序）。</summary>
public static class MySqlUserShopStatements
{
    /// <summary>MySqlUserShopDB.pas:238 — field FStatementUpdateAllBusiness.</summary>
    public const string UserShop_UpdateAllBusiness = "update UserShop set IsBusiness = 0;";

    /// <summary>MySqlUserShopDB.pas:243 — field FStatementUpdateHumanBusiness.</summary>
    public const string UserShop_UpdateHumanBusiness = "update UserShop set IsBusiness = ? where HumanName = ?;";

    /// <summary>MySqlUserShopDB.pas:247 — field FStatementHumanNameExists.</summary>
    public const string UserShop_CheckHumanNameExists = "select 1 FROM UserShop where HumanName = ?;";

    /// <summary>MySqlUserShopDB.pas:251 — field FStatementShopNameExists.</summary>
    public const string UserShop_CheckShopNameExists = "select 1 FROM UserShop where ShopName = ?;";

    /// <summary>MySqlUserShopDB.pas:255 — field FStatementInsertUserShop.</summary>
    public const string UserShop_InsertUserShop = "insert into UserShop(HumanName, ShopName, IsBusiness) values(?, ?, 1);";

    /// <summary>MySqlUserShopDB.pas:259 — field FStatementUserShopRename.</summary>
    public const string UserShop_UpdateShopName = "update UserShop set ShopName = ? where ShopID = ?;";

    /// <summary>MySqlUserShopDB.pas:263 — field FStatementUserShopRename2.</summary>
    public const string UserShop_UpdateShopName2 = "update UserShop set HumanName = ? where HumanName = ?";

    /// <summary>MySqlUserShopDB.pas:267 — field FStatementShopItemBuyerRenameName.</summary>
    public const string UserShop_ShopItemBuyerRenameName = "update UserShopItem set BuyerName = ? where BuyerName = ?";

    /// <summary>MySqlUserShopDB.pas:271 — field FStatementGetUserShopInfo.</summary>
    public const string UserShop_GetUserShopInfo = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE A.HumanName = ?;";

    /// <summary>MySqlUserShopDB.pas:280 — field FStatementIncUserShopCareValue.</summary>
    public const string UserShop_IncUserShopCareValue = "UPDATE UserShop SET CareValue = CareValue + 1 where HumanName = ?";

    /// <summary>MySqlUserShopDB.pas:284 — field FStatementGetMaxShopItemID.</summary>
    public const string UserShop_GetMaxShopItemID = "select ifnull(Max(ItemID), 0) + 1 from UserShopItem where ShopID = ?;";

    /// <summary>MySqlUserShopDB.pas:288 — field FStatementInsertUserShopItem.</summary>
    public const string UserShop_InsertShopItem = "insert into UserShopItem(ShopID,ItemID,ItemType,CreateDate,IsAllowSell,MoneyType,ItemPrice,IsGetMoney,BuyerName,ItemDBName,ItemName) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

    /// <summary>MySqlUserShopDB.pas:294 — field FStatementUpdateUserShopItem.</summary>
    public const string UserShop_UpdateShopItem = "update UserShopItem set CreateDate = CURRENT_TIMESTAMP, ItemType = ?, IsAllowSell = ?, MoneyType = ?, ItemPrice = ? where length(ifnull(BuyerName, '''')) = 0 and ShopID = ? and ItemID = ?";

    /// <summary>MySqlUserShopDB.pas:299 — field FStatementBuyUserShopItem.</summary>
    public const string UserShop_BuyShopItem = "update UserShopItem set CreateDate = CURRENT_TIMESTAMP, BuyerName = ? where length(ifnull(BuyerName, '''')) = 0 and ShopID = ? and ItemID = ?";

    /// <summary>MySqlUserShopDB.pas:304 — field FStatementGetMoneyShopItem.</summary>
    public const string UserShop_GetMoneyShopItem = "update UserShopItem set IsGetMoney = 1 where length(ifnull(BuyerName, '''')) > 0 and ShopID = ? and ItemID = ?";

    /// <summary>MySqlUserShopDB.pas:309 — field FStatementGetSelledAndNoGetMoneyTotal.</summary>
    public const string UserShop_GetSelledAndNoGetMoneyTotal = "SELECT B.HumanName, A.MoneyType, Sum(A.ItemPrice) SumPrice FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID and length(ifnull(A.BuyerName, '''')) > 0 and IsGetMoney = 0 GROUP BY B.HumanName, A.MoneyType ORDER BY B.HumanName";

    /// <summary>MySqlUserShopDB.pas:316 — field FStatementGetTimeHasArrivedSellItems.</summary>
    public const string UserShop_GetTimeHasArrivedSellItems = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName, C.MakeIndex,C.DBIndex,C.IsBind,C.BindOption, C.Dura FROM UserShopItem A, UserShop B, Items C WHERE A.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID AND (A.IsAllowSell = 1) and length(ifnull(A.BuyerName, '''')) = 0 and TIMESTAMPDIFF(SECOND, A.createdate, CURRENT_TIMESTAMP) > ?";

    /// <summary>MySqlUserShopDB.pas:325 — field FStatementSetTimeHasArrivedSellItems.</summary>
    public const string UserShop_SetTimeHasArrivedSellItems = "UPDATE UserShopItem set IsAllowSell = 0 WHERE (IsAllowSell = 1) and length(ifnull(BuyerName, '''')) = 0 and TIMESTAMPDIFF(SECOND, CreateDate, CURRENT_TIMESTAMP) > ?";

    /// <summary>MySqlUserShopDB.pas:330 — field FStatementGetShopSellingItem_ASC.</summary>
    public const string UserShop_GetSellingItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:336 — field FStatementGetShopSellingItem_DESC.</summary>
    public const string UserShop_GetSellingItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:342 — field FStatementGetShopSelledItem_ASC.</summary>
    public const string UserShop_GetSelledItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:347 — field FStatementGetShopSelledItem_DESC.</summary>
    public const string UserShop_GetSelledItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:352 — field FStatementGetShopStorageItem_ASC.</summary>
    public const string UserShop_GetStorageItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:358 — field FStatementGetShopStorageItem_DESC.</summary>
    public const string UserShop_GetStorageItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:364 — field FStatementGetShopSellingAndStorageItem_ASC.</summary>
    public const string UserShop_GetSellingAndStorageItem_ASC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:369 — field FStatementGetShopSellingAndStorageItem_DESC.</summary>
    public const string UserShop_GetSellingAndStorageItem_DESC = "SELECT A.ShopID, A.ItemID, A.MoneyType, A.ItemType, A.IsAllowSell, A.ItemPrice, A.CreateDate, A.IsGetMoney,A.BuyerName, B.ShopName, B.HumanName FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?)  order by A.ItemPrice desc limit 5 offset ? ";

    /// <summary>MySqlUserShopDB.pas:374 — field FStatementGetShopSellingItem_Count.</summary>
    public const string UserShop_GetSellingItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:379 — field FStatementGetShopSelledItem_Count.</summary>
    public const string UserShop_GetSelledItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) > 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:384 — field FStatementGetShopStorageItem_Count.</summary>
    public const string UserShop_GetStorageItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:389 — field FStatementGetShopSellingAndStorageItem_Count.</summary>
    public const string UserShop_GetSellingAndStorageItem_Count = "SELECT Count(A.ShopID) FROM UserShopItem A, UserShop B WHERE A.ShopID = B.ShopID  and length(ifnull(A.BuyerName, '''')) = 0  and (A.ItemType >= ?) and (A.ItemType <= ?)  and (A.MoneyType >= ?) and (A.MoneyType <= ?)  and (A.ItemPrice >= ?) and (A.ItemPrice <= ?)  and ((1 = ?) or (B.HumanName = ?))  and (B.IsBusiness >= ?) and (B.IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:394 — field FStatementGetAllShop_Sort0.</summary>
    public const string UserShop_GetAllShop_S0 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SellItemCount desc  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:398 — field FStatementGetAllShop_Sort1.</summary>
    public const string UserShop_GetAllShop_S1 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SellItemCount  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:402 — field FStatementGetAllShop_Sort2.</summary>
    public const string UserShop_GetAllShop_S2 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SelledItemCount desc  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:406 — field FStatementGetAllShop_Sort3.</summary>
    public const string UserShop_GetAllShop_S3 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by SelledItemCount  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:410 — field FStatementGetAllShop_Sort4.</summary>
    public const string UserShop_GetAllShop_S4 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by CareValue desc  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:414 — field FStatementGetAllShop_Sort5.</summary>
    public const string UserShop_GetAllShop_S5 = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 1 and length(ifnull(BuyerName, '''')) = 0) as SellItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and length(ifnull(BuyerName, '''')) > 0) as SelledItemCount,(select count(*) from UserShopItem where ShopID = A.ShopID and IsAllowSell = 0 and length(ifnull(BuyerName, '''')) = 0) as StorageItemCount FROM UserShop A WHERE   (A.IsBusiness >= ?) and (A.IsBusiness <= ?)  order by CareValue  limit 8 offset ?";

    /// <summary>MySqlUserShopDB.pas:417 — field FStatementGetAllShop_Count.</summary>
    public const string UserShop_GetAllShop_Count_S = "SELECT Count(*) FROM UserShop WHERE  (IsBusiness >= ?) and (IsBusiness <= ?) ";

    /// <summary>MySqlUserShopDB.pas:423 — field FStatementGetAllShop_Ex.</summary>
    public const string UserShop_GetAllShop_Ex = "SELECT A.ShopID,A.HumanName,A.ShopName,A.IsBusiness,A.CreateDate,A.CareValue FROM UserShop A ";

    /// <summary>MySqlUserShopDB.pas:463 — field FStatementGetHumanSellingItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSellingItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and (A.IsAllowSell >= ?) and (A.IsAllowSell <= ?) and length(ifnull(A.BuyerName, '''')) = 0  and B.IsBusiness >= ? and B.IsBusiness <= ?  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>MySqlUserShopDB.pas:470 — field FStatementGetHumanSelledItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSelledItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and length(ifnull(A.BuyerName, '''')) > 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>MySqlUserShopDB.pas:476 — field FStatementGetHumanStorageItem_MakeIndex.</summary>
    public const string UserShop_GetHumanStorageItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and (A.IsAllowSell = 0) and length(ifnull(A.BuyerName, '''')) = 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>MySqlUserShopDB.pas:483 — field FStatementGetHumanSellingAndStorageItem_MakeIndex.</summary>
    public const string UserShop_GetHumanSellingAndStorageItem_MakeIndex = "SELECT \tA.ShopID,\tA.ItemID,\tA.MoneyType,\tA.ItemType,\tA.IsAllowSell,\tA.ItemPrice,\tA.CreateDate,\tA.IsGetMoney,\tA.BuyerName,\tB.ShopName,\tB.HumanName,\tC.MakeIndex,\tC.DBIndex,\tC.IsBind,\tC.BindOption,    C.Dura FROM \tUserShopItem A,\tUserShop B,\tItems C WHERE \tA.ShopID = B.ShopID AND C.ParentID = A.ShopID AND C.ItemType = 1 AND C.ItemIndex = A.ItemID  and length(ifnull(A.BuyerName, '''')) = 0  and ((1 = ?) or (B.HumanName = ?))  and C.MakeIndex = ? ";

    /// <summary>MySqlUserShopDB.pas:489 — field FStatementGetItemBindOption.</summary>
    public const string UserShop_GetItemBindOption = "select MakeIndex,IsBind,BindOption from Items where ParentID = ? and ItemType = ? and ItemIndex = ?;";

}