<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>GXX.RunGate</RootNamespace>
    <AssemblyName>RunGate</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GXX.Core\GXX.Core.csproj" />
    <ProjectReference Include="..\GXX.GatewayKit\GXX.GatewayKit.csproj" />
  </ItemGroup></Project>
