// <auto-generated>
//     Generated by src/GXX.Client/GUI/Share/FStateDeclGen.ps1 from the Delphi source;
//     do not hand transpose. Regenerate instead of editing.
//     Source: Source/Client-HGE/GUI/Share/FState.pas
//       const 49-57 / type 60-1114 / var 1117 / const 1133 / TFrmDlg members 311-1114
// </auto-generated>

namespace GXX.Client.GUI.Share;

/// <summary>FState.pas unit level constants (source lines 49-57: 8 scalars + 1 string array).</summary>
public static class FStateConstTable
{
    /// <summary>Constant count.</summary>
    public const int Count = 9;

    /// <summary>SHA-256 of the names joined by '\n' (UTF-8), declaration order.</summary>
    public const string NamesSha256 = "f1d51ddf786d4f4b163a9a8fbbe3412bdd9a943b67ab37f0462cfe45c2232095";

    /// <summary>Constant names in source declaration order.</summary>
    public static readonly string[] Names =
    {
        "BOTTOMBOARD800", // line 49 : 371; // 主操作介面图形号
        "BOTTOMBOARD1024", // line 50 : 2; // 主操作介面图形号
        "VIEWCHATLINE", // line 51 : 9;
        "MAXSTATEPAGE", // line 52 : 4;
        "LISTLINEHEIGHT", // line 53 : 13;
        "MAXMENU", // line 54 : 10;
        "MINMAP_RECT_SIZE", // line 55 : 2;
        "MINMAP_RECT_SIZE2", // line 56 : 3;
        "AdjustAbilHints:array[0..8] of string", // line 57 : ('攻击力', '魔法(魔法师)', '道术(道士)', '防御', '魔法防御', '生命值', '魔法值', '准确', '敏捷');
    };
}

/// <summary>FState.pas type declarations (source lines 60-1114: 24 non TFrmDlg types).</summary>
public static class FStateTypeTable
{
    /// <summary>Type count.</summary>
    public const int Count = 24;

    /// <summary>SHA-256 of the names joined by '\n' (UTF-8), declaration order.</summary>
    public const string NamesSha256 = "f3f37602b8cd8101c71c8e5cc9f7e7894b2992b48b238eb333196e3793bc8397";

    /// <summary>Type names in source declaration order.</summary>
    public static readonly string[] Names =
    {
        "TArrHintWindows", // line 60 : array
        "PTArrHintWindows", // line 62 : pointer
        "TSpotDlgMode", // line 64 : enum
        "TDiceInfo", // line 66 : record
        "pTDiceInfo", // line 76 : pointer
        "TGuildGroup", // line 78 : class:TObject
        "TGuildGroupList", // line 91 : class:TObject
        "PShowGuildInfo", // line 109 : pointer
        "TShowGuildInfo", // line 111 : record
        "TShowGuildList", // line 117 : class:TObject
        "TGuildJoinUserList", // line 132 : class:TObject
        "TNpcButton", // line 146 : class:TDxImageButton
        "TNpcGraphicButton", // line 165 : class:TDxImageButton
        "TNpcItemButton", // line 178 : class:TDxImageButton
        "TNpcUserItemButton", // line 193 : class:TNpcItemButton
        "TNpcItemBoxButton", // line 198 : class:TDxImageButton
        "TNpcProgressBoxButton", // line 204 : class:TDxImageButton
        "TNpcLabel", // line 225 : class:TDxLabel
        "TCountDownLabel", // line 237 : class:TDxLabel
        "TImgCountDownButton", // line 253 : class:TDxImageButton
        "TNpcInputEdit", // line 270 : class:TDxEdit
        "TNpcScrollBox", // line 284 : class:TDxScrollBox
        "TMissionLabel", // line 300 : class:TDxTreeNode
        "TMagicButton", // line 305 : class:TDxImageButton
    };

    /// <summary>Source kind marker per <see cref="Names"/> entry (class:X / record / enum / array / pointer).</summary>
    public static readonly string[] Kinds =
    {
        "array", // TArrHintWindows
        "pointer", // PTArrHintWindows
        "enum", // TSpotDlgMode
        "record", // TDiceInfo
        "pointer", // pTDiceInfo
        "class:TObject", // TGuildGroup
        "class:TObject", // TGuildGroupList
        "pointer", // PShowGuildInfo
        "record", // TShowGuildInfo
        "class:TObject", // TShowGuildList
        "class:TObject", // TGuildJoinUserList
        "class:TDxImageButton", // TNpcButton
        "class:TDxImageButton", // TNpcGraphicButton
        "class:TDxImageButton", // TNpcItemButton
        "class:TNpcItemButton", // TNpcUserItemButton
        "class:TDxImageButton", // TNpcItemBoxButton
        "class:TDxImageButton", // TNpcProgressBoxButton
        "class:TDxLabel", // TNpcLabel
        "class:TDxLabel", // TCountDownLabel
        "class:TDxImageButton", // TImgCountDownButton
        "class:TDxEdit", // TNpcInputEdit
        "class:TDxScrollBox", // TNpcScrollBox
        "class:TDxTreeNode", // TMissionLabel
        "class:TDxImageButton", // TMagicButton
    };
}

/// <summary>TFrmDlg field declarations (source lines 311-1114: 201 entries).</summary>
public static class TFrmDlgFieldTable
{
    /// <summary>Field count (multi name lines are expanded, so this exceeds the line count).</summary>
    public const int Count = 201;

    /// <summary>SHA-256 of the names joined by '\n' (UTF-8), declaration order.</summary>
    public const string NamesSha256 = "f37ac42a635fd5ce8f8884953f7f4dca86f4dbb1c8221f1ec5ed4fb2dde804f7";

    /// <summary>Field names in source declaration order.</summary>
    public static readonly string[] Names =
    {
        "DBackground", // line 312 : TDxControlEngine
        "DEdId", // line 313 : TDxEdit
        "DEdPasswd", // line 314 : TDxEdit
        "DEdNewId", // line 315 : TDxEdit
        "DEdConfirm", // line 316 : TDxEdit
        "DEdChgId", // line 317 : TDxEdit
        "DEdChgL2Pw", // line 318 : TDxEdit
        "DEdChrName", // line 319 : TDxEdit
        "DscStart", // line 320 : TDxImageButton
        "DscUpChr", // line 321 : TDxImageButton
        "DscDownChr", // line 322 : TDxImageButton
        "DEdChat", // line 323 : TDxImageEdit
        "DGuildDlg", // line 324 : TDxImageForm
        "DChatMemo", // line 325 : TDxChatMemo
        "DWhisperMemo", // line 326 : TDxChatMemo
        "DBotPlusAbil", // line 327 : TDxImageButton
        "DGrpAllowGroup", // line 328 : TDxImageButton
        "DMemoGroupMembers", // line 329 : TDxListView
        "DLabelGroupMembersOwner", // line 330 : TDxLabel
        "DMerchantDlg", // line 331 : TDxImageForm
        "DMerchantDlgClose", // line 332 : TDxImageButton
        "DMerchantDlgHelp", // line 333 : TDxImageButton
        "DMissionMemo", // line 334 : TDxScrollBox
        "DCheckBoxAutoAnswersWhisper", // line 335 : TDxImageButton
        "DEditAutoAnswersWhisper", // line 336 : TDxEdit
        "DSpecialCmdMenu", // line 337 : TDxPopupMenu
        "DListViewDeleteHuman", // line 338 : TDxListView
        "LabelDSelectChrServerName", // line 339 : TDxLabel
        "LabelSelectChrDlgCharName1", // line 340 : TDxLabel
        "LabelSelectChrDlgJob1", // line 341 : TDxLabel
        "LabelSelectChrDlgLevel1", // line 342 : TDxLabel
        "LabelSelectChrDlgCharName2", // line 343 : TDxLabel
        "LabelSelectChrDlgJob2", // line 344 : TDxLabel
        "LabelSelectChrDlgLevel2", // line 345 : TDxLabel
        "LabelSelectChrDlgCharName3", // line 346 : TDxLabel
        "LabelSelectChrDlgJob3", // line 347 : TDxLabel
        "LabelSelectChrDlgLevel3", // line 348 : TDxLabel
        "DHelmetUS1_", // line 349 : TDxImageButton
        "DMainMenu", // line 350 : TDxPopupMenu
        "DMinMapDlg", // line 353 : TDxImageForm
        "DSayItemDlg", // line 354 : TDxImageForm
        "DSayItemDlgClose", // line 355 : TDxImageButton
        "DUpdateStatusDlg", // line 356 : TDxImageForm
        "DLieDragon", // line 357 : TDxImageForm
        "DGoToLieDragon", // line 358 : TDxImageButton
        "DLieDragonClose", // line 359 : TDxImageButton
        "DLieDragonNextPage", // line 360 : TDxImageButton
        "DLieDragonPrevPage", // line 361 : TDxImageButton
        "DLieDragonNpc", // line 362 : TDxImageForm
        "DLieDragonNpcClose", // line 363 : TDxImageButton
        "MsgText", // line 366 : string
        "m_nDiceCount", // line 367 : int
        "m_boPlayDice", // line 368 : bool
        "m_Dice", // line 369 : TDiceInfo[10]
        "MerchantCMD", // line 370 : string
        "MerchantName", // line 371 : string
        "MerchantFace", // line 372 : int
        "MDlgStr", // line 373 : string
        "RequireAddPoints", // line 374 : bool
        "SelectMenuStr", // line 375 : string
        "LastestClickTime", // line 376 : uint
        "SpotDlgMode", // line 377 : TSpotDlgMode
        "MenuList", // line 378 : TGList
        "menuindex", // line 379 : int
        "CurDetailItem", // line 380 : string
        "MenuTopLine", // line 381 : int
        "TradingItemTopLine", // line 382 : int
        "TradingItemSelIndex", // line 383 : int
        "BoDetailMenu", // line 384 : bool
        "BoStorageMenu", // line 385 : bool
        "BoNoDisplayMaxDura", // line 386 : bool
        "BoMakeDrugMenu", // line 387 : bool
        "NewAccountTitle", // line 389 : string
        "DlgEditText", // line 390 : string
        "GuildGroupListPage", // line 391 : int
        "GuildGroupList", // line 392 : TGuildGroupList
        "Guild", // line 393 : string
        "GuildFlag", // line 394 : string
        "GuildCommanderMode", // line 395 : int
        "GuildStrs", // line 396 : TStringList
        "GuildStrs2", // line 397 : TStringList
        "GuildNotice", // line 398 : TStringList
        "GuildWJ", // line 399 : TStringList
        "GuildMembers", // line 400 : TStringList
        "GuildTopLine", // line 401 : int
        "GuildEditHint", // line 402 : string
        "GuildChats", // line 403 : TStringList
        "WantAddGuildName", // line 404 : string
        "ShowGuildListPage", // line 405 : int
        "ShowGuildList", // line 406 : TShowGuildList
        "GuildJoinUserList", // line 407 : TGuildJoinUserList
        "GuildJoinUserListPage", // line 408 : int
        "GuildOnlineCount", // line 409 : int
        "GuildMemberCount", // line 410 : int
        "GuildMemberMaxLimit", // line 411 : int
        "BoGuildChat", // line 412 : bool
        "HeroMagicIndex", // line 413 : int
        "MagicIndex", // line 414 : int
        "RankingPage", // line 415 : int
        "Initialized", // line 416 : bool
        "ShopTabPage", // line 417 : int
        "RankingSelectLine", // line 418 : int
        "SelDeleteCharName", // line 419 : string
        "Memo", // line 420 : TMemo
        "ViewDlgEdit", // line 421 : bool
        "MenuTop", // line 422 : int
        "BlinkTime", // line 423 : uint
        "BlinkCount", // line 424 : int
        "BoxDlgWideScreen", // line 425 : bool
        "m_sLoginId", // line 426 : string
        "m_sLoginPasswd", // line 427 : string
        "FAbilHPTick", // line 428 : uint
        "FAbilMPTick", // line 429 : uint
        "FAbilHPIndex", // line 430 : int
        "FAbilMPIndex", // line 431 : int
        "GameGoldDealMenuIndex", // line 432 : int
        "GuildMemoVisible", // line 433 : bool
        "StorageHeroInfos", // line 434 : TStorageHeroInfo[2]
        "ClientVersion", // line 436 : TClientVersion
        "ShowMiniBigMapXY", // line 437 : bool
        "BigMinMapX", // line 438 : int
        "BigMinMapY", // line 439 : int
        "MapTextureWidth", // line 440 : int
        "MapTextureHeight", // line 441 : int
        "FRemoveStoneLock", // line 442 : bool
        "FRemoveStoneShowEffect", // line 443 : bool
        "FRemoveStoneShowEffectTick", // line 444 : uint
        "FRemoveStoneShowEffectIdx", // line 445 : int
        "FRemoveStoneIdx", // line 446 : int
        "FRemoveStoneIndex", // line 447 : int
        "FOverlapStoneItemMakeIndex", // line 448 : int
        "FRemoveStoneHideStone", // line 449 : bool
        "FRemoveStoneHideStoneMsg", // line 450 : string
        "FRemoveStoneHideStoneEffect", // line 451 : bool
        "FRemoveStoneHideStoneEffectTick", // line 452 : uint
        "FRemoveStoneHideStoneEffectIdx", // line 453 : int
        "FShowProgressBarTime", // line 454 : uint
        "FShowProgressBarTick", // line 455 : uint
        "FShowProgressBarCmd", // line 456 : int
        "FShowProgressBarParam1", // line 457 : int
        "FShowProgressBarParam2", // line 458 : int
        "FDStorageViewDlgCount", // line 459 : int
        "FDStorageViewDlgMaxCount", // line 459 : int
        "FDStorageViewDlgPage", // line 459 : int
        "FDStorageViewDlgMaxPage", // line 459 : int
        "FNpcStoragePage", // line 460 : int
        "FGameShopPageControlIndex", // line 461 : int
        "FGameShopPageIndex", // line 462 : int
        "FGroupChatBottomSpace", // line 463 : int
        "FChatMemoBottomSpace", // line 464 : int
        "FEditChatBottomSpace", // line 465 : int
        "FChangeChatHeightBottomSpace", // line 466 : int
        "FDayBrightIconStartIndex", // line 467 : int
        "FMagicBallStartIndex", // line 468 : int
        "FHeroState185IconStartIndex", // line 470 : int
        "FHeroStateIconStartIndex", // line 471 : int
        "FHeroBagItem40ImageIndex", // line 473 : int
        "FBotPlusAbilFlashStartIndex", // line 475 : int
        "FJewelryBoxUpImageIndex", // line 477 : int
        "FJewelryBoxDownImageIndex", // line 478 : int
        "FHeroJewelryBoxUpImageIndex", // line 479 : int
        "FHeroJewelryBoxDownImageIndex", // line 480 : int
        "_DLableMenuDlgC1", // line 481 : TDxLabel
        "_DLableMenuDlgC2", // line 482 : TDxLabel
        "_DLableMenuDlgC3", // line 483 : TDxLabel
        "_ListViewMenuDlg", // line 484 : TDxListView
        "dwControlHelpCickTick", // line 486 : uint
        "FIsRingLeft", // line 487 : bool
        "FIsArmRingLeft", // line 488 : bool
        "FIsFashionRingLeft", // line 489 : bool
        "FIsFashionArmRingLeft", // line 490 : bool
        "boSayItemDlgMoveOutClose", // line 501 : bool
        "nSayItemMakeIndex", // line 502 : int
        "FSayItemHintWin", // line 503 : object
        "FGuildGroupIndex", // line 504 : int
        "FGuildJoinJob", // line 505 : int
        "FGuildJoinLevel", // line 506 : int
        "FGuildJoinMsg", // line 507 : string
        "FGuildViewMemberInfo", // line 508 : TGuildMemeberInfo
        "FScreenMagicBtnList", // line 509 : TList
        "FStorageViewDlgMerchant", // line 510 : long
        "FMiniMapLoadIndex", // line 511 : int
        "FMiniMapLoadSurfaceTime", // line 512 : uint
        "FMiniMapSurface", // line 513 : TTexture
        "m_boRandomCodeClick", // line 515 : bool
        "FAuctionAllItemsSortField", // line 516 : int
        "FAuctionAllItemsSortASC", // line 517 : bool
        "FAuctionAllItemsPage", // line 518 : int
        "FAuctionMyItemsPage", // line 519 : int
        "FAuctionMyAuctioningItemsPage", // line 520 : int
        "FAuctionMyItemsBagPage", // line 521 : int
        "FAuctionMyItemsBagSelectIndex", // line 522 : int
        "FAuctionMyItemsPageCount", // line 523 : int
        "FAuctionAllItemsPageCount", // line 524 : int
        "FAuctionMyAuctioningItemsPageCount", // line 525 : int
        "FAuctionMyItemsBagPageCount", // line 526 : int
        "FGuardianLevelRewardItems", // line 527 : TClientItem[4]
        "FGuardianLevelItemCounts", // line 528 : TGuardianLevelItemCounts
        "FGuardianLevelStatueMonRecogId", // line 529 : int
        "FCurrentBagPage", // line 530 : byte
        "FExtBagPageCount", // line 531 : byte
    };
}

/// <summary>TFrmDlg method/property declarations (source lines 311-1114: 538 entries).</summary>
public static class TFrmDlgMethodTable
{
    /// <summary>Member count (incl. 5 overload groups, 1 property, 1 constructor, 1 destructor).</summary>
    public const int Count = 538;

    /// <summary>SHA-256 of the names joined by '\n' (UTF-8), declaration order (overload names repeat).</summary>
    public const string NamesSha256 = "714c3ee324ee5f25335d0b0e88e93f06a94e5a33e947eeb5dcf948c44978eb96";

    /// <summary>Member names in source declaration order (overloads repeat).</summary>
    public static readonly string[] Names =
    {
        "OnMagicButtonClick", // line 493 : procedure private
        "OnMagicButtonDblClick", // line 494 : procedure private
        "OnMagicButtonMouseMove", // line 495 : procedure private
        "OnMagicButtonMove", // line 496 : procedure private
        "CreateNpcQRButtonFromText", // line 499 : function private
        "Create", // line 533 : constructor public
        "Destroy", // line 534 : destructor public
        "UpDate", // line 535 : procedure public
        "DBottomInRealArea", // line 536 : procedure public
        "DItemGridGridSelect", // line 537 : procedure public
        "DItemGridGridPaint", // line 538 : procedure public
        "DItemGridDblClick", // line 539 : procedure public
        "DBackgroundBackgroundClick", // line 540 : procedure public
        "DItemGridGridMouseMove", // line 541 : procedure public
        "DBelt1DirectPaint", // line 542 : procedure public
        "DBelt1DblClick", // line 543 : procedure public
        "DLoginCloseClick", // line 544 : procedure public
        "DLoginOkClick", // line 545 : procedure public
        "DLoginNewClick", // line 546 : procedure public
        "DLoginChgPwClick", // line 547 : procedure public
        "DNewAccountOkClick", // line 548 : procedure public
        "DNewAccountCloseClick", // line 549 : procedure public
        "DChgpwOkClick", // line 550 : procedure public
        "DChgpwCancelClick", // line 551 : procedure public
        "DSWWeaponClick", // line 552 : procedure public
        "DCloseBagClick", // line 553 : procedure public
        "DBelt1Click", // line 554 : procedure public
        "DStateWinClick", // line 555 : procedure public
        "DBelt1MouseMove", // line 556 : procedure public
        "DBelt1MouseDown", // line 557 : procedure public
        "DMerchantDlgCloseClick", // line 558 : procedure public
        "DMerchantDlgClick", // line 559 : procedure public
        "DMenuCloseClick", // line 560 : procedure public
        "DMenuDlgDirectPaint", // line 561 : procedure public
        "DMenuDlgClick", // line 562 : procedure public
        "DMenuDlgMouseMove", // line 563 : procedure public
        "DSellDlgCloseClick", // line 564 : procedure public
        "DSellDlgSpotClick", // line 565 : procedure public
        "DSellDlgSpotDirectPaint", // line 566 : procedure public
        "DSellDlgSpotMouseMove", // line 567 : procedure public
        "DSellDlgOkClick", // line 568 : procedure public
        "DMenuBuyClick", // line 569 : procedure public
        "DMenuPrevClick", // line 570 : procedure public
        "DMenuNextClick", // line 571 : procedure public
        "DGoldClick", // line 572 : procedure public
        "DSWLightDirectPaint", // line 573 : procedure public
        "DBackgroundMouseDown", // line 574 : procedure public
        "DStateWinMouseMove", // line 575 : procedure public
        "DLoginNewClickSound", // line 576 : procedure public
        "DStMag1Click", // line 577 : procedure public
        "DStMag1MouseDown", // line 578 : procedure public
        "DStMag1MouseUp", // line 579 : procedure public
        "DKsOkClick", // line 582 : procedure public
        "DDealOkClick", // line 583 : procedure public
        "DDealCloseClick", // line 584 : procedure public
        "DBotTradeClick", // line 585 : procedure public
        "BotChallengeClick", // line 586 : procedure public
        "DDealRemoteDlgDirectPaint", // line 587 : procedure public
        "DDealDlgDirectPaint", // line 588 : procedure public
        "DDGridGridSelect", // line 589 : procedure public
        "DDGridGridPaint", // line 590 : procedure public
        "DDGridGridMouseMove", // line 591 : procedure public
        "DDRGridGridPaint", // line 592 : procedure public
        "DDRGridGridMouseMove", // line 593 : procedure public
        "DDGoldClick", // line 594 : procedure public
        "DUserState1MouseMove", // line 595 : procedure public
        "DCloseUS1Click", // line 596 : procedure public
        "DNecklaceUS1DirectPaint", // line 597 : procedure public
        "DGuildDlgDirectPaint", // line 598 : procedure public
        "DGDUpClick", // line 599 : procedure public
        "DGDDownClick", // line 600 : procedure public
        "DGDCloseClick", // line 601 : procedure public
        "DGDHomeClick", // line 602 : procedure public
        "DGDListClick", // line 603 : procedure public
        "DGDAddMemClick", // line 604 : procedure public
        "DGDDelMemClick", // line 605 : procedure public
        "DGDEditNoticeClick", // line 606 : procedure public
        "DGDEditGradeClick", // line 607 : procedure public
        "DNewGuildDlgCloseClick", // line 608 : procedure public
        "DNewGuildNoticeClick", // line 609 : procedure public
        "DGuildEditNoticeDirectPaint", // line 610 : procedure public
        "DGDChatClick", // line 611 : procedure public
        "DAdjustAbilCloseClick", // line 612 : procedure public
        "DBotPlusAbilClick", // line 613 : procedure public
        "DAdjustAbilOkClick", // line 614 : procedure public
        "DBotPlusAbilDirectPaint", // line 615 : procedure public
        "DAdjustAbilityMouseMove", // line 616 : procedure public
        "DUserState1MouseDown", // line 617 : procedure public
        "DChgGamePwdDirectPaint", // line 618 : procedure public
        "DscSelect1InRealArea", // line 619 : procedure public
        "DCreateChrDirectPaint", // line 620 : procedure public
        "DItemBagMouseMove", // line 621 : procedure public
        "DBottomMouseMove", // line 622 : procedure public
        "DNewAccountCancelClick", // line 623 : procedure public
        "DHeroM2ShopDlgShowOnClick", // line 624 : procedure public
        "DShopDlgDirectPaint", // line 625 : procedure public
        "DButtonShopPrevClick", // line 626 : procedure public
        "DButtonShopNextClick", // line 627 : procedure public
        "DBotRankingHomeClick", // line 628 : procedure public
        "DBotRankingUpClick", // line 629 : procedure public
        "DBotRankingDownClick", // line 630 : procedure public
        "DBotRankingLastClick", // line 631 : procedure public
        "DButtonShopBuyClick", // line 632 : procedure public
        "DButtonShopBuyGiveClick", // line 633 : procedure public
        "MinMapLevelChange", // line 634 : procedure public
        "DMinMapDlgShow", // line 635 : procedure public
        "DMinMapDlgHide", // line 636 : procedure public
        "DMinMapDlgResize", // line 637 : procedure public
        "DMinMapDlgMouseEnter", // line 638 : procedure public
        "DMinMapDlgMouseLeave", // line 639 : procedure public
        "DMinMapDlgMouseMove", // line 640 : procedure public
        "DMinMapDlgMouseUP", // line 641 : procedure public
        "DMinMapDlgClick", // line 642 : procedure public
        "DscStartDirectPaint", // line 643 : procedure public
        "DDiceDlgDirectPaint", // line 644 : procedure public
        "OnGetImage", // line 645 : procedure public
        "HideAllControls", // line 646 : procedure public
        "RestoreHideControls", // line 647 : procedure public
        "DealItemReturnBag", // line 648 : procedure public
        "DealZeroGold", // line 649 : procedure public
        "OpenSoundOption", // line 650 : procedure public
        "FindActiveControl", // line 653 : function public
        "AddNpcMemo", // line 654 : procedure public
        "LoadJsonControl", // line 655 : procedure public
        "DBotRankClick", // line 656 : procedure public
        "DBotWhisperClick", // line 657 : procedure public
        "DBotHorseClick", // line 658 : procedure public
        "DOptionClick", // line 659 : procedure public
        "DWhisperDlgCloseClick", // line 660 : procedure public
        "DRankingDlgCloseClick", // line 661 : procedure public
        "DShopDlgCloseClick", // line 662 : procedure public
        "DMissionDlgClick", // line 663 : procedure public
        "DMissionDlgCloseClick", // line 664 : procedure public
        "DGrpDlgCloseClick", // line 665 : procedure public
        "DBotGroupClick", // line 666 : procedure public
        "DGrpAllowGroupClick", // line 667 : procedure public
        "DBotGroupMouseDown", // line 668 : procedure public
        "DBotExitClick", // line 671 : procedure public
        "DGDAllyClick", // line 672 : procedure public
        "DGDBreakAllyClick", // line 673 : procedure public
        "DButtonFriendClick", // line 674 : procedure public
        "DBotRankingClick", // line 675 : procedure public
        "DBotRankingCloseClick", // line 676 : procedure public
        "DBotFriendClick", // line 677 : procedure public
        "DFrdCloseClick", // line 678 : procedure public
        "DChgGamePwdCloseClick", // line 679 : procedure public
        "DGameGoldDealDlgMouseMove", // line 680 : procedure public
        "DGameGoldDealMenuDlgPaint", // line 681 : procedure public
        "DGameGoldDealMenuDlgMouseMove", // line 682 : procedure public
        "DGameGoldDealGridGridPaint", // line 683 : procedure public
        "DGameGoldDealGridGridSelect", // line 684 : procedure public
        "DGameGoldDealGridGridMouseMove", // line 685 : procedure public
        "DGameGoldDealDlgCloseClick", // line 686 : procedure public
        "DGameGoldDealCancelClick", // line 687 : procedure public
        "DGameGoldDealMenuDlgCloseClick", // line 688 : procedure public
        "DBuyGameGoldDealItemOKClick", // line 689 : procedure public
        "DBuyGameGoldDealItemCancelClick", // line 690 : procedure public
        "DGameGoldDealItemCancelClick", // line 691 : procedure public
        "DBotFuncClick", // line 692 : procedure public
        "DBotFuncMouseMove", // line 693 : procedure public
        "DStMagMouseMove", // line 694 : procedure public
        "DMissionMerchantDlgClick", // line 695 : procedure public
        "DNPC_IMG_PAINT", // line 696 : procedure public
        "DNPC_IMGEX_PAINT", // line 697 : procedure public
        "DNPC_IMGNUM_PAINT", // line 698 : procedure public
        "DNPC_PLAYIMG_PAINT", // line 699 : procedure public
        "DNPC_IMGPAY_PAINT", // line 700 : procedure public
        "Close", // line 701 : procedure public
        "MakeShareControlAddrList", // line 702 : function public
        "LoadShareFromStream", // line 703 : procedure public
        "OpenDSelectChrDlg", // line 704 : procedure public
        "Initialize", // line 705 : procedure public
        "LoadFromStream", // line 706 : procedure public
        "MakeControlAddrList", // line 707 : function public
        "GetMissionTreeView", // line 708 : function public
        "GetMissionActivePageIndex", // line 709 : function public
        "SetMissionActivePageIndex", // line 710 : procedure public
        "MissionPageClear", // line 711 : procedure public
        "LoginPasswdOK", // line 712 : procedure public
        "OpenDLoginDlg", // line 713 : procedure public
        "CloseDLoginDlg", // line 714 : procedure public
        "OpenDDoorDlg", // line 715 : procedure public
        "CloseDDoorDlg", // line 716 : procedure public
        "OpenDRealNameDlg", // line 718 : procedure public
        "CloseDRealNameDlg", // line 719 : procedure public
        "OpenDGetPwdBackDlg", // line 721 : procedure public
        "CloseDGetPwdBackDlg", // line 722 : procedure public
        "OpenDRegAccount", // line 724 : procedure public
        "CloseDRegAccount", // line 725 : procedure public
        "OpenDBindPhone", // line 727 : procedure public
        "CloseDBindPhone", // line 728 : procedure public
        "CheckUserEntrys", // line 729 : function public
        "NewIdRetry", // line 730 : procedure public
        "NewAccountOk", // line 731 : procedure public
        "OpenDNewAccountDlg", // line 732 : procedure public
        "CloseDNewAccountDlg", // line 733 : procedure public
        "ChangePassWordOK", // line 734 : procedure public
        "OpenDChgPwDlg", // line 735 : procedure public
        "CloseDChgPwDlg", // line 736 : procedure public
        "OpenDSelServerDlg", // line 737 : procedure public
        "CloseDSelServerDlg", // line 738 : procedure public
        "CloseDSelectChrDlg", // line 739 : procedure public
        "OpenDCreateChrDlg", // line 740 : procedure public
        "CloseDCreateChrDlg", // line 741 : procedure public
        "MakeNewChar", // line 742 : procedure public
        "OpenDMerchantDlg", // line 743 : procedure public
        "CloseDMerchantDlg", // line 744 : procedure public
        "RestoreDMerchantDlg", // line 745 : procedure public
        "OpenDMenuDlg", // line 746 : procedure public
        "CloseDMenuDlg", // line 747 : procedure public
        "OpenTradingMarketItemsDlg", // line 748 : procedure public
        "RecallTradingSellPrices", // line 749 : procedure public
        "CheckDStorageViewDlgShow", // line 750 : function public
        "OpenDStorageViewDlg", // line 751 : procedure public
        "RefrshDStorageViewDlgText", // line 752 : procedure public
        "RefrshDStorageOpen", // line 753 : procedure public
        "CheckDTradingMarketDlgVisible", // line 754 : function public
        "OpenDItemBagDlg", // line 755 : procedure public
        "CloseDItemBagDlg", // line 756 : procedure public
        "OpenDAuctionDlg", // line 757 : procedure public
        "CloseDAuctionDlg", // line 758 : procedure public
        "CloseDAuctionBuyDlg", // line 759 : procedure public
        "CloseDAuctionSellDlg", // line 760 : procedure public
        "OpenDAuctionBroadcastDlg", // line 761 : procedure public
        "CloseDAuctionBroadcastDlg", // line 762 : procedure public
        "OpenSellPlayDlg", // line 763 : procedure public
        "OpenDelSellPlayDlg", // line 764 : procedure public
        "OpenSellPlayerShopDlg", // line 765 : procedure public
        "SetSellPlayerShopItemPageInfo", // line 766 : procedure public
        "OpenViewSellPlayerInfo", // line 767 : procedure public
        "OpenViewSellPlayerBagItems", // line 768 : procedure public
        "OpenViewSellPlayerStorage", // line 769 : procedure public
        "SellPlayerAbilChange", // line 770 : procedure public
        "ShowSellPlayerOtherInfo", // line 771 : procedure public
        "ClearSellPlayerOtherInfo", // line 772 : procedure public
        "OpenDSellDlg", // line 773 : procedure public
        "CloseDSellDlg", // line 774 : procedure public
        "OpenDDealDlg", // line 775 : procedure public
        "CloseDDealDlg", // line 776 : procedure public
        "OpenDDealRemoteDlg", // line 777 : procedure public
        "CloseDDealRemoteDlg", // line 778 : procedure public
        "OpenDStateWinDlg", // line 779 : procedure public
        "CloseDStateWinDlg", // line 780 : procedure public
        "OpenDShopDlg", // line 781 : procedure public
        "CloseDShopDlg", // line 782 : procedure public
        "OpenDUserState1Dlg", // line 783 : procedure public
        "CloseDUserState1Dlg", // line 784 : procedure public
        "OpenDFriendDlg", // line 785 : procedure public
        "CloseDFriendDlg", // line 786 : procedure public
        "OpenDGroupDlg", // line 787 : procedure public
        "CloseDGroupDlg", // line 788 : procedure public
        "OpenDWhisperDlg", // line 789 : procedure public
        "CloseDWhisperDlg", // line 790 : procedure public
        "OpenDRankingDlg", // line 791 : procedure public
        "CloseDRankingDlg", // line 792 : procedure public
        "OpenDGameGoldDealDlg", // line 793 : procedure public
        "CloseDGameGoldDealDlg", // line 794 : procedure public
        "OpenDGameGoldDealMenuDlg", // line 795 : procedure public
        "CloseDGameGoldDealMenuDlg", // line 796 : procedure public
        "OpenDGuildDlg", // line 797 : procedure public
        "CloseDGuildDlg", // line 798 : procedure public
        "DGuildChangeRankNo", // line 799 : procedure public
        "UpdateGuildJoinCondition", // line 800 : procedure public
        "RefreshDGuildManageListViewWJ", // line 801 : procedure public
        "OpenGuildViewMemeberInfo", // line 802 : procedure public
        "OpenGuildEditGradeDlg", // line 803 : procedure public
        "OpenDGuildEditNoticeDlg", // line 804 : procedure public
        "CloseDGuildEditNoticeDlg", // line 805 : procedure public
        "RefreshGuildMembers", // line 806 : procedure public
        "CloseDGuildDlg_New", // line 807 : procedure public
        "OpenDGuildEditNoticeDlg_New", // line 808 : procedure public
        "RefreshGuildJoinUserList", // line 809 : procedure public
        "DoSetGuildWantAddGuildName", // line 810 : procedure public
        "OpenDGuildApplyDlg", // line 811 : procedure public
        "CloseDGuildApplyDlg", // line 812 : procedure public
        "OpenDGuildNoticeDlg", // line 813 : procedure public
        "CloseDGuildNoticeDlg", // line 814 : procedure public
        "OpenDMissionDlg", // line 815 : procedure public
        "CloseDMissionDlg", // line 816 : procedure public
        "OpenDAdjustAbilityDlg", // line 817 : procedure public
        "CloseDAdjustAbilityDlg", // line 818 : procedure public
        "IsDAdjustAbilityDlgShow", // line 819 : function public
        "OpenDHeroStateDlg", // line 820 : procedure public
        "CloseDHeroStateDlg", // line 821 : procedure public
        "OpenDHeroItemBagDlg", // line 822 : procedure public
        "CloseDHeroItemBagDlg", // line 823 : procedure public
        "OpenDHeroStateWinDlg", // line 824 : procedure public
        "CloseDHeroStateWinDlg", // line 825 : procedure public
        "SetHeroBagCount", // line 826 : procedure public
        "CloseDHeroJewelryBoxDlg", // line 827 : procedure public
        "CloseDHeroGodBlessDlg", // line 828 : procedure public
        "OpenDDeleteHumanDlg", // line 829 : procedure public
        "CloseDDeleteHumanDlg", // line 830 : procedure public
        "OpenMyStatus", // line 831 : procedure public
        "OpenMyMagic", // line 832 : procedure public
        "AddDDrinkWineDlgSay", // line 833 : procedure public
        "OpenDPleaseDrinkWineDlg", // line 834 : procedure public
        "CloseDPleaseDrinkWineDlg", // line 835 : procedure public
        "OpenDGuessfingerDlg", // line 836 : procedure public
        "CloseDGuessfingerDlg", // line 837 : procedure public
        "OpenDMakeWineDlg", // line 838 : procedure public
        "CloseDMakeWineDlg", // line 839 : procedure public
        "OpenDMakeMedicinalWineDlg", // line 840 : procedure public
        "CloseDMakeMedicinalWineDlg", // line 841 : procedure public
        "OpenDStorageHeroInfoDlg", // line 842 : procedure public
        "CloseDStorageHeroInfoDlg", // line 843 : procedure public
        "OpenDHeroAppraisalInfoDlg", // line 846 : procedure public
        "CloseDHeroAppraisalInfoDlg", // line 847 : procedure public
        "OpenDHeroAppraisalDlg", // line 848 : procedure public
        "CloseDHeroAppraisalDlg", // line 849 : procedure public
        "OpenDHeroAutoPracticeDlg", // line 851 : procedure public
        "CloseDHeroAutoPracticeDlg", // line 852 : procedure public
        "ShowCollectProgressBarDlg", // line 853 : procedure public
        "CloseCollectProgressBarDlg", // line 854 : procedure public
        "BringToFrontCollectProgressBarDlg", // line 855 : procedure public
        "ShowProgressBarDlg", // line 856 : procedure public
        "CloseProgressBarDlg", // line 857 : procedure public
        "ShowSayItemDlg", // line 858 : procedure public
        "CloseSayItemDlg", // line 859 : procedure public
        "ShowDGJPointsDlg", // line 860 : procedure public
        "IsDGJPointsShow", // line 861 : function public
        "GetUserStateShieldRect", // line 862 : function public
        "DMessageDlg", // line 863 : function public
        "DMessageDiceDlg", // line 864 : function public
        "DMessageLoadDataDlg", // line 865 : function public
        "DMessageNoticeDlg", // line 866 : function public
        "ShowMDlg", // line 867 : procedure public
        "ShowGorupJoinDlg", // line 868 : procedure public
        "ResetMenuDlg", // line 869 : procedure public
        "CloseMDlg", // line 870 : procedure public
        "ToggleShowGroupDlg", // line 871 : procedure public
        "ViewBottomBox", // line 872 : procedure public
        "MySelfAbilChange", // line 873 : procedure public
        "MyHeroAbilChange", // line 874 : procedure public
        "SetMagicKeyDlg", // line 875 : function public
        "CloseDKeySelDlg", // line 876 : procedure public
        "RefLoadConfig", // line 877 : procedure public
        "OpenUserState", // line 878 : procedure public
        "AttactkModeChange", // line 879 : procedure public
        "OpenDChallengeDlg", // line 880 : procedure public
        "CloseDChallengeDlg", // line 881 : procedure public
        "RefreshChallengeDlg", // line 882 : procedure public
        "OpenDUpgradeDlg", // line 883 : procedure public
        "CloseDUpgradeDlg", // line 884 : procedure public
        "OpenDRandomCodeDlg", // line 885 : procedure public
        "CloseDRandomCodeDlg", // line 886 : procedure public
        "ReInputDRandomCode", // line 887 : procedure public
        "NpcItemButtonDirectPaint", // line 888 : procedure public
        "NpcItemButtonMouseMove", // line 889 : procedure public
        "NpcUserItemButtonDirectPaint", // line 890 : procedure public
        "NpcUserItemButtonMouseMove", // line 891 : procedure public
        "NpcLabelMouseMove", // line 894 : procedure public
        "NpcButtonMouseMove", // line 897 : procedure public
        "ItemBoxButtonClick", // line 900 : procedure public
        "ItemBoxButtonMouseMove", // line 901 : procedure public
        "ItemBoxButtonStartSubDirectPaint", // line 902 : procedure public
        "ProgressButtonStartSubDirectPaint", // line 903 : procedure public
        "DCloseStateClick", // line 904 : procedure public
        "DSSrvCloseClick", // line 905 : procedure public
        "DOpenShopClick", // line 906 : procedure public
        "DMyHeroStateClick", // line 907 : procedure public
        "DMyHeroStateCloseClick", // line 908 : procedure public
        "DMyHeroBagClick", // line 909 : procedure public
        "DMyHeroBagCloseClick", // line 910 : procedure public
        "LabelDStateWinCharNameClick", // line 911 : procedure public
        "CancelItemMoving", // line 912 : procedure public
        "CancelMagicMoving", // line 913 : procedure public
        "DropMovingItem", // line 914 : procedure public
        "SoldOutGoods", // line 915 : procedure public
        "DelStorageItem", // line 916 : procedure public
        "GetMouseItemInfo", // line 917 : procedure public
        "GetMouseItemInfo", // line 918 : procedure public
        "ShowMouseItemInfo", // line 919 : procedure public
        "ShowMouseItemInfo", // line 920 : procedure public
        "GetMouseItemInfoWindow", // line 921 : procedure public
        "GetMouseFengHaoItemInfoWindow", // line 922 : procedure public
        "GetTzItemHintWindow", // line 923 : function public
        "GetTzItemHintWindowEx", // line 924 : function public
        "ClearMerchantSay", // line 925 : procedure public
        "ClearMerchantSay", // line 926 : procedure public
        "AddGuildChat", // line 927 : procedure public
        "AddMissionMemo1", // line 928 : procedure public
        "AddMissionMemo2", // line 929 : procedure public
        "DrawGridItem", // line 932 : procedure public
        "DrawGridItemEx", // line 935 : procedure public
        "DrawGridStdItem", // line 936 : procedure public
        "DrawBodyItem", // line 939 : procedure public
        "DrawBodyItemBelowEffect", // line 942 : procedure public
        "DrawBodyItemEffect", // line 943 : procedure public
        "DrawBodyItemEffect", // line 944 : procedure public
        "CheckDGameShopDlgVisible", // line 945 : function public
        "OpenDGameShopDlg", // line 946 : procedure public
        "CloseDGameShopDlg", // line 947 : procedure public
        "OpenDMyShopDlg", // line 948 : procedure public
        "CloseDMyShopDlg", // line 949 : procedure public
        "OpenDUserShopDlg", // line 950 : procedure public
        "CloseDUserShopDlg", // line 951 : procedure public
        "CheckDHeroM2ShopDlgVisible", // line 952 : function public
        "OpenDHeroM2ShopDlg", // line 953 : procedure public
        "CloseDHeroM2ShopDlg", // line 954 : procedure public
        "CloseDHeroM2InputPriceDlg", // line 957 : procedure public
        "OpenDHeroM2ShopRemoteDlg", // line 958 : procedure public
        "CloseDHeroM2ShopRemoteDlg", // line 959 : procedure public
        "DBotUserShopClick", // line 960 : procedure public
        "DDownHorseClick", // line 961 : procedure public
        "DWebClick", // line 962 : procedure public
        "DActionLogClick", // line 963 : procedure public
        "SetMyShopPageCount", // line 964 : procedure public
        "SetGameShopPageCount", // line 965 : procedure public
        "SetUserShopItemPageCount", // line 966 : procedure public
        "DDeleteHumanDlgCloseClick", // line 967 : procedure public
        "DGetBackDeleteHumanClick", // line 968 : procedure public
        "DListViewDeleteHumanListItemClick", // line 969 : procedure public
        "DSpecialCmdMenuClick", // line 970 : procedure public
        "MerchantDlgPaint", // line 971 : procedure public
        "DDiceDlgProcess", // line 972 : procedure public
        "DChallengeItemReturnBag", // line 973 : procedure public
        "ChallengeZeroGold", // line 974 : procedure public
        "DChallengeOkClick", // line 975 : procedure public
        "DChallengeCloseClick", // line 976 : procedure public
        "DDChallengeGoldClick", // line 977 : procedure public
        "DChallengeGridGridPaint", // line 978 : procedure public
        "DChallengeGridGridSelect", // line 979 : procedure public
        "DChallengeGridGridMouseMove", // line 980 : procedure public
        "DChallengeRemoteGridGridPaint", // line 981 : procedure public
        "DChallengeRemoteGridGridMouseMove", // line 982 : procedure public
        "DControlHelpClick", // line 983 : procedure public
        "DRandomCodeDlgDirectPaint", // line 984 : procedure public
        "DItemBagDirectPaint", // line 985 : procedure public
        "DStPageUpClick", // line 986 : procedure public
        "DMainBottomCenterHeightChangeQuery", // line 987 : procedure public
        "DMainBottomCenterHeightChanged", // line 988 : procedure public
        "DMainBottomDlgStartSubPaint", // line 989 : procedure public
        "DMagicBallStopPaint", // line 990 : procedure public
        "DMagicBallGetHumAbility", // line 991 : procedure public
        "OnGetGroupAttackProgress", // line 992 : procedure public
        "DStateMemo4DirectPaint", // line 993 : procedure public
        "DHeroStateWinDirectPaint", // line 994 : procedure public
        "DBotMiniMapClick", // line 995 : procedure public
        "DUserState1DirectPaint", // line 996 : procedure public
        "DWeaponUS1MouseMove", // line 997 : procedure public
        "DMinMapDlgDirectPaint", // line 998 : procedure public
        "DSelectChrWindowsPaint", // line 999 : procedure public
        "DSWWeaponMouseMove", // line 1000 : procedure public
        "ItemBagDirectPaint", // line 1001 : procedure public
        "StPageUpClick", // line 1002 : procedure public
        "MainBottomCenterHeightChangeQuery", // line 1003 : procedure public
        "MainBottomCenterHeightChanged", // line 1004 : procedure public
        "MainBottomDlgStartSubPaint", // line 1005 : procedure public
        "MagicBallStopPaint", // line 1006 : procedure public
        "StateMemo4DirectPaint", // line 1007 : procedure public
        "HeroStateWinDirectPaint", // line 1008 : procedure public
        "BotMiniMapClick", // line 1009 : procedure public
        "UserState1DirectPaint", // line 1010 : procedure public
        "WeaponUS1MouseMove", // line 1011 : procedure public
        "MinMapDlgDirectPaint", // line 1012 : procedure public
        "SelectChrWindowsPaint", // line 1013 : procedure public
        "SWWeaponMouseMove", // line 1014 : procedure public
        "OpenDBoxDlg", // line 1015 : procedure public
        "CloseDBoxDlg", // line 1016 : procedure public
        "OpenDItemBoxDlg", // line 1017 : procedure public
        "CloseDItemBoxDlg", // line 1018 : procedure public
        "SetGuessfinger", // line 1019 : procedure public
        "SetDrinkDrunkValue", // line 1020 : procedure public
        "CheckShowRemoveStoneForm", // line 1022 : function public
        "ShowRemoveStoneForm", // line 1023 : procedure public
        "CheckDMinMapBigDlgMouseDown", // line 1024 : function public
        "CheckDMinMapBigDlgVisible", // line 1025 : function public
        "OpenDMinMapBigDlg", // line 1026 : procedure public
        "CloseDMinMapBigDlg", // line 1027 : procedure public
        "CheckDMinMapExDlgVisible", // line 1028 : function public
        "CheckDMinMapExShowButton", // line 1029 : function public
        "OpenDMinMapExDlg", // line 1030 : procedure public
        "CloseDMinMapExDlg", // line 1031 : procedure public
        "SelectChrWindowsPaint205", // line 1032 : procedure public
        "DStUpgradeMagicButtonClick", // line 1033 : procedure public
        "DStHeroUpgradeMagicButtonClick", // line 1034 : procedure public
        "DStUpgradeMagicMouseMove", // line 1035 : procedure public
        "DHeroStUpgradeMagicMouseMove", // line 1036 : procedure public
        "DStateRefurbishLabelClick", // line 1037 : procedure public
        "GuildGroupIndex", // line 1038 : property public
        "ClearDMissionMemo", // line 1041 : procedure public
        "DMouseMoveClearHints", // line 1042 : procedure public
        "DNpcScrollBoxMove", // line 1043 : procedure public
        "DNpcScrollBoxDown", // line 1044 : procedure public
        "DNpcScrollBoxUp", // line 1045 : procedure public
        "DLieDragonPaint", // line 1048 : procedure public
        "DLieDragonClosePaint", // line 1050 : procedure public
        "DLieDragonCloseClick", // line 1052 : procedure public
        "DLieDragonNextPagePaint", // line 1054 : procedure public
        "DLieDragonPrevPagePaint", // line 1056 : procedure public
        "DLieDragonNextPageClick", // line 1058 : procedure public
        "DGoToLieDragontPaint", // line 1060 : procedure public
        "DGoToLieDragonClick", // line 1062 : procedure public
        "DLieDragonNpcPaint", // line 1064 : procedure public
        "DLieDragonNpcCloseClick", // line 1066 : procedure public
        "DSayItemDlgPaint", // line 1069 : procedure public
        "DSayItemDlgCloseClick", // line 1070 : procedure public
        "DSayItemDlgMouseDown", // line 1071 : procedure public
        "DSayItemDlgMouseMove", // line 1072 : procedure public
        "DUpdateStatusDlgPaint", // line 1073 : procedure public
        "DUpdateStatusDlgMouseEnter", // line 1074 : procedure public
        "DUpdateStatusDlgMouseLeave", // line 1075 : procedure public
        "DUpdateStatusDlgDblClick", // line 1076 : procedure public
        "UpdateBusinessStatusText", // line 1079 : procedure public
        "UpdateShopMoneyInfo", // line 1080 : procedure public
        "GetLastHistroySendSay", // line 1082 : function public
        "GetPreHistroySendSay", // line 1083 : function public
        "GetNextHistroySendSay", // line 1084 : function public
        "IsInputChatEdit", // line 1085 : function public
        "ShowChatEdit", // line 1086 : procedure public
        "HideChatEdit", // line 1087 : procedure public
        "FindMagicButton", // line 1088 : function public
        "ClearScreenMagicButtons", // line 1089 : procedure public
        "AddScreenMagicButton", // line 1090 : procedure public
        "DelScreenMagicButton", // line 1091 : procedure public
        "DelScreenMagicButton", // line 1092 : procedure public
        "SaveMagicButtons", // line 1093 : procedure public
        "LoadMagicButtons", // line 1094 : procedure public
        "SetAuctionPageCount", // line 1095 : procedure public
        "RequestAuctionItems", // line 1096 : procedure public
        "OpenGameLevelDlg", // line 1097 : procedure public
        "CloseGameLevelDlg", // line 1098 : procedure public
        "RefreshGuardianLevelStatueMonHP", // line 1099 : procedure public
        "SetGuardianLevelBatchNo", // line 1100 : procedure public
        "ShowGuardianLevelResult", // line 1101 : procedure public
        "RefreshAdjustAbilityValue", // line 1102 : procedure public
        "DMessageDlgDeleteUser", // line 1103 : function public
        "DCustomButtonClick", // line 1104 : procedure public
        "RestoreButton_DItemBagArrange", // line 1105 : procedure public
        "ResetBagPageButton", // line 1106 : procedure public
        "ClearNewGroupMember", // line 1107 : procedure public
        "RefreshNewGroupMember", // line 1108 : procedure public
        "ReshowNewGroupMember", // line 1109 : procedure public
        "CheckDMinMapDlgExVisible", // line 1110 : function public
        "ReSetControl", // line 1111 : procedure public
        "OpenDBetterItemDlg", // line 1112 : procedure public
        "CloseDBetterItemDlg", // line 1113 : procedure public
    };

    /// <summary>Full source declaration text, 1:1, for verbatim read back comparison.</summary>
    public static readonly string[] Decls =
    {
        "procedure OnMagicButtonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 493
        "procedure OnMagicButtonDblClick(Sender:TObject; X, Y:Integer); stdcall;", // line 494
        "procedure OnMagicButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 495
        "procedure OnMagicButtonMove(Sender:TObject); stdcall;", // line 496
        "function CreateNpcQRButtonFromText(sText:string; AOwner:TDxControl; nX, nY:Integer; nDID:Integer):TNpcGraphicButton;", // line 499
        "constructor Create; virtual;", // line 533
        "destructor Destroy(); override;", // line 534
        "procedure UpDate; virtual;", // line 535
        "procedure DBottomInRealArea(Sender:TObject; X, Y:Integer; var IsRealArea:Boolean); stdcall;", // line 536
        "procedure DItemGridGridSelect(Sender:TObject; ACol, ARow:Integer; Button:TMouseButton; Shift:TShiftState); stdcall;", // line 537
        "procedure DItemGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 538
        "procedure DItemGridDblClick(Sender:TObject; X, Y:Integer); stdcall;", // line 539
        "procedure DBackgroundBackgroundClick(Sender:TObject); stdcall;", // line 540
        "procedure DItemGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 541
        "procedure DBelt1DirectPaint(Sender:TObject); stdcall;", // line 542
        "procedure DBelt1DblClick(Sender:TObject; X, Y:Integer); stdcall;", // line 543
        "procedure DLoginCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 544
        "procedure DLoginOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 545
        "procedure DLoginNewClick(Sender:TObject; X, Y:Integer); stdcall;", // line 546
        "procedure DLoginChgPwClick(Sender:TObject; X, Y:Integer); stdcall;", // line 547
        "procedure DNewAccountOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 548
        "procedure DNewAccountCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 549
        "procedure DChgpwOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 550
        "procedure DChgpwCancelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 551
        "procedure DSWWeaponClick(Sender:TObject; X, Y:Integer); stdcall;", // line 552
        "procedure DCloseBagClick(Sender:TObject; X, Y:Integer); stdcall;", // line 553
        "procedure DBelt1Click(Sender:TObject; X, Y:Integer); stdcall;", // line 554
        "procedure DStateWinClick(Sender:TObject; X, Y:Integer); stdcall;", // line 555
        "procedure DBelt1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 556
        "procedure DBelt1MouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 557
        "procedure DMerchantDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 558
        "procedure DMerchantDlgClick(Sender:TObject; X, Y:Integer); stdcall;", // line 559
        "procedure DMenuCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 560
        "procedure DMenuDlgDirectPaint(Sender:TObject); stdcall;", // line 561
        "procedure DMenuDlgClick(Sender:TObject; X, Y:Integer); stdcall;", // line 562
        "procedure DMenuDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 563
        "procedure DSellDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 564
        "procedure DSellDlgSpotClick(Sender:TObject; X, Y:Integer); stdcall;", // line 565
        "procedure DSellDlgSpotDirectPaint(Sender:TObject); stdcall;", // line 566
        "procedure DSellDlgSpotMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 567
        "procedure DSellDlgOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 568
        "procedure DMenuBuyClick(Sender:TObject; X, Y:Integer); stdcall;", // line 569
        "procedure DMenuPrevClick(Sender:TObject; X, Y:Integer); stdcall;", // line 570
        "procedure DMenuNextClick(Sender:TObject; X, Y:Integer); stdcall;", // line 571
        "procedure DGoldClick(Sender:TObject; X, Y:Integer); stdcall;", // line 572
        "procedure DSWLightDirectPaint(Sender:TObject); stdcall;", // line 573
        "procedure DBackgroundMouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 574
        "procedure DStateWinMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 575
        "procedure DLoginNewClickSound(Sender:TObject; Clicksound:TClickSound); stdcall;", // line 576
        "procedure DStMag1Click(Sender:TObject; X, Y:Integer); stdcall;", // line 577
        "procedure DStMag1MouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 578
        "procedure DStMag1MouseUp(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 579
        "procedure DKsOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 582
        "procedure DDealOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 583
        "procedure DDealCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 584
        "procedure DBotTradeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 585
        "procedure BotChallengeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 586
        "procedure DDealRemoteDlgDirectPaint(Sender:TObject); stdcall;", // line 587
        "procedure DDealDlgDirectPaint(Sender:TObject); stdcall;", // line 588
        "procedure DDGridGridSelect(Sender:TObject; ACol, ARow:Integer; Button:TMouseButton; Shift:TShiftState); stdcall;", // line 589
        "procedure DDGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 590
        "procedure DDGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 591
        "procedure DDRGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 592
        "procedure DDRGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 593
        "procedure DDGoldClick(Sender:TObject; X, Y:Integer); stdcall;", // line 594
        "procedure DUserState1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 595
        "procedure DCloseUS1Click(Sender:TObject; X, Y:Integer); stdcall;", // line 596
        "procedure DNecklaceUS1DirectPaint(Sender:TObject); stdcall;", // line 597
        "procedure DGuildDlgDirectPaint(Sender:TObject); stdcall;", // line 598
        "procedure DGDUpClick(Sender:TObject; X, Y:Integer); stdcall;", // line 599
        "procedure DGDDownClick(Sender:TObject; X, Y:Integer); stdcall;", // line 600
        "procedure DGDCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 601
        "procedure DGDHomeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 602
        "procedure DGDListClick(Sender:TObject; X, Y:Integer); stdcall;", // line 603
        "procedure DGDAddMemClick(Sender:TObject; X, Y:Integer); stdcall;", // line 604
        "procedure DGDDelMemClick(Sender:TObject; X, Y:Integer); stdcall;", // line 605
        "procedure DGDEditNoticeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 606
        "procedure DGDEditGradeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 607
        "procedure DNewGuildDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 608
        "procedure DNewGuildNoticeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 609
        "procedure DGuildEditNoticeDirectPaint(Sender:TObject); stdcall;", // line 610
        "procedure DGDChatClick(Sender:TObject; X, Y:Integer); stdcall;", // line 611
        "procedure DAdjustAbilCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 612
        "procedure DBotPlusAbilClick(Sender:TObject; X, Y:Integer); stdcall;", // line 613
        "procedure DAdjustAbilOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 614
        "procedure DBotPlusAbilDirectPaint(Sender:TObject); stdcall;", // line 615
        "procedure DAdjustAbilityMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 616
        "procedure DUserState1MouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 617
        "procedure DChgGamePwdDirectPaint(Sender:TObject); stdcall;", // line 618
        "procedure DscSelect1InRealArea(Sender:TObject; X, Y:Integer; var IsRealArea:Boolean); stdcall;", // line 619
        "procedure DCreateChrDirectPaint(Sender:TObject); stdcall;", // line 620
        "procedure DItemBagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 621
        "procedure DBottomMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 622
        "procedure DNewAccountCancelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 623
        "procedure DHeroM2ShopDlgShowOnClick(Sender:TObject; X, Y:Integer); stdcall;", // line 624
        "procedure DShopDlgDirectPaint(Sender:TObject); stdcall;", // line 625
        "procedure DButtonShopPrevClick(Sender:TObject; X, Y:Integer); stdcall;", // line 626
        "procedure DButtonShopNextClick(Sender:TObject; X, Y:Integer); stdcall;", // line 627
        "procedure DBotRankingHomeClick(Sender:TObject; X, Y:Integer); stdcall;", // line 628
        "procedure DBotRankingUpClick(Sender:TObject; X, Y:Integer); stdcall;", // line 629
        "procedure DBotRankingDownClick(Sender:TObject; X, Y:Integer); stdcall;", // line 630
        "procedure DBotRankingLastClick(Sender:TObject; X, Y:Integer); stdcall;", // line 631
        "procedure DButtonShopBuyClick(Sender:TObject; X, Y:Integer); stdcall;", // line 632
        "procedure DButtonShopBuyGiveClick(Sender:TObject; X, Y:Integer); stdcall;", // line 633
        "procedure MinMapLevelChange; virtual;", // line 634
        "procedure DMinMapDlgShow(Sender:TObject); stdcall;", // line 635
        "procedure DMinMapDlgHide(Sender:TObject); stdcall;", // line 636
        "procedure DMinMapDlgResize(Sender:TObject); stdcall;", // line 637
        "procedure DMinMapDlgMouseEnter(Sender:TObject); stdcall;", // line 638
        "procedure DMinMapDlgMouseLeave(Sender:TObject); stdcall;", // line 639
        "procedure DMinMapDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 640
        "procedure DMinMapDlgMouseUP(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 641
        "procedure DMinMapDlgClick(Sender:TObject; X, Y:Integer); stdcall;", // line 642
        "procedure DscStartDirectPaint(Sender:TObject); stdcall;", // line 643
        "procedure DDiceDlgDirectPaint(Sender:TObject); stdcall;", // line 644
        "procedure OnGetImage(Sender:TObject; ImageType:TImageType; var AImage:TObject);", // line 645
        "procedure HideAllControls;", // line 646
        "procedure RestoreHideControls;", // line 647
        "procedure DealItemReturnBag(mitem:TClientItem);", // line 648
        "procedure DealZeroGold;", // line 649
        "procedure OpenSoundOption(Sender:TObject; X, Y:Integer); stdcall;", // line 650
        "function FindActiveControl(Sender:TObject; X, Y:Integer):TDxControl;", // line 653
        "procedure AddNpcMemo(AOwner:TDxControl; X, Y:Integer; AOnClick:TOnClickEx; Text:string; ChangeOwnerSize:Boolean = True; IsFromAddDlg:Boolean = False; OneLineHeight:Integer = 16; IsDesigning:Boolean = False);", // line 654
        "procedure LoadJsonControl(DOwner:TDxControl; aJson:ISuperObject);", // line 655
        "procedure DBotRankClick(Sender:TObject; X, Y:Integer); stdcall;", // line 656
        "procedure DBotWhisperClick(Sender:TObject; X, Y:Integer); stdcall;", // line 657
        "procedure DBotHorseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 658
        "procedure DOptionClick(Sender:TObject; X, Y:Integer); stdcall;", // line 659
        "procedure DWhisperDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 660
        "procedure DRankingDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 661
        "procedure DShopDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 662
        "procedure DMissionDlgClick(Sender:TObject; X, Y:Integer); stdcall;", // line 663
        "procedure DMissionDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 664
        "procedure DGrpDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 665
        "procedure DBotGroupClick(Sender:TObject; X, Y:Integer); stdcall;", // line 666
        "procedure DGrpAllowGroupClick(Sender:TObject; X, Y:Integer); stdcall;", // line 667
        "procedure DBotGroupMouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 668
        "procedure DBotExitClick(Sender:TObject; X, Y:Integer); stdcall;", // line 671
        "procedure DGDAllyClick(Sender:TObject; X, Y:Integer); stdcall;", // line 672
        "procedure DGDBreakAllyClick(Sender:TObject; X, Y:Integer); stdcall;", // line 673
        "procedure DButtonFriendClick(Sender:TObject; X, Y:Integer); stdcall;", // line 674
        "procedure DBotRankingClick(Sender:TObject; X, Y:Integer); stdcall;", // line 675
        "procedure DBotRankingCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 676
        "procedure DBotFriendClick(Sender:TObject; X, Y:Integer); stdcall;", // line 677
        "procedure DFrdCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 678
        "procedure DChgGamePwdCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 679
        "procedure DGameGoldDealDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 680
        "procedure DGameGoldDealMenuDlgPaint(Sender:TObject); stdcall;", // line 681
        "procedure DGameGoldDealMenuDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 682
        "procedure DGameGoldDealGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 683
        "procedure DGameGoldDealGridGridSelect(Sender:TObject; ACol, ARow:Integer; Button:TMouseButton; Shift:TShiftState); stdcall;", // line 684
        "procedure DGameGoldDealGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 685
        "procedure DGameGoldDealDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 686
        "procedure DGameGoldDealCancelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 687
        "procedure DGameGoldDealMenuDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 688
        "procedure DBuyGameGoldDealItemOKClick(Sender:TObject; X, Y:Integer); stdcall;", // line 689
        "procedure DBuyGameGoldDealItemCancelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 690
        "procedure DGameGoldDealItemCancelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 691
        "procedure DBotFuncClick(Sender:TObject; X, Y:Integer); stdcall;", // line 692
        "procedure DBotFuncMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 693
        "procedure DStMagMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 694
        "procedure DMissionMerchantDlgClick(Sender:TObject; X, Y:Integer); stdcall;", // line 695
        "procedure DNPC_IMG_PAINT(Sender:TObject); stdcall;", // line 696
        "procedure DNPC_IMGEX_PAINT(Sender:TObject); stdcall;", // line 697
        "procedure DNPC_IMGNUM_PAINT(Sender:TObject); stdcall;", // line 698
        "procedure DNPC_PLAYIMG_PAINT(Sender:TObject); stdcall;", // line 699
        "procedure DNPC_IMGPAY_PAINT(Sender:TObject); stdcall;", // line 700
        "procedure Close; virtual;", // line 701
        "function MakeShareControlAddrList():THashedStringList; virtual;", // line 702
        "procedure LoadShareFromStream(MemoryStream:TMemoryStream); virtual;", // line 703
        "procedure OpenDSelectChrDlg; virtual;", // line 704
        "procedure Initialize; virtual; abstract;", // line 705
        "procedure LoadFromStream(MemoryStream:TMemoryStream); virtual; abstract;", // line 706
        "function MakeControlAddrList():THashedStringList; virtual; abstract;", // line 707
        "function GetMissionTreeView(Index:Integer):TDxTreeView; virtual; abstract;", // line 708
        "function GetMissionActivePageIndex:Integer; virtual; abstract;", // line 709
        "procedure SetMissionActivePageIndex(Index:Integer); virtual; abstract;", // line 710
        "procedure MissionPageClear; virtual; abstract;", // line 711
        "procedure LoginPasswdOK; virtual; abstract;", // line 712
        "procedure OpenDLoginDlg; virtual; abstract;", // line 713
        "procedure CloseDLoginDlg; virtual; abstract;", // line 714
        "procedure OpenDDoorDlg; virtual; abstract;", // line 715
        "procedure CloseDDoorDlg; virtual; abstract;", // line 716
        "procedure OpenDRealNameDlg; virtual; abstract;", // line 718
        "procedure CloseDRealNameDlg; virtual; abstract;", // line 719
        "procedure OpenDGetPwdBackDlg; virtual; abstract;", // line 721
        "procedure CloseDGetPwdBackDlg; virtual; abstract;", // line 722
        "procedure OpenDRegAccount; virtual; abstract;", // line 724
        "procedure CloseDRegAccount; virtual; abstract;", // line 725
        "procedure OpenDBindPhone; virtual; abstract;", // line 727
        "procedure CloseDBindPhone; virtual; abstract;", // line 728
        "function CheckUserEntrys:Boolean; virtual; abstract;", // line 729
        "procedure NewIdRetry(ue:TUserEntry; ua:TUserEntryAdd); virtual; abstract;", // line 730
        "procedure NewAccountOk(ue:pTUserEntry; ua:pTUserEntryAdd); virtual; abstract;", // line 731
        "procedure OpenDNewAccountDlg; virtual; abstract;", // line 732
        "procedure CloseDNewAccountDlg; virtual; abstract;", // line 733
        "procedure ChangePassWordOK(); virtual; abstract;", // line 734
        "procedure OpenDChgPwDlg; virtual; abstract;", // line 735
        "procedure CloseDChgPwDlg; virtual; abstract;", // line 736
        "procedure OpenDSelServerDlg; virtual; abstract;", // line 737
        "procedure CloseDSelServerDlg; virtual; abstract;", // line 738
        "procedure CloseDSelectChrDlg; virtual; abstract;", // line 739
        "procedure OpenDCreateChrDlg(Left, Top:Integer); virtual; abstract;", // line 740
        "procedure CloseDCreateChrDlg; virtual; abstract;", // line 741
        "procedure MakeNewChar(Index:Integer; UserChr:pTUserCharacterInfo); virtual; abstract;", // line 742
        "procedure OpenDMerchantDlg; virtual; abstract;", // line 743
        "procedure CloseDMerchantDlg; virtual; abstract;", // line 744
        "procedure RestoreDMerchantDlg; virtual; abstract;", // line 745
        "procedure OpenDMenuDlg(IsTrading:Boolean); virtual; abstract;", // line 746
        "procedure CloseDMenuDlg; virtual; abstract;", // line 747
        "procedure OpenTradingMarketItemsDlg; virtual; abstract;", // line 748
        "procedure RecallTradingSellPrices; virtual; abstract;", // line 749
        "function CheckDStorageViewDlgShow(IsStorageViewDlgIsExt:Boolean):Boolean; virtual; abstract;", // line 750
        "procedure OpenDStorageViewDlg(Merchant:Int64; IsTakeBackItem:Boolean; ResetPosition, IsStorageViewDlgIsExt:Boolean; PosX:Integer = 0; PosY:Integer = 0); virtual; abstract;", // line 751
        "procedure RefrshDStorageViewDlgText(IsStorageViewDlgIsExt:Boolean; ACount, AMaxCount, APage, AMaxPage:Integer); virtual;", // line 752
        "procedure RefrshDStorageOpen(); virtual; abstract;", // line 753
        "function CheckDTradingMarketDlgVisible:Boolean; virtual; abstract;", // line 754
        "procedure OpenDItemBagDlg; virtual; abstract;", // line 755
        "procedure CloseDItemBagDlg; virtual; abstract;", // line 756
        "procedure OpenDAuctionDlg(nPage:Integer; ShowAuctionID:Integer = 0); virtual; abstract;", // line 757
        "procedure CloseDAuctionDlg; virtual; abstract;", // line 758
        "procedure CloseDAuctionBuyDlg; virtual; abstract;", // line 759
        "procedure CloseDAuctionSellDlg; virtual; abstract;", // line 760
        "procedure OpenDAuctionBroadcastDlg(sText:string; nAuctionID, nShowTime:Integer); virtual; abstract;", // line 761
        "procedure CloseDAuctionBroadcastDlg; virtual; abstract;", // line 762
        "procedure OpenSellPlayDlg(CurrentType:Integer); virtual; abstract;", // line 763
        "procedure OpenDelSellPlayDlg(Players:string); virtual; abstract;", // line 764
        "procedure OpenSellPlayerShopDlg(CurrentType:Integer); virtual; abstract;", // line 765
        "procedure SetSellPlayerShopItemPageInfo(Page, MaxPage, ViewStorageOption:Integer); virtual; abstract;", // line 766
        "procedure OpenViewSellPlayerInfo; virtual; abstract;", // line 767
        "procedure OpenViewSellPlayerBagItems(SellPlayerMoney:PSellPlayerMoney; ExtBagOpenItemCount, ExtBagPageCount:Word); virtual; abstract;", // line 768
        "procedure OpenViewSellPlayerStorage(Header:PTSellPlayerStorageViewHeader; HeaderExt:PTSellPlayerStorageExtViewHeader); virtual; abstract;", // line 769
        "procedure SellPlayerAbilChange; virtual; abstract;", // line 770
        "procedure ShowSellPlayerOtherInfo(msgstr:string; TextOffsetX, TextOffsetY:Integer); virtual; abstract;", // line 771
        "procedure ClearSellPlayerOtherInfo; virtual; abstract;", // line 772
        "procedure OpenDSellDlg(nPage:Integer); virtual; abstract;", // line 773
        "procedure CloseDSellDlg; virtual; abstract;", // line 774
        "procedure OpenDDealDlg; virtual; abstract;", // line 775
        "procedure CloseDDealDlg; virtual; abstract;", // line 776
        "procedure OpenDDealRemoteDlg; virtual; abstract;", // line 777
        "procedure CloseDDealRemoteDlg; virtual; abstract;", // line 778
        "procedure OpenDStateWinDlg; virtual; abstract;", // line 779
        "procedure CloseDStateWinDlg; virtual; abstract;", // line 780
        "procedure OpenDShopDlg; virtual; abstract;", // line 781
        "procedure CloseDShopDlg; virtual; abstract;", // line 782
        "procedure OpenDUserState1Dlg; virtual; abstract;", // line 783
        "procedure CloseDUserState1Dlg; virtual; abstract;", // line 784
        "procedure OpenDFriendDlg; virtual; abstract;", // line 785
        "procedure CloseDFriendDlg; virtual; abstract;", // line 786
        "procedure OpenDGroupDlg; virtual; abstract;", // line 787
        "procedure CloseDGroupDlg; virtual; abstract;", // line 788
        "procedure OpenDWhisperDlg; virtual; abstract;", // line 789
        "procedure CloseDWhisperDlg; virtual; abstract;", // line 790
        "procedure OpenDRankingDlg; virtual; abstract;", // line 791
        "procedure CloseDRankingDlg; virtual; abstract;", // line 792
        "procedure OpenDGameGoldDealDlg; virtual; abstract;", // line 793
        "procedure CloseDGameGoldDealDlg; virtual; abstract;", // line 794
        "procedure OpenDGameGoldDealMenuDlg(DealCancel:Boolean); virtual; abstract;", // line 795
        "procedure CloseDGameGoldDealMenuDlg; virtual; abstract;", // line 796
        "procedure OpenDGuildDlg(IsNew:Boolean; boEnabledAlly:Boolean); virtual; abstract;", // line 797
        "procedure CloseDGuildDlg; virtual; abstract;", // line 798
        "procedure DGuildChangeRankNo; virtual; abstract;", // line 799
        "procedure UpdateGuildJoinCondition(AJob:Integer; ALevel:Integer; AMsg:string); virtual;", // line 800
        "procedure RefreshDGuildManageListViewWJ; virtual; abstract;", // line 801
        "procedure OpenGuildViewMemeberInfo(MemberInfo:TGuildMemeberInfo); virtual;", // line 802
        "procedure OpenGuildEditGradeDlg; virtual; abstract;", // line 803
        "procedure OpenDGuildEditNoticeDlg; virtual; abstract;", // line 804
        "procedure CloseDGuildEditNoticeDlg; virtual; abstract;", // line 805
        "procedure RefreshGuildMembers(GroupIndex:Integer); virtual; abstract;", // line 806
        "procedure CloseDGuildDlg_New; virtual; abstract;", // line 807
        "procedure OpenDGuildEditNoticeDlg_New; virtual; abstract;", // line 808
        "procedure RefreshGuildJoinUserList; virtual; abstract;", // line 809
        "procedure DoSetGuildWantAddGuildName(S:string); virtual; abstract;", // line 810
        "procedure OpenDGuildApplyDlg; virtual; abstract;", // line 811
        "procedure CloseDGuildApplyDlg; virtual; abstract;", // line 812
        "procedure OpenDGuildNoticeDlg(GuildName:string; JoinMsg:string; JoinJob, JoinLevel:Integer); virtual; abstract;", // line 813
        "procedure CloseDGuildNoticeDlg; virtual; abstract;", // line 814
        "procedure OpenDMissionDlg(X:Integer = 0; Y:Integer = 0); virtual; abstract;", // line 815
        "procedure CloseDMissionDlg; virtual; abstract;", // line 816
        "procedure OpenDAdjustAbilityDlg; virtual; abstract;", // line 817
        "procedure CloseDAdjustAbilityDlg; virtual; abstract;", // line 818
        "function IsDAdjustAbilityDlgShow:Boolean; virtual; abstract;", // line 819
        "procedure OpenDHeroStateDlg; virtual; abstract;", // line 820
        "procedure CloseDHeroStateDlg; virtual; abstract;", // line 821
        "procedure OpenDHeroItemBagDlg; virtual; abstract;", // line 822
        "procedure CloseDHeroItemBagDlg; virtual; abstract;", // line 823
        "procedure OpenDHeroStateWinDlg; virtual; abstract;", // line 824
        "procedure CloseDHeroStateWinDlg; virtual; abstract;", // line 825
        "procedure SetHeroBagCount(BagCount:Integer); virtual; abstract;", // line 826
        "procedure CloseDHeroJewelryBoxDlg; virtual;", // line 827
        "procedure CloseDHeroGodBlessDlg; virtual;", // line 828
        "procedure OpenDDeleteHumanDlg; virtual; abstract;", // line 829
        "procedure CloseDDeleteHumanDlg; virtual; abstract;", // line 830
        "procedure OpenMyStatus; virtual; abstract;", // line 831
        "procedure OpenMyMagic; virtual; abstract;", // line 832
        "procedure AddDDrinkWineDlgSay(nPos:Integer; Text:string); virtual; abstract;", // line 833
        "procedure OpenDPleaseDrinkWineDlg(sNpcName:string; nIcon:Integer); virtual; abstract;", // line 834
        "procedure CloseDPleaseDrinkWineDlg; virtual; abstract;", // line 835
        "procedure OpenDGuessfingerDlg(sNpcName:string; nIcon:Integer); virtual; abstract;", // line 836
        "procedure CloseDGuessfingerDlg; virtual; abstract;", // line 837
        "procedure OpenDMakeWineDlg; virtual; abstract;", // line 838
        "procedure CloseDMakeWineDlg; virtual; abstract;", // line 839
        "procedure OpenDMakeMedicinalWineDlg; virtual; abstract;", // line 840
        "procedure CloseDMakeMedicinalWineDlg; virtual; abstract;", // line 841
        "procedure OpenDStorageHeroInfoDlg; virtual; abstract;", // line 842
        "procedure CloseDStorageHeroInfoDlg; virtual; abstract;", // line 843
        "procedure OpenDHeroAppraisalInfoDlg; virtual; abstract;", // line 846
        "procedure CloseDHeroAppraisalInfoDlg; virtual; abstract;", // line 847
        "procedure OpenDHeroAppraisalDlg; virtual; abstract;", // line 848
        "procedure CloseDHeroAppraisalDlg; virtual; abstract;", // line 849
        "procedure OpenDHeroAutoPracticeDlg; virtual; abstract;", // line 851
        "procedure CloseDHeroAutoPracticeDlg; virtual; abstract;", // line 852
        "procedure ShowCollectProgressBarDlg(Progress:Integer; Text:string); virtual; abstract;", // line 853
        "procedure CloseCollectProgressBarDlg; virtual; abstract;", // line 854
        "procedure BringToFrontCollectProgressBarDlg; virtual; abstract;", // line 855
        "procedure ShowProgressBarDlg(Text:string); virtual; abstract;", // line 856
        "procedure CloseProgressBarDlg; virtual; abstract;", // line 857
        "procedure ShowSayItemDlg(Item:PTClientItem; X, Y:Integer); virtual; abstract;", // line 858
        "procedure CloseSayItemDlg(X, Y:Integer);", // line 859
        "procedure ShowDGJPointsDlg; virtual; abstract;", // line 860
        "function IsDGJPointsShow:Boolean; virtual; abstract;", // line 861
        "function GetUserStateShieldRect:TRect; virtual; abstract;", // line 862
        "function DMessageDlg(MsgStr:string; DlgButtons:TMsgDlgButtons; DefaultText:string = \u0027\u0027; MaxLen:Integer = 0):TModalResult; virtual; abstract;", // line 863
        "function DMessageDiceDlg:TModalResult; virtual; abstract;", // line 864
        "function DMessageLoadDataDlg(MsgStr:string):TModalResult; virtual; abstract;", // line 865
        "function DMessageNoticeDlg(MsgStr:string):TModalResult; virtual; abstract;", // line 866
        "procedure ShowMDlg(face:Integer; mname, msgstr:string; boSetBagItemPos:Boolean = True; IsDesigning:Boolean = False); virtual;", // line 867
        "procedure ShowGorupJoinDlg(MsgStr:string; Data:string); virtual; abstract;", // line 868
        "procedure ResetMenuDlg(ClearMenuList:Boolean = True); virtual; abstract;", // line 869
        "procedure CloseMDlg; virtual; abstract;", // line 870
        "procedure ToggleShowGroupDlg; virtual; abstract;", // line 871
        "procedure ViewBottomBox(Visible:Boolean); virtual; abstract;", // line 872
        "procedure MySelfAbilChange; virtual; abstract;", // line 873
        "procedure MyHeroAbilChange; virtual; abstract;", // line 874
        "function SetMagicKeyDlg(MagicName:string; Icon:TGameImages; IconIndex:Integer; var MagicKey:Char):Boolean; virtual; abstract;", // line 875
        "procedure CloseDKeySelDlg; virtual; abstract;", // line 876
        "procedure RefLoadConfig; virtual; abstract;", // line 877
        "procedure OpenUserState(); virtual; abstract;", // line 878
        "procedure AttactkModeChange; virtual;", // line 879
        "procedure OpenDChallengeDlg; virtual;", // line 880
        "procedure CloseDChallengeDlg; virtual;", // line 881
        "procedure RefreshChallengeDlg; virtual;", // line 882
        "procedure OpenDUpgradeDlg; virtual;", // line 883
        "procedure CloseDUpgradeDlg; virtual;", // line 884
        "procedure OpenDRandomCodeDlg; virtual;", // line 885
        "procedure CloseDRandomCodeDlg; virtual;", // line 886
        "procedure ReInputDRandomCode; virtual;", // line 887
        "procedure NpcItemButtonDirectPaint(Sender:TObject); stdcall;", // line 888
        "procedure NpcItemButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 889
        "procedure NpcUserItemButtonDirectPaint(Sender:TObject); stdcall;", // line 890
        "procedure NpcUserItemButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 891
        "procedure NpcLabelMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 894
        "procedure NpcButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 897
        "procedure ItemBoxButtonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 900
        "procedure ItemBoxButtonMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 901
        "procedure ItemBoxButtonStartSubDirectPaint(Sender:TObject); stdcall;", // line 902
        "procedure ProgressButtonStartSubDirectPaint(Sender:TObject); stdcall;", // line 903
        "procedure DCloseStateClick(Sender:TObject; X, Y:Integer); stdcall;", // line 904
        "procedure DSSrvCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 905
        "procedure DOpenShopClick(Sender:TObject; X, Y:Integer); stdcall;", // line 906
        "procedure DMyHeroStateClick(Sender:TObject; X, Y:Integer); stdcall;", // line 907
        "procedure DMyHeroStateCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 908
        "procedure DMyHeroBagClick(Sender:TObject; X, Y:Integer); stdcall;", // line 909
        "procedure DMyHeroBagCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 910
        "procedure LabelDStateWinCharNameClick(Sender:TObject; X, Y:Integer); stdcall;", // line 911
        "procedure CancelItemMoving;", // line 912
        "procedure CancelMagicMoving;", // line 913
        "procedure DropMovingItem;", // line 914
        "procedure SoldOutGoods(nMakeIndex, nItemCount:Integer; sData:string; IsFromTradingDlg:Boolean);", // line 915
        "procedure DelStorageItem(itemserverindex, nCount:Integer);", // line 916
        "procedure GetMouseItemInfo(Actor:TActor; MouseItem:pTClientItem; Secret:Boolean; var iname, line1, line2, line3:string; var IsUseableLine2, IsUseableLine3:Boolean); overload;", // line 917
        "procedure GetMouseItemInfo(Actor:TActor; MouseItem:pTClientItem; Secret:Boolean; HintList:TArrHintWindows; boFromTitile:Boolean = False; boShowSellPrice:Boolean = True; TZWin:TList = nil; IsShowCompareImage:Boolean = False); overload;", // line 918
        "procedure ShowMouseItemInfo(Actor:TActor; MouseItem:pTClientItem; X, Y:Integer; Secret:Boolean; ShowTzItemDesc:Byte = 0; DrawUp:Boolean = False; DrawLeft:Boolean = False; boCompareUseItem:Boolean = False; boShowSellPrice:Boolean = True; boHeroM2ShopItem:Boolean = False); overload;", // line 919
        "procedure ShowMouseItemInfo(Actor:TActor; MouseItem:pTClientItem; X, Y:Integer; Secret:Boolean; HintList:TList; ShowTzItemDesc:Byte = 0; DrawUp:Boolean = False; DrawLeft:Boolean = False); overload;", // line 920
        "procedure GetMouseItemInfoWindow(ArrHintWindows:TArrHintWindows; Actor:TActor; MouseItem:pTClientItem; X, Y:Integer; Secret:Boolean; DrawUp:Boolean = False; DrawLeft:Boolean = False);", // line 921
        "procedure GetMouseFengHaoItemInfoWindow(ArrHintWindows:TArrHintWindows; Actor:TActor; MouseItem:pTClientItem; X, Y:Integer; Secret:Boolean; DrawUp:Boolean = False; DrawLeft:Boolean = False);", // line 922
        "function GetTzItemHintWindow(btUser, btSex:Byte; sItemName:string):TList;", // line 923
        "function GetTzItemHintWindowEx(btUser, btSex:Byte; Actor:TActor; MouseItem:pTClientItem; Secret:Boolean; boShowSellPrice:Boolean = True):TList;", // line 924
        "procedure ClearMerchantSay; overload;", // line 925
        "procedure ClearMerchantSay(Owner:TDxControl); overload;", // line 926
        "procedure AddGuildChat(Str:string); virtual;", // line 927
        "procedure AddMissionMemo1(Page:Byte; Text:string);", // line 928
        "procedure AddMissionMemo2(Text:string);", // line 929
        "procedure DrawGridItem(ARect:TRect; Item:PTClientItem; Effect:Pointer; IsDrawLight:Boolean = True);", // line 932
        "procedure DrawGridItemEx(ARect:TRect; Item:PTClientItem; Effect:Pointer; IsBlend:Boolean = False);", // line 935
        "procedure DrawGridStdItem(ARect:TRect; Item:pTStdItem; Effect:Pointer);", // line 936
        "procedure DrawBodyItem(ARect:TRect; Item:pTStdItem; btHeroM2Light:Byte; Effect:Pointer; BodyBelowItemEfect:Boolean {是否绘制底层的物资 chongchong 2016-08-04});", // line 939
        "procedure DrawBodyItemBelowEffect(ARect:TRect; Item:pTStdItem; Effect:Pointer);", // line 942
        "procedure DrawBodyItemEffect(X, Y:Integer; Item:pTStdItem; Effect:Pointer; IsBelowItem:Boolean); overload;", // line 943
        "procedure DrawBodyItemEffect(ARect:TRect; Item:pTStdItem; Effect:Pointer; IsBelowItem:Boolean); overload;", // line 944
        "function CheckDGameShopDlgVisible:Boolean; virtual; abstract;", // line 945
        "procedure OpenDGameShopDlg(IsCheckTime:Boolean = True); virtual; abstract;", // line 946
        "procedure CloseDGameShopDlg; virtual; abstract;", // line 947
        "procedure OpenDMyShopDlg(ClientUserShop:PClientUserShop); virtual; abstract;", // line 948
        "procedure CloseDMyShopDlg; virtual; abstract;", // line 949
        "procedure OpenDUserShopDlg(ClientUserShop:PClientUserShop); virtual; abstract;", // line 950
        "procedure CloseDUserShopDlg; virtual; abstract;", // line 951
        "function CheckDHeroM2ShopDlgVisible:Boolean; virtual; abstract;", // line 952
        "procedure OpenDHeroM2ShopDlg; virtual; abstract;", // line 953
        "procedure CloseDHeroM2ShopDlg; virtual; abstract;", // line 954
        "procedure CloseDHeroM2InputPriceDlg; virtual; abstract;", // line 957
        "procedure OpenDHeroM2ShopRemoteDlg(UserName:string); virtual; abstract;", // line 958
        "procedure CloseDHeroM2ShopRemoteDlg; virtual; abstract;", // line 959
        "procedure DBotUserShopClick(Sender:TObject; X, Y:Integer); stdcall;", // line 960
        "procedure DDownHorseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 961
        "procedure DWebClick(Sender:TObject; X, Y:Integer); stdcall;", // line 962
        "procedure DActionLogClick(Sender:TObject; X, Y:Integer); stdcall;", // line 963
        "procedure SetMyShopPageCount; virtual; abstract;", // line 964
        "procedure SetGameShopPageCount; virtual; abstract;", // line 965
        "procedure SetUserShopItemPageCount; virtual; abstract;", // line 966
        "procedure DDeleteHumanDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 967
        "procedure DGetBackDeleteHumanClick(Sender:TObject; X, Y:Integer); stdcall;", // line 968
        "procedure DListViewDeleteHumanListItemClick(Sender:TObject; ARow, ACol:Integer; ListItem:TObject; ViewItem:Pointer); stdcall;", // line 969
        "procedure DSpecialCmdMenuClick(Sender:TObject; X, Y:Integer); stdcall;", // line 970
        "procedure MerchantDlgPaint(Sender:TObject);", // line 971
        "procedure DDiceDlgProcess(Sender:TObject); stdcall;", // line 972
        "procedure DChallengeItemReturnBag(mitem:TClientItem);", // line 973
        "procedure ChallengeZeroGold;", // line 974
        "procedure DChallengeOkClick(Sender:TObject; X, Y:Integer); stdcall;", // line 975
        "procedure DChallengeCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 976
        "procedure DDChallengeGoldClick(Sender:TObject; X, Y:Integer); stdcall;", // line 977
        "procedure DChallengeGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 978
        "procedure DChallengeGridGridSelect(Sender:TObject; ACol, ARow:Integer; Button:TMouseButton; Shift:TShiftState); stdcall;", // line 979
        "procedure DChallengeGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 980
        "procedure DChallengeRemoteGridGridPaint(Sender:TObject; ACol, ARow:Integer; Rect:TRect; State:TGridDrawState); stdcall;", // line 981
        "procedure DChallengeRemoteGridGridMouseMove(Sender:TObject; ACol, ARow:Integer; Shift:TShiftState); stdcall;", // line 982
        "procedure DControlHelpClick(Sender:TObject; X, Y:Integer); stdcall;", // line 983
        "procedure DRandomCodeDlgDirectPaint(Sender:TObject); stdcall;", // line 984
        "procedure DItemBagDirectPaint(Sender:TObject); stdcall;", // line 985
        "procedure DStPageUpClick(Sender:TObject; X, Y:Integer); stdcall;", // line 986
        "procedure DMainBottomCenterHeightChangeQuery(Sender:TObject; var CanChange:Boolean); stdcall;", // line 987
        "procedure DMainBottomCenterHeightChanged(Sender:TObject); stdcall;", // line 988
        "procedure DMainBottomDlgStartSubPaint(Sender:TObject); stdcall;", // line 989
        "procedure DMagicBallStopPaint(Sender:TObject); stdcall;", // line 990
        "procedure DMagicBallGetHumAbility(Sender:TObject; var Job:Byte; var Level, HP, MaxHP, MP, MaxMP:LongWord); stdcall;", // line 991
        "procedure OnGetGroupAttackProgress(Sender:TObject; var IsShowGroupAttack, IsShowContinueAttack:Boolean; var nGroupAttackProgress:Integer; var IsContinueFlash:Boolean); stdcall;", // line 992
        "procedure DStateMemo4DirectPaint(Sender:TObject); stdcall;", // line 993
        "procedure DHeroStateWinDirectPaint(Sender:TObject); stdcall;", // line 994
        "procedure DBotMiniMapClick(Sender:TObject; X, Y:Integer); stdcall;", // line 995
        "procedure DUserState1DirectPaint(Sender:TObject); stdcall;", // line 996
        "procedure DWeaponUS1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 997
        "procedure DMinMapDlgDirectPaint(Sender:TObject); stdcall;", // line 998
        "procedure DSelectChrWindowsPaint(Sender:TObject); stdcall;", // line 999
        "procedure DSWWeaponMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1000
        "procedure ItemBagDirectPaint(Sender:TObject); virtual; abstract;", // line 1001
        "procedure StPageUpClick(Sender:TObject; X, Y:Integer); virtual; abstract;", // line 1002
        "procedure MainBottomCenterHeightChangeQuery(Sender:TObject; var CanChange:Boolean); virtual; abstract;", // line 1003
        "procedure MainBottomCenterHeightChanged(Sender:TObject); virtual; abstract;", // line 1004
        "procedure MainBottomDlgStartSubPaint(Sender:TObject); virtual; abstract;", // line 1005
        "procedure MagicBallStopPaint(Sender:TObject); virtual; abstract;", // line 1006
        "procedure StateMemo4DirectPaint(Sender:TObject); virtual; abstract;", // line 1007
        "procedure HeroStateWinDirectPaint(Sender:TObject); virtual; abstract;", // line 1008
        "procedure BotMiniMapClick(Sender:TObject; X, Y:Integer); virtual;", // line 1009
        "procedure UserState1DirectPaint(Sender:TObject); virtual;", // line 1010
        "procedure WeaponUS1MouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); virtual;", // line 1011
        "procedure MinMapDlgDirectPaint(Sender:TObject); virtual;", // line 1012
        "procedure SelectChrWindowsPaint(Sender:TObject); virtual;", // line 1013
        "procedure SWWeaponMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); virtual;", // line 1014
        "procedure OpenDBoxDlg(nShape:Integer); virtual; abstract;", // line 1015
        "procedure CloseDBoxDlg; virtual; abstract;", // line 1016
        "procedure OpenDItemBoxDlg; virtual; abstract;", // line 1017
        "procedure CloseDItemBoxDlg; virtual; abstract;", // line 1018
        "procedure SetGuessfinger; virtual; abstract;", // line 1019
        "procedure SetDrinkDrunkValue; virtual; abstract;", // line 1020
        "function CheckShowRemoveStoneForm:Boolean; virtual; abstract;", // line 1022
        "procedure ShowRemoveStoneForm; virtual; abstract;", // line 1023
        "function CheckDMinMapBigDlgMouseDown(Pt:TPoint):Boolean; virtual; abstract;", // line 1024
        "function CheckDMinMapBigDlgVisible:Boolean; virtual; abstract;", // line 1025
        "procedure OpenDMinMapBigDlg; virtual; abstract;", // line 1026
        "procedure CloseDMinMapBigDlg; virtual; abstract;", // line 1027
        "function CheckDMinMapExDlgVisible:Boolean; virtual; abstract;", // line 1028
        "function CheckDMinMapExShowButton:Boolean; virtual; abstract;", // line 1029
        "procedure OpenDMinMapExDlg; virtual; abstract;", // line 1030
        "procedure CloseDMinMapExDlg; virtual; abstract;", // line 1031
        "procedure SelectChrWindowsPaint205(Sender:TObject);", // line 1032
        "procedure DStUpgradeMagicButtonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1033
        "procedure DStHeroUpgradeMagicButtonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1034
        "procedure DStUpgradeMagicMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1035
        "procedure DHeroStUpgradeMagicMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1036
        "procedure DStateRefurbishLabelClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1037
        "property GuildGroupIndex:Integer read FGuildGroupIndex;", // line 1038
        "procedure ClearDMissionMemo;", // line 1041
        "procedure DMouseMoveClearHints(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1042
        "procedure DNpcScrollBoxMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1043
        "procedure DNpcScrollBoxDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1044
        "procedure DNpcScrollBoxUp(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1045
        "procedure DLieDragonPaint(Sender:TObject); stdcall;", // line 1048
        "procedure DLieDragonClosePaint(Sender:TObject); stdcall;", // line 1050
        "procedure DLieDragonCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1052
        "procedure DLieDragonNextPagePaint(Sender:TObject); stdcall;", // line 1054
        "procedure DLieDragonPrevPagePaint(Sender:TObject); stdcall;", // line 1056
        "procedure DLieDragonNextPageClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1058
        "procedure DGoToLieDragontPaint(Sender:TObject); stdcall;", // line 1060
        "procedure DGoToLieDragonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1062
        "procedure DLieDragonNpcPaint(Sender:TObject); stdcall;", // line 1064
        "procedure DLieDragonNpcCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1066
        "procedure DSayItemDlgPaint(Sender:TObject); stdcall;", // line 1069
        "procedure DSayItemDlgCloseClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1070
        "procedure DSayItemDlgMouseDown(Sender:TObject; Button:TMouseButton; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1071
        "procedure DSayItemDlgMouseMove(Sender:TObject; Shift:TShiftState; X, Y:Integer); stdcall;", // line 1072
        "procedure DUpdateStatusDlgPaint(Sender:TObject); stdcall;", // line 1073
        "procedure DUpdateStatusDlgMouseEnter(Sender:TObject); stdcall;", // line 1074
        "procedure DUpdateStatusDlgMouseLeave(Sender:TObject); stdcall;", // line 1075
        "procedure DUpdateStatusDlgDblClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1076
        "procedure UpdateBusinessStatusText; virtual; abstract;", // line 1079
        "procedure UpdateShopMoneyInfo; virtual; abstract;", // line 1080
        "function GetLastHistroySendSay:string; virtual;", // line 1082
        "function GetPreHistroySendSay:string; virtual;", // line 1083
        "function GetNextHistroySendSay:string; virtual;", // line 1084
        "function IsInputChatEdit:Boolean;", // line 1085
        "procedure ShowChatEdit(IsSetFocus:Boolean = True);", // line 1086
        "procedure HideChatEdit;", // line 1087
        "function FindMagicButton(Magic:PTClientMagic):TMagicButton;", // line 1088
        "procedure ClearScreenMagicButtons;", // line 1089
        "procedure AddScreenMagicButton(Magic:PTClientMagic; const X, Y:Integer; IsSave:Boolean = True);", // line 1090
        "procedure DelScreenMagicButton(Magic:PTClientMagic); overload;", // line 1091
        "procedure DelScreenMagicButton(MagicID:Word); overload;", // line 1092
        "procedure SaveMagicButtons;", // line 1093
        "procedure LoadMagicButtons;", // line 1094
        "procedure SetAuctionPageCount(); virtual; abstract;", // line 1095
        "procedure RequestAuctionItems; virtual; abstract;", // line 1096
        "procedure OpenGameLevelDlg(StatueMonRecogId:Integer; LevelNo:Integer); virtual; abstract;", // line 1097
        "procedure CloseGameLevelDlg(); virtual; abstract;", // line 1098
        "procedure RefreshGuardianLevelStatueMonHP(Actor:TActor); virtual; abstract;", // line 1099
        "procedure SetGuardianLevelBatchNo(NO:Integer); virtual; abstract;", // line 1100
        "procedure ShowGuardianLevelResult(IsOK:Boolean; IsShow:Boolean); virtual; abstract;", // line 1101
        "procedure RefreshAdjustAbilityValue; virtual; abstract;", // line 1102
        "function DMessageDlgDeleteUser(MsgStr:string):TModalResult; virtual; abstract;", // line 1103
        "procedure DCustomButtonClick(Sender:TObject; X, Y:Integer); stdcall;", // line 1104
        "procedure RestoreButton_DItemBagArrange; virtual; abstract;", // line 1105
        "procedure ResetBagPageButton; virtual; abstract;", // line 1106
        "procedure ClearNewGroupMember; virtual; abstract;", // line 1107
        "procedure RefreshNewGroupMember(Index:Integer); virtual; abstract;", // line 1108
        "procedure ReshowNewGroupMember; virtual; abstract;", // line 1109
        "function CheckDMinMapDlgExVisible:Boolean; virtual; abstract;", // line 1110
        "procedure ReSetControl; virtual; abstract;", // line 1111
        "procedure OpenDBetterItemDlg(); virtual; abstract;", // line 1112
        "procedure CloseDBetterItemDlg(); virtual; abstract;", // line 1113
    };
}
