// <auto-generated>
//   Generated by GXX.CSharp/tools/gen/GenSqlCreateTable.ps1.
//   The per-constant fingerprints (length / first line / last line) are
//   extracted from the Delphi source, so any later drift in the ported
//   constants fails here.  See the conversion doc, section 5 (test gate).
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using GXX.Core.Data;
using Xunit;

namespace GXX.Core.Tests;

/// <summary>
/// MySqlCreateTableSql.pas / MsSqlCreateTableSql.pas const section, pinned 1:1.
/// </summary>
public sealed class SqlCreateTableSqlTests
{
    private static readonly Dictionary<string, string> All = new();

    static SqlCreateTableSqlTests()
    {
        foreach (var t in new[] { typeof(MySqlCreateTableSql), typeof(MsSqlCreateTableSql) })
            foreach (var f in t.GetFields(BindingFlags.Public | BindingFlags.Static))
                if (f.IsLiteral && f.FieldType == typeof(string))
                    All[t.Name + "." + f.Name] = (string)f.GetValue(null)!;
    }

    public static IEnumerable<object[]> Fingerprints()
    {
        yield return new object[] { "MySqlCreateTableSql.MYSQL_DBVERSION", 8, "20220219", "20220219" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CEATE_DB_CONSTANT", 148, "CREATE TABLE if not exists `db_constant`(", ");" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_ACCOUNT_TABLES", 971, "drop table IF EXISTS `Account`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"account_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_ROLEDATA_TABLES", 23600, "drop table IF EXISTS `HeroAbil`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_HERO_ROLEDATA_TABLES", 9972, "drop table IF EXISTS `HeroAbil`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_HUMAN_ROLEDATA_TABLES", 4057, "drop table IF EXISTS `Human`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_TEST", 1174, "drop table IF EXISTS `HumanItems`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_HUMAN_2_ROLEDATA_TABLES", 4312, "drop table IF EXISTS `HumanItems`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_HUMAN_1_ROLEDATA_TABLES", 6603, "drop table IF EXISTS `HumanAbil`;", ");REPLACE INTO db_constant(ConstName, ConstValue) Values(\"role_version\", 20220219)" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_M2DBVERSION", 8, "20200916", "20200916" };
        yield return new object[] { "MySqlCreateTableSql.MYSQL_CREATE_M2DATA_TABLES", 6111, "drop table IF EXISTS `AuctionAttention`;", "REPLACE INTO db_constant(ConstName, ConstValue) Values(\"m2data_version\", 20200916)" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_DBVERSION", 8, "20180719", "20180719" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_CEATE_DB_CONSTANT", 154, "if object_id('db_constant', 'u') is null ", ");" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_CREATE_ACCOUNT_TABLES", 1058, "if object_id('Account', 'u') is not null drop table Account;", "END" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_CREATE_ROLEDATA_TABLES", 16811, "if object_id('HeroAbil', 'u') is not null drop table HeroAbil;", "END" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_M2DBVERSION", 8, "20180615", "20180615" };
        yield return new object[] { "MsSqlCreateTableSql.MSSQL_CREATE_M2DATA_TABLES", 4752, "if object_id('AuctionAttention', 'u') is not null drop table AuctionAttention;", "END" };
    }

    [Theory]
    [MemberData(nameof(Fingerprints))]
    public void ConstantMatchesDelphiSource(string key, int len, string first, string last)
    {
        Assert.True(All.ContainsKey(key), $"missing constant: {key}");
        var v = All[key];
        Assert.Equal(len, v.Length);
        var lines = v.Split(new[] { "\r\n" }, StringSplitOptions.None);
        Assert.Equal(first, lines[0]);
        Assert.Equal(last, lines.Last(l => l.Length > 0));
    }

    [Fact]
    public void ConstantCountMatchesDelphiSource()
    {
        Assert.Equal(17, All.Count);
    }

    /// <summary>Delphi sLineBreak is CRLF, not LF -- pin the newline bytes.</summary>
    [Fact]
    public void UsesCrLfNotLf()
    {
        var v = MySqlCreateTableSql.MYSQL_CEATE_DB_CONSTANT;
        Assert.Contains("\r\n", v);
        Assert.DoesNotContain("\n\n", v);
    }

    /// <summary>The CEATE typo is in the original source; it must not be "fixed".</summary>
    [Fact]
    public void KeepsOriginalTypoInConstantName()
    {
        Assert.Contains("MySqlCreateTableSql.MYSQL_CEATE_DB_CONSTANT", All.Keys);
        Assert.DoesNotContain("MySqlCreateTableSql.MYSQL_CREATE_DB_CONSTANT", All.Keys);
    }

    /// <summary>Account script embeds the db_constant script, then the version REPLACE.</summary>
    [Fact]
    public void AccountScriptEmbedsDbConstantThenVersion()
    {
        var v = MySqlCreateTableSql.MYSQL_CREATE_ACCOUNT_TABLES;
        var embedded = MySqlCreateTableSql.MYSQL_CEATE_DB_CONSTANT;
        Assert.Contains(embedded, v);
        Assert.True(v.IndexOf(embedded, StringComparison.Ordinal)
                    > v.IndexOf("CREATE TABLE `Account`", StringComparison.Ordinal));
        Assert.EndsWith("Values(\"account_version\", " + MySqlCreateTableSql.MYSQL_DBVERSION + ")", v);
    }

    [Theory]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_ROLEDATA_TABLES")]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_HERO_ROLEDATA_TABLES")]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_HUMAN_ROLEDATA_TABLES")]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_HUMAN_1_ROLEDATA_TABLES")]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_HUMAN_2_ROLEDATA_TABLES")]
    [InlineData("MySqlCreateTableSql.MYSQL_CREATE_M2DATA_TABLES")]
    [InlineData("MsSqlCreateTableSql.MSSQL_CREATE_ROLEDATA_TABLES")]
    [InlineData("MsSqlCreateTableSql.MSSQL_CREATE_M2DATA_TABLES")]
    public void TableScriptsContainCreateTable(string key)
    {
        var v = All[key];
        Assert.True(v.Length > 100);
        Assert.Contains("CREATE TABLE", v);
        Assert.Contains(";", v);
    }
}
